// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NTrivial
{

	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialAssignment>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialAssignmentInt>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialAssignmentBoth>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialAssignmentDerived>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialAssignmentDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialCopy>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialCopyInt>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialCopyBoth>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialCopyDerived>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialCopyDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialConstruct>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialConstructDerived>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CNonTrivialConstructDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDestructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	TCHasTrivialDestructor<CTestClassVirtual>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialDestructor<CTestClassWithDestructor>::mc_Value						));
	
}

// Void
DMibStaticCheck((	TCHasTrivialDestructor<CTestUnion>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	TCHasTrivialDestructor<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCHasTrivialDestructor<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCHasTrivialDestructor<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCHasTrivialDestructor<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	TCHasTrivialDestructor<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCHasTrivialDestructor<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	TCHasTrivialDestructor<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCHasTrivialDestructor<ETestEnum>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<int>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDestructor<CTestClass>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDestructor<CTestC>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDestructor<CTestV>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestVRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCVRef>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestRRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCRRef>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestVRRef>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCHasTrivialDestructor<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDestructor<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDestructor<PFFunc2>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2RRef>::mc_Value						));
#endif
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCHasTrivialDestructor<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDestructor<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDestructor<PFFunc2El>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2ElRRef>::mc_Value						));
#endif
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<CMPtr>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDestructor<CMCPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDestructor<CTestArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestArray2C>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestArray2V>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<CTest2DArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<CTest3DArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDestructor<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDestructor<void *>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDestructor<void>::mc_Value							));

