// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

// Is Int
DMibStaticCheck((	!TCIsInteger<ufp32>::mc_Value	));
	
DMibStaticCheck((	TCIsInteger<int8192>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<aint>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uaint>::mc_Value	));
DMibStaticCheck((	TCIsInteger<smint>::mc_Value	));
DMibStaticCheck((	TCIsInteger<mint>::mc_Value	));

DMibStaticCheck((	TCIsInteger<uint4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint8>::mc_Value	));

DMibStaticCheck((	!TCIsInteger<fp4096>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp2048>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp1024>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp512>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp256>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp128>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp80>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp64>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp32>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp16>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<const int8192>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<const uint4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint8>::mc_Value	));

DMibStaticCheck((	!TCIsInteger<const fp4096>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp2048>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp1024>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp512>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp256>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp128>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp80>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp64>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp32>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp16>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<volatile uint8>::mc_Value	));

DMibStaticCheck((	!TCIsInteger<volatile fp4096>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp2048>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp1024>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp512>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp256>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp128>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp80>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp64>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp32>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp16>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<volatile fp8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<const volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<const volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const volatile uint8>::mc_Value	));

DMibStaticCheck((	!TCIsInteger<const volatile fp4096>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp2048>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp1024>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp512>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp256>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp128>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp80>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp64>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp32>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp16>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const volatile fp8>::mc_Value	));

DMibStaticCheck((	!TCIsInteger<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsInteger<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestVRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestCVRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsInteger<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMCVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMCVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMCPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMCVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMCPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMCVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArray2V>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArray2CV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArrayCV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<void *>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<void>::mc_Value				));

// Is Float
DMibStaticCheck((	TCIsFloat<ufp32>::mc_Value	));
	
DMibStaticCheck((	!TCIsFloat<int8192>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<aint>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uaint>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<smint>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<mint>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint8>::mc_Value	));

DMibStaticCheck((	TCIsFloat<fp4096>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp2048>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp1024>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp512>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp256>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp128>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp80>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp64>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp32>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp16>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<const int8192>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<const uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint8>::mc_Value	));

DMibStaticCheck((	TCIsFloat<const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp512>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp256>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp128>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp80>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp64>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp32>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp16>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<volatile int8192>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile int8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<volatile uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsFloat<volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsFloat<volatile fp8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<const volatile int8192>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile int8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<const volatile uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsFloat<const volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const volatile fp8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsFloat<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestVRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestCVRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsFloat<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMCVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMCVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMCPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMCVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMCPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMCVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArray2V>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArray2CV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArrayCV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<void *>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<void>::mc_Value				));


// Is Float
DMibStaticCheck((	TCIsArithmetic<ufp32>::mc_Value	));
	
DMibStaticCheck((	TCIsArithmetic<int8192>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<aint>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uaint>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<smint>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<mint>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<uint4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<fp4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const int8192>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const uint4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<volatile fp8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const volatile fp8>::mc_Value	));

DMibStaticCheck((	!TCIsArithmetic<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsArithmetic<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestVRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestCVRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsArithmetic<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMCVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMCVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMCPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMCVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMCPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMCVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArray2V>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArray2CV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArrayCV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<void *>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<void>::mc_Value				));

