// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NNothrow
{

	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsAssignment>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsAssignmentInt>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsAssignmentBoth>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsAssignmentDerived>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsAssignmentDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CNothrow>::mc_Value						));

	DMibStaticCheck((	!TCHasNothrowCopyConstructor<CThrowsCopy>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsCopyInt>::mc_Value						));
	DMibStaticCheck((	!TCHasNothrowCopyConstructor<CThrowsCopyBoth>::mc_Value						));
#ifndef DMibCompiler_GCC
	DMibStaticCheck((	!TCHasNothrowCopyConstructor<CThrowsCopyDerived>::mc_Value						));
#endif
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsCopyDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CNothrow>::mc_Value						));

	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsConstruct>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsConstructDerived>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CThrowsConstructDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowCopyConstructor<CNothrow>::mc_Value						));

	DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestClassVirtual>::mc_Value						));
	
}

// Void
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestUnion>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	TCHasNothrowCopyConstructor<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCHasNothrowCopyConstructor<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCHasNothrowCopyConstructor<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCHasNothrowCopyConstructor<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	TCHasNothrowCopyConstructor<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCHasNothrowCopyConstructor<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	TCHasNothrowCopyConstructor<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCHasNothrowCopyConstructor<ETestEnum>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<int>::mc_Value							));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestClass>::mc_Value							));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestC>::mc_Value							));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestV>::mc_Value							));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestVRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCVRef>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestRRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCRRef>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestVRRef>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCHasNothrowCopyConstructor<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowCopyConstructor<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowCopyConstructor<PFFunc2>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCHasNothrowCopyConstructor<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowCopyConstructor<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowCopyConstructor<PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMPtr>::mc_Value							));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMCPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMVPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestArray2>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestArray2C>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestArray2V>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestArray>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestArrayC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestArrayV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest2DArray>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest3DArray>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowCopyConstructor<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowCopyConstructor<void *>::mc_Value						));
DMibStaticCheck((	TCHasNothrowCopyConstructor<void>::mc_Value							));

