// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	TCIsEnum<ETestEnum>::mc_Value	));

// Void
DMibStaticCheck((	!TCIsEnum<CTestUnion>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTestClass0>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTestClass1>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTestStruct0>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTestStruct1>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<const CTestClass0>::mc_Value				));
DMibStaticCheck((	!TCIsEnum<const CTestClass1>::mc_Value				));
DMibStaticCheck((	!TCIsEnum<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	!TCIsEnum<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCIsEnum<ETestEnum>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<int>::mc_Value							));
DMibStaticCheck((	!TCIsEnum<CTestClass>::mc_Value							));
DMibStaticCheck((	!TCIsEnum<CTestC>::mc_Value							));
DMibStaticCheck((	!TCIsEnum<CTestPtr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CTestCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CTestPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CMPtr>::mc_Value							));
DMibStaticCheck((	!TCIsEnum<CMCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CMPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CMCPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<CTestArray2>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTestArray2C>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTestArray>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTestArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsEnum<CTest2DArray>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsEnum<CTest3DArray>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsEnum<void *>::mc_Value						));
DMibStaticCheck((	!TCIsEnum<void>::mc_Value							));

