// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsMemberObjectPointer<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<ETestEnum>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestClass>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCV>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestVRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCVRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsMemberObjectPointer<CMPtr>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCPtr>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMVPtr>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMPtrC>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMPtrV>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArray>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArrayV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArray>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArrayV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<void *>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<void>::mc_Value			));

// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestV>::CType, CTestV>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCV>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestPtr>::CType, CTestPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCPtr>::CType, CTestCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestVPtr>::CType, CTestVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCVPtr>::CType, CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestPtrC>::CType, CTestPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCPtrC>::CType, CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestVPtrC>::CType, CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCVPtrC>::CType, CTestCVPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestPtrV>::CType, CTestPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCPtrV>::CType, CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestVPtrV>::CType, CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCVPtrV>::CType, CTestCVPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestPtrCV>::CType, CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCPtrCV>::CType, CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestVPtrCV>::CType, CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCVPtrCV>::CType, CTestCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestVRef>::CType, CTestVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCVRef>::CType, CTestCVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestVRRef>::CType, CTestVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCVRRef>::CType, CTestCVRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0Ref>::CType, FFunc0Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1Ref>::CType, FFunc1Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2Ref>::CType, FFunc2Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0RRef>::CType, FFunc0RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1RRef>::CType, FFunc1RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2RRef>::CType, FFunc2RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0PtrV>::CType, FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1PtrV>::CType, FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2PtrV>::CType, FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0PtrCV>::CType, FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1PtrCV>::CType, FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2PtrCV>::CType, FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0PtrV>::CType, FMFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1PtrV>::CType, FMFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2PtrV>::CType, FMFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0PtrCV>::CType, FMFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1PtrCV>::CType, FMFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2PtrCV>::CType, FMFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CPtrV>::CType, FMFunc0CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CPtrV>::CType, FMFunc1CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CPtrV>::CType, FMFunc2CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0VPtr>::CType, FMFunc0VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1VPtr>::CType, FMFunc1VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2VPtr>::CType, FMFunc2VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0VPtrC>::CType, FMFunc0VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1VPtrC>::CType, FMFunc1VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2VPtrC>::CType, FMFunc2VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0VPtrV>::CType, FMFunc0VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1VPtrV>::CType, FMFunc1VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2VPtrV>::CType, FMFunc2VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CVPtr>::CType, FMFunc0CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CVPtr>::CType, FMFunc1CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CVPtr>::CType, FMFunc2CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElPtrV>::CType, FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElPtrV>::CType, FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElPtrV>::CType, FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMPtr>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCPtr>::CType, CTestBase const>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMVPtr>::CType, CTestBase volatile>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCVPtr>::CType, CTestBase const volatile>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMPtrC>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCPtrC>::CType, CTestBase const>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMVPtrC>::CType, CTestBase volatile>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCVPtrC>::CType, CTestBase const volatile>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMPtrV>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCPtrV>::CType, CTestBase const>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMVPtrV>::CType, CTestBase volatile>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCVPtrV>::CType, CTestBase const volatile>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMPtrCV>::CType, CTestBase>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCPtrCV>::CType, CTestBase const>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMVPtrCV>::CType, CTestBase volatile>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCVPtrCV>::CType, CTestBase const volatile>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArray2V>::CType, CTestArray2V>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArray2CV>::CType, CTestArray2CV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArrayV>::CType, CTestArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArrayCV>::CType, CTestArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArray2V>::CType, CTest2DArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArray2CV>::CType, CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArray2V>::CType, CTest3DArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArray2CV>::CType, CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<void>::CType, void>::mc_Value							));


// Class
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestUnion>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestClass0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestClass1>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestStruct0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestStruct1>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<ETestEnum>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestClass>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestC>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestV>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestVPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCVPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestVPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCVPtrC>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestPtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCPtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestVPtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCVPtrV>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestPtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCPtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestVPtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCVPtrCV>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestRef>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestVRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCVRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestVRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCVRRef>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc0>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc1>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc2>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0Ref>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1Ref>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2Ref>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0RRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1RRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2RRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0PtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1PtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2PtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0PtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1PtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2PtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0Ptr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1Ptr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2Ptr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0PtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1PtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2PtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0PtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1PtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2PtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0PtrCV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1PtrCV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2PtrCV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0VPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1VPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2VPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0VPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1VPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2VPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0VPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1VPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2VPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0VPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1VPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2VPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CVPtrC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CVPtrC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CVPtrC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CVPtrV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CVPtrV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CVPtrV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc0El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc1El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc2El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElPtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElPtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElPtrV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElPtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElPtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElPtrCV>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElPtr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElPtr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElPtr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElPtrCV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElPtrCV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElPtrCV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElVPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElVPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElVPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElVPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElVPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElVPtrV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCVPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCVPtrC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCVPtrC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCVPtrC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCVPtrV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCVPtrV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCVPtrV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCVPtrCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMPtr>::CType, CTestClass0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCPtr>::CType, CTestClass0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMVPtr>::CType, CTestClass0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCVPtr>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMPtrC>::CType, CTestClass0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCPtrC>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMVPtrC>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCVPtrC>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMPtrV>::CType, CTestClass0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCPtrV>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMVPtrV>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCVPtrV>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMPtrCV>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCPtrCV>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMVPtrCV>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCVPtrCV>::CType, CTestClass0>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArray2>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArray2C>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArray2V>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArray2CV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArray>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArrayC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArrayV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArrayCV>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArray2>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArray2C>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArray2V>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArray2CV>::CType, void>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArray>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArrayC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArrayV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArrayCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArray2>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArray2C>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArray2V>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArray2CV>::CType, void>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArray>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArrayC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArrayV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArrayCV>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<void *>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<void>::CType, void>::mc_Value							));




