// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

static_assert(cIsEnum<ETestEnum>);

// Void
static_assert(!cIsEnum<CTestUnion>);
static_assert(!cIsEnum<CTestClass0>);
static_assert(!cIsEnum<CTestClass1>);
static_assert(!cIsEnum<CTestStruct0>);
static_assert(!cIsEnum<CTestStruct1>);
static_assert(!cIsEnum<const CTestClass0>);
static_assert(!cIsEnum<const CTestClass1>);
static_assert(!cIsEnum<const CTestStruct0>);
static_assert(!cIsEnum<const CTestStruct1>);
static_assert(cIsEnum<ETestEnum>);
static_assert(!cIsEnum<int>);
static_assert(!cIsEnum<CTestClass>);
static_assert(!cIsEnum<CTestC>);
static_assert(!cIsEnum<CTestPtr>);
static_assert(!cIsEnum<CTestCPtr>);
static_assert(!cIsEnum<CTestPtrC>);
static_assert(!cIsEnum<CTestCPtrC>);
static_assert(!cIsEnum<CTestRef>);
static_assert(!cIsEnum<CTestCRef>);
static_assert(!cIsEnum<CTestRRef>);
static_assert(!cIsEnum<CTestCRRef>);
static_assert(!cIsEnum<PFFunc0>);
static_assert(!cIsEnum<PFFunc1>);
static_assert(!cIsEnum<PFFunc2>);
static_assert(!cIsEnum<FFunc0Ref>);
static_assert(!cIsEnum<FFunc1Ref>);
static_assert(!cIsEnum<FFunc2Ref>);
static_assert(!cIsEnum<FFunc0RRef>);
static_assert(!cIsEnum<FFunc1RRef>);
static_assert(!cIsEnum<FFunc2RRef>);
static_assert(!cIsEnum<FFunc0Ptr>);
static_assert(!cIsEnum<FFunc1Ptr>);
static_assert(!cIsEnum<FFunc2Ptr>);
static_assert(!cIsEnum<FFunc0PtrC>);
static_assert(!cIsEnum<FFunc1PtrC>);
static_assert(!cIsEnum<FFunc2PtrC>);
static_assert(!cIsEnum<FMFunc0Ptr>);
static_assert(!cIsEnum<FMFunc1Ptr>);
static_assert(!cIsEnum<FMFunc2Ptr>);
static_assert(!cIsEnum<FMFunc0PtrC>);
static_assert(!cIsEnum<FMFunc1PtrC>);
static_assert(!cIsEnum<FMFunc2PtrC>);
static_assert(!cIsEnum<FMFunc0CPtr>);
static_assert(!cIsEnum<FMFunc1CPtr>);
static_assert(!cIsEnum<FMFunc2CPtr>);
static_assert(!cIsEnum<FMFunc0CPtrC>);
static_assert(!cIsEnum<FMFunc1CPtrC>);
static_assert(!cIsEnum<FMFunc2CPtrC>);
static_assert(!cIsEnum<PFFunc0El>);
static_assert(!cIsEnum<PFFunc1El>);
static_assert(!cIsEnum<PFFunc2El>);
static_assert(!cIsEnum<FFunc0ElRef>);
static_assert(!cIsEnum<FFunc1ElRef>);
static_assert(!cIsEnum<FFunc2ElRef>);
static_assert(!cIsEnum<FFunc0ElRRef>);
static_assert(!cIsEnum<FFunc1ElRRef>);
static_assert(!cIsEnum<FFunc2ElRRef>);
static_assert(!cIsEnum<FFunc0ElPtr>);
static_assert(!cIsEnum<FFunc1ElPtr>);
static_assert(!cIsEnum<FFunc2ElPtr>);
static_assert(!cIsEnum<FFunc0ElPtrC>);
static_assert(!cIsEnum<FFunc1ElPtrC>);
static_assert(!cIsEnum<FFunc2ElPtrC>);
static_assert(!cIsEnum<FMFunc0ElPtr>);
static_assert(!cIsEnum<FMFunc1ElPtr>);
static_assert(!cIsEnum<FMFunc2ElPtr>);
static_assert(!cIsEnum<FMFunc0ElPtrC>);
static_assert(!cIsEnum<FMFunc1ElPtrC>);
static_assert(!cIsEnum<FMFunc2ElPtrC>);
static_assert(!cIsEnum<FMFunc0ElCPtr>);
static_assert(!cIsEnum<FMFunc1ElCPtr>);
static_assert(!cIsEnum<FMFunc2ElCPtr>);
static_assert(!cIsEnum<FMFunc0ElCPtrC>);
static_assert(!cIsEnum<FMFunc1ElCPtrC>);
static_assert(!cIsEnum<FMFunc2ElCPtrC>);
static_assert(!cIsEnum<CMPtr>);
static_assert(!cIsEnum<CMCPtr>);
static_assert(!cIsEnum<CMPtrC>);
static_assert(!cIsEnum<CMCPtrC>);
static_assert(!cIsEnum<CTestArray2>);
static_assert(!cIsEnum<CTestArray2C>);
static_assert(!cIsEnum<CTestArray>);
static_assert(!cIsEnum<CTestArrayC>);
static_assert(!cIsEnum<CTest2DArray2>);
static_assert(!cIsEnum<CTest2DArray2C>);
static_assert(!cIsEnum<CTest2DArray>);
static_assert(!cIsEnum<CTest2DArrayC>);
static_assert(!cIsEnum<CTest3DArray2>);
static_assert(!cIsEnum<CTest3DArray2C>);
static_assert(!cIsEnum<CTest3DArray>);
static_assert(!cIsEnum<CTest3DArrayC>);
static_assert(!cIsEnum<void *>);
static_assert(!cIsEnum<void>);
