// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	TCIsScalar<int8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<aint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uaint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<smint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<mint>::mc_Value	));

DMibStaticCheck((	TCIsScalar<uint8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<fp4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const int8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const aint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uaint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const smint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const mint>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const uint8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<volatile aint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uaint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile smint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile mint>::mc_Value	));

DMibStaticCheck((	TCIsScalar<volatile uint8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<volatile fp8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const volatile aint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uaint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile smint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile mint>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const volatile uint8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const volatile fp8>::mc_Value	));

DMibStaticCheck((	!TCIsScalar<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsScalar<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsScalar<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<CTestCV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestCPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestVPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestPtrC>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestPtrV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestVRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestCVRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<PFFunc2>::mc_Value			));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	!TCIsScalar<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc2RRef>::mc_Value		));
#endif
DMibStaticCheck((	TCIsScalar<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsScalar<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsScalar<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<PFFunc2El>::mc_Value			));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	!TCIsScalar<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc2ElRRef>::mc_Value		));
#endif
DMibStaticCheck((	TCIsScalar<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsScalar<CMPtr>::mc_Value				));
DMibStaticCheck((	TCIsScalar<CMCPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMVPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMPtrC>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMCVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMPtrV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMCVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMCPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMCVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArray2V>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArray2CV>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArrayCV>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsScalar<void *>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<void>::mc_Value				));

