// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NTrivial
{

	DMibStaticCheck((	TCHasTrivialDefaultConstructor<CNonTrivialAssignment>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDefaultConstructor<CNonTrivialAssignmentInt>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDefaultConstructor<CNonTrivialAssignmentBoth>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDefaultConstructor<CNonTrivialAssignmentDerived>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDefaultConstructor<CNonTrivialAssignmentDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CNonTrivialCopy>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CNonTrivialCopyInt>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CNonTrivialCopyBoth>::mc_Value						));
	
#ifndef DMibCompiler_GCC
	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CNonTrivialCopyDerived>::mc_Value						));
#endif
	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CNonTrivialCopyDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CNonTrivialConstruct>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CNonTrivialConstructDerived>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CNonTrivialConstructDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestClassVirtual>::mc_Value						));

}

// Void
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestUnion>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<ETestEnum>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<int>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestClass>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestC>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestV>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestVRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestCVRef>::mc_Value					));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestVRRef>::mc_Value					));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialDefaultConstructor<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMPtr>::mc_Value							));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMCPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestArray2C>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestArray2V>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest2DArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest3DArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<void *>::mc_Value						));
DMibStaticCheck((	TCHasTrivialDefaultConstructor<void>::mc_Value							));

