// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

// Largest type
DMibStaticCheck((	TCIsSame<TCLargestType<CTestStruct1, CTestStruct0>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestUnion, CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<const CTestUnion, const CTestUnion>::CType, const CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestClass0, CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestClass1, CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestStruct0, CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestStruct1, CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<ETestEnum, ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestClass, CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestC, CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestPtr, CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestCPtr, CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestPtrC, CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestCPtrC, CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestRef, CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestCRef, CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestRRef, CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestCRRef, CTestCRRef>::CType, CTestCRRef>::mc_Value				));
/*
DMibStaticCheck((	TCIsSame<TCLargestType<PFFunc0, PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<PFFunc1, PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<PFFunc2, PFFunc2>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc0Ref, FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc1Ref, FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc2Ref, FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc0RRef, FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc1RRef, FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc2RRef, FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc0Ptr, FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc1Ptr, FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc2Ptr, FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc0PtrC, FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc1PtrC, FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc2PtrC, FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc0Ptr, FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc1Ptr, FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc2Ptr, FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc0PtrC, FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc1PtrC, FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc2PtrC, FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc0CPtr, FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc1CPtr, FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc2CPtr, FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc0CPtrC, FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc1CPtrC, FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc2CPtrC, FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<PFFunc0El, PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<PFFunc1El, PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<PFFunc2El, PFFunc2El>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc0ElRef, FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc1ElRef, FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc2ElRef, FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc0ElRRef, FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc1ElRRef, FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc2ElRRef, FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc0ElPtr, FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc1ElPtr, FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc2ElPtr, FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc0ElPtrC, FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc1ElPtrC, FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FFunc2ElPtrC, FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc0ElPtr, FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc1ElPtr, FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc2ElPtr, FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc0ElPtrC, FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc1ElPtrC, FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc2ElPtrC, FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc0ElCPtr, FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc1ElCPtr, FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc2ElCPtr, FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc0ElCPtrC, FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc1ElCPtrC, FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<FMFunc2ElCPtrC, FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
*/
DMibStaticCheck((	TCIsSame<TCLargestType<CMPtr, CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCLargestType<CMCPtr, CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<CMPtrC, CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<CMCPtrC, CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestArray2, CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<CTestArray2C, CTestArray2C>::CType, CTestArray2C>::mc_Value		));
//DMibStaticCheck((	TCIsSame<TCLargestType<CTestArray, CTestArray>::CType, CTestArray>::mc_Value			));
//DMibStaticCheck((	TCIsSame<TCLargestType<CTestArrayC, CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargestType<CTest2DArray2, CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<CTest2DArray2C, CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
//DMibStaticCheck((	TCIsSame<TCLargestType<CTest2DArray, CTest2DArray>::CType, CTest2DArray>::mc_Value		));
//DMibStaticCheck((	TCIsSame<TCLargestType<CTest2DArrayC, CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<CTest3DArray2, CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<CTest3DArray2C, CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
//DMibStaticCheck((	TCIsSame<TCLargestType<CTest3DArray, CTest3DArray>::CType, CTest3DArray>::mc_Value		));
//DMibStaticCheck((	TCIsSame<TCLargestType<CTest3DArrayC, CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargestType<void *, void *>::CType, void *>::mc_Value					));
//DMibStaticCheck((	TCIsSame<TCLargestType<void, void>::CType, void>::mc_Value						));

// Smallest type
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestStruct1, CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestUnion, CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestClass0, CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestClass1, CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestStruct0, CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestStruct1, CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<ETestEnum, ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestClass, CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestC, CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestPtr, CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestCPtr, CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestPtrC, CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestCPtrC, CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestRef, CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestCRef, CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestRRef, CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestCRRef, CTestCRRef>::CType, CTestCRRef>::mc_Value				));
/*DMibStaticCheck((	TCIsSame<TCSmallestType<PFFunc0, PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<PFFunc1, PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<PFFunc2, PFFunc2>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc0Ref, FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc1Ref, FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc2Ref, FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc0RRef, FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc1RRef, FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc2RRef, FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc0Ptr, FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc1Ptr, FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc2Ptr, FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc0PtrC, FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc1PtrC, FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc2PtrC, FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc0Ptr, FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc1Ptr, FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc2Ptr, FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc0PtrC, FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc1PtrC, FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc2PtrC, FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc0CPtr, FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc1CPtr, FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc2CPtr, FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc0CPtrC, FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc1CPtrC, FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc2CPtrC, FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<PFFunc0El, PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<PFFunc1El, PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<PFFunc2El, PFFunc2El>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc0ElRef, FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc1ElRef, FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc2ElRef, FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc0ElRRef, FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc1ElRRef, FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc2ElRRef, FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc0ElPtr, FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc1ElPtr, FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc2ElPtr, FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc0ElPtrC, FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc1ElPtrC, FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FFunc2ElPtrC, FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc0ElPtr, FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc1ElPtr, FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc2ElPtr, FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc0ElPtrC, FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc1ElPtrC, FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc2ElPtrC, FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc0ElCPtr, FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc1ElCPtr, FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc2ElCPtr, FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc0ElCPtrC, FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc1ElCPtrC, FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<FMFunc2ElCPtrC, FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
*/
DMibStaticCheck((	TCIsSame<TCSmallestType<CMPtr, CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCSmallestType<CMCPtr, CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<CMPtrC, CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<CMCPtrC, CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestArray2, CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTestArray2C, CTestArray2C>::CType, CTestArray2C>::mc_Value		));
//DMibStaticCheck((	TCIsSame<TCSmallestType<CTestArray, CTestArray>::CType, CTestArray>::mc_Value			));
//DMibStaticCheck((	TCIsSame<TCSmallestType<CTestArrayC, CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTest2DArray2, CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTest2DArray2C, CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
//DMibStaticCheck((	TCIsSame<TCSmallestType<CTest2DArray, CTest2DArray>::CType, CTest2DArray>::mc_Value		));
//DMibStaticCheck((	TCIsSame<TCSmallestType<CTest2DArrayC, CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTest3DArray2, CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<CTest3DArray2C, CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
//DMibStaticCheck((	TCIsSame<TCSmallestType<CTest3DArray, CTest3DArray>::CType, CTest3DArray>::mc_Value		));
//DMibStaticCheck((	TCIsSame<TCSmallestType<CTest3DArrayC, CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallestType<void *, void *>::CType, void *>::mc_Value					));
//DMibStaticCheck((	TCIsSame<TCSmallestType<void, void>::CType, void>::mc_Value						));

// Smaller type
DMibStaticCheck((	TCIsSame<TCSmallerType<int8192>::CType, int4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int4096>::CType, int2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int2048>::CType, int1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int1024>::CType, int512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int512>::CType, int256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int256>::CType, int128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int160>::CType, int80>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int128>::CType, int64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int64>::CType, int32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int32>::CType, int16>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int16>::CType, int8>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<int8>::CType, int8>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCSmallerType<uint8192>::CType, uint4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint4096>::CType, uint2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint2048>::CType, uint1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint1024>::CType, uint512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint512>::CType, uint256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint256>::CType, uint128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint160>::CType, uint80>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint128>::CType, uint64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint64>::CType, uint32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint32>::CType, uint16>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint16>::CType, uint8>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<uint8>::CType, uint8>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCSmallerType<fp4096>::CType, fp2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp2048>::CType, fp1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp1024>::CType, fp512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp512>::CType, fp256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp256>::CType, fp128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp128>::CType, fp64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp64>::CType, fp32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp32>::CType, fp16>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp16>::CType, fp8>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<fp8>::CType, fp8>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCSmallerType<const int8192>::CType, const int4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int4096>::CType, const int2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int2048>::CType, const int1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int1024>::CType, const int512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int512>::CType, const int256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int256>::CType, const int128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int160>::CType, const int80>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int128>::CType, const int64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int64>::CType, const int32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int32>::CType, const int16>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int16>::CType, const int8>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const int8>::CType, const int8>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCSmallerType<const uint8192>::CType, const uint4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint4096>::CType, const uint2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint2048>::CType, const uint1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint1024>::CType, const uint512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint512>::CType, const uint256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint256>::CType, const uint128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint160>::CType, const uint80>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint128>::CType, const uint64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint64>::CType, const uint32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint32>::CType, const uint16>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint16>::CType, const uint8>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const uint8>::CType, const uint8>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCSmallerType<const fp4096>::CType, const fp2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp2048>::CType, const fp1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp1024>::CType, const fp512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp512>::CType, const fp256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp256>::CType, const fp128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp128>::CType, const fp64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp64>::CType, const fp32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp32>::CType, const fp16>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp16>::CType, const fp8>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<const fp8>::CType, const fp8>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCSmallerType<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<PFFunc2>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<PFFunc2El>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCSmallerType<CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestArray2C>::CType, CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestArray>::CType, CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTest2DArray>::CType, CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTest3DArray>::CType, CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSmallerType<void *>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSmallerType<void>::CType, void>::mc_Value						));

// Larger type
DMibStaticCheck((	TCIsSame<TCLargerType<int4096>::CType, int8192>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int2048>::CType, int4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int1024>::CType, int2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int512>::CType, int1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int256>::CType, int512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int128>::CType, int256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int80>::CType, int160>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int64>::CType, int128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int32>::CType, int64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int16>::CType, int32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<int8>::CType, int16>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCLargerType<uint4096>::CType, uint8192>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint2048>::CType, uint4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint1024>::CType, uint2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint512>::CType, uint1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint256>::CType, uint512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint128>::CType, uint256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint80>::CType, uint160>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint64>::CType, uint128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint32>::CType, uint64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint16>::CType, uint32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<uint8>::CType, uint16>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCLargerType<fp2048>::CType, fp4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<fp1024>::CType, fp2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<fp512>::CType, fp1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<fp256>::CType, fp512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<fp128>::CType, fp256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<fp64>::CType, fp128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<fp32>::CType, fp64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<fp16>::CType, fp32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<fp8>::CType, fp16>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCLargerType<const int4096>::CType, const int8192>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int2048>::CType, const int4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int1024>::CType, const int2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int512>::CType, const int1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int256>::CType, const int512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int128>::CType, const int256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int80>::CType, const int160>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int64>::CType, const int128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int32>::CType, const int64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int16>::CType, const int32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const int8>::CType, const int16>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCLargerType<const uint4096>::CType, const uint8192>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint2048>::CType, const uint4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint1024>::CType, const uint2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint512>::CType, const uint1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint256>::CType, const uint512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint128>::CType, const uint256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint80>::CType, const uint160>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint64>::CType, const uint128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint32>::CType, const uint64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint16>::CType, const uint32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const uint8>::CType, const uint16>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCLargerType<const fp2048>::CType, const fp4096>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const fp1024>::CType, const fp2048>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const fp512>::CType, const fp1024>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const fp256>::CType, const fp512>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const fp128>::CType, const fp256>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const fp64>::CType, const fp128>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const fp32>::CType, const fp64>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const fp16>::CType, const fp32>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<const fp8>::CType, const fp16>::mc_Value			));

DMibStaticCheck((	TCIsSame<TCLargerType<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<PFFunc2>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<PFFunc2El>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCLargerType<CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestArray2C>::CType, CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestArray>::CType, CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCLargerType<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCLargerType<CTest2DArray>::CType, CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCLargerType<CTest3DArray>::CType, CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCLargerType<void *>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCLargerType<void>::CType, void>::mc_Value						));

