// Copyright © Unbroken AB
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "Test_TypeTraits_TestTypes.h"

static_assert(!cIsReference<CTestUnion>);
static_assert(!cIsReference<CTestClass0>);
static_assert(!cIsReference<CTestClass1>);
static_assert(!cIsReference<CTestStruct0>);
static_assert(!cIsReference<CTestStruct1>);
static_assert(!cIsReference<ETestEnum>);
static_assert(!cIsReference<CTestClass>);
static_assert(!cIsReference<CTestC>);
static_assert(!cIsReference<CTestPtr>);
static_assert(!cIsReference<CTestCPtr>);
static_assert(!cIsReference<CTestPtrC>);
static_assert(!cIsReference<CTestCPtrC>);
static_assert(cIsReference<CTestRef>);
static_assert(cIsReference<CTestCRef>);
static_assert(cIsReference<CTestRRef>);
static_assert(cIsReference<CTestCRRef>);
static_assert(!cIsReference<PFFunc0>);
static_assert(!cIsReference<PFFunc1>);
static_assert(!cIsReference<PFFunc2>);
static_assert(cIsReference<FFunc0Ref>);
static_assert(cIsReference<FFunc1Ref>);
static_assert(cIsReference<FFunc2Ref>);
static_assert(cIsReference<FFunc0RRef>);
static_assert(cIsReference<FFunc1RRef>);
static_assert(cIsReference<FFunc2RRef>);
static_assert(!cIsReference<FFunc0Ptr>);
static_assert(!cIsReference<FFunc1Ptr>);
static_assert(!cIsReference<FFunc2Ptr>);
static_assert(!cIsReference<FFunc0PtrC>);
static_assert(!cIsReference<FFunc1PtrC>);
static_assert(!cIsReference<FFunc2PtrC>);
static_assert(!cIsReference<FMFunc0Ptr>);
static_assert(!cIsReference<FMFunc1Ptr>);
static_assert(!cIsReference<FMFunc2Ptr>);
static_assert(!cIsReference<FMFunc0PtrC>);
static_assert(!cIsReference<FMFunc1PtrC>);
static_assert(!cIsReference<FMFunc2PtrC>);
static_assert(!cIsReference<FMFunc0CPtr>);
static_assert(!cIsReference<FMFunc1CPtr>);
static_assert(!cIsReference<FMFunc2CPtr>);
static_assert(!cIsReference<FMFunc0CPtrC>);
static_assert(!cIsReference<FMFunc1CPtrC>);
static_assert(!cIsReference<FMFunc2CPtrC>);
static_assert(!cIsReference<PFFunc0El>);
static_assert(!cIsReference<PFFunc1El>);
static_assert(!cIsReference<PFFunc2El>);
static_assert(cIsReference<FFunc0ElRef>);
static_assert(cIsReference<FFunc1ElRef>);
static_assert(cIsReference<FFunc2ElRef>);
static_assert(cIsReference<FFunc0ElRRef>);
static_assert(cIsReference<FFunc1ElRRef>);
static_assert(cIsReference<FFunc2ElRRef>);
static_assert(!cIsReference<FFunc0ElPtr>);
static_assert(!cIsReference<FFunc1ElPtr>);
static_assert(!cIsReference<FFunc2ElPtr>);
static_assert(!cIsReference<FFunc0ElPtrC>);
static_assert(!cIsReference<FFunc1ElPtrC>);
static_assert(!cIsReference<FFunc2ElPtrC>);
static_assert(!cIsReference<FMFunc0ElPtr>);
static_assert(!cIsReference<FMFunc1ElPtr>);
static_assert(!cIsReference<FMFunc2ElPtr>);
static_assert(!cIsReference<FMFunc0ElPtrC>);
static_assert(!cIsReference<FMFunc1ElPtrC>);
static_assert(!cIsReference<FMFunc2ElPtrC>);
static_assert(!cIsReference<FMFunc0ElCPtr>);
static_assert(!cIsReference<FMFunc1ElCPtr>);
static_assert(!cIsReference<FMFunc2ElCPtr>);
static_assert(!cIsReference<FMFunc0ElCPtrC>);
static_assert(!cIsReference<FMFunc1ElCPtrC>);
static_assert(!cIsReference<FMFunc2ElCPtrC>);
static_assert(!cIsReference<CMPtr>);
static_assert(!cIsReference<CMCPtr>);
static_assert(!cIsReference<CMPtrC>);
static_assert(!cIsReference<CMCPtrC>);
static_assert(!cIsReference<CTestArray2>);
static_assert(!cIsReference<CTestArray2C>);
static_assert(!cIsReference<CTestArray>);
static_assert(!cIsReference<CTestArrayC>);
static_assert(!cIsReference<CTest2DArray2>);
static_assert(!cIsReference<CTest2DArray2C>);
static_assert(!cIsReference<CTest2DArray>);
static_assert(!cIsReference<CTest2DArrayC>);
static_assert(!cIsReference<CTest3DArray2>);
static_assert(!cIsReference<CTest3DArray2C>);
static_assert(!cIsReference<CTest3DArray>);
static_assert(!cIsReference<CTest3DArrayC>);
static_assert(!cIsReference<void *>);
static_assert(!cIsReference<void>);

static_assert(cIsSame<TCAddLValueReference<CTestUnion>, CTestUnion &>);
static_assert(cIsSame<TCAddLValueReference<CTestClass0>, CTestClass0 &>);
static_assert(cIsSame<TCAddLValueReference<CTestClass1>, CTestClass1 &>);
static_assert(cIsSame<TCAddLValueReference<CTestStruct0>, CTestStruct0 &>);
static_assert(cIsSame<TCAddLValueReference<CTestStruct1>, CTestStruct1 &>);
static_assert(cIsSame<TCAddLValueReference<ETestEnum>, ETestEnum &>);
static_assert(cIsSame<TCAddLValueReference<CTestClass>, CTestClass &>);
static_assert(cIsSame<TCAddLValueReference<CTestC>, CTestC &>);
static_assert(cIsSame<TCAddLValueReference<CTestPtr>, CTestPtr &>);
static_assert(cIsSame<TCAddLValueReference<CTestCPtr>, CTestCPtr &>);
static_assert(cIsSame<TCAddLValueReference<CTestPtrC>, CTestPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CTestCPtrC>, CTestCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CTestRef>, CTestRef>);
static_assert(cIsSame<TCAddLValueReference<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCAddLValueReference<CTestRRef>, CTestRef>);
static_assert(cIsSame<TCAddLValueReference<CTestCRRef>, CTestCRef>);
static_assert(cIsSame<TCAddLValueReference<PFFunc0>, PFFunc0 &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc1>, PFFunc1 &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc2>, PFFunc2 &>);
static_assert(cIsSame<TCAddLValueReference<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc0RRef>, FFunc0Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc1RRef>, FFunc1Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc2RRef>, FFunc2Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc0Ptr>, FFunc0Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc1Ptr>, FFunc1Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc2Ptr>, FFunc2Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc0PtrC>, FFunc0PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FFunc1PtrC>, FFunc1PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FFunc2PtrC>, FFunc2PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0Ptr>, FMFunc0Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1Ptr>, FMFunc1Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2Ptr>, FMFunc2Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0PtrC>, FMFunc0PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1PtrC>, FMFunc1PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2PtrC>, FMFunc2PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0CPtr>, FMFunc0CPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1CPtr>, FMFunc1CPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2CPtr>, FMFunc2CPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0CPtrC>, FMFunc0CPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1CPtrC>, FMFunc1CPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2CPtrC>, FMFunc2CPtrC &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc0El>, PFFunc0El &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc1El>, PFFunc1El &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc2El>, PFFunc2El &>);
static_assert(cIsSame<TCAddLValueReference<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc0ElRRef>, FFunc0ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc1ElRRef>, FFunc1ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc2ElRRef>, FFunc2ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc0ElPtr>, FFunc0ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc1ElPtr>, FFunc1ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc2ElPtr>, FFunc2ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc0ElPtrC>, FFunc0ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FFunc1ElPtrC>, FFunc1ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FFunc2ElPtrC>, FFunc2ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0ElPtr>, FMFunc0ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1ElPtr>, FMFunc1ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2ElPtr>, FMFunc2ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0ElPtrC>, FMFunc0ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1ElPtrC>, FMFunc1ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2ElPtrC>, FMFunc2ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0ElCPtr>, FMFunc0ElCPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1ElCPtr>, FMFunc1ElCPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2ElCPtr>, FMFunc2ElCPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0ElCPtrC>, FMFunc0ElCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1ElCPtrC>, FMFunc1ElCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2ElCPtrC>, FMFunc2ElCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CMPtr>, CMPtr &>);
static_assert(cIsSame<TCAddLValueReference<CMCPtr>, CMCPtr &>);
static_assert(cIsSame<TCAddLValueReference<CMPtrC>, CMPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CMCPtrC>, CMCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CTestArray2>, CTestArray2 &>);
static_assert(cIsSame<TCAddLValueReference<CTestArray2C>, CTestArray2C &>);
static_assert(cIsSame<TCAddLValueReference<CTestArray>, CTestArray &>);
static_assert(cIsSame<TCAddLValueReference<CTestArrayC>, CTestArrayC &>);
static_assert(cIsSame<TCAddLValueReference<CTest2DArray2>, CTest2DArray2 &>);
static_assert(cIsSame<TCAddLValueReference<CTest2DArray2C>, CTest2DArray2C &>);
static_assert(cIsSame<TCAddLValueReference<CTest2DArray>, CTest2DArray &>);
static_assert(cIsSame<TCAddLValueReference<CTest2DArrayC>, CTest2DArrayC &>);
static_assert(cIsSame<TCAddLValueReference<CTest3DArray2>, CTest3DArray2 &>);
static_assert(cIsSame<TCAddLValueReference<CTest3DArray2C>, CTest3DArray2C &>);
static_assert(cIsSame<TCAddLValueReference<CTest3DArray>, CTest3DArray &>);
static_assert(cIsSame<TCAddLValueReference<CTest3DArrayC>, CTest3DArrayC &>);
static_assert(cIsSame<TCAddLValueReference<void *>, void *&>);
static_assert(cIsSame<TCAddLValueReference<void>, void>);

// Remove pointer
static_assert(cIsSame<TCRemoveReference<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCRemoveReference<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCRemoveReference<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCRemoveReference<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCRemoveReference<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCRemoveReference<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCRemoveReference<CTestClass>, CTestClass>);
static_assert(cIsSame<TCRemoveReference<CTestC>, CTestC>);
static_assert(cIsSame<TCRemoveReference<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCRemoveReference<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCRemoveReference<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCRemoveReference<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCRemoveReference<CTestRef>, CTestClass>);
static_assert(cIsSame<TCRemoveReference<CTestCRef>, CTestC>);
static_assert(cIsSame<TCRemoveReference<CTestRRef>, CTestClass>);
static_assert(cIsSame<TCRemoveReference<CTestCRRef>, CTestC>);
static_assert(cIsSame<TCRemoveReference<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCRemoveReference<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCRemoveReference<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCRemoveReference<FFunc0Ref>, PFFunc0>);
static_assert(cIsSame<TCRemoveReference<FFunc1Ref>, PFFunc1>);
static_assert(cIsSame<TCRemoveReference<FFunc2Ref>, PFFunc2>);
static_assert(cIsSame<TCRemoveReference<FFunc0RRef>, PFFunc0>);
static_assert(cIsSame<TCRemoveReference<FFunc1RRef>, PFFunc1>);
static_assert(cIsSame<TCRemoveReference<FFunc2RRef>, PFFunc2>);
static_assert(cIsSame<TCRemoveReference<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCRemoveReference<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCRemoveReference<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCRemoveReference<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCRemoveReference<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCRemoveReference<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCRemoveReference<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCRemoveReference<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCRemoveReference<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCRemoveReference<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCRemoveReference<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCRemoveReference<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCRemoveReference<FFunc0ElRef>, PFFunc0El>);
static_assert(cIsSame<TCRemoveReference<FFunc1ElRef>, PFFunc1El>);
static_assert(cIsSame<TCRemoveReference<FFunc2ElRef>, PFFunc2El>);
static_assert(cIsSame<TCRemoveReference<FFunc0ElRRef>, PFFunc0El>);
static_assert(cIsSame<TCRemoveReference<FFunc1ElRRef>, PFFunc1El>);
static_assert(cIsSame<TCRemoveReference<FFunc2ElRRef>, PFFunc2El>);
static_assert(cIsSame<TCRemoveReference<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCRemoveReference<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCRemoveReference<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCRemoveReference<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveReference<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveReference<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCRemoveReference<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCRemoveReference<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCRemoveReference<CMPtr>, CMPtr>);
static_assert(cIsSame<TCRemoveReference<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCRemoveReference<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCRemoveReference<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCRemoveReference<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCRemoveReference<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCRemoveReference<CTestArray>, CTestArray>);
static_assert(cIsSame<TCRemoveReference<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCRemoveReference<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCRemoveReference<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCRemoveReference<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCRemoveReference<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCRemoveReference<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCRemoveReference<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCRemoveReference<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCRemoveReference<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCRemoveReference<void *>, void *>);
static_assert(cIsSame<TCRemoveReference<void *&>, void *>);
static_assert(cIsSame<TCRemoveReference<void>, void>);


// Storable
static_assert(cIsSame<TCRemoveReferenceStorable<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCRemoveReferenceStorable<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestClass>, CTestClass>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestC>, CTestC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestRef>, CTestClass>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestCRef>, CTestC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestRRef>, CTestClass>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestCRRef>, CTestC>);
static_assert(cIsSame<TCRemoveReferenceStorable<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCRemoveReferenceStorable<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCRemoveReferenceStorable<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCRemoveReferenceStorable<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCRemoveReferenceStorable<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CMPtr>, CMPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCRemoveReferenceStorable<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestArray>, CTestArray>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCRemoveReferenceStorable<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCRemoveReferenceStorable<void *>, void *>);
static_assert(cIsSame<TCRemoveReferenceStorable<void *&>, void *>);
static_assert(cIsSame<TCRemoveReferenceStorable<void>, void>);



// Copy refernce

static_assert(cIsSame<TCCopyReference<int, int>, int>);
static_assert(cIsSame<TCCopyReference<int, int &>, int>);
static_assert(cIsSame<TCCopyReference<int, int &&>, int>);
static_assert(cIsSame<TCCopyReference<int &, int>, int &>);
static_assert(cIsSame<TCCopyReference<int &, int &>, int &>);
static_assert(cIsSame<TCCopyReference<int &, int &&>, int &>);
static_assert(cIsSame<TCCopyReference<int &&, int>, int &&>);
static_assert(cIsSame<TCCopyReference<int &&, int &>, int &&>);
static_assert(cIsSame<TCCopyReference<int &&, int &&>, int &&>);

static_assert(cIsSame<TCCopyReference<CTestUnion, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestClass0, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestClass1, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestStruct0, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestStruct1, int>, int>);
static_assert(cIsSame<TCCopyReference<ETestEnum, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestClass, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestC, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestCPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestCPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestRef, int>, int &>);
static_assert(cIsSame<TCCopyReference<CTestCRef, int>, int &>);
static_assert(cIsSame<TCCopyReference<CTestRRef, int>, int &&>);
static_assert(cIsSame<TCCopyReference<CTestCRRef, int>, int &&>);
static_assert(cIsSame<TCCopyReference<PFFunc0, int>, int>);
static_assert(cIsSame<TCCopyReference<PFFunc1, int>, int>);
static_assert(cIsSame<TCCopyReference<PFFunc2, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc0Ref, int>, int &>);
static_assert(cIsSame<TCCopyReference<FFunc1Ref, int>, int &>);
static_assert(cIsSame<TCCopyReference<FFunc2Ref, int>, int &>);
static_assert(cIsSame<TCCopyReference<FFunc0RRef, int>, int &&>);
static_assert(cIsSame<TCCopyReference<FFunc1RRef, int>, int &&>);
static_assert(cIsSame<TCCopyReference<FFunc2RRef, int>, int &&>);
static_assert(cIsSame<TCCopyReference<FFunc0Ptr, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc1Ptr, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc2Ptr, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc0PtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc1PtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc2PtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc0Ptr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc1Ptr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc2Ptr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc0PtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc1PtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc2PtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc0CPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc1CPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc2CPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc0CPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc1CPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc2CPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<PFFunc0El, int>, int>);
static_assert(cIsSame<TCCopyReference<PFFunc1El, int>, int>);
static_assert(cIsSame<TCCopyReference<PFFunc2El, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc0ElRef, int>, int &>);
static_assert(cIsSame<TCCopyReference<FFunc1ElRef, int>, int &>);
static_assert(cIsSame<TCCopyReference<FFunc2ElRef, int>, int &>);
static_assert(cIsSame<TCCopyReference<FFunc0ElRRef, int>, int &&>);
static_assert(cIsSame<TCCopyReference<FFunc1ElRRef, int>, int &&>);
static_assert(cIsSame<TCCopyReference<FFunc2ElRRef, int>, int &&>);
static_assert(cIsSame<TCCopyReference<FFunc0ElPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc1ElPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc2ElPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc0ElPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc1ElPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FFunc2ElPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc0ElPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc1ElPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc2ElPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc0ElPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc1ElPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc2ElPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc0ElCPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc1ElCPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc2ElCPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc0ElCPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc1ElCPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<FMFunc2ElCPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<CMPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<CMCPtr, int>, int>);
static_assert(cIsSame<TCCopyReference<CMPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<CMCPtrC, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestArray2, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestArray2C, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestArray, int>, int>);
static_assert(cIsSame<TCCopyReference<CTestArrayC, int>, int>);
static_assert(cIsSame<TCCopyReference<CTest2DArray2, int>, int>);
static_assert(cIsSame<TCCopyReference<CTest2DArray2C, int>, int>);
static_assert(cIsSame<TCCopyReference<CTest2DArray, int>, int>);
static_assert(cIsSame<TCCopyReference<CTest2DArrayC, int>, int>);
static_assert(cIsSame<TCCopyReference<CTest3DArray2, int>, int>);
static_assert(cIsSame<TCCopyReference<CTest3DArray2C, int>, int>);
static_assert(cIsSame<TCCopyReference<CTest3DArray, int>, int>);
static_assert(cIsSame<TCCopyReference<CTest3DArrayC, int>, int>);
static_assert(cIsSame<TCCopyReference<void *, int>, int>);
static_assert(cIsSame<TCCopyReference<void *&, int>, int &>);
static_assert(cIsSame<TCCopyReference<void, int>, int>);
