// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

// Largest type
static_assert(cIsSame<TCLargestType<CTestStruct1, CTestStruct0>, CTestStruct1>);
static_assert(cIsSame<TCLargestType<CTestUnion, CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCLargestType<const CTestUnion, const CTestUnion>, const CTestUnion>);
static_assert(cIsSame<TCLargestType<CTestClass0, CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCLargestType<CTestClass1, CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCLargestType<CTestStruct0, CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCLargestType<CTestStruct1, CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCLargestType<ETestEnum, ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCLargestType<CTestClass, CTestClass>, CTestClass>);
static_assert(cIsSame<TCLargestType<CTestC, CTestC>, CTestC>);
static_assert(cIsSame<TCLargestType<CTestPtr, CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCLargestType<CTestCPtr, CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCLargestType<CTestPtrC, CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCLargestType<CTestCPtrC, CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCLargestType<CTestRef, CTestRef>, CTestRef>);
static_assert(cIsSame<TCLargestType<CTestCRef, CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCLargestType<CTestRRef, CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCLargestType<CTestCRRef, CTestCRRef>, CTestCRRef>);
/*
static_assert(cIsSame<TCLargestType<PFFunc0, PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCLargestType<PFFunc1, PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCLargestType<PFFunc2, PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCLargestType<FFunc0Ref, FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCLargestType<FFunc1Ref, FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCLargestType<FFunc2Ref, FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCLargestType<FFunc0RRef, FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCLargestType<FFunc1RRef, FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCLargestType<FFunc2RRef, FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCLargestType<FFunc0Ptr, FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCLargestType<FFunc1Ptr, FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCLargestType<FFunc2Ptr, FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCLargestType<FFunc0PtrC, FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCLargestType<FFunc1PtrC, FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCLargestType<FFunc2PtrC, FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCLargestType<FMFunc0Ptr, FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCLargestType<FMFunc1Ptr, FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCLargestType<FMFunc2Ptr, FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCLargestType<FMFunc0PtrC, FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCLargestType<FMFunc1PtrC, FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCLargestType<FMFunc2PtrC, FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCLargestType<FMFunc0CPtr, FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCLargestType<FMFunc1CPtr, FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCLargestType<FMFunc2CPtr, FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCLargestType<FMFunc0CPtrC, FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCLargestType<FMFunc1CPtrC, FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCLargestType<FMFunc2CPtrC, FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCLargestType<PFFunc0El, PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCLargestType<PFFunc1El, PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCLargestType<PFFunc2El, PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCLargestType<FFunc0ElRef, FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCLargestType<FFunc1ElRef, FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCLargestType<FFunc2ElRef, FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCLargestType<FFunc0ElRRef, FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCLargestType<FFunc1ElRRef, FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCLargestType<FFunc2ElRRef, FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCLargestType<FFunc0ElPtr, FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCLargestType<FFunc1ElPtr, FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCLargestType<FFunc2ElPtr, FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCLargestType<FFunc0ElPtrC, FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCLargestType<FFunc1ElPtrC, FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCLargestType<FFunc2ElPtrC, FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCLargestType<FMFunc0ElPtr, FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCLargestType<FMFunc1ElPtr, FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCLargestType<FMFunc2ElPtr, FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCLargestType<FMFunc0ElPtrC, FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCLargestType<FMFunc1ElPtrC, FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCLargestType<FMFunc2ElPtrC, FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCLargestType<FMFunc0ElCPtr, FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCLargestType<FMFunc1ElCPtr, FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCLargestType<FMFunc2ElCPtr, FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCLargestType<FMFunc0ElCPtrC, FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCLargestType<FMFunc1ElCPtrC, FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCLargestType<FMFunc2ElCPtrC, FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
*/
static_assert(cIsSame<TCLargestType<CMPtr, CMPtr>, CMPtr>);
static_assert(cIsSame<TCLargestType<CMCPtr, CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCLargestType<CMPtrC, CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCLargestType<CMCPtrC, CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCLargestType<CTestArray2, CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCLargestType<CTestArray2C, CTestArray2C>, CTestArray2C>);
//static_assert(cIsSame<TCLargestType<CTestArray, CTestArray>, CTestArray>);
//static_assert(cIsSame<TCLargestType<CTestArrayC, CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCLargestType<CTest2DArray2, CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCLargestType<CTest2DArray2C, CTest2DArray2C>, CTest2DArray2C>);
//static_assert(cIsSame<TCLargestType<CTest2DArray, CTest2DArray>, CTest2DArray>);
//static_assert(cIsSame<TCLargestType<CTest2DArrayC, CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCLargestType<CTest3DArray2, CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCLargestType<CTest3DArray2C, CTest3DArray2C>, CTest3DArray2C>);
//static_assert(cIsSame<TCLargestType<CTest3DArray, CTest3DArray>, CTest3DArray>);
//static_assert(cIsSame<TCLargestType<CTest3DArrayC, CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCLargestType<void *, void *>, void *>);
//static_assert(cIsSame<TCLargestType<void, void>, void>);

// Smallest type
static_assert(cIsSame<TCSmallestType<CTestStruct1, CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCSmallestType<CTestUnion, CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCSmallestType<CTestClass0, CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCSmallestType<CTestClass1, CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCSmallestType<CTestStruct0, CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCSmallestType<CTestStruct1, CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCSmallestType<ETestEnum, ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCSmallestType<CTestClass, CTestClass>, CTestClass>);
static_assert(cIsSame<TCSmallestType<CTestC, CTestC>, CTestC>);
static_assert(cIsSame<TCSmallestType<CTestPtr, CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCSmallestType<CTestCPtr, CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCSmallestType<CTestPtrC, CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCSmallestType<CTestCPtrC, CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCSmallestType<CTestRef, CTestRef>, CTestRef>);
static_assert(cIsSame<TCSmallestType<CTestCRef, CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCSmallestType<CTestRRef, CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCSmallestType<CTestCRRef, CTestCRRef>, CTestCRRef>);
/*static_assert(cIsSame<TCSmallestType<PFFunc0, PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCSmallestType<PFFunc1, PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCSmallestType<PFFunc2, PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCSmallestType<FFunc0Ref, FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCSmallestType<FFunc1Ref, FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCSmallestType<FFunc2Ref, FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCSmallestType<FFunc0RRef, FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCSmallestType<FFunc1RRef, FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCSmallestType<FFunc2RRef, FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCSmallestType<FFunc0Ptr, FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCSmallestType<FFunc1Ptr, FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCSmallestType<FFunc2Ptr, FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCSmallestType<FFunc0PtrC, FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCSmallestType<FFunc1PtrC, FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCSmallestType<FFunc2PtrC, FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc0Ptr, FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCSmallestType<FMFunc1Ptr, FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCSmallestType<FMFunc2Ptr, FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCSmallestType<FMFunc0PtrC, FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc1PtrC, FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc2PtrC, FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc0CPtr, FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc1CPtr, FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc2CPtr, FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc0CPtrC, FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc1CPtrC, FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc2CPtrC, FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCSmallestType<PFFunc0El, PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCSmallestType<PFFunc1El, PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCSmallestType<PFFunc2El, PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCSmallestType<FFunc0ElRef, FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCSmallestType<FFunc1ElRef, FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCSmallestType<FFunc2ElRef, FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCSmallestType<FFunc0ElRRef, FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCSmallestType<FFunc1ElRRef, FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCSmallestType<FFunc2ElRRef, FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCSmallestType<FFunc0ElPtr, FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCSmallestType<FFunc1ElPtr, FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCSmallestType<FFunc2ElPtr, FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCSmallestType<FFunc0ElPtrC, FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCSmallestType<FFunc1ElPtrC, FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCSmallestType<FFunc2ElPtrC, FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc0ElPtr, FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc1ElPtr, FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc2ElPtr, FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc0ElPtrC, FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc1ElPtrC, FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc2ElPtrC, FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc0ElCPtr, FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc1ElCPtr, FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc2ElCPtr, FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCSmallestType<FMFunc0ElCPtrC, FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc1ElCPtrC, FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCSmallestType<FMFunc2ElCPtrC, FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
*/
static_assert(cIsSame<TCSmallestType<CMPtr, CMPtr>, CMPtr>);
static_assert(cIsSame<TCSmallestType<CMCPtr, CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCSmallestType<CMPtrC, CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCSmallestType<CMCPtrC, CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCSmallestType<CTestArray2, CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCSmallestType<CTestArray2C, CTestArray2C>, CTestArray2C>);
//static_assert(cIsSame<TCSmallestType<CTestArray, CTestArray>, CTestArray>);
//static_assert(cIsSame<TCSmallestType<CTestArrayC, CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCSmallestType<CTest2DArray2, CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCSmallestType<CTest2DArray2C, CTest2DArray2C>, CTest2DArray2C>);
//static_assert(cIsSame<TCSmallestType<CTest2DArray, CTest2DArray>, CTest2DArray>);
//static_assert(cIsSame<TCSmallestType<CTest2DArrayC, CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCSmallestType<CTest3DArray2, CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCSmallestType<CTest3DArray2C, CTest3DArray2C>, CTest3DArray2C>);
//static_assert(cIsSame<TCSmallestType<CTest3DArray, CTest3DArray>, CTest3DArray>);
//static_assert(cIsSame<TCSmallestType<CTest3DArrayC, CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCSmallestType<void *, void *>, void *>);
//static_assert(cIsSame<TCSmallestType<void, void>, void>);

// Smaller type
static_assert(cIsSame<TCSmallerType<int16384>, int8192>);
static_assert(cIsSame<TCSmallerType<int8192>, int4096>);
static_assert(cIsSame<TCSmallerType<int4096>, int2048>);
static_assert(cIsSame<TCSmallerType<int2048>, int1024>);
static_assert(cIsSame<TCSmallerType<int1024>, int512>);
static_assert(cIsSame<TCSmallerType<int512>, int256>);
static_assert(cIsSame<TCSmallerType<int256>, int128>);
static_assert(cIsSame<TCSmallerType<int160>, int80>);
static_assert(cIsSame<TCSmallerType<int192>, int96>);
static_assert(cIsSame<TCSmallerType<int128>, int64>);
static_assert(cIsSame<TCSmallerType<int64>, int32>);
static_assert(cIsSame<TCSmallerType<int32>, int16>);
static_assert(cIsSame<TCSmallerType<int16>, int8>);
static_assert(cIsSame<TCSmallerType<int8>, int8>);

static_assert(cIsSame<TCSmallerType<uint16384>, uint8192>);
static_assert(cIsSame<TCSmallerType<uint8192>, uint4096>);
static_assert(cIsSame<TCSmallerType<uint4096>, uint2048>);
static_assert(cIsSame<TCSmallerType<uint2048>, uint1024>);
static_assert(cIsSame<TCSmallerType<uint1024>, uint512>);
static_assert(cIsSame<TCSmallerType<uint512>, uint256>);
static_assert(cIsSame<TCSmallerType<uint256>, uint128>);
static_assert(cIsSame<TCSmallerType<uint160>, uint80>);
static_assert(cIsSame<TCSmallerType<uint192>, uint96>);
static_assert(cIsSame<TCSmallerType<uint128>, uint64>);
static_assert(cIsSame<TCSmallerType<uint64>, uint32>);
static_assert(cIsSame<TCSmallerType<uint32>, uint16>);
static_assert(cIsSame<TCSmallerType<uint16>, uint8>);
static_assert(cIsSame<TCSmallerType<uint8>, uint8>);

static_assert(cIsSame<TCSmallerType<fp4096>, fp2048>);
static_assert(cIsSame<TCSmallerType<fp2048>, fp1024>);
static_assert(cIsSame<TCSmallerType<fp1024>, fp512>);
static_assert(cIsSame<TCSmallerType<fp512>, fp256>);
static_assert(cIsSame<TCSmallerType<fp256>, fp128>);
static_assert(cIsSame<TCSmallerType<fp128>, fp64>);
static_assert(cIsSame<TCSmallerType<fp64>, fp32>);
static_assert(cIsSame<TCSmallerType<fp32>, fp16>);
static_assert(cIsSame<TCSmallerType<fp16>, fp8>);
static_assert(cIsSame<TCSmallerType<fp8>, fp8>);

static_assert(cIsSame<TCSmallerType<const int16384>, const int8192>);
static_assert(cIsSame<TCSmallerType<const int8192>, const int4096>);
static_assert(cIsSame<TCSmallerType<const int4096>, const int2048>);
static_assert(cIsSame<TCSmallerType<const int2048>, const int1024>);
static_assert(cIsSame<TCSmallerType<const int1024>, const int512>);
static_assert(cIsSame<TCSmallerType<const int512>, const int256>);
static_assert(cIsSame<TCSmallerType<const int256>, const int128>);
static_assert(cIsSame<TCSmallerType<const int160>, const int80>);
static_assert(cIsSame<TCSmallerType<const int192>, const int96>);
static_assert(cIsSame<TCSmallerType<const int128>, const int64>);
static_assert(cIsSame<TCSmallerType<const int64>, const int32>);
static_assert(cIsSame<TCSmallerType<const int32>, const int16>);
static_assert(cIsSame<TCSmallerType<const int16>, const int8>);
static_assert(cIsSame<TCSmallerType<const int8>, const int8>);

static_assert(cIsSame<TCSmallerType<const uint16384>, const uint8192>);
static_assert(cIsSame<TCSmallerType<const uint8192>, const uint4096>);
static_assert(cIsSame<TCSmallerType<const uint4096>, const uint2048>);
static_assert(cIsSame<TCSmallerType<const uint2048>, const uint1024>);
static_assert(cIsSame<TCSmallerType<const uint1024>, const uint512>);
static_assert(cIsSame<TCSmallerType<const uint512>, const uint256>);
static_assert(cIsSame<TCSmallerType<const uint256>, const uint128>);
static_assert(cIsSame<TCSmallerType<const uint160>, const uint80>);
static_assert(cIsSame<TCSmallerType<const uint192>, const uint96>);
static_assert(cIsSame<TCSmallerType<const uint128>, const uint64>);
static_assert(cIsSame<TCSmallerType<const uint64>, const uint32>);
static_assert(cIsSame<TCSmallerType<const uint32>, const uint16>);
static_assert(cIsSame<TCSmallerType<const uint16>, const uint8>);
static_assert(cIsSame<TCSmallerType<const uint8>, const uint8>);

static_assert(cIsSame<TCSmallerType<const fp4096>, const fp2048>);
static_assert(cIsSame<TCSmallerType<const fp2048>, const fp1024>);
static_assert(cIsSame<TCSmallerType<const fp1024>, const fp512>);
static_assert(cIsSame<TCSmallerType<const fp512>, const fp256>);
static_assert(cIsSame<TCSmallerType<const fp256>, const fp128>);
static_assert(cIsSame<TCSmallerType<const fp128>, const fp64>);
static_assert(cIsSame<TCSmallerType<const fp64>, const fp32>);
static_assert(cIsSame<TCSmallerType<const fp32>, const fp16>);
static_assert(cIsSame<TCSmallerType<const fp16>, const fp8>);
static_assert(cIsSame<TCSmallerType<const fp8>, const fp8>);

static_assert(cIsSame<TCSmallerType<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCSmallerType<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCSmallerType<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCSmallerType<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCSmallerType<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCSmallerType<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCSmallerType<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCSmallerType<CTestClass>, CTestClass>);
static_assert(cIsSame<TCSmallerType<CTestC>, CTestC>);
static_assert(cIsSame<TCSmallerType<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCSmallerType<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCSmallerType<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCSmallerType<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCSmallerType<CTestRef>, CTestRef>);
static_assert(cIsSame<TCSmallerType<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCSmallerType<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCSmallerType<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCSmallerType<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCSmallerType<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCSmallerType<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCSmallerType<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCSmallerType<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCSmallerType<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCSmallerType<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCSmallerType<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCSmallerType<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCSmallerType<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCSmallerType<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCSmallerType<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCSmallerType<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCSmallerType<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCSmallerType<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCSmallerType<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCSmallerType<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCSmallerType<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCSmallerType<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCSmallerType<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCSmallerType<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCSmallerType<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCSmallerType<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCSmallerType<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCSmallerType<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCSmallerType<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCSmallerType<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCSmallerType<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCSmallerType<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCSmallerType<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCSmallerType<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCSmallerType<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCSmallerType<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCSmallerType<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCSmallerType<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCSmallerType<CMPtr>, CMPtr>);
static_assert(cIsSame<TCSmallerType<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCSmallerType<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCSmallerType<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCSmallerType<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCSmallerType<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCSmallerType<CTestArray>, CTestArray>);
static_assert(cIsSame<TCSmallerType<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCSmallerType<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCSmallerType<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCSmallerType<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCSmallerType<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCSmallerType<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCSmallerType<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCSmallerType<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCSmallerType<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCSmallerType<void *>, void *>);
static_assert(cIsSame<TCSmallerType<void>, void>);

// Larger type
static_assert(cIsSame<TCLargerType<int8192>, int16384>);
static_assert(cIsSame<TCLargerType<int4096>, int8192>);
static_assert(cIsSame<TCLargerType<int2048>, int4096>);
static_assert(cIsSame<TCLargerType<int1024>, int2048>);
static_assert(cIsSame<TCLargerType<int512>, int1024>);
static_assert(cIsSame<TCLargerType<int256>, int512>);
static_assert(cIsSame<TCLargerType<int128>, int256>);
static_assert(cIsSame<TCLargerType<int80>, int160>);
static_assert(cIsSame<TCLargerType<int96>, int192>);
static_assert(cIsSame<TCLargerType<int64>, int128>);
static_assert(cIsSame<TCLargerType<int32>, int64>);
static_assert(cIsSame<TCLargerType<int16>, int32>);
static_assert(cIsSame<TCLargerType<int8>, int16>);

static_assert(cIsSame<TCLargerType<uint8192>, uint16384>);
static_assert(cIsSame<TCLargerType<uint4096>, uint8192>);
static_assert(cIsSame<TCLargerType<uint2048>, uint4096>);
static_assert(cIsSame<TCLargerType<uint1024>, uint2048>);
static_assert(cIsSame<TCLargerType<uint512>, uint1024>);
static_assert(cIsSame<TCLargerType<uint256>, uint512>);
static_assert(cIsSame<TCLargerType<uint128>, uint256>);
static_assert(cIsSame<TCLargerType<uint80>, uint160>);
static_assert(cIsSame<TCLargerType<uint96>, uint192>);
static_assert(cIsSame<TCLargerType<uint64>, uint128>);
static_assert(cIsSame<TCLargerType<uint32>, uint64>);
static_assert(cIsSame<TCLargerType<uint16>, uint32>);
static_assert(cIsSame<TCLargerType<uint8>, uint16>);

static_assert(cIsSame<TCLargerType<fp2048>, fp4096>);
static_assert(cIsSame<TCLargerType<fp1024>, fp2048>);
static_assert(cIsSame<TCLargerType<fp512>, fp1024>);
static_assert(cIsSame<TCLargerType<fp256>, fp512>);
static_assert(cIsSame<TCLargerType<fp128>, fp256>);
static_assert(cIsSame<TCLargerType<fp64>, fp128>);
static_assert(cIsSame<TCLargerType<fp32>, fp64>);
static_assert(cIsSame<TCLargerType<fp16>, fp32>);
static_assert(cIsSame<TCLargerType<fp8>, fp16>);

static_assert(cIsSame<TCLargerType<const int8192>, const int16384>);
static_assert(cIsSame<TCLargerType<const int4096>, const int8192>);
static_assert(cIsSame<TCLargerType<const int2048>, const int4096>);
static_assert(cIsSame<TCLargerType<const int1024>, const int2048>);
static_assert(cIsSame<TCLargerType<const int512>, const int1024>);
static_assert(cIsSame<TCLargerType<const int256>, const int512>);
static_assert(cIsSame<TCLargerType<const int128>, const int256>);
static_assert(cIsSame<TCLargerType<const int80>, const int160>);
static_assert(cIsSame<TCLargerType<const int96>, const int192>);
static_assert(cIsSame<TCLargerType<const int64>, const int128>);
static_assert(cIsSame<TCLargerType<const int32>, const int64>);
static_assert(cIsSame<TCLargerType<const int16>, const int32>);
static_assert(cIsSame<TCLargerType<const int8>, const int16>);

static_assert(cIsSame<TCLargerType<const uint8192>, const uint16384>);
static_assert(cIsSame<TCLargerType<const uint4096>, const uint8192>);
static_assert(cIsSame<TCLargerType<const uint2048>, const uint4096>);
static_assert(cIsSame<TCLargerType<const uint1024>, const uint2048>);
static_assert(cIsSame<TCLargerType<const uint512>, const uint1024>);
static_assert(cIsSame<TCLargerType<const uint256>, const uint512>);
static_assert(cIsSame<TCLargerType<const uint128>, const uint256>);
static_assert(cIsSame<TCLargerType<const uint80>, const uint160>);
static_assert(cIsSame<TCLargerType<const uint96>, const uint192>);
static_assert(cIsSame<TCLargerType<const uint64>, const uint128>);
static_assert(cIsSame<TCLargerType<const uint32>, const uint64>);
static_assert(cIsSame<TCLargerType<const uint16>, const uint32>);
static_assert(cIsSame<TCLargerType<const uint8>, const uint16>);

static_assert(cIsSame<TCLargerType<const fp2048>, const fp4096>);
static_assert(cIsSame<TCLargerType<const fp1024>, const fp2048>);
static_assert(cIsSame<TCLargerType<const fp512>, const fp1024>);
static_assert(cIsSame<TCLargerType<const fp256>, const fp512>);
static_assert(cIsSame<TCLargerType<const fp128>, const fp256>);
static_assert(cIsSame<TCLargerType<const fp64>, const fp128>);
static_assert(cIsSame<TCLargerType<const fp32>, const fp64>);
static_assert(cIsSame<TCLargerType<const fp16>, const fp32>);
static_assert(cIsSame<TCLargerType<const fp8>, const fp16>);

static_assert(cIsSame<TCLargerType<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCLargerType<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCLargerType<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCLargerType<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCLargerType<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCLargerType<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCLargerType<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCLargerType<CTestClass>, CTestClass>);
static_assert(cIsSame<TCLargerType<CTestC>, CTestC>);
static_assert(cIsSame<TCLargerType<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCLargerType<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCLargerType<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCLargerType<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCLargerType<CTestRef>, CTestRef>);
static_assert(cIsSame<TCLargerType<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCLargerType<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCLargerType<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCLargerType<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCLargerType<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCLargerType<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCLargerType<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCLargerType<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCLargerType<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCLargerType<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCLargerType<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCLargerType<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCLargerType<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCLargerType<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCLargerType<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCLargerType<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCLargerType<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCLargerType<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCLargerType<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCLargerType<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCLargerType<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCLargerType<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCLargerType<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCLargerType<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCLargerType<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCLargerType<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCLargerType<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCLargerType<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCLargerType<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCLargerType<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCLargerType<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCLargerType<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCLargerType<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCLargerType<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCLargerType<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCLargerType<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCLargerType<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCLargerType<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCLargerType<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCLargerType<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCLargerType<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCLargerType<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCLargerType<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCLargerType<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCLargerType<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCLargerType<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCLargerType<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCLargerType<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCLargerType<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCLargerType<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCLargerType<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCLargerType<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCLargerType<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCLargerType<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCLargerType<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCLargerType<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCLargerType<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCLargerType<CMPtr>, CMPtr>);
static_assert(cIsSame<TCLargerType<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCLargerType<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCLargerType<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCLargerType<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCLargerType<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCLargerType<CTestArray>, CTestArray>);
static_assert(cIsSame<TCLargerType<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCLargerType<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCLargerType<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCLargerType<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCLargerType<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCLargerType<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCLargerType<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCLargerType<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCLargerType<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCLargerType<void *>, void *>);
static_assert(cIsSame<TCLargerType<void>, void>);

