// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsRValueReference<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<ETestEnum>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestClass>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CTestCV>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CTestPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTestRef>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestVRef>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCVRef>::mc_Value		));
DMibStaticCheck((	TCIsRValueReference<CTestRRef>::mc_Value		));
DMibStaticCheck((	TCIsRValueReference<CTestCRRef>::mc_Value		));
DMibStaticCheck((	TCIsRValueReference<CTestVRRef>::mc_Value		));
DMibStaticCheck((	TCIsRValueReference<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<FFunc0Ref>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc1Ref>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc2Ref>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc0RRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc1RRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc2RRef>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<FFunc0ElRef>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc1ElRef>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc2ElRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc0ElRRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc1ElRRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc2ElRRef>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CMPtr>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CMPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CMPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CMVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CMCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTestArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTestArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArray>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArrayV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArray>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArrayV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<void *>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<void>::mc_Value			));



DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestUnion>::CType, CTestUnion &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestClass0>::CType, CTestClass0 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestClass1>::CType, CTestClass1 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestStruct0>::CType, CTestStruct0 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestStruct1>::CType, CTestStruct1 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<ETestEnum>::CType, ETestEnum &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestClass>::CType, CTestClass &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestC>::CType, CTestC &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestV>::CType, CTestV &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCV>::CType, CTestCV &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestPtr>::CType, CTestPtr &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCPtr>::CType, CTestCPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestVPtr>::CType, CTestVPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCVPtr>::CType, CTestCVPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestPtrC>::CType, CTestPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCPtrC>::CType, CTestCPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestVPtrC>::CType, CTestVPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCVPtrC>::CType, CTestCVPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestPtrV>::CType, CTestPtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCPtrV>::CType, CTestCPtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestVPtrV>::CType, CTestVPtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCVPtrV>::CType, CTestCVPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestPtrCV>::CType, CTestPtrCV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCPtrCV>::CType, CTestCPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestVPtrCV>::CType, CTestVPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCVPtrCV>::CType, CTestCVPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestRef>::CType, CTestRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCRef>::CType, CTestCRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestVRef>::CType, CTestVRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCVRef>::CType, CTestCVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestRRef>::CType, CTestRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCRRef>::CType, CTestCRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestVRRef>::CType, CTestVRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCVRRef>::CType, CTestCVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc0>::CType, PFFunc0 &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc1>::CType, PFFunc1 &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc2>::CType, PFFunc2 &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0Ref>::CType, FFunc0RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1Ref>::CType, FFunc1RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2Ref>::CType, FFunc2RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0RRef>::CType, FFunc0RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1RRef>::CType, FFunc1RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2RRef>::CType, FFunc2RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0Ptr>::CType, FFunc0Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1Ptr>::CType, FFunc1Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2Ptr>::CType, FFunc2Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0PtrC>::CType, FFunc0PtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1PtrC>::CType, FFunc1PtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2PtrC>::CType, FFunc2PtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0PtrV>::CType, FFunc0PtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1PtrV>::CType, FFunc1PtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2PtrV>::CType, FFunc2PtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0PtrCV>::CType, FFunc0PtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1PtrCV>::CType, FFunc1PtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2PtrCV>::CType, FFunc2PtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0Ptr>::CType, FMFunc0Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1Ptr>::CType, FMFunc1Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2Ptr>::CType, FMFunc2Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0PtrC>::CType, FMFunc0PtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1PtrC>::CType, FMFunc1PtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2PtrC>::CType, FMFunc2PtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0PtrV>::CType, FMFunc0PtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1PtrV>::CType, FMFunc1PtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2PtrV>::CType, FMFunc2PtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0PtrCV>::CType, FMFunc0PtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1PtrCV>::CType, FMFunc1PtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2PtrCV>::CType, FMFunc2PtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CPtr>::CType, FMFunc0CPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CPtr>::CType, FMFunc1CPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CPtr>::CType, FMFunc2CPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CPtrV>::CType, FMFunc0CPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CPtrV>::CType, FMFunc1CPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CPtrV>::CType, FMFunc2CPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0VPtr>::CType, FMFunc0VPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1VPtr>::CType, FMFunc1VPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2VPtr>::CType, FMFunc2VPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0VPtrC>::CType, FMFunc0VPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1VPtrC>::CType, FMFunc1VPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2VPtrC>::CType, FMFunc2VPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0VPtrV>::CType, FMFunc0VPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1VPtrV>::CType, FMFunc1VPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2VPtrV>::CType, FMFunc2VPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CVPtr>::CType, FMFunc0CVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CVPtr>::CType, FMFunc1CVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CVPtr>::CType, FMFunc2CVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc0El>::CType, PFFunc0El &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc1El>::CType, PFFunc1El &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc2El>::CType, PFFunc2El &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElRef>::CType, FFunc0ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElRef>::CType, FFunc1ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElRef>::CType, FFunc2ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElPtr>::CType, FFunc0ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElPtr>::CType, FFunc1ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElPtr>::CType, FFunc2ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElPtrV>::CType, FFunc0ElPtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElPtrV>::CType, FFunc1ElPtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElPtrV>::CType, FFunc2ElPtrV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMPtr>::CType, CMPtr &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCPtr>::CType, CMCPtr &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMVPtr>::CType, CMVPtr &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCVPtr>::CType, CMCVPtr &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMPtrC>::CType, CMPtrC &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCPtrC>::CType, CMCPtrC &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMVPtrC>::CType, CMVPtrC &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCVPtrC>::CType, CMCVPtrC &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMPtrV>::CType, CMPtrV &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCPtrV>::CType, CMCPtrV &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMVPtrV>::CType, CMVPtrV &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCVPtrV>::CType, CMCVPtrV &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMPtrCV>::CType, CMPtrCV &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCPtrCV>::CType, CMCPtrCV &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMVPtrCV>::CType, CMVPtrCV &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCVPtrCV>::CType, CMCVPtrCV &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArray2>::CType, CTestArray2 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArray2C>::CType, CTestArray2C &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArray2V>::CType, CTestArray2V &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArray2CV>::CType, CTestArray2CV &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArray>::CType, CTestArray>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArrayC>::CType, CTestArrayC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArrayV>::CType, CTestArrayV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArrayCV>::CType, CTestArrayCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArray2>::CType, CTest2DArray2 &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArray2C>::CType, CTest2DArray2C &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArray2V>::CType, CTest2DArray2V &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArray2CV>::CType, CTest2DArray2CV &&>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArray>::CType, CTest2DArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArray2>::CType, CTest3DArray2 &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArray2C>::CType, CTest3DArray2C &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArray2V>::CType, CTest3DArray2V &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArray2CV>::CType, CTest3DArray2CV &&>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArray>::CType, CTest3DArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<void *>::CType, void *&&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<void>::CType, void>::mc_Value								));

// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestV>::CType, CTestV>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCV>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestPtr>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestVPtr>::CType, CTestVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCVPtr>::CType, CTestCVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCPtrC>::CType, CTestCPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestVPtrC>::CType, CTestVPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCVPtrC>::CType, CTestCVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestPtrV>::CType, CTestPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCPtrV>::CType, CTestCPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestVPtrV>::CType, CTestVPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCVPtrV>::CType, CTestCVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestPtrCV>::CType, CTestPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCPtrCV>::CType, CTestCPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestVPtrCV>::CType, CTestVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCVPtrCV>::CType, CTestCVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestVRef>::CType, CTestVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCVRef>::CType, CTestCVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestRRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCRRef>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestVRRef>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCVRRef>::CType, CTestCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0RRef>::CType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1RRef>::CType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2RRef>::CType, PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0PtrV>::CType, FFunc0PtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1PtrV>::CType, FFunc1PtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2PtrV>::CType, FFunc2PtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0PtrCV>::CType, FFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1PtrCV>::CType, FFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2PtrCV>::CType, FFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0PtrV>::CType, FMFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1PtrV>::CType, FMFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2PtrV>::CType, FMFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0PtrCV>::CType, FMFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1PtrCV>::CType, FMFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2PtrCV>::CType, FMFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CPtrV>::CType, FMFunc0CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CPtrV>::CType, FMFunc1CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CPtrV>::CType, FMFunc2CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0VPtr>::CType, FMFunc0VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1VPtr>::CType, FMFunc1VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2VPtr>::CType, FMFunc2VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0VPtrC>::CType, FMFunc0VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1VPtrC>::CType, FMFunc1VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2VPtrC>::CType, FMFunc2VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0VPtrV>::CType, FMFunc0VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1VPtrV>::CType, FMFunc1VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2VPtrV>::CType, FMFunc2VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CVPtr>::CType, FMFunc0CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CVPtr>::CType, FMFunc1CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CVPtr>::CType, FMFunc2CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElRRef>::CType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElRRef>::CType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElRRef>::CType, PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElPtrV>::CType, FFunc0ElPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElPtrV>::CType, FFunc1ElPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElPtrV>::CType, FFunc2ElPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMVPtr>::CType, CMVPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCVPtr>::CType, CMCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMPtrC>::CType, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMVPtrC>::CType, CMVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCVPtrC>::CType, CMCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMPtrV>::CType, CMPtrV>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCPtrV>::CType, CMCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMVPtrV>::CType, CMVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCVPtrV>::CType, CMCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMPtrCV>::CType, CMPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCPtrCV>::CType, CMCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMVPtrCV>::CType, CMVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCVPtrCV>::CType, CMCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArray2V>::CType, CTestArray2V>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArray2CV>::CType, CTestArray2CV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArrayV>::CType, CTestArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArrayCV>::CType, CTestArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArray2V>::CType, CTest2DArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArray2CV>::CType, CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArray2V>::CType, CTest3DArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArray2CV>::CType, CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<void *&&>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<void>::CType, void>::mc_Value							));
