// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

#if 1
//ndef DMibCompiler_GCC
// POD definition changed for C++0x, lets not check this yet
// Void

// Special POD testing
DMibStaticCheck((	!TCIsPOD<CTestClassVirtual>::mc_Value					));
DMibStaticCheck((	!TCIsPOD<CTestClassWithDestructor>::mc_Value			));
DMibStaticCheck((	!TCIsPOD<CTestClassWithDestructorNonTrivial>::mc_Value			));
DMibStaticCheck((	!TCIsPOD<CTestClassWithConstructor>::mc_Value			));
DMibStaticCheck((	!TCIsPOD<CTestClassWithConstructorNonTrivial>::mc_Value			));
DMibStaticCheck((	!TCIsPOD<CTestClassWithCopyConstructor>::mc_Value			));
DMibStaticCheck((	!TCIsPOD<CTestClassWithCopyConstructorNonTrivial>::mc_Value			));
DMibStaticCheck((	!TCIsPOD<CTestClassWithMoveConstructor>::mc_Value			));
DMibStaticCheck((	!TCIsPOD<CTestClassWithMoveConstructorNonTrivial>::mc_Value			));
DMibStaticCheck((	TCIsPOD<CTestClassWithEnum>::mc_Value			));
DMibStaticCheck((	TCIsPOD<CTestClassWithPrivate>::mc_Value			));
DMibStaticCheck((	!TCIsPOD<CTestClassWithBase>::mc_Value			));


DMibStaticCheck((	TCIsPOD<CTestUnion>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCIsPOD<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCIsPOD<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCIsPOD<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCIsPOD<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCIsPOD<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsPOD<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsPOD<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsPOD<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsPOD<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsPOD<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCIsPOD<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	TCIsPOD<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCIsPOD<ETestEnum>::mc_Value						));
DMibStaticCheck((	TCIsPOD<int>::mc_Value							));
DMibStaticCheck((	TCIsPOD<CTestClass>::mc_Value							));
DMibStaticCheck((	TCIsPOD<CTestC>::mc_Value							));
DMibStaticCheck((	TCIsPOD<CTestV>::mc_Value							));
DMibStaticCheck((	TCIsPOD<CTestCV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CTestPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPOD<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<CTestVRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<CTestCVRef>::mc_Value					));
DMibStaticCheck((	!TCIsPOD<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCIsPOD<CTestVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsPOD<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsPOD<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCIsPOD<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsPOD<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsPOD<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	TCIsPOD<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<CMPtr>::mc_Value							));
DMibStaticCheck((	TCIsPOD<CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMVPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMPtrV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsPOD<CTestArray2>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestArray2C>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestArray2V>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestArray>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestArrayC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestArrayV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	TCIsPOD<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	TCIsPOD<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<CTest2DArray>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	TCIsPOD<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	TCIsPOD<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<CTest3DArray>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	TCIsPOD<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	TCIsPOD<void *>::mc_Value						));
DMibStaticCheck((	TCIsPOD<void>::mc_Value							));

#endif