// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"


namespace NConvertible
{

	DMibStaticCheck((	TCIsConvertible<int, float>::mc_Value					));

	class CTestConvert
	{
	public:
		CTestConvert(int);
		operator int ();
	};

	class CTestConvert2
	{
	public:
		operator CTestConvert ();
	};
	class CTestInherit : public CTestClass
	{
	public:
		int m_Test;
	};
	
	DMibStaticCheck((	TCIsConvertible<CTestConvert, int>::mc_Value					));
	DMibStaticCheck((	TCIsConvertible<int, CTestConvert>::mc_Value					));
	DMibStaticCheck((	!TCIsConvertible<CTestConvert, char *>::mc_Value					));
	DMibStaticCheck((	!TCIsConvertible<char *, CTestConvert>::mc_Value					));
	DMibStaticCheck((	TCIsConvertible<CTestConvert, float>::mc_Value					));
	DMibStaticCheck((	!TCIsConvertible<CTestConvert, char *>::mc_Value					));

	DMibStaticCheck((	!TCIsConvertible<CTestConvert2, int>::mc_Value					));
	DMibStaticCheck((	!TCIsConvertible<int, CTestConvert2>::mc_Value					));
	DMibStaticCheck((	!TCIsConvertible<CTestConvert2, char *>::mc_Value					));
	DMibStaticCheck((	!TCIsConvertible<char *, CTestConvert2>::mc_Value					));

	DMibStaticCheck((	TCIsConvertible<CTestInherit, CTestClass>::mc_Value					));
	DMibStaticCheck((	TCIsConvertible<CTestInherit &&, CTestClass &&>::mc_Value					));
}

// Void
DMibStaticCheck((	!TCIsConvertible<CTestUnion, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestClass0, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestClass1, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestStruct0, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestStruct1, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<const CTestClass0, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<const CTestClass1, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<const CTestStruct0, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<const CTestStruct1, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<volatile CTestClass0, int>::mc_Value			));
DMibStaticCheck((	!TCIsConvertible<volatile CTestClass1, int>::mc_Value			));
DMibStaticCheck((	!TCIsConvertible<volatile CTestStruct0, int>::mc_Value			));
DMibStaticCheck((	!TCIsConvertible<volatile CTestStruct1, int>::mc_Value			));
DMibStaticCheck((	!TCIsConvertible<const volatile CTestClass0, int>::mc_Value		));
DMibStaticCheck((	!TCIsConvertible<const volatile CTestClass1, int>::mc_Value		));
DMibStaticCheck((	!TCIsConvertible<const volatile CTestStruct0, int>::mc_Value	));
DMibStaticCheck((	!TCIsConvertible<const volatile CTestStruct1, int>::mc_Value	));
DMibStaticCheck((	TCIsConvertible<ETestEnum, int>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<int, int>::mc_Value							));
DMibStaticCheck((	!TCIsConvertible<CTestClass, int>::mc_Value							));
DMibStaticCheck((	!TCIsConvertible<CTestC, int>::mc_Value							));
DMibStaticCheck((	!TCIsConvertible<CTestV, int>::mc_Value							));
DMibStaticCheck((	!TCIsConvertible<CTestCV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestCPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestVPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestCVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestCVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestPtrV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestCPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestCVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestCPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestVPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestCVPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestCRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestVRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestCVRef, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestCRRef, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestVRRef, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestCVRRef, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<PFFunc0, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<PFFunc1, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<PFFunc2, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc1Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc2Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc1RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc2RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc1Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc2Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc1PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc2PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc0PtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc1PtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc2PtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc0PtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc1PtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc2PtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0PtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1PtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2PtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0PtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1PtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2PtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0CPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1CPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2CPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0CPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1CPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2CPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0VPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1VPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2VPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0VPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1VPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2VPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0VPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1VPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2VPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0VPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1VPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2VPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0CVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1CVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2CVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0CVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1CVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2CVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0CVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1CVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2CVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0CVPtrCV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<FMFunc1CVPtrCV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<FMFunc2CVPtrCV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<PFFunc0El, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<PFFunc1El, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<PFFunc2El, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc1ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc2ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc1ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc2ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc1ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc2ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc1ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc2ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc0ElPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc1ElPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc2ElPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc0ElPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc1ElPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FFunc2ElPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElCPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElCPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElCPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElCPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElCPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElCPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElVPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElVPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElVPtrCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElCVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElCVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElCVPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElCVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElCVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElCVPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElCVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElCVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElCVPtrV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<FMFunc0ElCVPtrCV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<FMFunc1ElCVPtrCV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<FMFunc2ElCVPtrCV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CMPtr, int>::mc_Value							));
DMibStaticCheck((	!TCIsConvertible<CMCPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMVPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMCVPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMCPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMVPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMCVPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMPtrV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMCPtrV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMVPtrV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMCVPtrV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMPtrCV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMCPtrCV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMVPtrCV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CMCVPtrCV, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<CTestArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArray2C, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArray2V, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArray2CV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArrayV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArrayCV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray2C, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray2V, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray2CV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArrayV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArrayCV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray2C, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray2V, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray2CV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest3DArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest3DArrayV, int>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest3DArrayCV, int>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<void *, int>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<void, int>::mc_Value							));


DMibStaticCheck((	TCIsConvertible<CTestUnion, CTestUnion>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestClass0, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestClass1, CTestClass1>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestStruct0, CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestStruct1, CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<const CTestClass0, const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<const CTestClass1, const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<const CTestStruct0, const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<const CTestStruct1, const CTestStruct1>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<volatile CTestClass0, CTestClass0>::mc_Value			));
DMibStaticCheck((	!TCIsConvertible<volatile CTestClass1, CTestClass1>::mc_Value			));
DMibStaticCheck((	!TCIsConvertible<volatile CTestStruct0, CTestStruct0>::mc_Value			));
DMibStaticCheck((	!TCIsConvertible<volatile CTestStruct1, CTestStruct1>::mc_Value			));
DMibStaticCheck((	!TCIsConvertible<const volatile CTestClass0, const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsConvertible<const volatile CTestClass1, const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsConvertible<const volatile CTestStruct0, const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsConvertible<const volatile CTestStruct1, const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCIsConvertible<ETestEnum, ETestEnum>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<int, int>::mc_Value							));
DMibStaticCheck((	TCIsConvertible<CTestClass, CTestClass>::mc_Value							));
DMibStaticCheck((	TCIsConvertible<CTestC, CTestC>::mc_Value							));
DMibStaticCheck((	!TCIsConvertible<CTestV, CTestV>::mc_Value							));
DMibStaticCheck((	!TCIsConvertible<CTestCV, CTestCV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestPtr, CTestPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestCPtr, CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestVPtr, CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestCVPtr, CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestPtrC, CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestCPtrC, CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestVPtrC, CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestCVPtrC, CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestPtrV, CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestCPtrV, CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestVPtrV, CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestCVPtrV, CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestPtrCV, CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestCPtrCV, CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestVPtrCV, CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestCVPtrCV, CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestRef, CTestRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestCRef, CTestCRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestVRef, CTestVRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestCVRef, CTestCVRef>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestRRef, CTestRRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CTestCRRef, CTestCRRef>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestVRRef, CTestVRRef>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestCVRRef, CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<PFFunc0, PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<PFFunc1, PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<PFFunc2, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0Ref, FFunc0Ref>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1Ref, FFunc1Ref>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2Ref, FFunc2Ref>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0Ref, FFunc0RRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1Ref, FFunc1RRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2Ref, FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0Ref, FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1Ref, FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2Ref, FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0RRef, FFunc0RRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1RRef, FFunc1RRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2RRef, FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0RRef, FFunc0Ref>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1RRef, FFunc1Ref>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2RRef, FFunc2Ref>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0RRef, FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1RRef, FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2RRef, FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0Ptr, FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc1Ptr, FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc2Ptr, FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc0Ptr, FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc1Ptr, FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<FFunc2Ptr, FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0PtrC, FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc1PtrC, FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc2PtrC, FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc0PtrV, FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc1PtrV, FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc2PtrV, FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc0PtrCV, FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc1PtrCV, FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc2PtrCV, FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0Ptr, FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1Ptr, FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2Ptr, FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0PtrC, FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1PtrC, FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2PtrC, FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0PtrV, FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1PtrV, FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2PtrV, FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0PtrCV, FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1PtrCV, FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2PtrCV, FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0CPtr, FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1CPtr, FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2CPtr, FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0CPtrC, FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1CPtrC, FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2CPtrC, FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0CPtrV, FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1CPtrV, FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2CPtrV, FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0CPtrCV, FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1CPtrCV, FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2CPtrCV, FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0VPtr, FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1VPtr, FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2VPtr, FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0VPtrC, FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1VPtrC, FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2VPtrC, FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0VPtrV, FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1VPtrV, FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2VPtrV, FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0VPtrCV, FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1VPtrCV, FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2VPtrCV, FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0CVPtr, FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1CVPtr, FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2CVPtr, FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0CVPtrC, FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1CVPtrC, FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2CVPtrC, FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0CVPtrV, FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1CVPtrV, FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2CVPtrV, FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0CVPtrCV, FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<FMFunc1CVPtrCV, FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<FMFunc2CVPtrCV, FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<PFFunc0El, PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<PFFunc1El, PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsConvertible<PFFunc2El, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0ElRef, FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1ElRef, FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2ElRef, FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0ElRRef, FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1ElRRef, FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2ElRRef, FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0ElPtr, FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc1ElPtr, FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc2ElPtr, FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<FFunc0ElPtrC, FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc1ElPtrC, FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc2ElPtrC, FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc0ElPtrV, FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc1ElPtrV, FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc2ElPtrV, FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc0ElPtrCV, FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc1ElPtrCV, FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FFunc2ElPtrCV, FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElPtr, FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElPtr, FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElPtr, FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElPtrC, FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElPtrC, FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElPtrC, FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElPtrV, FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElPtrV, FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElPtrV, FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElPtrCV, FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElPtrCV, FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElPtrCV, FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElCPtr, FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElCPtr, FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElCPtr, FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElCPtrC, FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElCPtrC, FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElCPtrC, FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElCPtrV, FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElCPtrV, FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElCPtrV, FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElCPtrCV, FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElCPtrCV, FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElCPtrCV, FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElVPtr, FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElVPtr, FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElVPtr, FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElVPtrC, FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElVPtrC, FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElVPtrC, FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElVPtrV, FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElVPtrV, FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElVPtrV, FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElVPtrCV, FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElVPtrCV, FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElVPtrCV, FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElCVPtr, FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElCVPtr, FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElCVPtr, FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElCVPtrC, FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElCVPtrC, FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElCVPtrC, FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElCVPtrV, FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElCVPtrV, FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElCVPtrV, FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<FMFunc0ElCVPtrCV, FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<FMFunc1ElCVPtrCV, FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<FMFunc2ElCVPtrCV, FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<CMPtr, CMPtr>::mc_Value							));
DMibStaticCheck((	TCIsConvertible<CMCPtr, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMVPtr, CMVPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMCVPtr, CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMPtrC, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMCPtrC, CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMVPtrC, CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMCVPtrC, CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMPtrV, CMPtrV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMCPtrV, CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMVPtrV, CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMCVPtrV, CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMPtrCV, CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMCPtrCV, CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMVPtrCV, CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<CMCVPtrCV, CMCVPtrCV>::mc_Value						));

DMibStaticCheck((	TCIsConvertible<CTestArray2, TCDecay<CTestArray2>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestArray2C, TCDecay<CTestArray2C>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestArray2V, TCDecay<CTestArray2V>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestArray2CV, TCDecay<CTestArray2CV>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestArray, TCDecay<CTestArray>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestArrayC, TCDecay<CTestArrayC>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestArrayV, TCDecay<CTestArrayV>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTestArrayCV, TCDecay<CTestArrayCV>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest2DArray2, TCDecay<CTest2DArray2>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest2DArray2C, TCDecay<CTest2DArray2C>::CType>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<CTest2DArray2V, TCDecay<CTest2DArray2V>::CType>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<CTest2DArray2CV, TCDecay<CTest2DArray2CV>::CType>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<CTest2DArray, TCDecay<CTest2DArray>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest2DArrayC, TCDecay<CTest2DArrayC>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest2DArrayV, TCDecay<CTest2DArrayV>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest2DArrayCV, TCDecay<CTest2DArrayCV>::CType>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<CTest3DArray2, TCDecay<CTest3DArray2>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest3DArray2C, TCDecay<CTest3DArray2C>::CType>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<CTest3DArray2V, TCDecay<CTest3DArray2V>::CType>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<CTest3DArray2CV, TCDecay<CTest3DArray2CV>::CType>::mc_Value				));
DMibStaticCheck((	TCIsConvertible<CTest3DArray, TCDecay<CTest3DArray>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest3DArrayC, TCDecay<CTest3DArrayC>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest3DArrayV, TCDecay<CTest3DArrayV>::CType>::mc_Value					));
DMibStaticCheck((	TCIsConvertible<CTest3DArrayCV, TCDecay<CTest3DArrayCV>::CType>::mc_Value				));


DMibStaticCheck((	!TCIsConvertible<CTestArray2, CTestArray2>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArray2C, CTestArray2C>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArray2V, CTestArray2V>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArray2CV, CTestArray2CV>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArray, CTestArray>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArrayC, CTestArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArrayV, CTestArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTestArrayCV, CTestArrayCV>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray2, CTest2DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray2C, CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray2V, CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray2CV, CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest2DArray, CTest2DArray>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArrayC, CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArrayV, CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest2DArrayCV, CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray2, CTest3DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray2C, CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray2V, CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray2CV, CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	!TCIsConvertible<CTest3DArray, CTest3DArray>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest3DArrayC, CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest3DArrayV, CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsConvertible<CTest3DArrayCV, CTest3DArrayCV>::mc_Value				));

DMibStaticCheck((	TCIsConvertible<void *, void *>::mc_Value						));
DMibStaticCheck((	TCIsConvertible<void, void>::mc_Value							));

