// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

// Is Int
DMibStaticCheck((	!TCIsInteger<ufp32>::mc_Value	));
	
DMibStaticCheck((	TCIsInteger<int8192>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<int8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<aint>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uaint>::mc_Value	));
DMibStaticCheck((	TCIsInteger<smint>::mc_Value	));
DMibStaticCheck((	TCIsInteger<mint>::mc_Value	));

DMibStaticCheck((	TCIsInteger<uint4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<uint8>::mc_Value	));

DMibStaticCheck((	!TCIsInteger<fp4096>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp2048>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp1024>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp512>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp256>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp128>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp80>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp64>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp32>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp16>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<fp8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<const int8192>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const int8>::mc_Value	));

DMibStaticCheck((	TCIsInteger<const uint4096>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint2048>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint1024>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint512>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint256>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint160>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint128>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint80>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint64>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint32>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint16>::mc_Value	));
DMibStaticCheck((	TCIsInteger<const uint8>::mc_Value	));

DMibStaticCheck((	!TCIsInteger<const fp4096>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp2048>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp1024>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp512>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp256>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp128>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp80>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp64>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp32>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp16>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<const fp8>::mc_Value	));







DMibStaticCheck((	!TCIsInteger<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsInteger<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsInteger<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsInteger<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsInteger<void *>::mc_Value			));
DMibStaticCheck((	!TCIsInteger<void>::mc_Value				));

// Is Float
DMibStaticCheck((	TCIsFloat<ufp32>::mc_Value	));
	
DMibStaticCheck((	!TCIsFloat<int8192>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<int8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<aint>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uaint>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<smint>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<mint>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<uint8>::mc_Value	));

DMibStaticCheck((	TCIsFloat<fp4096>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp2048>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp1024>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp512>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp256>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp128>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp80>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp64>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp32>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp16>::mc_Value	));
DMibStaticCheck((	TCIsFloat<fp8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<const int8192>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const int8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<const uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint512>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint256>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint160>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint128>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint80>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint64>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint32>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint16>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<const uint8>::mc_Value	));

DMibStaticCheck((	TCIsFloat<const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp512>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp256>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp128>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp80>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp64>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp32>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp16>::mc_Value	));
DMibStaticCheck((	TCIsFloat<const fp8>::mc_Value	));

DMibStaticCheck((	!TCIsFloat<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsFloat<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsFloat<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsFloat<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsFloat<void *>::mc_Value			));
DMibStaticCheck((	!TCIsFloat<void>::mc_Value				));


// Is Float
DMibStaticCheck((	TCIsArithmetic<ufp32>::mc_Value	));
	
DMibStaticCheck((	TCIsArithmetic<int8192>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<int8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<aint>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uaint>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<smint>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<mint>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<uint4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<uint8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<fp4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<fp8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const int8192>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const int8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const uint4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint160>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const uint8>::mc_Value	));

DMibStaticCheck((	TCIsArithmetic<const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp512>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp256>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp128>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp80>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp64>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp32>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp16>::mc_Value	));
DMibStaticCheck((	TCIsArithmetic<const fp8>::mc_Value	));

DMibStaticCheck((	!TCIsArithmetic<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsArithmetic<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsArithmetic<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArithmetic<void *>::mc_Value			));
DMibStaticCheck((	!TCIsArithmetic<void>::mc_Value				));

