// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

static_assert(!cIsArray<CTestUnion>);
static_assert(!cIsArray<CTestClass0>);
static_assert(!cIsArray<CTestClass1>);
static_assert(!cIsArray<CTestStruct0>);
static_assert(!cIsArray<CTestStruct1>);
static_assert(!cIsArray<ETestEnum>);
static_assert(!cIsArray<CTestClass>);
static_assert(!cIsArray<CTestC>);
static_assert(!cIsArray<CTestPtr>);
static_assert(!cIsArray<CTestCPtr>);
static_assert(!cIsArray<CTestPtrC>);
static_assert(!cIsArray<CTestCPtrC>);
static_assert(!cIsArray<CTestRef>);
static_assert(!cIsArray<CTestCRef>);
static_assert(!cIsArray<CTestRRef>);
static_assert(!cIsArray<CTestCRRef>);
static_assert(!cIsArray<PFFunc0>);
static_assert(!cIsArray<PFFunc1>);
static_assert(!cIsArray<PFFunc2>);
static_assert(!cIsArray<FFunc0Ref>);
static_assert(!cIsArray<FFunc1Ref>);
static_assert(!cIsArray<FFunc2Ref>);
static_assert(!cIsArray<FFunc0RRef>);
static_assert(!cIsArray<FFunc1RRef>);
static_assert(!cIsArray<FFunc2RRef>);
static_assert(!cIsArray<FFunc0Ptr>);
static_assert(!cIsArray<FFunc1Ptr>);
static_assert(!cIsArray<FFunc2Ptr>);
static_assert(!cIsArray<FFunc0PtrC>);
static_assert(!cIsArray<FFunc1PtrC>);
static_assert(!cIsArray<FFunc2PtrC>);
static_assert(!cIsArray<FMFunc0Ptr>);
static_assert(!cIsArray<FMFunc1Ptr>);
static_assert(!cIsArray<FMFunc2Ptr>);
static_assert(!cIsArray<FMFunc0PtrC>);
static_assert(!cIsArray<FMFunc1PtrC>);
static_assert(!cIsArray<FMFunc2PtrC>);
static_assert(!cIsArray<FMFunc0CPtr>);
static_assert(!cIsArray<FMFunc1CPtr>);
static_assert(!cIsArray<FMFunc2CPtr>);
static_assert(!cIsArray<FMFunc0CPtrC>);
static_assert(!cIsArray<FMFunc1CPtrC>);
static_assert(!cIsArray<FMFunc2CPtrC>);
static_assert(!cIsArray<PFFunc0El>);
static_assert(!cIsArray<PFFunc1El>);
static_assert(!cIsArray<PFFunc2El>);
static_assert(!cIsArray<FFunc0ElRef>);
static_assert(!cIsArray<FFunc1ElRef>);
static_assert(!cIsArray<FFunc2ElRef>);
static_assert(!cIsArray<FFunc0ElRRef>);
static_assert(!cIsArray<FFunc1ElRRef>);
static_assert(!cIsArray<FFunc2ElRRef>);
static_assert(!cIsArray<FFunc0ElPtr>);
static_assert(!cIsArray<FFunc1ElPtr>);
static_assert(!cIsArray<FFunc2ElPtr>);
static_assert(!cIsArray<FFunc0ElPtrC>);
static_assert(!cIsArray<FFunc1ElPtrC>);
static_assert(!cIsArray<FFunc2ElPtrC>);
static_assert(!cIsArray<FMFunc0ElPtr>);
static_assert(!cIsArray<FMFunc1ElPtr>);
static_assert(!cIsArray<FMFunc2ElPtr>);
static_assert(!cIsArray<FMFunc0ElPtrC>);
static_assert(!cIsArray<FMFunc1ElPtrC>);
static_assert(!cIsArray<FMFunc2ElPtrC>);
static_assert(!cIsArray<FMFunc0ElCPtr>);
static_assert(!cIsArray<FMFunc1ElCPtr>);
static_assert(!cIsArray<FMFunc2ElCPtr>);
static_assert(!cIsArray<FMFunc0ElCPtrC>);
static_assert(!cIsArray<FMFunc1ElCPtrC>);
static_assert(!cIsArray<FMFunc2ElCPtrC>);
static_assert(!cIsArray<CMPtr>);
static_assert(!cIsArray<CMCPtr>);
static_assert(!cIsArray<CMPtrC>);
static_assert(!cIsArray<CMCPtrC>);
static_assert(cIsArray<CTestArray2>);
static_assert(cIsArray<CTestArray2C>);
static_assert(cIsArray<CTestArray>);
static_assert(cIsArray<CTestArrayC>);
static_assert(cIsArray<CTest2DArray2>);
static_assert(cIsArray<CTest2DArray2C>);
static_assert(cIsArray<CTest2DArray>);
static_assert(cIsArray<CTest2DArrayC>);
static_assert(cIsArray<CTest3DArray2>);
static_assert(cIsArray<CTest3DArray2C>);
static_assert(cIsArray<CTest3DArray>);
static_assert(cIsArray<CTest3DArrayC>);
static_assert(!cIsArray<void *>);
static_assert(!cIsArray<void>);


static_assert(!cIsUnboundedArray<CTestUnion>);
static_assert(!cIsUnboundedArray<CTestClass0>);
static_assert(!cIsUnboundedArray<CTestClass1>);
static_assert(!cIsUnboundedArray<CTestStruct0>);
static_assert(!cIsUnboundedArray<CTestStruct1>);
static_assert(!cIsUnboundedArray<ETestEnum>);
static_assert(!cIsUnboundedArray<CTestClass>);
static_assert(!cIsUnboundedArray<CTestC>);
static_assert(!cIsUnboundedArray<CTestPtr>);
static_assert(!cIsUnboundedArray<CTestCPtr>);
static_assert(!cIsUnboundedArray<CTestPtrC>);
static_assert(!cIsUnboundedArray<CTestCPtrC>);
static_assert(!cIsUnboundedArray<CTestRef>);
static_assert(!cIsUnboundedArray<CTestCRef>);
static_assert(!cIsUnboundedArray<CTestRRef>);
static_assert(!cIsUnboundedArray<CTestCRRef>);
static_assert(!cIsUnboundedArray<PFFunc0>);
static_assert(!cIsUnboundedArray<PFFunc1>);
static_assert(!cIsUnboundedArray<PFFunc2>);
static_assert(!cIsUnboundedArray<FFunc0Ref>);
static_assert(!cIsUnboundedArray<FFunc1Ref>);
static_assert(!cIsUnboundedArray<FFunc2Ref>);
static_assert(!cIsUnboundedArray<FFunc0RRef>);
static_assert(!cIsUnboundedArray<FFunc1RRef>);
static_assert(!cIsUnboundedArray<FFunc2RRef>);
static_assert(!cIsUnboundedArray<FFunc0Ptr>);
static_assert(!cIsUnboundedArray<FFunc1Ptr>);
static_assert(!cIsUnboundedArray<FFunc2Ptr>);
static_assert(!cIsUnboundedArray<FFunc0PtrC>);
static_assert(!cIsUnboundedArray<FFunc1PtrC>);
static_assert(!cIsUnboundedArray<FFunc2PtrC>);
static_assert(!cIsUnboundedArray<FMFunc0Ptr>);
static_assert(!cIsUnboundedArray<FMFunc1Ptr>);
static_assert(!cIsUnboundedArray<FMFunc2Ptr>);
static_assert(!cIsUnboundedArray<FMFunc0PtrC>);
static_assert(!cIsUnboundedArray<FMFunc1PtrC>);
static_assert(!cIsUnboundedArray<FMFunc2PtrC>);
static_assert(!cIsUnboundedArray<FMFunc0CPtr>);
static_assert(!cIsUnboundedArray<FMFunc1CPtr>);
static_assert(!cIsUnboundedArray<FMFunc2CPtr>);
static_assert(!cIsUnboundedArray<FMFunc0CPtrC>);
static_assert(!cIsUnboundedArray<FMFunc1CPtrC>);
static_assert(!cIsUnboundedArray<FMFunc2CPtrC>);
static_assert(!cIsUnboundedArray<PFFunc0El>);
static_assert(!cIsUnboundedArray<PFFunc1El>);
static_assert(!cIsUnboundedArray<PFFunc2El>);
static_assert(!cIsUnboundedArray<FFunc0ElRef>);
static_assert(!cIsUnboundedArray<FFunc1ElRef>);
static_assert(!cIsUnboundedArray<FFunc2ElRef>);
static_assert(!cIsUnboundedArray<FFunc0ElRRef>);
static_assert(!cIsUnboundedArray<FFunc1ElRRef>);
static_assert(!cIsUnboundedArray<FFunc2ElRRef>);
static_assert(!cIsUnboundedArray<FFunc0ElPtr>);
static_assert(!cIsUnboundedArray<FFunc1ElPtr>);
static_assert(!cIsUnboundedArray<FFunc2ElPtr>);
static_assert(!cIsUnboundedArray<FFunc0ElPtrC>);
static_assert(!cIsUnboundedArray<FFunc1ElPtrC>);
static_assert(!cIsUnboundedArray<FFunc2ElPtrC>);
static_assert(!cIsUnboundedArray<FMFunc0ElPtr>);
static_assert(!cIsUnboundedArray<FMFunc1ElPtr>);
static_assert(!cIsUnboundedArray<FMFunc2ElPtr>);
static_assert(!cIsUnboundedArray<FMFunc0ElPtrC>);
static_assert(!cIsUnboundedArray<FMFunc1ElPtrC>);
static_assert(!cIsUnboundedArray<FMFunc2ElPtrC>);
static_assert(!cIsUnboundedArray<FMFunc0ElCPtr>);
static_assert(!cIsUnboundedArray<FMFunc1ElCPtr>);
static_assert(!cIsUnboundedArray<FMFunc2ElCPtr>);
static_assert(!cIsUnboundedArray<FMFunc0ElCPtrC>);
static_assert(!cIsUnboundedArray<FMFunc1ElCPtrC>);
static_assert(!cIsUnboundedArray<FMFunc2ElCPtrC>);
static_assert(!cIsUnboundedArray<CMPtr>);
static_assert(!cIsUnboundedArray<CMCPtr>);
static_assert(!cIsUnboundedArray<CMPtrC>);
static_assert(!cIsUnboundedArray<CMCPtrC>);
static_assert(!cIsUnboundedArray<CTestArray2>);
static_assert(!cIsUnboundedArray<CTestArray2C>);
static_assert(cIsUnboundedArray<CTestArray>);
static_assert(cIsUnboundedArray<CTestArrayC>);
static_assert(!cIsUnboundedArray<CTest2DArray2>);
static_assert(!cIsUnboundedArray<CTest2DArray2C>);
static_assert(cIsUnboundedArray<CTest2DArray>);
static_assert(cIsUnboundedArray<CTest2DArrayC>);
static_assert(!cIsUnboundedArray<CTest3DArray2>);
static_assert(!cIsUnboundedArray<CTest3DArray2C>);
static_assert(cIsUnboundedArray<CTest3DArray>);
static_assert(cIsUnboundedArray<CTest3DArrayC>);
static_assert(!cIsUnboundedArray<void *>);
static_assert(!cIsUnboundedArray<void>);


static_assert(cIsSame<TCRemoveExtent<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCRemoveExtent<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCRemoveExtent<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCRemoveExtent<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCRemoveExtent<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCRemoveExtent<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCRemoveExtent<CTestClass>, CTestClass>);
static_assert(cIsSame<TCRemoveExtent<CTestC>, CTestC>);
static_assert(cIsSame<TCRemoveExtent<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCRemoveExtent<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCRemoveExtent<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCRemoveExtent<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCRemoveExtent<CTestRef>, CTestRef>);
static_assert(cIsSame<TCRemoveExtent<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCRemoveExtent<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCRemoveExtent<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCRemoveExtent<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCRemoveExtent<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCRemoveExtent<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCRemoveExtent<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCRemoveExtent<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCRemoveExtent<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCRemoveExtent<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCRemoveExtent<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCRemoveExtent<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCRemoveExtent<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCRemoveExtent<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCRemoveExtent<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCRemoveExtent<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCRemoveExtent<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCRemoveExtent<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCRemoveExtent<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCRemoveExtent<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCRemoveExtent<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCRemoveExtent<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCRemoveExtent<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveExtent<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveExtent<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCRemoveExtent<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCRemoveExtent<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCRemoveExtent<CMPtr>, CMPtr>);
static_assert(cIsSame<TCRemoveExtent<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCRemoveExtent<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCRemoveExtent<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCRemoveExtent<CTestArray2>, CTestBase>);
static_assert(cIsSame<TCRemoveExtent<CTestArray2C>, CTestBase const>);
static_assert(cIsSame<TCRemoveExtent<CTestArray>, CTestBase>);
static_assert(cIsSame<TCRemoveExtent<CTestArrayC>, CTestBase const>);
static_assert(cIsSame<TCRemoveExtent<CTest2DArray2>, CTestArray2>);
static_assert(cIsSame<TCRemoveExtent<CTest2DArray2C>, CTestArray2C>);
static_assert(cIsSame<TCRemoveExtent<CTest2DArray>, CTestArray2>);
static_assert(cIsSame<TCRemoveExtent<CTest2DArrayC>, CTestArray2C>);
static_assert(cIsSame<TCRemoveExtent<CTest3DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCRemoveExtent<CTest3DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCRemoveExtent<CTest3DArray>, CTest2DArray2>);
static_assert(cIsSame<TCRemoveExtent<CTest3DArrayC>, CTest2DArray2C>);
static_assert(cIsSame<TCRemoveExtent<void *>, void *>);
static_assert(cIsSame<TCRemoveExtent<void>, void>);

// Remove pointer
static_assert(cIsSame<TCRemoveAllExtents<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCRemoveAllExtents<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCRemoveAllExtents<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCRemoveAllExtents<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCRemoveAllExtents<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCRemoveAllExtents<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCRemoveAllExtents<CTestClass>, CTestClass>);
static_assert(cIsSame<TCRemoveAllExtents<CTestC>, CTestC>);
static_assert(cIsSame<TCRemoveAllExtents<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCRemoveAllExtents<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCRemoveAllExtents<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<CTestRef>, CTestRef>);
static_assert(cIsSame<TCRemoveAllExtents<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCRemoveAllExtents<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCRemoveAllExtents<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCRemoveAllExtents<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCRemoveAllExtents<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCRemoveAllExtents<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCRemoveAllExtents<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCRemoveAllExtents<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<CMPtr>, CMPtr>);
static_assert(cIsSame<TCRemoveAllExtents<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCRemoveAllExtents<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCRemoveAllExtents<CTestArray2>, CTestBase>);
static_assert(cIsSame<TCRemoveAllExtents<CTestArray2C>, CTestBase const>);
static_assert(cIsSame<TCRemoveAllExtents<CTestArray>, CTestBase>);
static_assert(cIsSame<TCRemoveAllExtents<CTestArrayC>, CTestBase const>);
static_assert(cIsSame<TCRemoveAllExtents<CTest2DArray2>, CTestBase>);
static_assert(cIsSame<TCRemoveAllExtents<CTest2DArray2C>, CTestBase const>);
static_assert(cIsSame<TCRemoveAllExtents<CTest2DArray>, CTestBase>);
static_assert(cIsSame<TCRemoveAllExtents<CTest2DArrayC>, CTestBase const>);
static_assert(cIsSame<TCRemoveAllExtents<CTest3DArray2>, CTestBase>);
static_assert(cIsSame<TCRemoveAllExtents<CTest3DArray2C>, CTestBase const>);
static_assert(cIsSame<TCRemoveAllExtents<CTest3DArray>, CTestBase>);
static_assert(cIsSame<TCRemoveAllExtents<CTest3DArrayC>, CTestBase const>);
static_assert(cIsSame<TCRemoveAllExtents<void *>, void *>);
static_assert(cIsSame<TCRemoveAllExtents<void>, void>);


// Remove pointer
static_assert(cIsSame<TCDecay<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCDecay<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCDecay<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCDecay<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCDecay<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCDecay<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCDecay<CTestClass>, CTestClass>);
static_assert(cIsSame<TCDecay<CTestC>, CTestClass>);
static_assert(cIsSame<TCDecay<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCDecay<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCDecay<CTestPtrC>, CTestPtr>);
static_assert(cIsSame<TCDecay<CTestCPtrC>, CTestCPtr>);
static_assert(cIsSame<TCDecay<CTestRef>, CTestClass>);
static_assert(cIsSame<TCDecay<CTestCRef>, CTestClass>);
static_assert(cIsSame<TCDecay<CTestRRef>, CTestClass>);
static_assert(cIsSame<TCDecay<CTestCRRef>, CTestClass>);
static_assert(cIsSame<TCDecay<PFFunc0>, FFunc0Ptr>);
static_assert(cIsSame<TCDecay<PFFunc1>, FFunc1Ptr>);
static_assert(cIsSame<TCDecay<PFFunc2>, FFunc2Ptr>);
static_assert(cIsSame<TCDecay<FFunc0Ref>, FFunc0Ptr>);
static_assert(cIsSame<TCDecay<FFunc1Ref>, FFunc1Ptr>);
static_assert(cIsSame<TCDecay<FFunc2Ref>, FFunc2Ptr>);
static_assert(cIsSame<TCDecay<FFunc0RRef>, FFunc0Ptr>);
static_assert(cIsSame<TCDecay<FFunc1RRef>, FFunc1Ptr>);
static_assert(cIsSame<TCDecay<FFunc2RRef>, FFunc2Ptr>);
static_assert(cIsSame<TCDecay<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCDecay<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCDecay<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCDecay<FFunc0PtrC>, FFunc0Ptr>);
static_assert(cIsSame<TCDecay<FFunc1PtrC>, FFunc1Ptr>);
static_assert(cIsSame<TCDecay<FFunc2PtrC>, FFunc2Ptr>);
static_assert(cIsSame<TCDecay<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCDecay<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCDecay<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCDecay<FMFunc0PtrC>, FMFunc0Ptr>);
static_assert(cIsSame<TCDecay<FMFunc1PtrC>, FMFunc1Ptr>);
static_assert(cIsSame<TCDecay<FMFunc2PtrC>, FMFunc2Ptr>);
static_assert(cIsSame<TCDecay<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCDecay<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCDecay<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCDecay<FMFunc0CPtrC>, FMFunc0CPtr>);
static_assert(cIsSame<TCDecay<FMFunc1CPtrC>, FMFunc1CPtr>);
static_assert(cIsSame<TCDecay<FMFunc2CPtrC>, FMFunc2CPtr>);
static_assert(cIsSame<TCDecay<PFFunc0El>, FFunc0ElPtr>);
static_assert(cIsSame<TCDecay<PFFunc1El>, FFunc1ElPtr>);
static_assert(cIsSame<TCDecay<PFFunc2El>, FFunc2ElPtr>);
static_assert(cIsSame<TCDecay<FFunc0ElRef>, FFunc0ElPtr>);
static_assert(cIsSame<TCDecay<FFunc1ElRef>, FFunc1ElPtr>);
static_assert(cIsSame<TCDecay<FFunc2ElRef>, FFunc2ElPtr>);
static_assert(cIsSame<TCDecay<FFunc0ElRRef>, FFunc0ElPtr>);
static_assert(cIsSame<TCDecay<FFunc1ElRRef>, FFunc1ElPtr>);
static_assert(cIsSame<TCDecay<FFunc2ElRRef>, FFunc2ElPtr>);
static_assert(cIsSame<TCDecay<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCDecay<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCDecay<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCDecay<FFunc0ElPtrC>, FFunc0ElPtr>);
static_assert(cIsSame<TCDecay<FFunc1ElPtrC>, FFunc1ElPtr>);
static_assert(cIsSame<TCDecay<FFunc2ElPtrC>, FFunc2ElPtr>);
static_assert(cIsSame<TCDecay<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCDecay<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCDecay<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCDecay<FMFunc0ElPtrC>, FMFunc0ElPtr>);
static_assert(cIsSame<TCDecay<FMFunc1ElPtrC>, FMFunc1ElPtr>);
static_assert(cIsSame<TCDecay<FMFunc2ElPtrC>, FMFunc2ElPtr>);
static_assert(cIsSame<TCDecay<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCDecay<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCDecay<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCDecay<FMFunc0ElCPtrC>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCDecay<FMFunc1ElCPtrC>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCDecay<FMFunc2ElCPtrC>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCDecay<CMPtr>, CMPtr>);
static_assert(cIsSame<TCDecay<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCDecay<CMPtrC>, CMPtr>);
static_assert(cIsSame<TCDecay<CMCPtrC>, CMCPtr>);
static_assert(cIsSame<TCDecay<CTestArray2>, CTestBase *>);
static_assert(cIsSame<TCDecay<CTestArray2C>, CTestBase const *>);
static_assert(cIsSame<TCDecay<CTestArray>, CTestBase *>);
static_assert(cIsSame<TCDecay<CTestArrayC>, CTestBase const *>);
static_assert(cIsSame<TCDecay<CTest2DArray2>, CTestArray2 *>);
static_assert(cIsSame<TCDecay<CTest2DArray2C>, CTestArray2C *>);
static_assert(cIsSame<TCDecay<CTest2DArray>, CTestArray2 *>);
static_assert(cIsSame<TCDecay<CTest2DArrayC>, CTestArray2C *>);
static_assert(cIsSame<TCDecay<CTest3DArray2>, CTest2DArray2 *>);
static_assert(cIsSame<TCDecay<CTest3DArray2C>, CTest2DArray2C *>);
static_assert(cIsSame<TCDecay<CTest3DArray>, CTest2DArray2 *>);
static_assert(cIsSame<TCDecay<CTest3DArrayC>, CTest2DArray2C *>);
static_assert(cIsSame<TCDecay<void *>, void *>);
static_assert(cIsSame<TCDecay<void>, void>);


// Extent
static_assert(gc_ArrayExtent<CTestUnion> == 0);
static_assert(gc_ArrayExtent<CTestClass0> == 0);
static_assert(gc_ArrayExtent<CTestClass1> == 0);
static_assert(gc_ArrayExtent<CTestStruct0> == 0);
static_assert(gc_ArrayExtent<CTestStruct1> == 0);
static_assert(gc_ArrayExtent<ETestEnum> == 0);
static_assert(gc_ArrayExtent<CTestClass> == 0);
static_assert(gc_ArrayExtent<CTestC> == 0);
static_assert(gc_ArrayExtent<CTestPtr> == 0);
static_assert(gc_ArrayExtent<CTestCPtr> == 0);
static_assert(gc_ArrayExtent<CTestPtrC> == 0);
static_assert(gc_ArrayExtent<CTestCPtrC> == 0);
static_assert(gc_ArrayExtent<CTestRef> == 0);
static_assert(gc_ArrayExtent<CTestCRef> == 0);
static_assert(gc_ArrayExtent<CTestRRef> == 0);
static_assert(gc_ArrayExtent<CTestCRRef> == 0);
static_assert(gc_ArrayExtent<PFFunc0> == 0);
static_assert(gc_ArrayExtent<PFFunc1> == 0);
static_assert(gc_ArrayExtent<PFFunc2> == 0);
static_assert(gc_ArrayExtent<FFunc0Ref> == 0);
static_assert(gc_ArrayExtent<FFunc1Ref> == 0);
static_assert(gc_ArrayExtent<FFunc2Ref> == 0);
static_assert(gc_ArrayExtent<FFunc0RRef> == 0);
static_assert(gc_ArrayExtent<FFunc1RRef> == 0);
static_assert(gc_ArrayExtent<FFunc2RRef> == 0);
static_assert(gc_ArrayExtent<FFunc0Ptr> == 0);
static_assert(gc_ArrayExtent<FFunc1Ptr> == 0);
static_assert(gc_ArrayExtent<FFunc2Ptr> == 0);
static_assert(gc_ArrayExtent<FFunc0PtrC> == 0);
static_assert(gc_ArrayExtent<FFunc1PtrC> == 0);
static_assert(gc_ArrayExtent<FFunc2PtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc0Ptr> == 0);
static_assert(gc_ArrayExtent<FMFunc1Ptr> == 0);
static_assert(gc_ArrayExtent<FMFunc2Ptr> == 0);
static_assert(gc_ArrayExtent<FMFunc0PtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc1PtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc2PtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc0CPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc1CPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc2CPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc0CPtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc1CPtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc2CPtrC> == 0);
static_assert(gc_ArrayExtent<PFFunc0El> == 0);
static_assert(gc_ArrayExtent<PFFunc1El> == 0);
static_assert(gc_ArrayExtent<PFFunc2El> == 0);
static_assert(gc_ArrayExtent<FFunc0ElRef> == 0);
static_assert(gc_ArrayExtent<FFunc1ElRef> == 0);
static_assert(gc_ArrayExtent<FFunc2ElRef> == 0);
static_assert(gc_ArrayExtent<FFunc0ElRRef> == 0);
static_assert(gc_ArrayExtent<FFunc1ElRRef> == 0);
static_assert(gc_ArrayExtent<FFunc2ElRRef> == 0);
static_assert(gc_ArrayExtent<FFunc0ElPtr> == 0);
static_assert(gc_ArrayExtent<FFunc1ElPtr> == 0);
static_assert(gc_ArrayExtent<FFunc2ElPtr> == 0);
static_assert(gc_ArrayExtent<FFunc0ElPtrC> == 0);
static_assert(gc_ArrayExtent<FFunc1ElPtrC> == 0);
static_assert(gc_ArrayExtent<FFunc2ElPtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc0ElPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc1ElPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc2ElPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc0ElPtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc1ElPtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc2ElPtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc0ElCPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc1ElCPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc2ElCPtr> == 0);
static_assert(gc_ArrayExtent<FMFunc0ElCPtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc1ElCPtrC> == 0);
static_assert(gc_ArrayExtent<FMFunc2ElCPtrC> == 0);
static_assert(gc_ArrayExtent<CMPtr> == 0);
static_assert(gc_ArrayExtent<CMCPtr> == 0);
static_assert(gc_ArrayExtent<CMPtrC> == 0);
static_assert(gc_ArrayExtent<CMCPtrC> == 0);
static_assert(gc_ArrayExtent<CTestArray2> == 2);
static_assert(gc_ArrayExtent<CTestArray2C> == 2);
static_assert(gc_ArrayExtent<CTestArray> == 0);
static_assert(gc_ArrayExtent<CTestArrayC> == 0);
static_assert(gc_ArrayExtent<CTest2DArray2> == 3);
static_assert(gc_ArrayExtent<CTest2DArray2C> == 3);
static_assert(gc_ArrayExtent<CTest2DArray> == 0);
static_assert(gc_ArrayExtent<CTest2DArrayC> == 0);
static_assert(gc_ArrayExtent<CTest3DArray2> == 4);
static_assert(gc_ArrayExtent<CTest3DArray2C> == 4);
static_assert(gc_ArrayExtent<CTest3DArray> == 0);
static_assert(gc_ArrayExtent<CTest3DArrayC> == 0);

static_assert(gc_ArrayExtent<CTestArray2, 1> == 0);
static_assert(gc_ArrayExtent<CTestArray2C, 1> == 0);
static_assert(gc_ArrayExtent<CTestArray, 1> == 0);
static_assert(gc_ArrayExtent<CTestArrayC, 1> == 0);
static_assert(gc_ArrayExtent<CTest2DArray2, 1> == 2);
static_assert(gc_ArrayExtent<CTest2DArray2C, 1> == 2);
static_assert(gc_ArrayExtent<CTest2DArray, 1> == 2);
static_assert(gc_ArrayExtent<CTest2DArrayC, 1> == 2);
static_assert(gc_ArrayExtent<CTest3DArray2, 1> == 3);
static_assert(gc_ArrayExtent<CTest3DArray2C, 1> == 3);
static_assert(gc_ArrayExtent<CTest3DArray, 1> == 3);
static_assert(gc_ArrayExtent<CTest3DArrayC, 1> == 3);

static_assert(gc_ArrayExtent<CTestArray2, 2> == 0);
static_assert(gc_ArrayExtent<CTestArray2C, 2> == 0);
static_assert(gc_ArrayExtent<CTestArray, 2> == 0);
static_assert(gc_ArrayExtent<CTestArrayC, 2> == 0);
static_assert(gc_ArrayExtent<CTest2DArray2, 2> == 0);
static_assert(gc_ArrayExtent<CTest2DArray2C, 2> == 0);
static_assert(gc_ArrayExtent<CTest2DArray, 2> == 0);
static_assert(gc_ArrayExtent<CTest2DArrayC, 2> == 0);
static_assert(gc_ArrayExtent<CTest3DArray2, 2> == 2);
static_assert(gc_ArrayExtent<CTest3DArray2C, 2> == 2);
static_assert(gc_ArrayExtent<CTest3DArray, 2> == 2);
static_assert(gc_ArrayExtent<CTest3DArrayC, 2> == 2);

static_assert(gc_ArrayExtent<void> == 0);
static_assert(gc_ArrayExtent<void *> == 0);
static_assert(gc_ArrayExtent<void, 1> == 0);
static_assert(gc_ArrayExtent<void *, 1> == 0);
static_assert(gc_ArrayExtent<void, 2> == 0);
static_assert(gc_ArrayExtent<void *, 2> == 0);


// Rank
static_assert(gc_ArrayRank<CTestUnion> == 0);
static_assert(gc_ArrayRank<CTestClass0> == 0);
static_assert(gc_ArrayRank<CTestClass1> == 0);
static_assert(gc_ArrayRank<CTestStruct0> == 0);
static_assert(gc_ArrayRank<CTestStruct1> == 0);
static_assert(gc_ArrayRank<ETestEnum> == 0);
static_assert(gc_ArrayRank<CTestClass> == 0);
static_assert(gc_ArrayRank<CTestC> == 0);
static_assert(gc_ArrayRank<CTestPtr> == 0);
static_assert(gc_ArrayRank<CTestCPtr> == 0);
static_assert(gc_ArrayRank<CTestPtrC> == 0);
static_assert(gc_ArrayRank<CTestCPtrC> == 0);
static_assert(gc_ArrayRank<CTestRef> == 0);
static_assert(gc_ArrayRank<CTestCRef> == 0);
static_assert(gc_ArrayRank<CTestRRef> == 0);
static_assert(gc_ArrayRank<CTestCRRef> == 0);
static_assert(gc_ArrayRank<PFFunc0> == 0);
static_assert(gc_ArrayRank<PFFunc1> == 0);
static_assert(gc_ArrayRank<PFFunc2> == 0);
static_assert(gc_ArrayRank<FFunc0Ref> == 0);
static_assert(gc_ArrayRank<FFunc1Ref> == 0);
static_assert(gc_ArrayRank<FFunc2Ref> == 0);
static_assert(gc_ArrayRank<FFunc0RRef> == 0);
static_assert(gc_ArrayRank<FFunc1RRef> == 0);
static_assert(gc_ArrayRank<FFunc2RRef> == 0);
static_assert(gc_ArrayRank<FFunc0Ptr> == 0);
static_assert(gc_ArrayRank<FFunc1Ptr> == 0);
static_assert(gc_ArrayRank<FFunc2Ptr> == 0);
static_assert(gc_ArrayRank<FFunc0PtrC> == 0);
static_assert(gc_ArrayRank<FFunc1PtrC> == 0);
static_assert(gc_ArrayRank<FFunc2PtrC> == 0);
static_assert(gc_ArrayRank<FMFunc0Ptr> == 0);
static_assert(gc_ArrayRank<FMFunc1Ptr> == 0);
static_assert(gc_ArrayRank<FMFunc2Ptr> == 0);
static_assert(gc_ArrayRank<FMFunc0PtrC> == 0);
static_assert(gc_ArrayRank<FMFunc1PtrC> == 0);
static_assert(gc_ArrayRank<FMFunc2PtrC> == 0);
static_assert(gc_ArrayRank<FMFunc0CPtr> == 0);
static_assert(gc_ArrayRank<FMFunc1CPtr> == 0);
static_assert(gc_ArrayRank<FMFunc2CPtr> == 0);
static_assert(gc_ArrayRank<FMFunc0CPtrC> == 0);
static_assert(gc_ArrayRank<FMFunc1CPtrC> == 0);
static_assert(gc_ArrayRank<FMFunc2CPtrC> == 0);
static_assert(gc_ArrayRank<PFFunc0El> == 0);
static_assert(gc_ArrayRank<PFFunc1El> == 0);
static_assert(gc_ArrayRank<PFFunc2El> == 0);
static_assert(gc_ArrayRank<FFunc0ElRef> == 0);
static_assert(gc_ArrayRank<FFunc1ElRef> == 0);
static_assert(gc_ArrayRank<FFunc2ElRef> == 0);
static_assert(gc_ArrayRank<FFunc0ElRRef> == 0);
static_assert(gc_ArrayRank<FFunc1ElRRef> == 0);
static_assert(gc_ArrayRank<FFunc2ElRRef> == 0);
static_assert(gc_ArrayRank<FFunc0ElPtr> == 0);
static_assert(gc_ArrayRank<FFunc1ElPtr> == 0);
static_assert(gc_ArrayRank<FFunc2ElPtr> == 0);
static_assert(gc_ArrayRank<FFunc0ElPtrC> == 0);
static_assert(gc_ArrayRank<FFunc1ElPtrC> == 0);
static_assert(gc_ArrayRank<FFunc2ElPtrC> == 0);
static_assert(gc_ArrayRank<FMFunc0ElPtr> == 0);
static_assert(gc_ArrayRank<FMFunc1ElPtr> == 0);
static_assert(gc_ArrayRank<FMFunc2ElPtr> == 0);
static_assert(gc_ArrayRank<FMFunc0ElPtrC> == 0);
static_assert(gc_ArrayRank<FMFunc1ElPtrC> == 0);
static_assert(gc_ArrayRank<FMFunc2ElPtrC> == 0);
static_assert(gc_ArrayRank<FMFunc0ElCPtr> == 0);
static_assert(gc_ArrayRank<FMFunc1ElCPtr> == 0);
static_assert(gc_ArrayRank<FMFunc2ElCPtr> == 0);
static_assert(gc_ArrayRank<FMFunc0ElCPtrC> == 0);
static_assert(gc_ArrayRank<FMFunc1ElCPtrC> == 0);
static_assert(gc_ArrayRank<FMFunc2ElCPtrC> == 0);
static_assert(gc_ArrayRank<CMPtr> == 0);
static_assert(gc_ArrayRank<CMCPtr> == 0);
static_assert(gc_ArrayRank<CMPtrC> == 0);
static_assert(gc_ArrayRank<CMCPtrC> == 0);
static_assert(gc_ArrayRank<CTestArray2> == 1);
static_assert(gc_ArrayRank<CTestArray2C> == 1);
static_assert(gc_ArrayRank<CTestArray> == 1);
static_assert(gc_ArrayRank<CTestArrayC> == 1);
static_assert(gc_ArrayRank<CTest2DArray2> == 2);
static_assert(gc_ArrayRank<CTest2DArray2C> == 2);
static_assert(gc_ArrayRank<CTest2DArray> == 2);
static_assert(gc_ArrayRank<CTest2DArrayC> == 2);
static_assert(gc_ArrayRank<CTest3DArray2> == 3);
static_assert(gc_ArrayRank<CTest3DArray2C> == 3);
static_assert(gc_ArrayRank<CTest3DArray> == 3);
static_assert(gc_ArrayRank<CTest3DArrayC> == 3);
static_assert(gc_ArrayRank<void> == 0);
static_assert(gc_ArrayRank<void *> == 0);
