// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsPointer<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<ETestEnum>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestClass>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CTestC>::mc_Value			));
DMibStaticCheck((	TCIsPointer<CTestPtr>::mc_Value			));
DMibStaticCheck((	TCIsPointer<CTestCPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0Ptr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1Ptr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2Ptr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CMPtr>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTest2DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArray>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArray>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArrayC>::mc_Value	));
DMibStaticCheck((	TCIsPointer<void *>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<void>::mc_Value			));



DMibStaticCheck((	TCIsSame<TCAddPointer<CTestUnion>::CType, CTestUnion *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestClass0>::CType, CTestClass0 *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestClass1>::CType, CTestClass1 *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestStruct0>::CType, CTestStruct0 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestStruct1>::CType, CTestStruct1 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<ETestEnum>::CType, ETestEnum *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestClass>::CType, CTestClass *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestC>::CType, CTestC *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestPtr>::CType, CTestPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCPtr>::CType, CTestCPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestPtrC>::CType, CTestPtrC *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCPtrC>::CType, CTestCPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestRef>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCRef>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestRRef>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCRRef>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc0>::CType, PFFunc0 *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc1>::CType, PFFunc1 *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc2>::CType, PFFunc2 *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0Ref>::CType, FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1Ref>::CType, FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2Ref>::CType, FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0RRef>::CType, FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1RRef>::CType, FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2RRef>::CType, FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0Ptr>::CType, FFunc0Ptr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1Ptr>::CType, FFunc1Ptr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2Ptr>::CType, FFunc2Ptr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0PtrC>::CType, FFunc0PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1PtrC>::CType, FFunc1PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2PtrC>::CType, FFunc2PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0Ptr>::CType, FMFunc0Ptr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1Ptr>::CType, FMFunc1Ptr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2Ptr>::CType, FMFunc2Ptr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0PtrC>::CType, FMFunc0PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1PtrC>::CType, FMFunc1PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2PtrC>::CType, FMFunc2PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CPtr>::CType, FMFunc0CPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CPtr>::CType, FMFunc1CPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CPtr>::CType, FMFunc2CPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CPtrC>::CType, FMFunc0CPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CPtrC>::CType, FMFunc1CPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CPtrC>::CType, FMFunc2CPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc0El>::CType, PFFunc0El *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc1El>::CType, PFFunc1El *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc2El>::CType, PFFunc2El *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElRef>::CType, FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElRef>::CType, FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElRef>::CType, FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElRRef>::CType, FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElRRef>::CType, FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElRRef>::CType, FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElPtr>::CType, FFunc0ElPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElPtr>::CType, FFunc1ElPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElPtr>::CType, FFunc2ElPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElPtrC>::CType, FFunc0ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElPtrC>::CType, FFunc1ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElPtrC>::CType, FFunc2ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElPtr>::CType, FMFunc0ElPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElPtr>::CType, FMFunc1ElPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElPtr>::CType, FMFunc2ElPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMPtr>::CType, CMPtr *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCPtr>::CType, CMCPtr *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMPtrC>::CType, CMPtrC *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCPtrC>::CType, CMCPtrC *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArray2>::CType, CTestArray2 *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArray2C>::CType, CTestArray2C *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArray>::CType, CTestArray *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArrayC>::CType, CTestArrayC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArray2>::CType, CTest2DArray2 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArray2C>::CType, CTest2DArray2C *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArray>::CType, CTest2DArray *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArrayC>::CType, CTest2DArrayC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArray2>::CType, CTest3DArray2 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArray2C>::CType, CTest3DArray2C *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArray>::CType, CTest3DArray *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArrayC>::CType, CTest3DArrayC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<void *>::CType, void **>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<void>::CType, void *>::mc_Value						));


// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestPtr>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCPtr>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestPtrC>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCPtrC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0Ref>::CType, FFunc0Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1Ref>::CType, FFunc1Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2Ref>::CType, FFunc2Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0RRef>::CType, FFunc0RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1RRef>::CType, FFunc1RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2RRef>::CType, FFunc2RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0Ptr>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1Ptr>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2Ptr>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0PtrC>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1PtrC>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2PtrC>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElPtr>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElPtr>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElPtr>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElPtrC>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElPtrC>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElPtrC>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMPtrC>::CType, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<void *>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<void>::CType, void>::mc_Value							));

