// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsPointer<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<ETestEnum>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestClass>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CTestCV>::mc_Value			));
DMibStaticCheck((	TCIsPointer<CTestPtr>::mc_Value			));
DMibStaticCheck((	TCIsPointer<CTestCPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestVPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestPtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestVRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestCVRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0Ptr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1Ptr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2Ptr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsPointer<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CMPtr>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CMPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CMPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<CMCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CMVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CMCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTestArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTestArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsPointer<CTestArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArray>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArrayV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArray>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArrayV>::mc_Value	));
DMibStaticCheck((	!TCIsPointer<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsPointer<void *>::mc_Value			));
DMibStaticCheck((	!TCIsPointer<void>::mc_Value			));



DMibStaticCheck((	TCIsSame<TCAddPointer<CTestUnion>::CType, CTestUnion *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestClass0>::CType, CTestClass0 *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestClass1>::CType, CTestClass1 *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestStruct0>::CType, CTestStruct0 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestStruct1>::CType, CTestStruct1 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<ETestEnum>::CType, ETestEnum *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestClass>::CType, CTestClass *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestC>::CType, CTestC *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestV>::CType, CTestV *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCV>::CType, CTestCV *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestPtr>::CType, CTestPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCPtr>::CType, CTestCPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestVPtr>::CType, CTestVPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCVPtr>::CType, CTestCVPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestPtrC>::CType, CTestPtrC *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCPtrC>::CType, CTestCPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestVPtrC>::CType, CTestVPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCVPtrC>::CType, CTestCVPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestPtrV>::CType, CTestPtrV *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCPtrV>::CType, CTestCPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestVPtrV>::CType, CTestVPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCVPtrV>::CType, CTestCVPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestPtrCV>::CType, CTestPtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCPtrCV>::CType, CTestCPtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestVPtrCV>::CType, CTestVPtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCVPtrCV>::CType, CTestCVPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestRef>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCRef>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestVRef>::CType, CTestVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCVRef>::CType, CTestCVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestRRef>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCRRef>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestVRRef>::CType, CTestVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestCVRRef>::CType, CTestCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc0>::CType, PFFunc0 *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc1>::CType, PFFunc1 *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc2>::CType, PFFunc2 *>::mc_Value					));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0Ref>::CType, FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1Ref>::CType, FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2Ref>::CType, FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0RRef>::CType, FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1RRef>::CType, FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2RRef>::CType, FFunc2Ptr>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0Ptr>::CType, FFunc0Ptr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1Ptr>::CType, FFunc1Ptr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2Ptr>::CType, FFunc2Ptr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0PtrC>::CType, FFunc0PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1PtrC>::CType, FFunc1PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2PtrC>::CType, FFunc2PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0PtrV>::CType, FFunc0PtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1PtrV>::CType, FFunc1PtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2PtrV>::CType, FFunc2PtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0PtrCV>::CType, FFunc0PtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1PtrCV>::CType, FFunc1PtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2PtrCV>::CType, FFunc2PtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0Ptr>::CType, FMFunc0Ptr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1Ptr>::CType, FMFunc1Ptr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2Ptr>::CType, FMFunc2Ptr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0PtrC>::CType, FMFunc0PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1PtrC>::CType, FMFunc1PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2PtrC>::CType, FMFunc2PtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0PtrV>::CType, FMFunc0PtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1PtrV>::CType, FMFunc1PtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2PtrV>::CType, FMFunc2PtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0PtrCV>::CType, FMFunc0PtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1PtrCV>::CType, FMFunc1PtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2PtrCV>::CType, FMFunc2PtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CPtr>::CType, FMFunc0CPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CPtr>::CType, FMFunc1CPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CPtr>::CType, FMFunc2CPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CPtrC>::CType, FMFunc0CPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CPtrC>::CType, FMFunc1CPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CPtrC>::CType, FMFunc2CPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CPtrV>::CType, FMFunc0CPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CPtrV>::CType, FMFunc1CPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CPtrV>::CType, FMFunc2CPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0VPtr>::CType, FMFunc0VPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1VPtr>::CType, FMFunc1VPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2VPtr>::CType, FMFunc2VPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0VPtrC>::CType, FMFunc0VPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1VPtrC>::CType, FMFunc1VPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2VPtrC>::CType, FMFunc2VPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0VPtrV>::CType, FMFunc0VPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1VPtrV>::CType, FMFunc1VPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2VPtrV>::CType, FMFunc2VPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CVPtr>::CType, FMFunc0CVPtr *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CVPtr>::CType, FMFunc1CVPtr *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CVPtr>::CType, FMFunc2CVPtr *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc0El>::CType, PFFunc0El *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc1El>::CType, PFFunc1El *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<PFFunc2El>::CType, PFFunc2El *>::mc_Value					));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElRef>::CType, FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElRef>::CType, FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElRef>::CType, FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElRRef>::CType, FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElRRef>::CType, FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElRRef>::CType, FFunc2ElPtr>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElPtr>::CType, FFunc0ElPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElPtr>::CType, FFunc1ElPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElPtr>::CType, FFunc2ElPtr *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElPtrC>::CType, FFunc0ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElPtrC>::CType, FFunc1ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElPtrC>::CType, FFunc2ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElPtrV>::CType, FFunc0ElPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElPtrV>::CType, FFunc1ElPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElPtrV>::CType, FFunc2ElPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElPtr>::CType, FMFunc0ElPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElPtr>::CType, FMFunc1ElPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElPtr>::CType, FMFunc2ElPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMPtr>::CType, CMPtr *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCPtr>::CType, CMCPtr *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMVPtr>::CType, CMVPtr *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCVPtr>::CType, CMCVPtr *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMPtrC>::CType, CMPtrC *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCPtrC>::CType, CMCPtrC *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMVPtrC>::CType, CMVPtrC *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCVPtrC>::CType, CMCVPtrC *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMPtrV>::CType, CMPtrV *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCPtrV>::CType, CMCPtrV *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMVPtrV>::CType, CMVPtrV *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCVPtrV>::CType, CMCVPtrV *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMPtrCV>::CType, CMPtrCV *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCPtrCV>::CType, CMCPtrCV *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMVPtrCV>::CType, CMVPtrCV *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CMCVPtrCV>::CType, CMCVPtrCV *>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArray2>::CType, CTestArray2 *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArray2C>::CType, CTestArray2C *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArray2V>::CType, CTestArray2V *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArray2CV>::CType, CTestArray2CV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArray>::CType, CTestArray *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArrayC>::CType, CTestArrayC *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArrayV>::CType, CTestArrayV *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTestArrayCV>::CType, CTestArrayCV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArray2>::CType, CTest2DArray2 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArray2C>::CType, CTest2DArray2C *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArray2V>::CType, CTest2DArray2V *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArray2CV>::CType, CTest2DArray2CV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArray>::CType, CTest2DArray *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArrayC>::CType, CTest2DArrayC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArrayV>::CType, CTest2DArrayV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest2DArrayCV>::CType, CTest2DArrayCV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArray2>::CType, CTest3DArray2 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArray2C>::CType, CTest3DArray2C *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArray2V>::CType, CTest3DArray2V *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArray2CV>::CType, CTest3DArray2CV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArray>::CType, CTest3DArray *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArrayC>::CType, CTest3DArrayC *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArrayV>::CType, CTest3DArrayV *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddPointer<CTest3DArrayCV>::CType, CTest3DArrayCV *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddPointer<void *>::CType, void **>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddPointer<void>::CType, void *>::mc_Value						));


// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestV>::CType, CTestV>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCV>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestPtr>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCPtr>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestVPtr>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCVPtr>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestPtrC>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCPtrC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestVPtrC>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCVPtrC>::CType, CTestCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestPtrV>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCPtrV>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestVPtrV>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCVPtrV>::CType, CTestCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestPtrCV>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCPtrCV>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestVPtrCV>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCVPtrCV>::CType, CTestCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestVRef>::CType, CTestVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCVRef>::CType, CTestCVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestVRRef>::CType, CTestVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestCVRRef>::CType, CTestCVRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0Ref>::CType, FFunc0Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1Ref>::CType, FFunc1Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2Ref>::CType, FFunc2Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0RRef>::CType, FFunc0RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1RRef>::CType, FFunc1RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2RRef>::CType, FFunc2RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0Ptr>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1Ptr>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2Ptr>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0PtrC>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1PtrC>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2PtrC>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0PtrV>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1PtrV>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2PtrV>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0PtrCV>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1PtrCV>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2PtrCV>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0PtrV>::CType, FMFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1PtrV>::CType, FMFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2PtrV>::CType, FMFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0PtrCV>::CType, FMFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1PtrCV>::CType, FMFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2PtrCV>::CType, FMFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CPtrV>::CType, FMFunc0CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CPtrV>::CType, FMFunc1CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CPtrV>::CType, FMFunc2CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0VPtr>::CType, FMFunc0VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1VPtr>::CType, FMFunc1VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2VPtr>::CType, FMFunc2VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0VPtrC>::CType, FMFunc0VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1VPtrC>::CType, FMFunc1VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2VPtrC>::CType, FMFunc2VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0VPtrV>::CType, FMFunc0VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1VPtrV>::CType, FMFunc1VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2VPtrV>::CType, FMFunc2VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CVPtr>::CType, FMFunc0CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CVPtr>::CType, FMFunc1CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CVPtr>::CType, FMFunc2CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElPtr>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElPtr>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElPtr>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElPtrC>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElPtrC>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElPtrC>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElPtrV>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElPtrV>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElPtrV>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc0ElPtrCV>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc1ElPtrCV>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FFunc2ElPtrCV>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMVPtr>::CType, CMVPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCVPtr>::CType, CMCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMPtrC>::CType, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMVPtrC>::CType, CMVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCVPtrC>::CType, CMCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMPtrV>::CType, CMPtrV>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCPtrV>::CType, CMCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMVPtrV>::CType, CMVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCVPtrV>::CType, CMCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMPtrCV>::CType, CMPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCPtrCV>::CType, CMCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMVPtrCV>::CType, CMVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CMCVPtrCV>::CType, CMCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArray2V>::CType, CTestArray2V>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArray2CV>::CType, CTestArray2CV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArrayV>::CType, CTestArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTestArrayCV>::CType, CTestArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArray2V>::CType, CTest2DArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArray2CV>::CType, CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArray2V>::CType, CTest3DArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArray2CV>::CType, CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemovePointer<void *>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemovePointer<void>::CType, void>::mc_Value							));

