// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NStandardLayout
{
	class CAbstract
	{
		virtual void f_Test() pure;
	};
	class CInheritAbstract : private CAbstract
	{
	};
	class CNonAbstract
	{
		virtual void f_Test();
	};
	class CNonVirtual
	{
		void f_Test();
	};
	DMibStaticCheck((	!TCIsStandardLayout<CAbstract>::mc_Value						));
	DMibStaticCheck((	!TCIsStandardLayout<CInheritAbstract>::mc_Value						));
	DMibStaticCheck((	!TCIsStandardLayout<CNonAbstract>::mc_Value						));
	DMibStaticCheck((	TCIsStandardLayout<CNonVirtual>::mc_Value						));
	
}

// Void
DMibStaticCheck((	TCIsStandardLayout<CTestUnion>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsStandardLayout<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsStandardLayout<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsStandardLayout<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsStandardLayout<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsStandardLayout<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCIsStandardLayout<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	TCIsStandardLayout<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCIsStandardLayout<ETestEnum>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<int>::mc_Value							));
DMibStaticCheck((	TCIsStandardLayout<CTestClass>::mc_Value							));
DMibStaticCheck((	TCIsStandardLayout<CTestC>::mc_Value							));
DMibStaticCheck((	TCIsStandardLayout<CTestV>::mc_Value							));
DMibStaticCheck((	TCIsStandardLayout<CTestCV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CTestPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStandardLayout<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<CTestVRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<CTestCVRef>::mc_Value					));
DMibStaticCheck((	!TCIsStandardLayout<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCIsStandardLayout<CTestVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsStandardLayout<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsStandardLayout<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsStandardLayout<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsStandardLayout<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<CMPtr>::mc_Value							));
DMibStaticCheck((	TCIsStandardLayout<CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMVPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMPtrV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<CTestArray2>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestArray2C>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestArray2V>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestArray>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestArrayC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestArrayV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<CTest2DArray>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<CTest3DArray>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	TCIsStandardLayout<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	TCIsStandardLayout<void *>::mc_Value						));
DMibStaticCheck((	TCIsStandardLayout<void>::mc_Value							));

