// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NStateless
{
	class CAbstract
	{
		virtual void f_Test() pure;
	};
	class CInheritAbstract : private CAbstract
	{
	};
	class CNonAbstract
	{
		virtual void f_Test();
	};
	class CNonVirtual
	{
		void f_Test();
	};
	DMibStaticCheck((	!TCIsStateless<CAbstract>::mc_Value						));
	DMibStaticCheck((	!TCIsStateless<CInheritAbstract>::mc_Value						));
	DMibStaticCheck((	!TCIsStateless<CNonAbstract>::mc_Value						));
	DMibStaticCheck((	TCIsStateless<CNonVirtual>::mc_Value						));
	
}

// Void
DMibStaticCheck((	!TCIsStateless<CTestUnion>::mc_Value						));
DMibStaticCheck((	TCIsStateless<CTestClass0>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCIsStateless<CTestStruct0>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCIsStateless<const CTestClass0>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCIsStateless<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCIsStateless<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	!TCIsStateless<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsStateless<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	!TCIsStateless<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsStateless<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsStateless<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCIsStateless<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsStateless<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsStateless<ETestEnum>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<int>::mc_Value							));
DMibStaticCheck((	!TCIsStateless<CTestClass>::mc_Value							));
DMibStaticCheck((	!TCIsStateless<CTestC>::mc_Value							));
DMibStaticCheck((	!TCIsStateless<CTestV>::mc_Value							));
DMibStaticCheck((	!TCIsStateless<CTestCV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestVRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestCVRef>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<PFFunc2>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	!TCIsStateless<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc2RRef>::mc_Value						));
#endif
DMibStaticCheck((	!TCIsStateless<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<PFFunc2El>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	!TCIsStateless<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc2ElRRef>::mc_Value						));
#endif
DMibStaticCheck((	!TCIsStateless<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<CMPtr>::mc_Value							));
DMibStaticCheck((	!TCIsStateless<CMCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMCVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMCPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMVPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMCPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMVPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<CTestArray2>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestArray2C>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestArray2V>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestArray>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<CTest2DArray>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<CTest3DArray>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsStateless<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	!TCIsStateless<void *>::mc_Value						));
DMibStaticCheck((	!TCIsStateless<void>::mc_Value							));

