// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Is function																						|
|___________________________________________________________________________________________________|
\***************************************************************************************************/



DMibStaticCheck((	!TCFunctionTraits<CTestUnion>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestClass0>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTestClass1>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTestStruct0>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTestStruct1>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<ETestEnum>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestClass>::mc_IsFunction				));
DMibStaticCheck((	!TCFunctionTraits<CTestC>::mc_IsFunction				));
DMibStaticCheck((	!TCFunctionTraits<CTestPtr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestCPtr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestPtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestCPtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestRef>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestCRef>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestRRef>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestCRRef>::mc_IsFunction			));
DMibStaticCheck((	TCFunctionTraits<PFFunc0>::mc_IsFunction				));
DMibStaticCheck((	TCFunctionTraits<PFFunc1>::mc_IsFunction				));
DMibStaticCheck((	TCFunctionTraits<PFFunc2>::mc_IsFunction				));
DMibStaticCheck((	!TCFunctionTraits<FFunc0Ref>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1Ref>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2Ref>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0RRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1RRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2RRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0Ptr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1Ptr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2Ptr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc0PtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1PtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2PtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0Ptr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1Ptr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2Ptr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0PtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1PtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2PtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0CPtr>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1CPtr>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2CPtr>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0CPtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1CPtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2CPtrC>::mc_IsFunction		));
DMibStaticCheck((	TCFunctionTraits<PFFunc0El>::mc_IsFunction				));
DMibStaticCheck((	TCFunctionTraits<PFFunc1El>::mc_IsFunction				));
DMibStaticCheck((	TCFunctionTraits<PFFunc2El>::mc_IsFunction				));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElRRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElRRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElRRef>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElPtr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElPtr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElPtr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElPtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElPtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElPtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElPtr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElPtr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElPtr>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElPtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElPtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElPtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElCPtr>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElCPtr>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElCPtr>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElCPtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElCPtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElCPtrC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CMPtr>::mc_IsFunction				));
DMibStaticCheck((	!TCFunctionTraits<CMCPtr>::mc_IsFunction				));
DMibStaticCheck((	!TCFunctionTraits<CMPtrC>::mc_IsFunction				));
DMibStaticCheck((	!TCFunctionTraits<CMCPtrC>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestArray2>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTestArray2C>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTestArray>::mc_IsFunction			));
DMibStaticCheck((	!TCFunctionTraits<CTestArrayC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray2>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray2C>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArrayC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray2>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray2C>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArrayC>::mc_IsFunction		));
DMibStaticCheck((	!TCFunctionTraits<void *>::mc_IsFunction				));
DMibStaticCheck((	!TCFunctionTraits<void>::mc_IsFunction				));



DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestUnion>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass0>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass1>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestStruct0>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestStruct1>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<ETestEnum>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestC>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestPtr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCPtr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestPtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCPtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestRef>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCRef>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestRRef>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCRRef>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc0>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc1>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc2>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0Ref>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1Ref>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2Ref>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0RRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1RRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2RRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0Ptr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1Ptr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2Ptr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0PtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1PtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2PtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0Ptr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1Ptr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2Ptr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0PtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1PtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2PtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0CPtr>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1CPtr>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2CPtr>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0CPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1CPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2CPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc0El>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc1El>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc2El>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElRRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElRRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElRRef>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElPtr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElPtr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElPtr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElPtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElPtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElPtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElPtr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElPtr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElPtr>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMPtr>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMCPtr>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMPtrC>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMCPtrC>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray2>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray2C>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray>::mc_IsMemberFunctionPointer			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArrayC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray2>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray2C>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArrayC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray2>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray2C>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArrayC>::mc_IsMemberFunctionPointer		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<void *>::mc_IsMemberFunctionPointer				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<void>::mc_IsMemberFunctionPointer				));


/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Arity																								|
|___________________________________________________________________________________________________|
\***************************************************************************************************/




DMibStaticCheck((	!TCFunctionTraits<CTestUnion>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestClass0>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTestClass1>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTestStruct0>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTestStruct1>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<ETestEnum>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestClass>::mc_Arity				));
DMibStaticCheck((	!TCFunctionTraits<CTestC>::mc_Arity				));
DMibStaticCheck((	!TCFunctionTraits<CTestPtr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestCPtr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestPtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestCPtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestRef>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestCRef>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestRRef>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestCRRef>::mc_Arity			));
DMibStaticCheck((	TCFunctionTraits<PFFunc0>::mc_Arity == 0		));
DMibStaticCheck((	TCFunctionTraits<PFFunc1>::mc_Arity == 0		));
DMibStaticCheck((	TCFunctionTraits<PFFunc2>::mc_Arity == 1		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0Ref>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1Ref>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2Ref>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0RRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1RRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2RRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0Ptr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1Ptr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2Ptr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc0PtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1PtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2PtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0Ptr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1Ptr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2Ptr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0PtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1PtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2PtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0CPtr>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1CPtr>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2CPtr>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0CPtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1CPtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2CPtrC>::mc_Arity		));
DMibStaticCheck((	TCFunctionTraits<PFFunc0El>::mc_Arity == 0			));
DMibStaticCheck((	TCFunctionTraits<PFFunc1El>::mc_Arity == 0			));
DMibStaticCheck((	TCFunctionTraits<PFFunc2El>::mc_Arity == 1			));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElRRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElRRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElRRef>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElPtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElPtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElPtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElPtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElPtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElPtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElCPtr>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElCPtr>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElCPtr>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElCPtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElCPtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElCPtrC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CMPtr>::mc_Arity				));
DMibStaticCheck((	!TCFunctionTraits<CMCPtr>::mc_Arity				));
DMibStaticCheck((	!TCFunctionTraits<CMPtrC>::mc_Arity				));
DMibStaticCheck((	!TCFunctionTraits<CMCPtrC>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestArray2>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTestArray2C>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTestArray>::mc_Arity			));
DMibStaticCheck((	!TCFunctionTraits<CTestArrayC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray2>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray2C>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArrayC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray2>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray2C>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArrayC>::mc_Arity		));
DMibStaticCheck((	!TCFunctionTraits<void *>::mc_Arity				));
DMibStaticCheck((	!TCFunctionTraits<void>::mc_Arity				));



DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestUnion>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass0>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass1>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestStruct0>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestStruct1>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<ETestEnum>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestC>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestPtr>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCPtr>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestPtrC>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCPtrC>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestRef>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCRef>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestRRef>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCRRef>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc0>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc1>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc2>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0Ref>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1Ref>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2Ref>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0RRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1RRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2RRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0Ptr>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1Ptr>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2Ptr>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0PtrC>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1PtrC>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2PtrC>::mc_Arity			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0Ptr>::mc_Arity == 0			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1Ptr>::mc_Arity == 0			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2Ptr>::mc_Arity == 1			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0PtrC>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1PtrC>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2PtrC>::mc_Arity == 1		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0CPtr>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1CPtr>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2CPtr>::mc_Arity == 1		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0CPtrC>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1CPtrC>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2CPtrC>::mc_Arity == 1		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc0El>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc1El>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc2El>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElRRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElRRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElRRef>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElPtr>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElPtrC>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElPtrC>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElPtrC>::mc_Arity			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElPtr>::mc_Arity == 0			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElPtr>::mc_Arity == 0			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElPtr>::mc_Arity == 1			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::mc_Arity == 1		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::mc_Arity == 1		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::mc_Arity == 0		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::mc_Arity == 1		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMPtr>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMCPtr>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMPtrC>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMCPtrC>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray2>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray2C>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray>::mc_Arity			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArrayC>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray2>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray2C>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArrayC>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray2>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray2C>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArrayC>::mc_Arity		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<void *>::mc_Arity				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<void>::mc_Arity				));



/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Ellipsis																							|
|___________________________________________________________________________________________________|
\***************************************************************************************************/



DMibStaticCheck((	!TCFunctionTraits<CTestUnion>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestClass0>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTestClass1>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTestStruct0>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTestStruct1>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<ETestEnum>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestClass>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<CTestC>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<CTestPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestCPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestCPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestRef>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestCRef>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestRRef>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestCRRef>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<PFFunc0>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<PFFunc1>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<PFFunc2>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<FFunc0Ref>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1Ref>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2Ref>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0RRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1RRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2RRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc0PtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1PtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2PtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0PtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1PtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2PtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0CPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1CPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2CPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0CPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1CPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2CPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	TCFunctionTraits<PFFunc0El>::mc_IsEllipsis				));
DMibStaticCheck((	TCFunctionTraits<PFFunc1El>::mc_IsEllipsis				));
DMibStaticCheck((	TCFunctionTraits<PFFunc2El>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElRRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElRRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElRRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc0ElPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc1ElPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FFunc2ElPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElCPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElCPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElCPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc0ElCPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc1ElCPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<FMFunc2ElCPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CMPtr>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<CMCPtr>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<CMPtrC>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<CMCPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestArray2>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTestArray2C>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTestArray>::mc_IsEllipsis			));
DMibStaticCheck((	!TCFunctionTraits<CTestArrayC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray2>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray2C>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArray>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTest2DArrayC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray2>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray2C>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArray>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<CTest3DArrayC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCFunctionTraits<void *>::mc_IsEllipsis				));
DMibStaticCheck((	!TCFunctionTraits<void>::mc_IsEllipsis				));



DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestUnion>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass0>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass1>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestStruct0>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestStruct1>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<ETestEnum>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestClass>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestC>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestRef>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCRef>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestRRef>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestCRRef>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc0>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc1>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc2>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0Ref>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1Ref>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2Ref>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0RRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1RRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2RRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0PtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1PtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2PtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc0Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc1Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc2Ptr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc0PtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc1PtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc2PtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc0CPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc1CPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc2CPtr>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc0CPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc1CPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FMFunc2CPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc0El>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc1El>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<PFFunc2El>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElRRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElRRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElRRef>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc0ElPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc1ElPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<FFunc2ElPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElPtr>::mc_IsEllipsis			));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::mc_IsEllipsis		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::mc_IsEllipsis		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::mc_IsEllipsis		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMPtr>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMCPtr>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMPtrC>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CMCPtrC>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray2>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray2C>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArray>::mc_IsEllipsis			));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTestArrayC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray2>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray2C>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArray>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest2DArrayC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray2>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray2C>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArray>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<CTest3DArrayC>::mc_IsEllipsis		));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<void *>::mc_IsEllipsis				));
DMibStaticCheck((	!TCMemberFunctionPointerTraits<void>::mc_IsEllipsis				));


/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Return																							|
|___________________________________________________________________________________________________|
\***************************************************************************************************/



DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestUnion>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestClass0>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestClass1>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestStruct0>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestStruct1>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<ETestEnum>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestClass>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestC>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestCPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestCPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestRef>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestCRef>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestRRef>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestCRRef>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<PFFunc0>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<PFFunc1>::CReturn, CTestBase>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<PFFunc2>::CReturn, CTestBase>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc0Ref>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc1Ref>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc2Ref>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc0RRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc1RRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc2RRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc0Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc1Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc2Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc0PtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc1PtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc2PtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc0Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc1Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc2Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc0PtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc1PtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc2PtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc0CPtr>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc1CPtr>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc2CPtr>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc0CPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc1CPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc2CPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<PFFunc0El>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<PFFunc1El>::CReturn, CTestBase>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<PFFunc2El>::CReturn, CTestBase>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc0ElRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc1ElRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc2ElRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc0ElRRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc1ElRRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc2ElRRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc0ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc1ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc2ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc0ElPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc1ElPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FFunc2ElPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc0ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc1ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc2ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc0ElPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc1ElPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc2ElPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc0ElCPtr>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc1ElCPtr>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc2ElCPtr>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc0ElCPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc1ElCPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<FMFunc2ElCPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CMPtr>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CMCPtr>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CMPtrC>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CMCPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestArray2>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestArray2C>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestArray>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTestArrayC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTest2DArray2>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTest2DArray2C>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTest2DArray>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTest2DArrayC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTest3DArray2>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTest3DArray2C>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTest3DArray>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<CTest3DArrayC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<void *>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits<void>::CReturn, void>::mc_Value				));

DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestUnion>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass0>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass1>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestStruct0>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestStruct1>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<ETestEnum>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestC>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestRef>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCRef>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestRRef>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCRRef>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc0>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc1>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc2>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0Ref>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1Ref>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2Ref>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0RRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1RRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2RRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0PtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1PtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2PtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0Ptr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1Ptr>::CReturn, CTestBase>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2Ptr>::CReturn, CTestBase>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0PtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1PtrC>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2PtrC>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtr>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtr>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtr>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtrC>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtrC>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc0El>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc1El>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc2El>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElRRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElRRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElRRef>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtr>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtr>::CReturn, CTestBase>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtr>::CReturn, CTestBase>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::CReturn, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMPtr>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMCPtr>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMPtrC>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMCPtrC>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray2>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray2C>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray>::CReturn, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArrayC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray2>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray2C>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArrayC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray2>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray2C>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArrayC>::CReturn, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<void *>::CReturn, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<void>::CReturn, void>::mc_Value				));


/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Argument type 0																					|
|___________________________________________________________________________________________________|
\***************************************************************************************************/

DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestUnion, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestClass0, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestClass1, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestStruct0, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestStruct1, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<ETestEnum, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestClass, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestC, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestCPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestCPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestRef, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestCRef, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestRRef, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestCRRef, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<PFFunc0, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<PFFunc1, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<PFFunc2, 0>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc0Ref, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc1Ref, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc2Ref, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc0RRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc1RRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc2RRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc0Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc1Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc2Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc0PtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc1PtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc2PtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc0Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc1Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc2Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc0PtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc1PtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc2PtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc0CPtr, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc1CPtr, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc2CPtr, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc0CPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc1CPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc2CPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<PFFunc0El, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<PFFunc1El, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<PFFunc2El, 0>::CType, CTestBase>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc0ElRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc1ElRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc2ElRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc0ElRRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc1ElRRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc2ElRRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc0ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc1ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc2ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc0ElPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc1ElPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FFunc2ElPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc0ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc1ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc2ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc0ElPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc1ElPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc2ElPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc0ElCPtr, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc1ElCPtr, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc2ElCPtr, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc0ElCPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc1ElCPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<FMFunc2ElCPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CMPtr, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CMCPtr, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CMPtrC, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CMCPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestArray2, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestArray2C, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestArray, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTestArrayC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTest2DArray2, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTest2DArray2C, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTest2DArray, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTest2DArrayC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTest3DArray2, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTest3DArray2C, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTest3DArray, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<CTest3DArrayC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<void *, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCFunctionTraits_ArgumentType<void, 0>::CType, void>::mc_Value				));

DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestUnion, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestClass0, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestClass1, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestStruct0, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestStruct1, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<ETestEnum, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestClass, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestC, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestCPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestCPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestRef, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestCRef, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestRRef, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestCRRef, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc0, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc1, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc2, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0Ref, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1Ref, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2Ref, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0RRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1RRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2RRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0PtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1PtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2PtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1Ptr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2Ptr, 0>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0PtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1PtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2PtrC, 0>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0CPtr, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1CPtr, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2CPtr, 0>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0CPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1CPtrC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2CPtrC, 0>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc0El, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc1El, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc2El, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0ElRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1ElRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2ElRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0ElRRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1ElRRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2ElRRef, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2ElPtr, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0ElPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1ElPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2ElPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0ElPtr, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1ElPtr, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2ElPtr, 0>::CType, CTestBase>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0ElPtrC, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1ElPtrC, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2ElPtrC, 0>::CType, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0ElCPtr, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1ElCPtr, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2ElCPtr, 0>::CType, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0ElCPtrC, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1ElCPtrC, 0>::CType, CFunctionTraitTag_Ellipsis>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2ElCPtrC, 0>::CType, CTestBase>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CMPtr, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CMCPtr, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CMPtrC, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CMCPtrC, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestArray2, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestArray2C, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestArray, 0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestArrayC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest2DArray2, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest2DArray2C, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest2DArray, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest2DArrayC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest3DArray2, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest3DArray2C, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest3DArray, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest3DArrayC, 0>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<void *, 0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits_ArgumentType<void, 0>::CType, void>::mc_Value				));

/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Class type																						|
|___________________________________________________________________________________________________|
\***************************************************************************************************/

DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestUnion>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass0>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass1>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestStruct0>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestStruct1>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<ETestEnum>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestC>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestPtr>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCPtr>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestPtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCPtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestRef>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCRef>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestRRef>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCRRef>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc0>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc1>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc2>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0Ref>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1Ref>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2Ref>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0RRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1RRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2RRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0Ptr>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1Ptr>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2Ptr>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0PtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1PtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2PtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0Ptr>::CClass, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1Ptr>::CClass, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2Ptr>::CClass, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0PtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1PtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2PtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtr>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtr>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtr>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc0El>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc1El>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc2El>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElRRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElRRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElRRef>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtr>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtr>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtr>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtr>::CClass, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtr>::CClass, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtr>::CClass, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::CClass, CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMPtr>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMCPtr>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMPtrC>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMCPtrC>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray2>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray2C>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray>::CClass, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArrayC>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray2>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray2C>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArrayC>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray2>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray2C>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArrayC>::CClass, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<void *>::CClass, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<void>::CClass, void>::mc_Value				));



/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Function type																						|
|___________________________________________________________________________________________________|
\***************************************************************************************************/

DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestUnion>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass0>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass1>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestStruct0>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestStruct1>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<ETestEnum>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestClass>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestC>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestPtr>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCPtr>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestPtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCPtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestRef>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCRef>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestRRef>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestCRRef>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc0>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc1>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc2>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0Ref>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1Ref>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2Ref>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0RRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1RRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2RRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0Ptr>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1Ptr>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2Ptr>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0PtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1PtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2PtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0Ptr>::CFunctionType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1Ptr>::CFunctionType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2Ptr>::CFunctionType, PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0PtrC>::CFunctionType, PFFunc0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1PtrC>::CFunctionType, PFFunc1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2PtrC>::CFunctionType, PFFunc2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtr>::CFunctionType, PFFunc0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtr>::CFunctionType, PFFunc1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtr>::CFunctionType, PFFunc2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtrC>::CFunctionType, PFFunc0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtrC>::CFunctionType, PFFunc1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtrC>::CFunctionType, PFFunc2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc0El>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc1El>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<PFFunc2El>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElRRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElRRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElRRef>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtr>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtr>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtr>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtr>::CFunctionType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtr>::CFunctionType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtr>::CFunctionType, PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::CFunctionType, PFFunc0El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::CFunctionType, PFFunc1El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::CFunctionType, PFFunc2El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::CFunctionType, PFFunc0El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::CFunctionType, PFFunc1El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::CFunctionType, PFFunc2El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::CFunctionType, PFFunc0El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::CFunctionType, PFFunc1El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::CFunctionType, PFFunc2El>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMPtr>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMCPtr>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMPtrC>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CMCPtrC>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray2>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray2C>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArray>::CFunctionType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTestArrayC>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray2>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray2C>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArray>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest2DArrayC>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray2>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray2C>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArray>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<CTest3DArrayC>::CFunctionType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<void *>::CFunctionType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFunctionPointerTraits<void>::CFunctionType, void>::mc_Value				));

