// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NTrivial
{

	DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CNonTrivialAssignment>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialAssignmentInt>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CNonTrivialAssignmentBoth>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CNonTrivialAssignmentDerived>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CNonTrivialAssignmentDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTrivial>::mc_Value						));

	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialCopy>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialCopyInt>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialCopyBoth>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialCopyDerived>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialCopyDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTrivial>::mc_Value						));

	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialConstruct>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialConstructDerived>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CNonTrivialConstructDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTrivial>::mc_Value						));

	DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CTestClassVirtual>::mc_Value						));

}

// Void
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestUnion>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<ETestEnum>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<int>::mc_Value							));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestClass>::mc_Value							));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestC>::mc_Value							));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestV>::mc_Value							));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CTestCRef>::mc_Value						));
#ifndef DCompiler_MSVC
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestVRef>::mc_Value						));
#endif
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CTestCVRef>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CTestCRRef>::mc_Value					));
#ifndef DCompiler_MSVC
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestVRRef>::mc_Value					));
#endif
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialAssignmentOperator<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMPtr>::mc_Value							));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMCPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestArray2C>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestArray2V>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest2DArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest3DArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<void *>::mc_Value						));
DMibStaticCheck((	TCHasTrivialAssignmentOperator<void>::mc_Value							));

