// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsLValueReference<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<ETestEnum>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestClass>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CTestCV>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CTestPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<CTestRef>::mc_Value			));
DMibStaticCheck((	TCIsLValueReference<CTestCRef>::mc_Value		));
DMibStaticCheck((	TCIsLValueReference<CTestVRef>::mc_Value		));
DMibStaticCheck((	TCIsLValueReference<CTestCVRef>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<PFFunc2>::mc_Value			));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsLValueReference<FFunc0Ref>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<FFunc1Ref>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<FFunc2Ref>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc0RRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc1RRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc2RRef>::mc_Value	));
#endif
DMibStaticCheck((	!TCIsLValueReference<FFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2PtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2VPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2VPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2VPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<PFFunc2El>::mc_Value			));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsLValueReference<FFunc0ElRef>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<FFunc1ElRef>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<FFunc2ElRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc0ElRRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc1ElRRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc2ElRRef>::mc_Value	));
#endif
DMibStaticCheck((	!TCIsLValueReference<FFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCVPtr>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCVPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCVPtrV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CMPtr>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CMPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CMPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CMVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CMCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTestArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTestArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArray>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArrayV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArray>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArrayV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<void *>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<void>::mc_Value			));



DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestUnion>::CType, CTestUnion &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestClass0>::CType, CTestClass0 &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestClass1>::CType, CTestClass1 &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestStruct0>::CType, CTestStruct0 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestStruct1>::CType, CTestStruct1 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<ETestEnum>::CType, ETestEnum &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestClass>::CType, CTestClass &>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestC>::CType, CTestC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestV>::CType, CTestV &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCV>::CType, CTestCV &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestPtr>::CType, CTestPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCPtr>::CType, CTestCPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestVPtr>::CType, CTestVPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCVPtr>::CType, CTestCVPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestPtrC>::CType, CTestPtrC &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCPtrC>::CType, CTestCPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestVPtrC>::CType, CTestVPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCVPtrC>::CType, CTestCVPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestPtrV>::CType, CTestPtrV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCPtrV>::CType, CTestCPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestVPtrV>::CType, CTestVPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCVPtrV>::CType, CTestCVPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestPtrCV>::CType, CTestPtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCPtrCV>::CType, CTestCPtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestVPtrCV>::CType, CTestVPtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCVPtrCV>::CType, CTestCVPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestRef>::CType, CTestRef>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCRef>::CType, CTestCRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestVRef>::CType, CTestVRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCVRef>::CType, CTestCVRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestRRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCRRef>::CType, CTestCRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestVRRef>::CType, CTestVRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCVRRef>::CType, CTestCVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc0>::CType, PFFunc0 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc1>::CType, PFFunc1 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc2>::CType, PFFunc2 &>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0Ref>::CType, FFunc0Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1Ref>::CType, FFunc1Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2Ref>::CType, FFunc2Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0RRef>::CType, FFunc0Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1RRef>::CType, FFunc1Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2RRef>::CType, FFunc2Ref>::mc_Value				));
#endif
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0Ptr>::CType, FFunc0Ptr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1Ptr>::CType, FFunc1Ptr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2Ptr>::CType, FFunc2Ptr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0PtrC>::CType, FFunc0PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1PtrC>::CType, FFunc1PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2PtrC>::CType, FFunc2PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0PtrV>::CType, FFunc0PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1PtrV>::CType, FFunc1PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2PtrV>::CType, FFunc2PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0PtrCV>::CType, FFunc0PtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1PtrCV>::CType, FFunc1PtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2PtrCV>::CType, FFunc2PtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0Ptr>::CType, FMFunc0Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1Ptr>::CType, FMFunc1Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2Ptr>::CType, FMFunc2Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0PtrC>::CType, FMFunc0PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1PtrC>::CType, FMFunc1PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2PtrC>::CType, FMFunc2PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0PtrV>::CType, FMFunc0PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1PtrV>::CType, FMFunc1PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2PtrV>::CType, FMFunc2PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0PtrCV>::CType, FMFunc0PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1PtrCV>::CType, FMFunc1PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2PtrCV>::CType, FMFunc2PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CPtr>::CType, FMFunc0CPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CPtr>::CType, FMFunc1CPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CPtr>::CType, FMFunc2CPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CPtrV>::CType, FMFunc0CPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CPtrV>::CType, FMFunc1CPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CPtrV>::CType, FMFunc2CPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0VPtr>::CType, FMFunc0VPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1VPtr>::CType, FMFunc1VPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2VPtr>::CType, FMFunc2VPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0VPtrC>::CType, FMFunc0VPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1VPtrC>::CType, FMFunc1VPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2VPtrC>::CType, FMFunc2VPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0VPtrV>::CType, FMFunc0VPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1VPtrV>::CType, FMFunc1VPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2VPtrV>::CType, FMFunc2VPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CVPtr>::CType, FMFunc0CVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CVPtr>::CType, FMFunc1CVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CVPtr>::CType, FMFunc2CVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc0El>::CType, PFFunc0El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc1El>::CType, PFFunc1El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc2El>::CType, PFFunc2El &>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElRRef>::CType, FFunc0ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElRRef>::CType, FFunc1ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElRRef>::CType, FFunc2ElRef>::mc_Value				));
#endif
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElPtr>::CType, FFunc0ElPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElPtr>::CType, FFunc1ElPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElPtr>::CType, FFunc2ElPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElPtrV>::CType, FFunc0ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElPtrV>::CType, FFunc1ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElPtrV>::CType, FFunc2ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMPtr>::CType, CMPtr &>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCPtr>::CType, CMCPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMVPtr>::CType, CMVPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCVPtr>::CType, CMCVPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMPtrC>::CType, CMPtrC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCPtrC>::CType, CMCPtrC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMVPtrC>::CType, CMVPtrC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCVPtrC>::CType, CMCVPtrC &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMPtrV>::CType, CMPtrV &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCPtrV>::CType, CMCPtrV &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMVPtrV>::CType, CMVPtrV &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCVPtrV>::CType, CMCVPtrV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMPtrCV>::CType, CMPtrCV &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCPtrCV>::CType, CMCPtrCV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMVPtrCV>::CType, CMVPtrCV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCVPtrCV>::CType, CMCVPtrCV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArray2>::CType, CTestArray2 &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArray2C>::CType, CTestArray2C &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArray2V>::CType, CTestArray2V &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArray2CV>::CType, CTestArray2CV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArray>::CType, CTestArray>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArrayC>::CType, CTestArrayC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArrayV>::CType, CTestArrayV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArrayCV>::CType, CTestArrayCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArray2>::CType, CTest2DArray2 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArray2C>::CType, CTest2DArray2C &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArray2V>::CType, CTest2DArray2V &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArray2CV>::CType, CTest2DArray2CV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArray>::CType, CTest2DArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArray2>::CType, CTest3DArray2 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArray2C>::CType, CTest3DArray2C &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArray2V>::CType, CTest3DArray2V &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArray2CV>::CType, CTest3DArray2CV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArray>::CType, CTest3DArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<void *>::CType, void *&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<void>::CType, void>::mc_Value								));

// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestV>::CType, CTestV>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCV>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestPtr>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestVPtr>::CType, CTestVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCVPtr>::CType, CTestCVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCPtrC>::CType, CTestCPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestVPtrC>::CType, CTestVPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCVPtrC>::CType, CTestCVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestPtrV>::CType, CTestPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCPtrV>::CType, CTestCPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestVPtrV>::CType, CTestVPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCVPtrV>::CType, CTestCVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestPtrCV>::CType, CTestPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCPtrCV>::CType, CTestCPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestVPtrCV>::CType, CTestVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCVPtrCV>::CType, CTestCVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestRef>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCRef>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestVRef>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCVRef>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestVRRef>::CType, CTestVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCVRRef>::CType, CTestCVRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc2>::CType, PFFunc2>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0Ref>::CType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1Ref>::CType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2Ref>::CType, PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0PtrV>::CType, FFunc0PtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1PtrV>::CType, FFunc1PtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2PtrV>::CType, FFunc2PtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0PtrCV>::CType, FFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1PtrCV>::CType, FFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2PtrCV>::CType, FFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0PtrV>::CType, FMFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1PtrV>::CType, FMFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2PtrV>::CType, FMFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0PtrCV>::CType, FMFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1PtrCV>::CType, FMFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2PtrCV>::CType, FMFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CPtrV>::CType, FMFunc0CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CPtrV>::CType, FMFunc1CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CPtrV>::CType, FMFunc2CPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0VPtr>::CType, FMFunc0VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1VPtr>::CType, FMFunc1VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2VPtr>::CType, FMFunc2VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0VPtrC>::CType, FMFunc0VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1VPtrC>::CType, FMFunc1VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2VPtrC>::CType, FMFunc2VPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0VPtrV>::CType, FMFunc0VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1VPtrV>::CType, FMFunc1VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2VPtrV>::CType, FMFunc2VPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CVPtr>::CType, FMFunc0CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CVPtr>::CType, FMFunc1CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CVPtr>::CType, FMFunc2CVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElRef>::CType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElRef>::CType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElRef>::CType, PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElPtrV>::CType, FFunc0ElPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElPtrV>::CType, FFunc1ElPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElPtrV>::CType, FFunc2ElPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMVPtr>::CType, CMVPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCVPtr>::CType, CMCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMPtrC>::CType, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMVPtrC>::CType, CMVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCVPtrC>::CType, CMCVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMPtrV>::CType, CMPtrV>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCPtrV>::CType, CMCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMVPtrV>::CType, CMVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCVPtrV>::CType, CMCVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMPtrCV>::CType, CMPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCPtrCV>::CType, CMCPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMVPtrCV>::CType, CMVPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCVPtrCV>::CType, CMCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArray2V>::CType, CTestArray2V>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArray2CV>::CType, CTestArray2CV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArrayV>::CType, CTestArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArrayCV>::CType, CTestArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArray2V>::CType, CTest2DArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArray2CV>::CType, CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArray2V>::CType, CTest3DArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArray2CV>::CType, CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<void *&>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<void>::CType, void>::mc_Value							));
