// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsReference<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsReference<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsReference<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestCV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsReference<CTestRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestCRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestVRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestCVRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestRRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestCRRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestVRRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsReference<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc2>::mc_Value			));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsReference<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc2RRef>::mc_Value		));
#endif
DMibStaticCheck((	!TCIsReference<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc2El>::mc_Value			));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsReference<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc2ElRRef>::mc_Value		));
#endif
DMibStaticCheck((	!TCIsReference<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsReference<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMCVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMCVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMCPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMCVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMCPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMCVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArray2V>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArray2CV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArrayCV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsReference<void *>::mc_Value			));
DMibStaticCheck((	!TCIsReference<void>::mc_Value				));



DMibStaticCheck((	TCIsSame<TCAddReference<CTestUnion>::CType, CTestUnion &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestClass0>::CType, CTestClass0 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestClass1>::CType, CTestClass1 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestStruct0>::CType, CTestStruct0 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestStruct1>::CType, CTestStruct1 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<ETestEnum>::CType, ETestEnum &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestClass>::CType, CTestClass &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestC>::CType, CTestC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestV>::CType, CTestV &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCV>::CType, CTestCV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestPtr>::CType, CTestPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCPtr>::CType, CTestCPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestVPtr>::CType, CTestVPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCVPtr>::CType, CTestCVPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestPtrC>::CType, CTestPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCPtrC>::CType, CTestCPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestVPtrC>::CType, CTestVPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCVPtrC>::CType, CTestCVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestPtrV>::CType, CTestPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCPtrV>::CType, CTestCPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestVPtrV>::CType, CTestVPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCVPtrV>::CType, CTestCVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestPtrCV>::CType, CTestPtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCPtrCV>::CType, CTestCPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestVPtrCV>::CType, CTestVPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCVPtrCV>::CType, CTestCVPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCRef>::CType, CTestCRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestVRef>::CType, CTestVRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCVRef>::CType, CTestCVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestRRef>::CType, CTestRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestVRRef>::CType, CTestVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCVRRef>::CType, CTestCVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc0>::CType, PFFunc0 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc1>::CType, PFFunc1 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc2>::CType, PFFunc2 &>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0Ptr>::CType, FFunc0Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1Ptr>::CType, FFunc1Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2Ptr>::CType, FFunc2Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0PtrC>::CType, FFunc0PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1PtrC>::CType, FFunc1PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2PtrC>::CType, FFunc2PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0PtrV>::CType, FFunc0PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1PtrV>::CType, FFunc1PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2PtrV>::CType, FFunc2PtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0PtrCV>::CType, FFunc0PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1PtrCV>::CType, FFunc1PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2PtrCV>::CType, FFunc2PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0Ptr>::CType, FMFunc0Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1Ptr>::CType, FMFunc1Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2Ptr>::CType, FMFunc2Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0PtrC>::CType, FMFunc0PtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1PtrC>::CType, FMFunc1PtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2PtrC>::CType, FMFunc2PtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0PtrV>::CType, FMFunc0PtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1PtrV>::CType, FMFunc1PtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2PtrV>::CType, FMFunc2PtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0PtrCV>::CType, FMFunc0PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1PtrCV>::CType, FMFunc1PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2PtrCV>::CType, FMFunc2PtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CPtr>::CType, FMFunc0CPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CPtr>::CType, FMFunc1CPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CPtr>::CType, FMFunc2CPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CPtrV>::CType, FMFunc0CPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CPtrV>::CType, FMFunc1CPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CPtrV>::CType, FMFunc2CPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0VPtr>::CType, FMFunc0VPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1VPtr>::CType, FMFunc1VPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2VPtr>::CType, FMFunc2VPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0VPtrC>::CType, FMFunc0VPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1VPtrC>::CType, FMFunc1VPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2VPtrC>::CType, FMFunc2VPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0VPtrV>::CType, FMFunc0VPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1VPtrV>::CType, FMFunc1VPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2VPtrV>::CType, FMFunc2VPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CVPtr>::CType, FMFunc0CVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CVPtr>::CType, FMFunc1CVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CVPtr>::CType, FMFunc2CVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc0El>::CType, PFFunc0El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc1El>::CType, PFFunc1El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc2El>::CType, PFFunc2El &>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElPtr>::CType, FFunc0ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElPtr>::CType, FFunc1ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElPtr>::CType, FFunc2ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElPtrV>::CType, FFunc0ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElPtrV>::CType, FFunc1ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElPtrV>::CType, FFunc2ElPtrV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CMPtr>::CType, CMPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCPtr>::CType, CMCPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CMVPtr>::CType, CMVPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCVPtr>::CType, CMCVPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMPtrC>::CType, CMPtrC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCPtrC>::CType, CMCPtrC &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMVPtrC>::CType, CMVPtrC &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCVPtrC>::CType, CMCVPtrC &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMPtrV>::CType, CMPtrV &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCPtrV>::CType, CMCPtrV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMVPtrV>::CType, CMVPtrV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCVPtrV>::CType, CMCVPtrV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMPtrCV>::CType, CMPtrCV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCPtrCV>::CType, CMCPtrCV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMVPtrCV>::CType, CMVPtrCV &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCVPtrCV>::CType, CMCVPtrCV &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArray2>::CType, CTestArray2 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArray2C>::CType, CTestArray2C &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArray2V>::CType, CTestArray2V &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArray2CV>::CType, CTestArray2CV &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArrayC>::CType, CTestArrayC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArrayV>::CType, CTestArrayV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArrayCV>::CType, CTestArrayCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArray2>::CType, CTest2DArray2 &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArray2C>::CType, CTest2DArray2C &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArray2V>::CType, CTest2DArray2V &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArray2CV>::CType, CTest2DArray2CV &>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArray2>::CType, CTest3DArray2 &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArray2C>::CType, CTest3DArray2C &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArray2V>::CType, CTest3DArray2V &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArray2CV>::CType, CTest3DArray2CV &>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<void *>::CType, void *&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<void>::CType, void>::mc_Value							));

// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestV>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCV>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestVPtr>::CType, CTestVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCVPtr>::CType, CTestCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestVPtrC>::CType, CTestVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCVPtrC>::CType, CTestCVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestPtrV>::CType, CTestPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCPtrV>::CType, CTestCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestVPtrV>::CType, CTestVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCVPtrV>::CType, CTestCVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestPtrCV>::CType, CTestPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCPtrCV>::CType, CTestCPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestVPtrCV>::CType, CTestVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCVPtrCV>::CType, CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCRef>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestVRef>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCVRef>::CType, CTestCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestRRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCRRef>::CType, CTestC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestVRRef>::CType, CTestV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCVRRef>::CType, CTestCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc2>::CType, PFFunc2>::mc_Value					));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0Ref>::CType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1Ref>::CType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2Ref>::CType, PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0RRef>::CType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1RRef>::CType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2RRef>::CType, PFFunc2>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0PtrV>::CType, FFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1PtrV>::CType, FFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2PtrV>::CType, FFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0PtrCV>::CType, FFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1PtrCV>::CType, FFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2PtrCV>::CType, FFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0PtrV>::CType, FMFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1PtrV>::CType, FMFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2PtrV>::CType, FMFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0PtrCV>::CType, FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1PtrCV>::CType, FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2PtrCV>::CType, FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CPtrV>::CType, FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CPtrV>::CType, FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CPtrV>::CType, FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0VPtr>::CType, FMFunc0VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1VPtr>::CType, FMFunc1VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2VPtr>::CType, FMFunc2VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0VPtrC>::CType, FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1VPtrC>::CType, FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2VPtrC>::CType, FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0VPtrV>::CType, FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1VPtrV>::CType, FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2VPtrV>::CType, FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CVPtr>::CType, FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CVPtr>::CType, FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CVPtr>::CType, FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc2El>::CType, PFFunc2El>::mc_Value					));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElRef>::CType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElRef>::CType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElRef>::CType, PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElRRef>::CType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElRRef>::CType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElRRef>::CType, PFFunc2El>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElPtrV>::CType, FFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElPtrV>::CType, FFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElPtrV>::CType, FFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMVPtr>::CType, CMVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCVPtr>::CType, CMCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMVPtrC>::CType, CMVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCVPtrC>::CType, CMCVPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMPtrV>::CType, CMPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCPtrV>::CType, CMCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMVPtrV>::CType, CMVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCVPtrV>::CType, CMCVPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMPtrCV>::CType, CMPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCPtrCV>::CType, CMCPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMVPtrCV>::CType, CMVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCVPtrCV>::CType, CMCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArray2C>::CType, CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArray2V>::CType, CTestArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArray2CV>::CType, CTestArray2CV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArray>::CType, CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArrayV>::CType, CTestArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArrayCV>::CType, CTestArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArray2V>::CType, CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArray2CV>::CType, CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArray>::CType, CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArray2V>::CType, CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArray2CV>::CType, CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArray>::CType, CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<void *>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<void *&>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<void>::CType, void>::mc_Value						));


// Storable
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestV>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCV>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestVPtr>::CType, CTestVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCVPtr>::CType, CTestCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestVPtrC>::CType, CTestVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCVPtrC>::CType, CTestCVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestPtrV>::CType, CTestPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCPtrV>::CType, CTestCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestVPtrV>::CType, CTestVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCVPtrV>::CType, CTestCVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestPtrCV>::CType, CTestPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCPtrCV>::CType, CTestCPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestVPtrCV>::CType, CTestVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCVPtrCV>::CType, CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCRef>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestVRef>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCVRef>::CType, CTestCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestRRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCRRef>::CType, CTestC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestVRRef>::CType, CTestV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCVRRef>::CType, CTestCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc2>::CType, PFFunc2>::mc_Value					));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0PtrV>::CType, FFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1PtrV>::CType, FFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2PtrV>::CType, FFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0PtrCV>::CType, FFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1PtrCV>::CType, FFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2PtrCV>::CType, FFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0PtrV>::CType, FMFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1PtrV>::CType, FMFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2PtrV>::CType, FMFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0PtrCV>::CType, FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1PtrCV>::CType, FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2PtrCV>::CType, FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CPtrV>::CType, FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CPtrV>::CType, FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CPtrV>::CType, FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0VPtr>::CType, FMFunc0VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1VPtr>::CType, FMFunc1VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2VPtr>::CType, FMFunc2VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0VPtrC>::CType, FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1VPtrC>::CType, FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2VPtrC>::CType, FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0VPtrV>::CType, FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1VPtrV>::CType, FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2VPtrV>::CType, FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CVPtr>::CType, FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CVPtr>::CType, FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CVPtr>::CType, FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc2El>::CType, PFFunc2El>::mc_Value					));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElPtrV>::CType, FFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElPtrV>::CType, FFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElPtrV>::CType, FFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMVPtr>::CType, CMVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCVPtr>::CType, CMCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMVPtrC>::CType, CMVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCVPtrC>::CType, CMCVPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMPtrV>::CType, CMPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCPtrV>::CType, CMCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMVPtrV>::CType, CMVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCVPtrV>::CType, CMCVPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMPtrCV>::CType, CMPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCPtrCV>::CType, CMCPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMVPtrCV>::CType, CMVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCVPtrCV>::CType, CMCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArray2C>::CType, CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArray2V>::CType, CTestArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArray2CV>::CType, CTestArray2CV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArray>::CType, CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArrayV>::CType, CTestArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArrayCV>::CType, CTestArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArray2V>::CType, CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArray2CV>::CType, CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArray>::CType, CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArray2V>::CType, CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArray2CV>::CType, CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArray>::CType, CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<void *>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<void *&>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<void>::CType, void>::mc_Value						));



// Copy refernce

DMibStaticCheck((	TCIsSame<TCCopyReference<int, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int, int &>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int, int &&>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &, int &>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &, int &&>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &&, int>::CType, int &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &&, int &>::CType, int &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &&, int &&>::CType, int &&>::mc_Value					));

DMibStaticCheck((	TCIsSame<TCCopyReference<CTestUnion, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestClass0, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestClass1, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestStruct0, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestStruct1, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<ETestEnum, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestClass, int>::CType, int>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestC, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestV, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCV, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestVPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCVPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestPtrC, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestVPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCVPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestPtrV, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestVPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCVPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestPtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCPtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestVPtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCVPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestRef, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCRef, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestVRef, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCVRef, int>::CType, int &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestRRef, int>::CType, int &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCRRef, int>::CType, int &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestVRRef, int>::CType, int &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCVRRef, int>::CType, int &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc0, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc1, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc2, int>::CType, int>::mc_Value					));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0Ref, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1Ref, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2Ref, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0RRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1RRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2RRef, int>::CType, int &&>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0Ptr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1Ptr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2Ptr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0PtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1PtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2PtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0PtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1PtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2PtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0Ptr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1Ptr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2Ptr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0PtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1PtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2PtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0PtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1PtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2PtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0VPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1VPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2VPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0VPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1VPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2VPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0VPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1VPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2VPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0VPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1VPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2VPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CVPtr, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CVPtr, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CVPtr, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CVPtrCV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CVPtrCV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CVPtrCV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc0El, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc1El, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc2El, int>::CType, int>::mc_Value					));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElRef, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElRef, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElRef, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElRRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElRRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElRRef, int>::CType, int &&>::mc_Value			));
#endif
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElPtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElPtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElPtrCV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElPtrV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElVPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElVPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElVPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElVPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElVPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElVPtrCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCVPtr, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCVPtr, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCVPtr, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCVPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCVPtrV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCVPtrCV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCVPtrCV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCVPtrCV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMPtr, int>::CType, int>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCPtr, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMVPtr, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCVPtr, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMPtrC, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCPtrC, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMVPtrC, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCVPtrC, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMPtrV, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCPtrV, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMVPtrV, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCVPtrV, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMPtrCV, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCPtrCV, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMVPtrCV, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCVPtrCV, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArray2, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArray2C, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArray2V, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArray2CV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArray, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArrayC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArrayV, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArrayCV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArray2, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArray2C, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArray2V, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArray2CV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArray, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArrayC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArrayV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArrayCV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArray2, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArray2C, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArray2V, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArray2CV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArray, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArrayC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArrayV, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArrayCV, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<void *, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<void *&, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<void, int>::CType, int>::mc_Value						));
