// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsRValueReference<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<ETestEnum>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestClass>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CTestPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestRef>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestCRef>::mc_Value		));
DMibStaticCheck((	TCIsRValueReference<CTestRRef>::mc_Value		));
DMibStaticCheck((	TCIsRValueReference<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<FFunc0Ref>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc1Ref>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc2Ref>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc0RRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc1RRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc2RRef>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<FFunc0ElRef>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc1ElRef>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc2ElRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc0ElRRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc1ElRRef>::mc_Value	));
DMibStaticCheck((	TCIsRValueReference<FFunc2ElRRef>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<FMFunc0ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc1ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<FMFunc2ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CMPtr>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArray>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest2DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArray>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<CTest3DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsRValueReference<void *>::mc_Value			));
DMibStaticCheck((	!TCIsRValueReference<void>::mc_Value			));



DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestUnion>::CType, CTestUnion &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestClass0>::CType, CTestClass0 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestClass1>::CType, CTestClass1 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestStruct0>::CType, CTestStruct0 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestStruct1>::CType, CTestStruct1 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<ETestEnum>::CType, ETestEnum &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestClass>::CType, CTestClass &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestC>::CType, CTestC &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestPtr>::CType, CTestPtr &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCPtr>::CType, CTestCPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestPtrC>::CType, CTestPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCPtrC>::CType, CTestCPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestRef>::CType, CTestRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCRef>::CType, CTestCRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestRRef>::CType, CTestRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestCRRef>::CType, CTestCRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc0>::CType, PFFunc0 &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc1>::CType, PFFunc1 &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc2>::CType, PFFunc2 &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0Ref>::CType, FFunc0RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1Ref>::CType, FFunc1RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2Ref>::CType, FFunc2RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0RRef>::CType, FFunc0RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1RRef>::CType, FFunc1RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2RRef>::CType, FFunc2RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0Ptr>::CType, FFunc0Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1Ptr>::CType, FFunc1Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2Ptr>::CType, FFunc2Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0PtrC>::CType, FFunc0PtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1PtrC>::CType, FFunc1PtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2PtrC>::CType, FFunc2PtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0Ptr>::CType, FMFunc0Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1Ptr>::CType, FMFunc1Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2Ptr>::CType, FMFunc2Ptr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0PtrC>::CType, FMFunc0PtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1PtrC>::CType, FMFunc1PtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2PtrC>::CType, FMFunc2PtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CPtr>::CType, FMFunc0CPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CPtr>::CType, FMFunc1CPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CPtr>::CType, FMFunc2CPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc0El>::CType, PFFunc0El &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc1El>::CType, PFFunc1El &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<PFFunc2El>::CType, PFFunc2El &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElRef>::CType, FFunc0ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElRef>::CType, FFunc1ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElRef>::CType, FFunc2ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElPtr>::CType, FFunc0ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElPtr>::CType, FFunc1ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElPtr>::CType, FFunc2ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMPtr>::CType, CMPtr &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCPtr>::CType, CMCPtr &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMPtrC>::CType, CMPtrC &&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CMCPtrC>::CType, CMCPtrC &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArray2>::CType, CTestArray2 &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArray2C>::CType, CTestArray2C &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArray>::CType, CTestArray>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTestArrayC>::CType, CTestArrayC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArray2>::CType, CTest2DArray2 &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArray2C>::CType, CTest2DArray2C &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArray>::CType, CTest2DArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArray2>::CType, CTest3DArray2 &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArray2C>::CType, CTest3DArray2C &&>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArray>::CType, CTest3DArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<void *>::CType, void *&&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddRValueReference<void>::CType, void>::mc_Value								));

// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestPtr>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCPtrC>::CType, CTestCPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestRRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestCRRef>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0RRef>::CType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1RRef>::CType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2RRef>::CType, PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElRRef>::CType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElRRef>::CType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElRRef>::CType, PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMPtrC>::CType, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<void *&&>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveRValueReference<void>::CType, void>::mc_Value							));
