// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	TCIsSame<CTestClass, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<float, float>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestClass, float>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestRef, CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsSame<CTestRRef, CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsSame<CTestC, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<CTestClass0, CTypedeffedClass0>::mc_Value	));

DMibStaticCheck((	TCIsSameUnqualified<CTestClass, CTestClass>::mc_Value		));
DMibStaticCheck((	TCIsSameUnqualified<CTestC, CTestClass>::mc_Value	));

// Void
DMibStaticCheck((	!TCIsSame<CTestUnion, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestClass0, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestClass1, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestStruct0, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestStruct1, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<const CTestClass0, int>::mc_Value				));
DMibStaticCheck((	!TCIsSame<const CTestClass1, int>::mc_Value				));
DMibStaticCheck((	!TCIsSame<const CTestStruct0, int>::mc_Value				));
DMibStaticCheck((	!TCIsSame<const CTestStruct1, int>::mc_Value				));
DMibStaticCheck((	!TCIsSame<ETestEnum, int>::mc_Value						));
DMibStaticCheck((	TCIsSame<int, int>::mc_Value							));
DMibStaticCheck((	!TCIsSame<CTestClass, int>::mc_Value							));
DMibStaticCheck((	!TCIsSame<CTestC, int>::mc_Value							));
DMibStaticCheck((	!TCIsSame<CTestPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CTestCPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CTestPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CTestCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CTestCRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CTestRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CTestCRRef, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<PFFunc0, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<PFFunc1, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<PFFunc2, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc0Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc1Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc2Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc0RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc1RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc2RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc0Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc1Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc2Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc0PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FFunc1PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FFunc2PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc0Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc1Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc2Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc0PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc1PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc2PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc0CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc1CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc2CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc0CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc1CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc2CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<PFFunc0El, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<PFFunc1El, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<PFFunc2El, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc0ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc1ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc2ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc0ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc1ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc2ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc0ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc1ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc2ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<FFunc0ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FFunc1ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FFunc2ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc0ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc1ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc2ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc0ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc1ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc2ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc0ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc1ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc2ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc0ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc1ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<FMFunc2ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CMPtr, int>::mc_Value							));
DMibStaticCheck((	!TCIsSame<CMCPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CMPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CMCPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<CTestArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestArray2C, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTestArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTest2DArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTest2DArray2C, int>::mc_Value				));
DMibStaticCheck((	!TCIsSame<CTest2DArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTest2DArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTest3DArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTest3DArray2C, int>::mc_Value				));
DMibStaticCheck((	!TCIsSame<CTest3DArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<CTest3DArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSame<void *, int>::mc_Value						));
DMibStaticCheck((	!TCIsSame<void, int>::mc_Value							));


DMibStaticCheck((	!TCIsSameUnqualified<CTestUnion, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTestClass0, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTestClass1, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTestStruct0, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTestStruct1, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<const CTestClass0, int>::mc_Value				));
DMibStaticCheck((	!TCIsSameUnqualified<const CTestClass1, int>::mc_Value				));
DMibStaticCheck((	!TCIsSameUnqualified<const CTestStruct0, int>::mc_Value				));
DMibStaticCheck((	!TCIsSameUnqualified<const CTestStruct1, int>::mc_Value				));
DMibStaticCheck((	!TCIsSameUnqualified<ETestEnum, int>::mc_Value						));
DMibStaticCheck((	TCIsSameUnqualified<int, int>::mc_Value							));
DMibStaticCheck((	!TCIsSameUnqualified<CTestClass, int>::mc_Value							));
DMibStaticCheck((	!TCIsSameUnqualified<CTestC, int>::mc_Value							));
DMibStaticCheck((	!TCIsSameUnqualified<CTestPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CTestCPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CTestPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CTestCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTestRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CTestCRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CTestRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CTestCRRef, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<PFFunc0, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<PFFunc1, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<PFFunc2, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc0Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc1Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc2Ref, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc0RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc1RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc2RRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc0Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc1Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc2Ptr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc0PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc1PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc2PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc0Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc1Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc2Ptr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc0PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc1PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc2PtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc0CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc1CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc2CPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc0CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc1CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc2CPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<PFFunc0El, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<PFFunc1El, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<PFFunc2El, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc0ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc1ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc2ElRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc0ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc1ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc2ElRRef, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc0ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc1ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc2ElPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc0ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc1ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FFunc2ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc0ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc1ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc2ElPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc0ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc1ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc2ElPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc0ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc1ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc2ElCPtr, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc0ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc1ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<FMFunc2ElCPtrC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CMPtr, int>::mc_Value							));
DMibStaticCheck((	!TCIsSameUnqualified<CMCPtr, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CMPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CMCPtrC, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<CTestArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTestArray2C, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTestArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTestArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTest2DArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTest2DArray2C, int>::mc_Value				));
DMibStaticCheck((	!TCIsSameUnqualified<CTest2DArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTest2DArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTest3DArray2, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTest3DArray2C, int>::mc_Value				));
DMibStaticCheck((	!TCIsSameUnqualified<CTest3DArray, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<CTest3DArrayC, int>::mc_Value					));
DMibStaticCheck((	!TCIsSameUnqualified<void *, int>::mc_Value						));
DMibStaticCheck((	!TCIsSameUnqualified<void, int>::mc_Value							));

