// Copyright © Unbroken AB
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "Test_TypeTraits_TestTypes.h"

/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Is function
|___________________________________________________________________________________________________|
\***************************************************************************************************/

static_assert(!TCFunctionTraits<CTestUnion>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestClass0>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestClass1>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestStruct0>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestStruct1>::mc_IsFunction);
static_assert(!TCFunctionTraits<ETestEnum>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestClass>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestC>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestCPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestCPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestCRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestRRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestCRRef>::mc_IsFunction);
static_assert(TCFunctionTraits<PFFunc0>::mc_IsFunction);
static_assert(TCFunctionTraits<PFFunc1>::mc_IsFunction);
static_assert(TCFunctionTraits<PFFunc2>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc0Ref>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc1Ref>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc2Ref>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc0RRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc1RRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc2RRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc0Ptr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc1Ptr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc2Ptr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc0PtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc1PtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc2PtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc0Ptr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc1Ptr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc2Ptr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc0PtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc1PtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc2PtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc0CPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc1CPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc2CPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc0CPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc1CPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc2CPtrC>::mc_IsFunction);
static_assert(TCFunctionTraits<PFFunc0El>::mc_IsFunction);
static_assert(TCFunctionTraits<PFFunc1El>::mc_IsFunction);
static_assert(TCFunctionTraits<PFFunc2El>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc0ElRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc1ElRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc2ElRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc0ElRRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc1ElRRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc2ElRRef>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc0ElPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc1ElPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc2ElPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc0ElPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc1ElPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FFunc2ElPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc0ElPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc1ElPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc2ElPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc0ElPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc1ElPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc2ElPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc0ElCPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc1ElCPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc2ElCPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc0ElCPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc1ElCPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<FMFunc2ElCPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<CMPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<CMCPtr>::mc_IsFunction);
static_assert(!TCFunctionTraits<CMPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<CMCPtrC>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestArray2>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestArray2C>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestArray>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTestArrayC>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTest2DArray2>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTest2DArray2C>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTest2DArray>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTest2DArrayC>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTest3DArray2>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTest3DArray2C>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTest3DArray>::mc_IsFunction);
static_assert(!TCFunctionTraits<CTest3DArrayC>::mc_IsFunction);
static_assert(!TCFunctionTraits<void *>::mc_IsFunction);
static_assert(!TCFunctionTraits<void>::mc_IsFunction);

static_assert(!TCMemberFunctionPointerTraits<CTestUnion>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestClass0>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestClass1>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestStruct0>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestStruct1>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<ETestEnum>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestClass>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestPtr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestCPtr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestPtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestCPtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestCRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestRRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestCRRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<PFFunc0>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<PFFunc1>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<PFFunc2>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc0Ref>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc1Ref>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc2Ref>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc0RRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc1RRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc2RRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc0Ptr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc1Ptr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc2Ptr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc0PtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc1PtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc2PtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc0Ptr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc1Ptr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc2Ptr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc0PtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc1PtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc2PtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc0CPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc1CPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc2CPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc0CPtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc1CPtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc2CPtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<PFFunc0El>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<PFFunc1El>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<PFFunc2El>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElRRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElRRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElRRef>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElPtr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElPtr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElPtr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElPtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElPtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElPtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::mc_IsMemberFunctionPointer);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CMPtr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CMCPtr>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CMPtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CMCPtrC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestArray2>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestArray2C>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestArray>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTestArrayC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray2>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray2C>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArrayC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray2>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray2C>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArrayC>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<void *>::mc_IsMemberFunctionPointer);
static_assert(!TCMemberFunctionPointerTraits<void>::mc_IsMemberFunctionPointer);


/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Arity
|___________________________________________________________________________________________________|
\***************************************************************************************************/




static_assert(!TCFunctionTraits<CTestUnion>::mc_Arity);
static_assert(!TCFunctionTraits<CTestClass0>::mc_Arity);
static_assert(!TCFunctionTraits<CTestClass1>::mc_Arity);
static_assert(!TCFunctionTraits<CTestStruct0>::mc_Arity);
static_assert(!TCFunctionTraits<CTestStruct1>::mc_Arity);
static_assert(!TCFunctionTraits<ETestEnum>::mc_Arity);
static_assert(!TCFunctionTraits<CTestClass>::mc_Arity);
static_assert(!TCFunctionTraits<CTestC>::mc_Arity);
static_assert(!TCFunctionTraits<CTestPtr>::mc_Arity);
static_assert(!TCFunctionTraits<CTestCPtr>::mc_Arity);
static_assert(!TCFunctionTraits<CTestPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<CTestCPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<CTestRef>::mc_Arity);
static_assert(!TCFunctionTraits<CTestCRef>::mc_Arity);
static_assert(!TCFunctionTraits<CTestRRef>::mc_Arity);
static_assert(!TCFunctionTraits<CTestCRRef>::mc_Arity);
static_assert(TCFunctionTraits<PFFunc0>::mc_Arity == 0);
static_assert(TCFunctionTraits<PFFunc1>::mc_Arity == 0);
static_assert(TCFunctionTraits<PFFunc2>::mc_Arity == 1);
static_assert(!TCFunctionTraits<FFunc0Ref>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc1Ref>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc2Ref>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc0RRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc1RRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc2RRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc0Ptr>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc1Ptr>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc2Ptr>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc0PtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc1PtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc2PtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc0Ptr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc1Ptr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc2Ptr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc0PtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc1PtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc2PtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc0CPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc1CPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc2CPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc0CPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc1CPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc2CPtrC>::mc_Arity);
static_assert(TCFunctionTraits<PFFunc0El>::mc_Arity == 0);
static_assert(TCFunctionTraits<PFFunc1El>::mc_Arity == 0);
static_assert(TCFunctionTraits<PFFunc2El>::mc_Arity == 1);
static_assert(!TCFunctionTraits<FFunc0ElRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc1ElRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc2ElRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc0ElRRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc1ElRRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc2ElRRef>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc0ElPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc1ElPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc2ElPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc0ElPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc1ElPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FFunc2ElPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc0ElPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc1ElPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc2ElPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc0ElPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc1ElPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc2ElPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc0ElCPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc1ElCPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc2ElCPtr>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc0ElCPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc1ElCPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<FMFunc2ElCPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<CMPtr>::mc_Arity);
static_assert(!TCFunctionTraits<CMCPtr>::mc_Arity);
static_assert(!TCFunctionTraits<CMPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<CMCPtrC>::mc_Arity);
static_assert(!TCFunctionTraits<CTestArray2>::mc_Arity);
static_assert(!TCFunctionTraits<CTestArray2C>::mc_Arity);
static_assert(!TCFunctionTraits<CTestArray>::mc_Arity);
static_assert(!TCFunctionTraits<CTestArrayC>::mc_Arity);
static_assert(!TCFunctionTraits<CTest2DArray2>::mc_Arity);
static_assert(!TCFunctionTraits<CTest2DArray2C>::mc_Arity);
static_assert(!TCFunctionTraits<CTest2DArray>::mc_Arity);
static_assert(!TCFunctionTraits<CTest2DArrayC>::mc_Arity);
static_assert(!TCFunctionTraits<CTest3DArray2>::mc_Arity);
static_assert(!TCFunctionTraits<CTest3DArray2C>::mc_Arity);
static_assert(!TCFunctionTraits<CTest3DArray>::mc_Arity);
static_assert(!TCFunctionTraits<CTest3DArrayC>::mc_Arity);
static_assert(!TCFunctionTraits<void *>::mc_Arity);
static_assert(!TCFunctionTraits<void>::mc_Arity);



static_assert(!TCMemberFunctionPointerTraits<CTestUnion>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestClass0>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestClass1>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestStruct0>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestStruct1>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<ETestEnum>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestClass>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestPtr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestCPtr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestPtrC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestCPtrC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestCRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestRRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestCRRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<PFFunc0>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<PFFunc1>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<PFFunc2>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc0Ref>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc1Ref>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc2Ref>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc0RRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc1RRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc2RRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc0Ptr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc1Ptr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc2Ptr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc0PtrC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc1PtrC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc2PtrC>::mc_Arity);
static_assert(TCMemberFunctionPointerTraits<FMFunc0Ptr>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc1Ptr>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc2Ptr>::mc_Arity == 1);
static_assert(TCMemberFunctionPointerTraits<FMFunc0PtrC>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc1PtrC>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc2PtrC>::mc_Arity == 1);
static_assert(TCMemberFunctionPointerTraits<FMFunc0CPtr>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc1CPtr>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc2CPtr>::mc_Arity == 1);
static_assert(TCMemberFunctionPointerTraits<FMFunc0CPtrC>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc1CPtrC>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc2CPtrC>::mc_Arity == 1);
static_assert(!TCMemberFunctionPointerTraits<PFFunc0El>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<PFFunc1El>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<PFFunc2El>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElRRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElRRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElRRef>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElPtr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElPtr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElPtr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElPtrC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElPtrC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElPtrC>::mc_Arity);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElPtr>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElPtr>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElPtr>::mc_Arity == 1);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::mc_Arity == 1);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::mc_Arity == 1);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::mc_Arity == 0);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::mc_Arity == 1);
static_assert(!TCMemberFunctionPointerTraits<CMPtr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CMCPtr>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CMPtrC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CMCPtrC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestArray2>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestArray2C>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestArray>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTestArrayC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray2>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray2C>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArrayC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray2>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray2C>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArrayC>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<void *>::mc_Arity);
static_assert(!TCMemberFunctionPointerTraits<void>::mc_Arity);



/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Ellipsis
|___________________________________________________________________________________________________|
\***************************************************************************************************/



static_assert(!TCFunctionTraits<CTestUnion>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestClass0>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestClass1>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestStruct0>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestStruct1>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<ETestEnum>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestClass>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestCPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestCPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestCRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestRRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestCRRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<PFFunc0>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<PFFunc1>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<PFFunc2>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc0Ref>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc1Ref>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc2Ref>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc0RRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc1RRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc2RRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc0Ptr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc1Ptr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc2Ptr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc0PtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc1PtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc2PtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc0Ptr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc1Ptr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc2Ptr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc0PtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc1PtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc2PtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc0CPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc1CPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc2CPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc0CPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc1CPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc2CPtrC>::mc_IsEllipsis);
static_assert(TCFunctionTraits<PFFunc0El>::mc_IsEllipsis);
static_assert(TCFunctionTraits<PFFunc1El>::mc_IsEllipsis);
static_assert(TCFunctionTraits<PFFunc2El>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc0ElRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc1ElRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc2ElRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc0ElRRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc1ElRRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc2ElRRef>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc0ElPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc1ElPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc2ElPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc0ElPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc1ElPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FFunc2ElPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc0ElPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc1ElPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc2ElPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc0ElPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc1ElPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc2ElPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc0ElCPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc1ElCPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc2ElCPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc0ElCPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc1ElCPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<FMFunc2ElCPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CMPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CMCPtr>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CMPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CMCPtrC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestArray2>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestArray2C>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestArray>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTestArrayC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTest2DArray2>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTest2DArray2C>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTest2DArray>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTest2DArrayC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTest3DArray2>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTest3DArray2C>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTest3DArray>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<CTest3DArrayC>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<void *>::mc_IsEllipsis);
static_assert(!TCFunctionTraits<void>::mc_IsEllipsis);



static_assert(!TCMemberFunctionPointerTraits<CTestUnion>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestClass0>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestClass1>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestStruct0>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestStruct1>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<ETestEnum>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestClass>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestCPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestCPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestCRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestRRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestCRRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<PFFunc0>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<PFFunc1>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<PFFunc2>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc0Ref>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc1Ref>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc2Ref>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc0RRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc1RRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc2RRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc0Ptr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc1Ptr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc2Ptr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc0PtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc1PtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc2PtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc0Ptr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc1Ptr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc2Ptr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc0PtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc1PtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc2PtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc0CPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc1CPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc2CPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc0CPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc1CPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FMFunc2CPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<PFFunc0El>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<PFFunc1El>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<PFFunc2El>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElRRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElRRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElRRef>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc0ElPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc1ElPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<FFunc2ElPtrC>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElPtr>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElPtr>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElPtr>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::mc_IsEllipsis);
static_assert(TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CMPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CMCPtr>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CMPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CMCPtrC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestArray2>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestArray2C>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestArray>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTestArrayC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray2>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray2C>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArray>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTest2DArrayC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray2>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray2C>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArray>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<CTest3DArrayC>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<void *>::mc_IsEllipsis);
static_assert(!TCMemberFunctionPointerTraits<void>::mc_IsEllipsis);


/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Return
|___________________________________________________________________________________________________|
\***************************************************************************************************/

static_assert(cIsSame<TCFunctionTraits<CTestUnion>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestClass0>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestClass1>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestStruct0>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestStruct1>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<ETestEnum>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestClass>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestCPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestCPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestCRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestRRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestCRRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<PFFunc0>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<PFFunc1>::CReturn, CTestBase>);
static_assert(cIsSame<TCFunctionTraits<PFFunc2>::CReturn, CTestBase>);
static_assert(cIsSame<TCFunctionTraits<FFunc0Ref>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc1Ref>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc2Ref>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc0RRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc1RRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc2RRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc0Ptr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc1Ptr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc2Ptr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc0PtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc1PtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc2PtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc0Ptr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc1Ptr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc2Ptr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc0PtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc1PtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc2PtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc0CPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc1CPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc2CPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc0CPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc1CPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc2CPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<PFFunc0El>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<PFFunc1El>::CReturn, CTestBase>);
static_assert(cIsSame<TCFunctionTraits<PFFunc2El>::CReturn, CTestBase>);
static_assert(cIsSame<TCFunctionTraits<FFunc0ElRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc1ElRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc2ElRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc0ElRRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc1ElRRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc2ElRRef>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc0ElPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc1ElPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc2ElPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc0ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc1ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FFunc2ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc0ElPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc1ElPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc2ElPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc0ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc1ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc2ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc0ElCPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc1ElCPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc2ElCPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc0ElCPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc1ElCPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<FMFunc2ElCPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CMPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CMCPtr>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CMPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CMCPtrC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestArray2>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestArray2C>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestArray>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTestArrayC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTest2DArray2>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTest2DArray2C>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTest2DArray>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTest2DArrayC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTest3DArray2>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTest3DArray2C>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTest3DArray>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<CTest3DArrayC>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<void *>::CReturn, void>);
static_assert(cIsSame<TCFunctionTraits<void>::CReturn, void>);

static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestUnion>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass0>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass1>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestStruct0>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestStruct1>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<ETestEnum>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestRRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCRRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc0>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc1>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc2>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0Ref>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1Ref>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2Ref>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0RRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1RRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2RRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0Ptr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1Ptr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2Ptr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0PtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1PtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2PtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0Ptr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1Ptr>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2Ptr>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0PtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1PtrC>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2PtrC>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtr>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtr>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtrC>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtrC>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc0El>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc1El>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc2El>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElRRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElRRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElRRef>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtr>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtr>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::CReturn, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMCPtr>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMCPtrC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray2>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray2C>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArrayC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray2>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray2C>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArrayC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray2>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray2C>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArrayC>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<void *>::CReturn, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<void>::CReturn, void>);


/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Argument type 0
|___________________________________________________________________________________________________|
\***************************************************************************************************/

static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestUnion, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestClass0, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestClass1, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestStruct0, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestStruct1, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<ETestEnum, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestClass, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestCPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestCPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestCRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestRRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestCRRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<PFFunc0, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<PFFunc1, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<PFFunc2, 0>, int>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc0Ref, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc1Ref, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc2Ref, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc0RRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc1RRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc2RRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc0Ptr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc1Ptr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc2Ptr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc0PtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc1PtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc2PtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc0Ptr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc1Ptr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc2Ptr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc0PtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc1PtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc2PtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc0CPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc1CPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc2CPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc0CPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc1CPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc2CPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<PFFunc0El, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<PFFunc1El, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<PFFunc2El, 0>, CTestBase>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc0ElRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc1ElRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc2ElRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc0ElRRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc1ElRRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc2ElRRef, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc0ElPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc1ElPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc2ElPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc0ElPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc1ElPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FFunc2ElPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc0ElPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc1ElPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc2ElPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc0ElPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc1ElPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc2ElPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc0ElCPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc1ElCPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc2ElCPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc0ElCPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc1ElCPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<FMFunc2ElCPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CMPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CMCPtr, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CMPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CMCPtrC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestArray2, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestArray2C, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestArray, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTestArrayC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTest2DArray2, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTest2DArray2C, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTest2DArray, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTest2DArrayC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTest3DArray2, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTest3DArray2C, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTest3DArray, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<CTest3DArrayC, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<void *, 0>, void>);
static_assert(cIsSame<TCFunctionTraits_ArgumentType<void, 0>, void>);

static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestUnion, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestClass0, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestClass1, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestStruct0, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestStruct1, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<ETestEnum, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestClass, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestCPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestCPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestCRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestRRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestCRRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc0, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc1, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc2, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0Ref, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1Ref, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2Ref, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0RRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1RRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2RRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0Ptr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1Ptr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2Ptr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0PtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1PtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2PtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0Ptr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1Ptr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2Ptr, 0>, int>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0PtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1PtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2PtrC, 0>, int>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0CPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1CPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2CPtr, 0>, int>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0CPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1CPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2CPtrC, 0>, int>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc0El, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc1El, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<PFFunc2El, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0ElRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1ElRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2ElRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0ElRRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1ElRRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2ElRRef, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0ElPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1ElPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2ElPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc0ElPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc1ElPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FFunc2ElPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0ElPtr, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1ElPtr, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2ElPtr, 0>, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0ElPtrC, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1ElPtrC, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2ElPtrC, 0>, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0ElCPtr, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1ElCPtr, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2ElCPtr, 0>, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc0ElCPtrC, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc1ElCPtrC, 0>, CFunctionTraitTag_Ellipsis>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<FMFunc2ElCPtrC, 0>, CTestBase>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CMPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CMCPtr, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CMPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CMCPtrC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestArray2, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestArray2C, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestArray, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTestArrayC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest2DArray2, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest2DArray2C, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest2DArray, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest2DArrayC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest3DArray2, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest3DArray2C, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest3DArray, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<CTest3DArrayC, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<void *, 0>, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits_ArgumentType<void, 0>, void>);

/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Class type
|___________________________________________________________________________________________________|
\***************************************************************************************************/

static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestUnion>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass0>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass1>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestStruct0>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestStruct1>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<ETestEnum>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestPtr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCPtr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestPtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCPtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestRRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCRRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc0>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc1>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc2>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0Ref>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1Ref>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2Ref>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0RRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1RRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2RRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0Ptr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1Ptr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2Ptr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0PtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1PtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2PtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0Ptr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1Ptr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2Ptr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0PtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1PtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2PtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc0El>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc1El>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc2El>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElRRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElRRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElRRef>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::CClass, CTestClass0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMPtr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMCPtr>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMPtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMCPtrC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray2>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray2C>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArrayC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray2>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray2C>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArrayC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray2>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray2C>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArrayC>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<void *>::CClass, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<void>::CClass, void>);



/***************************************************************************************************\
|¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯|
| Function type
|___________________________________________________________________________________________________|
\***************************************************************************************************/

static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestUnion>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass0>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass1>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestStruct0>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestStruct1>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<ETestEnum>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestClass>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestPtr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCPtr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestPtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCPtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestRRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestCRRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc0>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc1>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc2>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0Ref>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1Ref>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2Ref>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0RRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1RRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2RRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0Ptr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1Ptr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2Ptr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0PtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1PtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2PtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0Ptr>::CFunctionType, PFFunc0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1Ptr>::CFunctionType, PFFunc1>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2Ptr>::CFunctionType, PFFunc2>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0PtrC>::CFunctionType, PFFunc0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1PtrC>::CFunctionType, PFFunc1>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2PtrC>::CFunctionType, PFFunc2>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtr>::CFunctionType, PFFunc0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtr>::CFunctionType, PFFunc1>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtr>::CFunctionType, PFFunc2>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0CPtrC>::CFunctionType, PFFunc0>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1CPtrC>::CFunctionType, PFFunc1>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2CPtrC>::CFunctionType, PFFunc2>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc0El>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc1El>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<PFFunc2El>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElRRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElRRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElRRef>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc0ElPtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc1ElPtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FFunc2ElPtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtr>::CFunctionType, PFFunc0El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtr>::CFunctionType, PFFunc1El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtr>::CFunctionType, PFFunc2El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElPtrC>::CFunctionType, PFFunc0El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElPtrC>::CFunctionType, PFFunc1El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElPtrC>::CFunctionType, PFFunc2El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtr>::CFunctionType, PFFunc0El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtr>::CFunctionType, PFFunc1El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtr>::CFunctionType, PFFunc2El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc0ElCPtrC>::CFunctionType, PFFunc0El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc1ElCPtrC>::CFunctionType, PFFunc1El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<FMFunc2ElCPtrC>::CFunctionType, PFFunc2El>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMPtr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMCPtr>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMPtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CMCPtrC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray2>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray2C>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArray>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTestArrayC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray2>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray2C>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArray>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest2DArrayC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray2>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray2C>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArray>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<CTest3DArrayC>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<void *>::CFunctionType, void>);
static_assert(cIsSame<TCMemberFunctionPointerTraits<void>::CFunctionType, void>);

