// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

// Void
DMibStaticCheck((	!TCIsClass<CTestUnion>::mc_Value					));
DMibStaticCheck((	TCIsClass<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsClass<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCIsClass<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCIsClass<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCIsClass<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCIsClass<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCIsClass<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCIsClass<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	!TCIsClass<ETestEnum>::mc_Value						));
DMibStaticCheck((	!TCIsClass<int>::mc_Value							));
DMibStaticCheck((	TCIsClass<CTestClass>::mc_Value							));
DMibStaticCheck((	TCIsClass<CTestC>::mc_Value							));
DMibStaticCheck((	!TCIsClass<CTestPtr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CTestCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CTestPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCIsClass<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsClass<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsClass<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsClass<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsClass<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CMPtr>::mc_Value							));
DMibStaticCheck((	!TCIsClass<CMCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CMPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CMCPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsClass<CTestArray2>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTestArray2C>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTestArray>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTestArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsClass<CTest2DArray>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsClass<CTest3DArray>::mc_Value					));
DMibStaticCheck((	!TCIsClass<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsClass<void *>::mc_Value						));
DMibStaticCheck((	!TCIsClass<void>::mc_Value							));

