// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"


// Empty
DMibStaticCheck((	!TCIsEmpty<CTestUnion>::mc_Value		));
DMibStaticCheck((	TCIsEmpty<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTestClass1>::mc_Value		));
DMibStaticCheck((	TCIsEmpty<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsEmpty<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestCRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestRRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc0Ref>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc1Ref>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc2Ref>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc0RRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc1RRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc2RRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsEmpty<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsEmpty<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsEmpty<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsEmpty<void *>::mc_Value			));
DMibStaticCheck((	!TCIsEmpty<void>::mc_Value				));

