// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"


// Object
DMibStaticCheck((	TCIsObject<CTestUnion>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTestClass0>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTestClass1>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsObject<ETestEnum>::mc_Value			));
DMibStaticCheck((	TCIsObject<CTestClass>::mc_Value				));
DMibStaticCheck((	TCIsObject<CTestC>::mc_Value			));
DMibStaticCheck((	TCIsObject<CTestPtr>::mc_Value			));
DMibStaticCheck((	TCIsObject<CTestCPtr>::mc_Value			));
DMibStaticCheck((	TCIsObject<CTestPtrC>::mc_Value			));
DMibStaticCheck((	TCIsObject<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsObject<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsObject<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsObject<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsObject<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsObject<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	TCIsObject<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsObject<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsObject<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsObject<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsObject<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsObject<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsObject<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsObject<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsObject<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	TCIsObject<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsObject<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsObject<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsObject<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsObject<CMPtr>::mc_Value				));
DMibStaticCheck((	TCIsObject<CMCPtr>::mc_Value			));
DMibStaticCheck((	TCIsObject<CMPtrC>::mc_Value			));
DMibStaticCheck((	TCIsObject<CMCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsObject<CTestArray2>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTestArray>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTestArrayC>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsObject<CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsObject<CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsObject<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsObject<void *>::mc_Value			));
DMibStaticCheck((	!TCIsObject<void>::mc_Value				));

