// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

#ifdef DMibCompiler_GCC
#pragma GCC system_header
#endif

class CTestInherit : public CTestClass
{
public:
	int m_Test;
};

void blaha()
{
	class CTestInherit : public CTestClass
	{
	public:
		int m_Test;
	};

	CTestInherit Test3;
//	CTestClass &Test2 = NMib::fg_Move(Test3);
	CTestClass &Test4 = Test3;
	CTestClass &&Test5 = NMib::fg_Move(Test3);
}

#include <type_traits>

DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArrayNoDefault, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestClass *, void (CTestClass const *)>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass *, void (CTestClass *)>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass &, void (CTestClass &)>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass &&, void (CTestClass &&)>::mc_Value	));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestInherit &&, void (CTestClass &&)>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass &&, void (CTestInherit &&)>::mc_Value	));
#ifndef DCompiler_MSVC
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestClass &, void (CTestClass &&)>::mc_Value	));
#endif
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestClass &&, void (CTestClass &)>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass &&, void (CTestClass)>::mc_Value	));
#ifndef DCompiler_MSVC
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestClass &, void (CTestClass)>::mc_Value	));
#endif
DMibStaticCheck((	TCIsConstructorCallableWith<CTestBase, void (CTestBase&&)>::mc_Value	));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestNoDefaultConstruct, void ()>::mc_Value	));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestBase, void (int &)>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestNoDefaultConstruct, void (int &&)>::mc_Value	));


DMibStaticCheck((	TCIsConstructorCallableWith<CTestUnion, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass0, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass1, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestStruct0, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestStruct1, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<const CTestClass0, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<const CTestClass1, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<const CTestStruct0, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<const CTestStruct1, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<volatile CTestClass0, void ()>::mc_Value			));
DMibStaticCheck((	TCIsConstructorCallableWith<volatile CTestClass1, void ()>::mc_Value			));
DMibStaticCheck((	TCIsConstructorCallableWith<volatile CTestStruct0, void ()>::mc_Value			));
DMibStaticCheck((	TCIsConstructorCallableWith<volatile CTestStruct1, void ()>::mc_Value			));
DMibStaticCheck((	TCIsConstructorCallableWith<const volatile CTestClass0, void ()>::mc_Value		));
DMibStaticCheck((	TCIsConstructorCallableWith<const volatile CTestClass1, void ()>::mc_Value		));
DMibStaticCheck((	TCIsConstructorCallableWith<const volatile CTestStruct0, void ()>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<const volatile CTestStruct1, void ()>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<ETestEnum, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<int, void ()>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass, void ()>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestC, void ()>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestV, void ()>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestPtrC, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestPtrV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestCRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestVRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestCVRef, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestRRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestCRRef, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestVRRef, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestCVRRef, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc0, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc1, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc2, void ()>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc0Ref, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc1Ref, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc2Ref, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc0RRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc1RRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc2RRef, void ()>::mc_Value						));
#endif
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0Ptr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1Ptr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2Ptr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0PtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1PtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2PtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0PtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1PtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2PtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0PtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1PtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2PtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0Ptr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1Ptr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2Ptr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0PtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1PtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2PtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0PtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1PtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2PtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0PtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1PtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2PtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0VPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1VPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2VPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0VPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1VPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2VPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0VPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1VPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2VPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0VPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1VPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2VPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CVPtrCV, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CVPtrCV, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CVPtrCV, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc0El, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc1El, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc2El, void ()>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc0ElRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc1ElRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc2ElRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc0ElRRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc1ElRRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc2ElRRef, void ()>::mc_Value						));
#endif
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElVPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElVPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElVPtrCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCVPtr, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCVPtrC, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCVPtrV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCVPtrCV, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCVPtrCV, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCVPtrCV, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<CMPtr, void ()>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMVPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCVPtr, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMPtrC, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCPtrC, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMVPtrC, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCVPtrC, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMPtrV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCPtrV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMVPtrV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCVPtrV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMPtrCV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCPtrCV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMVPtrCV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCVPtrCV, void ()>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestArray2, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestArray2C, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestArray2V, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestArray2CV, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArray, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArrayC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArrayV, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArrayCV, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTest2DArray2, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTest2DArray2C, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<CTest2DArray2V, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<CTest2DArray2CV, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArray, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArrayC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArrayV, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArrayCV, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<CTest3DArray2, void ()>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTest3DArray2C, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<CTest3DArray2V, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<CTest3DArray2CV, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArray, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArrayC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArrayV, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArrayCV, void ()>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<void *, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<void, void ()>::mc_Value							));


/////////////////////////////////////////////////////
/////////////////////////////////////////////////////
/////////////////////////////////////////////////////


DMibStaticCheck((	TCIsConstructorCallableWith<CTestUnion, void (CTestUnion)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass0, void (CTestClass0)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass1, void (CTestClass1)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestStruct0, void (CTestStruct0)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestStruct1, void (CTestStruct1)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<const CTestClass0, void (CTestClass0)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<const CTestClass1, void (CTestClass1)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<const CTestStruct0, void (CTestStruct0)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<const CTestStruct1, void (CTestStruct1)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<volatile CTestClass0, void (CTestClass0)>::mc_Value			));
DMibStaticCheck((	TCIsConstructorCallableWith<volatile CTestClass1, void (CTestClass1)>::mc_Value			));
DMibStaticCheck((	TCIsConstructorCallableWith<volatile CTestStruct0, void (CTestStruct0)>::mc_Value			));
DMibStaticCheck((	TCIsConstructorCallableWith<volatile CTestStruct1, void (CTestStruct1)>::mc_Value			));
DMibStaticCheck((	TCIsConstructorCallableWith<const volatile CTestClass0, void (CTestClass0)>::mc_Value		));
DMibStaticCheck((	TCIsConstructorCallableWith<const volatile CTestClass1, void (CTestClass1)>::mc_Value		));
DMibStaticCheck((	TCIsConstructorCallableWith<const volatile CTestStruct0, void (CTestStruct0)>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<const volatile CTestStruct1, void (CTestStruct1)>::mc_Value	));
DMibStaticCheck((	TCIsConstructorCallableWith<ETestEnum, void (ETestEnum)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<int, void (int)>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestClass, void (CTestClass)>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestC, void (CTestC)>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestV, void (CTestV)>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCV, void (CTestCV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestPtr, void (CTestPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCPtr, void (CTestCPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVPtr, void (CTestVPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVPtr, void (CTestCVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestPtrC, void (CTestPtrC)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCPtrC, void (CTestCPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVPtrC, void (CTestVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVPtrC, void (CTestCVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestPtrV, void (CTestPtrV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCPtrV, void (CTestCPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVPtrV, void (CTestVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVPtrV, void (CTestCVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestPtrCV, void (CTestPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCPtrCV, void (CTestCPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVPtrCV, void (CTestVPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVPtrCV, void (CTestCVPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestRef, void (CTestRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCRef, void (CTestCRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVRef, void (CTestVRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVRef, void (CTestCVRef)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestRRef, void (CTestRRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCRRef, void (CTestCRRef)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestVRRef, void (CTestVRRef)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<CTestCVRRef, void (CTestCVRRef)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc0, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc1, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc2, void ()>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0Ref, void (FFunc0Ref)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1Ref, void (FFunc1Ref)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2Ref, void (FFunc2Ref)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0Ref, void (FFunc0RRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1Ref, void (FFunc1RRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2Ref, void (FFunc2RRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0RRef, void (FFunc0RRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1RRef, void (FFunc1RRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2RRef, void (FFunc2RRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0RRef, void (FFunc0Ref)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1RRef, void (FFunc1Ref)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2RRef, void (FFunc2Ref)>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc0Ref, void (FFunc0Ptr)>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc1Ref, void (FFunc1Ptr)>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc2Ref, void (FFunc2Ptr)>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc0RRef, void (FFunc0Ptr)>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc1RRef, void (FFunc1Ptr)>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<FFunc2RRef, void (FFunc2Ptr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0Ptr, void (FFunc0Ref)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1Ptr, void (FFunc1Ref)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2Ptr, void (FFunc2Ref)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0Ptr, void (FFunc0RRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1Ptr, void (FFunc1RRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2Ptr, void (FFunc2RRef)>::mc_Value						));
#endif
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0Ptr, void (FFunc0Ptr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1Ptr, void (FFunc1Ptr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2Ptr, void (FFunc2Ptr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0PtrC, void (FFunc0PtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1PtrC, void (FFunc1PtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2PtrC, void (FFunc2PtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0PtrV, void (FFunc0PtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1PtrV, void (FFunc1PtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2PtrV, void (FFunc2PtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0PtrCV, void (FFunc0PtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1PtrCV, void (FFunc1PtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2PtrCV, void (FFunc2PtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0Ptr, void (FMFunc0Ptr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1Ptr, void (FMFunc1Ptr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2Ptr, void (FMFunc2Ptr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0PtrC, void (FMFunc0PtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1PtrC, void (FMFunc1PtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2PtrC, void (FMFunc2PtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0PtrV, void (FMFunc0PtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1PtrV, void (FMFunc1PtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2PtrV, void (FMFunc2PtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0PtrCV, void (FMFunc0PtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1PtrCV, void (FMFunc1PtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2PtrCV, void (FMFunc2PtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CPtr, void (FMFunc0CPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CPtr, void (FMFunc1CPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CPtr, void (FMFunc2CPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CPtrC, void (FMFunc0CPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CPtrC, void (FMFunc1CPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CPtrC, void (FMFunc2CPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CPtrV, void (FMFunc0CPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CPtrV, void (FMFunc1CPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CPtrV, void (FMFunc2CPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CPtrCV, void (FMFunc0CPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CPtrCV, void (FMFunc1CPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CPtrCV, void (FMFunc2CPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0VPtr, void (FMFunc0VPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1VPtr, void (FMFunc1VPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2VPtr, void (FMFunc2VPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0VPtrC, void (FMFunc0VPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1VPtrC, void (FMFunc1VPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2VPtrC, void (FMFunc2VPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0VPtrV, void (FMFunc0VPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1VPtrV, void (FMFunc1VPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2VPtrV, void (FMFunc2VPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0VPtrCV, void (FMFunc0VPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1VPtrCV, void (FMFunc1VPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2VPtrCV, void (FMFunc2VPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CVPtr, void (FMFunc0CVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CVPtr, void (FMFunc1CVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CVPtr, void (FMFunc2CVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CVPtrC, void (FMFunc0CVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CVPtrC, void (FMFunc1CVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CVPtrC, void (FMFunc2CVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CVPtrV, void (FMFunc0CVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CVPtrV, void (FMFunc1CVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CVPtrV, void (FMFunc2CVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0CVPtrCV, void (FMFunc0CVPtrCV)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1CVPtrCV, void (FMFunc1CVPtrCV)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2CVPtrCV, void (FMFunc2CVPtrCV)>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc0El, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc1El, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<PFFunc2El, void ()>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElRef, void (FFunc0ElRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElRef, void (FFunc1ElRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElRef, void (FFunc2ElRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElRRef, void (FFunc0ElRRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElRRef, void (FFunc1ElRRef)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElRRef, void (FFunc2ElRRef)>::mc_Value						));
#endif
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElPtr, void (FFunc0ElPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElPtr, void (FFunc1ElPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElPtr, void (FFunc2ElPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElPtrC, void (FFunc0ElPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElPtrC, void (FFunc1ElPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElPtrC, void (FFunc2ElPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElPtrV, void (FFunc0ElPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElPtrV, void (FFunc1ElPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElPtrV, void (FFunc2ElPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc0ElPtrCV, void (FFunc0ElPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc1ElPtrCV, void (FFunc1ElPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FFunc2ElPtrCV, void (FFunc2ElPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElPtr, void (FMFunc0ElPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElPtr, void (FMFunc1ElPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElPtr, void (FMFunc2ElPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElPtrC, void (FMFunc0ElPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElPtrC, void (FMFunc1ElPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElPtrC, void (FMFunc2ElPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElPtrV, void (FMFunc0ElPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElPtrV, void (FMFunc1ElPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElPtrV, void (FMFunc2ElPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElPtrCV, void (FMFunc0ElPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElPtrCV, void (FMFunc1ElPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElPtrCV, void (FMFunc2ElPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCPtr, void (FMFunc0ElCPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCPtr, void (FMFunc1ElCPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCPtr, void (FMFunc2ElCPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCPtrC, void (FMFunc0ElCPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCPtrC, void (FMFunc1ElCPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCPtrC, void (FMFunc2ElCPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCPtrV, void (FMFunc0ElCPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCPtrV, void (FMFunc1ElCPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCPtrV, void (FMFunc2ElCPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCPtrCV, void (FMFunc0ElCPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCPtrCV, void (FMFunc1ElCPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCPtrCV, void (FMFunc2ElCPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElVPtr, void (FMFunc0ElVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElVPtr, void (FMFunc1ElVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElVPtr, void (FMFunc2ElVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElVPtrC, void (FMFunc0ElVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElVPtrC, void (FMFunc1ElVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElVPtrC, void (FMFunc2ElVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElVPtrV, void (FMFunc0ElVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElVPtrV, void (FMFunc1ElVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElVPtrV, void (FMFunc2ElVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElVPtrCV, void (FMFunc0ElVPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElVPtrCV, void (FMFunc1ElVPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElVPtrCV, void (FMFunc2ElVPtrCV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCVPtr, void (FMFunc0ElCVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCVPtr, void (FMFunc1ElCVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCVPtr, void (FMFunc2ElCVPtr)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCVPtrC, void (FMFunc0ElCVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCVPtrC, void (FMFunc1ElCVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCVPtrC, void (FMFunc2ElCVPtrC)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCVPtrV, void (FMFunc0ElCVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCVPtrV, void (FMFunc1ElCVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCVPtrV, void (FMFunc2ElCVPtrV)>::mc_Value					));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc0ElCVPtrCV, void (FMFunc0ElCVPtrCV)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc1ElCVPtrCV, void (FMFunc1ElCVPtrCV)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<FMFunc2ElCVPtrCV, void (FMFunc2ElCVPtrCV)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<CMPtr, void (CMPtr)>::mc_Value							));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCPtr, void (CMCPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMVPtr, void (CMVPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCVPtr, void (CMCVPtr)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMPtrC, void (CMPtrC)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCPtrC, void (CMCPtrC)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMVPtrC, void (CMVPtrC)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCVPtrC, void (CMCVPtrC)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMPtrV, void (CMPtrV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCPtrV, void (CMCPtrV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMVPtrV, void (CMVPtrV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCVPtrV, void (CMCVPtrV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMPtrCV, void (CMPtrCV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCPtrCV, void (CMCPtrCV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMVPtrCV, void (CMVPtrCV)>::mc_Value						));
DMibStaticCheck((	TCIsConstructorCallableWith<CMCVPtrCV, void (CMCVPtrCV)>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArray2, void (CTestArray2)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArray2C, void (CTestArray2C)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArray2V, void (CTestArray2V)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArray2CV, void (CTestArray2CV)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArray, void (CTestArray)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArrayC, void (CTestArrayC)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArrayV, void (CTestArrayV)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTestArrayCV, void (CTestArrayCV)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArray2, void (CTest2DArray2)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArray2C, void (CTest2DArray2C)>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArray2V, void (CTest2DArray2V)>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArray2CV, void (CTest2DArray2CV)>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArray, void (CTest2DArray)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArrayC, void (CTest2DArrayC)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArrayV, void (CTest2DArrayV)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest2DArrayCV, void (CTest2DArrayCV)>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArray2, void (CTest3DArray2)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArray2C, void (CTest3DArray2C)>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArray2V, void (CTest3DArray2V)>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArray2CV, void (CTest3DArray2CV)>::mc_Value				));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArray, void (CTest3DArray)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArrayC, void (CTest3DArrayC)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArrayV, void (CTest3DArrayV)>::mc_Value					));
DMibStaticCheck((	!TCIsConstructorCallableWith<CTest3DArrayCV, void (CTest3DArrayCV)>::mc_Value				));
DMibStaticCheck((	TCIsConstructorCallableWith<void *, void (void *)>::mc_Value						));
DMibStaticCheck((	!TCIsConstructorCallableWith<void, void ()>::mc_Value							));
