// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

static_assert(!cIsPointer<CTestUnion>);
static_assert(!cIsPointer<CTestClass0>);
static_assert(!cIsPointer<CTestClass1>);
static_assert(!cIsPointer<CTestStruct0>);
static_assert(!cIsPointer<CTestStruct1>);
static_assert(!cIsPointer<ETestEnum>);
static_assert(!cIsPointer<CTestClass>);
static_assert(!cIsPointer<CTestC>);
static_assert(cIsPointer<CTestPtr>);
static_assert(cIsPointer<CTestCPtr>);
static_assert(cIsPointer<CTestPtrC>);
static_assert(cIsPointer<CTestCPtrC>);
static_assert(!cIsPointer<CTestRef>);
static_assert(!cIsPointer<CTestCRef>);
static_assert(!cIsPointer<CTestRRef>);
static_assert(!cIsPointer<CTestCRRef>);
static_assert(!cIsPointer<PFFunc0>);
static_assert(!cIsPointer<PFFunc1>);
static_assert(!cIsPointer<PFFunc2>);
static_assert(!cIsPointer<FFunc0Ref>);
static_assert(!cIsPointer<FFunc1Ref>);
static_assert(!cIsPointer<FFunc2Ref>);
static_assert(!cIsPointer<FFunc0RRef>);
static_assert(!cIsPointer<FFunc1RRef>);
static_assert(!cIsPointer<FFunc2RRef>);
static_assert(cIsPointer<FFunc0Ptr>);
static_assert(cIsPointer<FFunc1Ptr>);
static_assert(cIsPointer<FFunc2Ptr>);
static_assert(cIsPointer<FFunc0PtrC>);
static_assert(cIsPointer<FFunc1PtrC>);
static_assert(cIsPointer<FFunc2PtrC>);
static_assert(!cIsPointer<FMFunc0Ptr>);
static_assert(!cIsPointer<FMFunc1Ptr>);
static_assert(!cIsPointer<FMFunc2Ptr>);
static_assert(!cIsPointer<FMFunc0PtrC>);
static_assert(!cIsPointer<FMFunc1PtrC>);
static_assert(!cIsPointer<FMFunc2PtrC>);
static_assert(!cIsPointer<FMFunc0CPtr>);
static_assert(!cIsPointer<FMFunc1CPtr>);
static_assert(!cIsPointer<FMFunc2CPtr>);
static_assert(!cIsPointer<FMFunc0CPtrC>);
static_assert(!cIsPointer<FMFunc1CPtrC>);
static_assert(!cIsPointer<FMFunc2CPtrC>);
static_assert(!cIsPointer<PFFunc0El>);
static_assert(!cIsPointer<PFFunc1El>);
static_assert(!cIsPointer<PFFunc2El>);
static_assert(!cIsPointer<FFunc0ElRef>);
static_assert(!cIsPointer<FFunc1ElRef>);
static_assert(!cIsPointer<FFunc2ElRef>);
static_assert(!cIsPointer<FFunc0ElRRef>);
static_assert(!cIsPointer<FFunc1ElRRef>);
static_assert(!cIsPointer<FFunc2ElRRef>);
static_assert(cIsPointer<FFunc0ElPtr>);
static_assert(cIsPointer<FFunc1ElPtr>);
static_assert(cIsPointer<FFunc2ElPtr>);
static_assert(cIsPointer<FFunc0ElPtrC>);
static_assert(cIsPointer<FFunc1ElPtrC>);
static_assert(cIsPointer<FFunc2ElPtrC>);
static_assert(!cIsPointer<FMFunc0ElPtr>);
static_assert(!cIsPointer<FMFunc1ElPtr>);
static_assert(!cIsPointer<FMFunc2ElPtr>);
static_assert(!cIsPointer<FMFunc0ElPtrC>);
static_assert(!cIsPointer<FMFunc1ElPtrC>);
static_assert(!cIsPointer<FMFunc2ElPtrC>);
static_assert(!cIsPointer<FMFunc0ElCPtr>);
static_assert(!cIsPointer<FMFunc1ElCPtr>);
static_assert(!cIsPointer<FMFunc2ElCPtr>);
static_assert(!cIsPointer<FMFunc0ElCPtrC>);
static_assert(!cIsPointer<FMFunc1ElCPtrC>);
static_assert(!cIsPointer<FMFunc2ElCPtrC>);
static_assert(!cIsPointer<CMPtr>);
static_assert(!cIsPointer<CMCPtr>);
static_assert(!cIsPointer<CMPtrC>);
static_assert(!cIsPointer<CMCPtrC>);
static_assert(!cIsPointer<CTestArray2>);
static_assert(!cIsPointer<CTestArray2C>);
static_assert(!cIsPointer<CTestArray>);
static_assert(!cIsPointer<CTestArrayC>);
static_assert(!cIsPointer<CTest2DArray2>);
static_assert(!cIsPointer<CTest2DArray2C>);
static_assert(!cIsPointer<CTest2DArray>);
static_assert(!cIsPointer<CTest2DArrayC>);
static_assert(!cIsPointer<CTest3DArray2>);
static_assert(!cIsPointer<CTest3DArray2C>);
static_assert(!cIsPointer<CTest3DArray>);
static_assert(!cIsPointer<CTest3DArrayC>);
static_assert(cIsPointer<void *>);
static_assert(!cIsPointer<void>);

static_assert(cIsSame<TCAddPointer<CTestUnion>, CTestUnion *>);
static_assert(cIsSame<TCAddPointer<CTestClass0>, CTestClass0 *>);
static_assert(cIsSame<TCAddPointer<CTestClass1>, CTestClass1 *>);
static_assert(cIsSame<TCAddPointer<CTestStruct0>, CTestStruct0 *>);
static_assert(cIsSame<TCAddPointer<CTestStruct1>, CTestStruct1 *>);
static_assert(cIsSame<TCAddPointer<ETestEnum>, ETestEnum *>);
static_assert(cIsSame<TCAddPointer<CTestClass>, CTestClass *>);
static_assert(cIsSame<TCAddPointer<CTestC>, CTestC *>);
static_assert(cIsSame<TCAddPointer<CTestPtr>, CTestPtr *>);
static_assert(cIsSame<TCAddPointer<CTestCPtr>, CTestCPtr *>);
static_assert(cIsSame<TCAddPointer<CTestPtrC>, CTestPtrC *>);
static_assert(cIsSame<TCAddPointer<CTestCPtrC>, CTestCPtrC *>);
static_assert(cIsSame<TCAddPointer<CTestRef>, CTestPtr>);
static_assert(cIsSame<TCAddPointer<CTestCRef>, CTestCPtr>);
static_assert(cIsSame<TCAddPointer<CTestRRef>, CTestPtr>);
static_assert(cIsSame<TCAddPointer<CTestCRRef>, CTestCPtr>);
static_assert(cIsSame<TCAddPointer<PFFunc0>, PFFunc0 *>);
static_assert(cIsSame<TCAddPointer<PFFunc1>, PFFunc1 *>);
static_assert(cIsSame<TCAddPointer<PFFunc2>, PFFunc2 *>);
static_assert(cIsSame<TCAddPointer<FFunc0Ref>, FFunc0Ptr>);
static_assert(cIsSame<TCAddPointer<FFunc1Ref>, FFunc1Ptr>);
static_assert(cIsSame<TCAddPointer<FFunc2Ref>, FFunc2Ptr>);
static_assert(cIsSame<TCAddPointer<FFunc0RRef>, FFunc0Ptr>);
static_assert(cIsSame<TCAddPointer<FFunc1RRef>, FFunc1Ptr>);
static_assert(cIsSame<TCAddPointer<FFunc2RRef>, FFunc2Ptr>);
static_assert(cIsSame<TCAddPointer<FFunc0Ptr>, FFunc0Ptr *>);
static_assert(cIsSame<TCAddPointer<FFunc1Ptr>, FFunc1Ptr *>);
static_assert(cIsSame<TCAddPointer<FFunc2Ptr>, FFunc2Ptr *>);
static_assert(cIsSame<TCAddPointer<FFunc0PtrC>, FFunc0PtrC *>);
static_assert(cIsSame<TCAddPointer<FFunc1PtrC>, FFunc1PtrC *>);
static_assert(cIsSame<TCAddPointer<FFunc2PtrC>, FFunc2PtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc0Ptr>, FMFunc0Ptr *>);
static_assert(cIsSame<TCAddPointer<FMFunc1Ptr>, FMFunc1Ptr *>);
static_assert(cIsSame<TCAddPointer<FMFunc2Ptr>, FMFunc2Ptr *>);
static_assert(cIsSame<TCAddPointer<FMFunc0PtrC>, FMFunc0PtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc1PtrC>, FMFunc1PtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc2PtrC>, FMFunc2PtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc0CPtr>, FMFunc0CPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc1CPtr>, FMFunc1CPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc2CPtr>, FMFunc2CPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc0CPtrC>, FMFunc0CPtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc1CPtrC>, FMFunc1CPtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc2CPtrC>, FMFunc2CPtrC *>);
static_assert(cIsSame<TCAddPointer<PFFunc0El>, PFFunc0El *>);
static_assert(cIsSame<TCAddPointer<PFFunc1El>, PFFunc1El *>);
static_assert(cIsSame<TCAddPointer<PFFunc2El>, PFFunc2El *>);
static_assert(cIsSame<TCAddPointer<FFunc0ElRef>, FFunc0ElPtr>);
static_assert(cIsSame<TCAddPointer<FFunc1ElRef>, FFunc1ElPtr>);
static_assert(cIsSame<TCAddPointer<FFunc2ElRef>, FFunc2ElPtr>);
static_assert(cIsSame<TCAddPointer<FFunc0ElRRef>, FFunc0ElPtr>);
static_assert(cIsSame<TCAddPointer<FFunc1ElRRef>, FFunc1ElPtr>);
static_assert(cIsSame<TCAddPointer<FFunc2ElRRef>, FFunc2ElPtr>);
static_assert(cIsSame<TCAddPointer<FFunc0ElPtr>, FFunc0ElPtr *>);
static_assert(cIsSame<TCAddPointer<FFunc1ElPtr>, FFunc1ElPtr *>);
static_assert(cIsSame<TCAddPointer<FFunc2ElPtr>, FFunc2ElPtr *>);
static_assert(cIsSame<TCAddPointer<FFunc0ElPtrC>, FFunc0ElPtrC *>);
static_assert(cIsSame<TCAddPointer<FFunc1ElPtrC>, FFunc1ElPtrC *>);
static_assert(cIsSame<TCAddPointer<FFunc2ElPtrC>, FFunc2ElPtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc0ElPtr>, FMFunc0ElPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc1ElPtr>, FMFunc1ElPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc2ElPtr>, FMFunc2ElPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc0ElPtrC>, FMFunc0ElPtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc1ElPtrC>, FMFunc1ElPtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc2ElPtrC>, FMFunc2ElPtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc0ElCPtr>, FMFunc0ElCPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc1ElCPtr>, FMFunc1ElCPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc2ElCPtr>, FMFunc2ElCPtr *>);
static_assert(cIsSame<TCAddPointer<FMFunc0ElCPtrC>, FMFunc0ElCPtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc1ElCPtrC>, FMFunc1ElCPtrC *>);
static_assert(cIsSame<TCAddPointer<FMFunc2ElCPtrC>, FMFunc2ElCPtrC *>);
static_assert(cIsSame<TCAddPointer<CMPtr>, CMPtr *>);
static_assert(cIsSame<TCAddPointer<CMCPtr>, CMCPtr *>);
static_assert(cIsSame<TCAddPointer<CMPtrC>, CMPtrC *>);
static_assert(cIsSame<TCAddPointer<CMCPtrC>, CMCPtrC *>);
static_assert(cIsSame<TCAddPointer<CTestArray2>, CTestArray2 *>);
static_assert(cIsSame<TCAddPointer<CTestArray2C>, CTestArray2C *>);
static_assert(cIsSame<TCAddPointer<CTestArray>, CTestArray *>);
static_assert(cIsSame<TCAddPointer<CTestArrayC>, CTestArrayC *>);
static_assert(cIsSame<TCAddPointer<CTest2DArray2>, CTest2DArray2 *>);
static_assert(cIsSame<TCAddPointer<CTest2DArray2C>, CTest2DArray2C *>);
static_assert(cIsSame<TCAddPointer<CTest2DArray>, CTest2DArray *>);
static_assert(cIsSame<TCAddPointer<CTest2DArrayC>, CTest2DArrayC *>);
static_assert(cIsSame<TCAddPointer<CTest3DArray2>, CTest3DArray2 *>);
static_assert(cIsSame<TCAddPointer<CTest3DArray2C>, CTest3DArray2C *>);
static_assert(cIsSame<TCAddPointer<CTest3DArray>, CTest3DArray *>);
static_assert(cIsSame<TCAddPointer<CTest3DArrayC>, CTest3DArrayC *>);
static_assert(cIsSame<TCAddPointer<void *>, void **>);
static_assert(cIsSame<TCAddPointer<void>, void *>);


// Remove pointer
static_assert(cIsSame<TCRemovePointer<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCRemovePointer<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCRemovePointer<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCRemovePointer<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCRemovePointer<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCRemovePointer<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCRemovePointer<CTestClass>, CTestClass>);
static_assert(cIsSame<TCRemovePointer<CTestC>, CTestC>);
static_assert(cIsSame<TCRemovePointer<CTestPtr>, CTestClass>);
static_assert(cIsSame<TCRemovePointer<CTestCPtr>, CTestC>);
static_assert(cIsSame<TCRemovePointer<CTestPtrC>, CTestClass>);
static_assert(cIsSame<TCRemovePointer<CTestCPtrC>, CTestC>);
static_assert(cIsSame<TCRemovePointer<CTestRef>, CTestRef>);
static_assert(cIsSame<TCRemovePointer<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCRemovePointer<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCRemovePointer<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCRemovePointer<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCRemovePointer<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCRemovePointer<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCRemovePointer<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCRemovePointer<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCRemovePointer<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCRemovePointer<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCRemovePointer<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCRemovePointer<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCRemovePointer<FFunc0Ptr>, PFFunc0>);
static_assert(cIsSame<TCRemovePointer<FFunc1Ptr>, PFFunc1>);
static_assert(cIsSame<TCRemovePointer<FFunc2Ptr>, PFFunc2>);
static_assert(cIsSame<TCRemovePointer<FFunc0PtrC>, PFFunc0>);
static_assert(cIsSame<TCRemovePointer<FFunc1PtrC>, PFFunc1>);
static_assert(cIsSame<TCRemovePointer<FFunc2PtrC>, PFFunc2>);
static_assert(cIsSame<TCRemovePointer<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCRemovePointer<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCRemovePointer<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCRemovePointer<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCRemovePointer<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCRemovePointer<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCRemovePointer<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCRemovePointer<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCRemovePointer<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCRemovePointer<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCRemovePointer<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCRemovePointer<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCRemovePointer<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCRemovePointer<FFunc0ElPtr>, PFFunc0El>);
static_assert(cIsSame<TCRemovePointer<FFunc1ElPtr>, PFFunc1El>);
static_assert(cIsSame<TCRemovePointer<FFunc2ElPtr>, PFFunc2El>);
static_assert(cIsSame<TCRemovePointer<FFunc0ElPtrC>, PFFunc0El>);
static_assert(cIsSame<TCRemovePointer<FFunc1ElPtrC>, PFFunc1El>);
static_assert(cIsSame<TCRemovePointer<FFunc2ElPtrC>, PFFunc2El>);
static_assert(cIsSame<TCRemovePointer<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCRemovePointer<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCRemovePointer<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCRemovePointer<CMPtr>, CMPtr>);
static_assert(cIsSame<TCRemovePointer<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCRemovePointer<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCRemovePointer<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCRemovePointer<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCRemovePointer<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCRemovePointer<CTestArray>, CTestArray>);
static_assert(cIsSame<TCRemovePointer<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCRemovePointer<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCRemovePointer<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCRemovePointer<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCRemovePointer<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCRemovePointer<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCRemovePointer<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCRemovePointer<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCRemovePointer<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCRemovePointer<void *>, void>);
static_assert(cIsSame<TCRemovePointer<void>, void>);

