// Copyright © Unbroken AB
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "Test_TypeTraits_TestTypes.h"

// Void
static_assert(!cIsClass<CTestUnion>);
static_assert(cIsClass<CTestClass0>);
static_assert(cIsClass<CTestClass1>);
static_assert(cIsClass<CTestStruct0>);
static_assert(cIsClass<CTestStruct1>);
static_assert(cIsClass<const CTestClass0>);
static_assert(cIsClass<const CTestClass1>);
static_assert(cIsClass<const CTestStruct0>);
static_assert(cIsClass<const CTestStruct1>);
static_assert(!cIsClass<ETestEnum>);
static_assert(!cIsClass<int>);
static_assert(cIsClass<CTestClass>);
static_assert(cIsClass<CTestC>);
static_assert(!cIsClass<CTestPtr>);
static_assert(!cIsClass<CTestCPtr>);
static_assert(!cIsClass<CTestPtrC>);
static_assert(!cIsClass<CTestCPtrC>);
static_assert(!cIsClass<CTestRef>);
static_assert(!cIsClass<CTestCRef>);
static_assert(!cIsClass<CTestRRef>);
static_assert(!cIsClass<CTestCRRef>);
static_assert(!cIsClass<PFFunc0>);
static_assert(!cIsClass<PFFunc1>);
static_assert(!cIsClass<PFFunc2>);
static_assert(!cIsClass<FFunc0Ref>);
static_assert(!cIsClass<FFunc1Ref>);
static_assert(!cIsClass<FFunc2Ref>);
static_assert(!cIsClass<FFunc0RRef>);
static_assert(!cIsClass<FFunc1RRef>);
static_assert(!cIsClass<FFunc2RRef>);
static_assert(!cIsClass<FFunc0Ptr>);
static_assert(!cIsClass<FFunc1Ptr>);
static_assert(!cIsClass<FFunc2Ptr>);
static_assert(!cIsClass<FFunc0PtrC>);
static_assert(!cIsClass<FFunc1PtrC>);
static_assert(!cIsClass<FFunc2PtrC>);
static_assert(!cIsClass<FMFunc0Ptr>);
static_assert(!cIsClass<FMFunc1Ptr>);
static_assert(!cIsClass<FMFunc2Ptr>);
static_assert(!cIsClass<FMFunc0PtrC>);
static_assert(!cIsClass<FMFunc1PtrC>);
static_assert(!cIsClass<FMFunc2PtrC>);
static_assert(!cIsClass<FMFunc0CPtr>);
static_assert(!cIsClass<FMFunc1CPtr>);
static_assert(!cIsClass<FMFunc2CPtr>);
static_assert(!cIsClass<FMFunc0CPtrC>);
static_assert(!cIsClass<FMFunc1CPtrC>);
static_assert(!cIsClass<FMFunc2CPtrC>);
static_assert(!cIsClass<PFFunc0El>);
static_assert(!cIsClass<PFFunc1El>);
static_assert(!cIsClass<PFFunc2El>);
static_assert(!cIsClass<FFunc0ElRef>);
static_assert(!cIsClass<FFunc1ElRef>);
static_assert(!cIsClass<FFunc2ElRef>);
static_assert(!cIsClass<FFunc0ElRRef>);
static_assert(!cIsClass<FFunc1ElRRef>);
static_assert(!cIsClass<FFunc2ElRRef>);
static_assert(!cIsClass<FFunc0ElPtr>);
static_assert(!cIsClass<FFunc1ElPtr>);
static_assert(!cIsClass<FFunc2ElPtr>);
static_assert(!cIsClass<FFunc0ElPtrC>);
static_assert(!cIsClass<FFunc1ElPtrC>);
static_assert(!cIsClass<FFunc2ElPtrC>);
static_assert(!cIsClass<FMFunc0ElPtr>);
static_assert(!cIsClass<FMFunc1ElPtr>);
static_assert(!cIsClass<FMFunc2ElPtr>);
static_assert(!cIsClass<FMFunc0ElPtrC>);
static_assert(!cIsClass<FMFunc1ElPtrC>);
static_assert(!cIsClass<FMFunc2ElPtrC>);
static_assert(!cIsClass<FMFunc0ElCPtr>);
static_assert(!cIsClass<FMFunc1ElCPtr>);
static_assert(!cIsClass<FMFunc2ElCPtr>);
static_assert(!cIsClass<FMFunc0ElCPtrC>);
static_assert(!cIsClass<FMFunc1ElCPtrC>);
static_assert(!cIsClass<FMFunc2ElCPtrC>);
static_assert(!cIsClass<CMPtr>);
static_assert(!cIsClass<CMCPtr>);
static_assert(!cIsClass<CMPtrC>);
static_assert(!cIsClass<CMCPtrC>);
static_assert(!cIsClass<CTestArray2>);
static_assert(!cIsClass<CTestArray2C>);
static_assert(!cIsClass<CTestArray>);
static_assert(!cIsClass<CTestArrayC>);
static_assert(!cIsClass<CTest2DArray2>);
static_assert(!cIsClass<CTest2DArray2C>);
static_assert(!cIsClass<CTest2DArray>);
static_assert(!cIsClass<CTest2DArrayC>);
static_assert(!cIsClass<CTest3DArray2>);
static_assert(!cIsClass<CTest3DArray2C>);
static_assert(!cIsClass<CTest3DArray>);
static_assert(!cIsClass<CTest3DArrayC>);
static_assert(!cIsClass<void *>);
static_assert(!cIsClass<void>);

