// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"


DMibTypeTraitsImplement_MemberTraits(m_Member);

DMibStaticCheck((	TCHasMember_m_Member<CTestUnion>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTestUnion1>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestUnion2>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestUnion3>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestUnion4>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestUnion5>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestUnion6>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTestUnion7>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct2>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct3>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct4>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct5>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct6>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct7>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct8>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct9>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct10>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct11>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct12>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct13>::mc_Value					));

DMibStaticCheck((	!TCHasMember_m_Member<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestClass1>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCHasMember_m_Member<CTestStruct1>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCHasMember_m_Member<const CTestClass1>::mc_Value				));
DMibStaticCheck((	!TCHasMember_m_Member<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCHasMember_m_Member<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	!TCHasMember_m_Member<ETestEnum>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<int>::mc_Value							));
DMibStaticCheck((	!TCHasMember_m_Member<CTestClass>::mc_Value							));
DMibStaticCheck((	!TCHasMember_m_Member<CTestC>::mc_Value							));
DMibStaticCheck((	!TCHasMember_m_Member<CTestPtr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CTestCPtr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CTestPtrC>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CMPtr>::mc_Value							));
DMibStaticCheck((	!TCHasMember_m_Member<CMCPtr>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CMPtrC>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CMCPtrC>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<CTestArray2>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTestArray2C>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTestArray>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTestArrayC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	!TCHasMember_m_Member<CTest2DArray>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	!TCHasMember_m_Member<CTest3DArray>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	!TCHasMember_m_Member<void *>::mc_Value						));
DMibStaticCheck((	!TCHasMember_m_Member<void>::mc_Value							));

DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestUnion>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestUnion1>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestUnion2>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestUnion3>::CType, int ()>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestUnion4>::CType, int (int)>::mc_Value					));

DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestUnion5>::CType, int ()>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestUnion6>::CType, int (int)>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestUnion7>::CType, void>::mc_Value					));


DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct2>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct3>::CType, int ()>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct4>::CType, int (int)>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct5>::CType, int ()>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct6>::CType, int (int)>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct7>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct8>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct9>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct10>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct11>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct12>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct13>::CType, int ()>::mc_Value					));


DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestClass0>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestClass1>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct0>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestStruct1>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<const CTestClass0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<const CTestClass1>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<const CTestStruct0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<const CTestStruct1>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<ETestEnum>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<int>::CType, void>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestClass>::CType, void>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestC>::CType, void>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestCPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestPtrC>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestCRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestRRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestCRRef>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<PFFunc0>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<PFFunc1>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<PFFunc2>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc0Ref>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc1Ref>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc2Ref>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc0RRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc1RRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc2RRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc0Ptr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc1Ptr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc2Ptr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc0PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc1PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc2PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc0Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc1Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc2Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc0PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc1PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc2PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc0CPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc1CPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc2CPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc0CPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc1CPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc2CPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<PFFunc0El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<PFFunc1El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<PFFunc2El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc0ElRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc1ElRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc2ElRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc0ElRRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc1ElRRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc2ElRRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc0ElPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc1ElPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc2ElPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc0ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc1ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FFunc2ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc0ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc1ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc2ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc0ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc1ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc2ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc0ElCPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc1ElCPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc2ElCPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc0ElCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc1ElCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<FMFunc2ElCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CMPtr>::CType, void>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CMCPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CMPtrC>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CMCPtrC>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestArray2>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestArray2C>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestArray>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTestArrayC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTest2DArray2>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTest2DArray2C>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTest2DArray>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTest2DArrayC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTest3DArray2>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTest3DArray2C>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTest3DArray>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<CTest3DArrayC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<void *>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberType_m_Member<void>::CType, void>::mc_Value							));



DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestUnion>::CType, int CTestUnion::*>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestUnion1>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestUnion2>::CType, int CTestUnion2::*>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestUnion3>::CType, int (CTestUnion3::*)()>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestUnion4>::CType, int (CTestUnion4::*)(int)>::mc_Value					));

DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestUnion5>::CType, int ()>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestUnion6>::CType, int (int)>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestUnion7>::CType, void>::mc_Value					));


DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct2>::CType, int CTestStruct2::*>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct3>::CType, int (CTestStruct3::*)()>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct4>::CType, int (CTestStruct4::*)(int)>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct5>::CType, int ()>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct6>::CType, int (int)>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct7>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct8>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct9>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct10>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct11>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct12>::CType, int CTestStruct2::*>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct13>::CType, int (CTestStruct3::*)()>::mc_Value					));


DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestClass0>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestClass1>::CType, int CTestClass1::*>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct0>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestStruct1>::CType, int CTestStruct1::*>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<const CTestClass0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<const CTestClass1>::CType, int CTestClass1::*>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<const CTestStruct0>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<const CTestStruct1>::CType, int CTestStruct1::*>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<ETestEnum>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<int>::CType, void>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestClass>::CType, void>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestC>::CType, void>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestCPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestPtrC>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestCRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestRRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestCRRef>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<PFFunc0>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<PFFunc1>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<PFFunc2>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc0Ref>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc1Ref>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc2Ref>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc0RRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc1RRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc2RRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc0Ptr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc1Ptr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc2Ptr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc0PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc1PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc2PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc0Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc1Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc2Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc0PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc1PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc2PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc0CPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc1CPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc2CPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc0CPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc1CPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc2CPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<PFFunc0El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<PFFunc1El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<PFFunc2El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc0ElRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc1ElRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc2ElRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc0ElRRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc1ElRRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc2ElRRef>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc0ElPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc1ElPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc2ElPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc0ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc1ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FFunc2ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc0ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc1ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc2ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc0ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc1ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc2ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc0ElCPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc1ElCPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc2ElCPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc0ElCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc1ElCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<FMFunc2ElCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CMPtr>::CType, void>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CMCPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CMPtrC>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CMCPtrC>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestArray2>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestArray2C>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestArray>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTestArrayC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTest2DArray2>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTest2DArray2C>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTest2DArray>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTest2DArrayC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTest3DArray2>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTest3DArray2C>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTest3DArray>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<CTest3DArrayC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<void *>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberFullType_m_Member<void>::CType, void>::mc_Value							));



DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestUnion>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestUnion1>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestUnion2>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestUnion3>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestUnion4>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestUnion5>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestUnion6>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestUnion7>::mc_Value					));

DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestStruct2>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestStruct3>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestStruct4>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestStruct5>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestStruct6>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestStruct7>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestStruct8>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestStruct9>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestStruct10>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestStruct11>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestStruct12>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallable_m_Member<CTestStruct13>::mc_Value					));

DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestClass0>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestClass1>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestStruct0>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestStruct1>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<const CTestClass0>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<const CTestClass1>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<ETestEnum>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<int>::mc_Value							));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestClass>::mc_Value							));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestC>::mc_Value							));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestPtr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CMPtr>::mc_Value							));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CMCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CMPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CMCPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestArray2>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestArray2C>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestArray>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTestArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTest2DArray>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTest3DArray>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<void *>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallable_m_Member<void>::mc_Value							));





DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestUnion, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestUnion1, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestUnion2, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestUnion3, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestUnion4, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestUnion5, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestUnion6, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestUnion7, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestUnion7, void (int)>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestUnion7, void (float)>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestUnion7, void (CTestUnion7)>::mc_Value					));

DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestStruct2, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestStruct3, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestStruct4, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestStruct5, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestStruct6, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestStruct7, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestStruct8, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestStruct9, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestStruct10, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestStruct11, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestStruct12, void ()>::mc_Value					));
DMibStaticCheck((	TCIsMemberCallableWith_m_Member<CTestStruct13, void ()>::mc_Value					));

DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestClass0, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestClass1, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestStruct0, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestStruct1, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<const CTestClass0, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<const CTestClass1, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<const CTestStruct0, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<const CTestStruct1, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<ETestEnum, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<int, void ()>::mc_Value							));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestClass, void ()>::mc_Value							));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestC, void ()>::mc_Value							));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestPtr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestCPtr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestPtrC, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestCPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestCRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestRRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestCRRef, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<PFFunc0, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<PFFunc1, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<PFFunc2, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc0Ref, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc1Ref, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc2Ref, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc0RRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc1RRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc2RRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc0Ptr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc1Ptr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc2Ptr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc0PtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc1PtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc2PtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc0Ptr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc1Ptr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc2Ptr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc0PtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc1PtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc2PtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc0CPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc1CPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc2CPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc0CPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc1CPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc2CPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<PFFunc0El, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<PFFunc1El, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<PFFunc2El, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc0ElRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc1ElRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc2ElRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc0ElRRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc1ElRRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc2ElRRef, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc0ElPtr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc1ElPtr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc2ElPtr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc0ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc1ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FFunc2ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc0ElPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc1ElPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc2ElPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc0ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc1ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc2ElPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc0ElCPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc1ElCPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc2ElCPtr, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc0ElCPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc1ElCPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<FMFunc2ElCPtrC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CMPtr, void ()>::mc_Value							));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CMCPtr, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CMPtrC, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CMCPtrC, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestArray2, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestArray2C, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestArray, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTestArrayC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTest2DArray2, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTest2DArray2C, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTest2DArray, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTest2DArrayC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTest3DArray2, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTest3DArray2C, void ()>::mc_Value				));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTest3DArray, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<CTest3DArrayC, void ()>::mc_Value					));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<void *, void ()>::mc_Value						));
DMibStaticCheck((	!TCIsMemberCallableWith_m_Member<void, void ()>::mc_Value							));
