// Copyright © Unbroken AB
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#include "Test_TypeTraits_TestTypes.h"

// Is Int
static_assert(!cIsInteger<ufp32>);

static_assert(cIsInteger<int16384>);
static_assert(cIsInteger<int8192>);
static_assert(cIsInteger<int4096>);
static_assert(cIsInteger<int2048>);
static_assert(cIsInteger<int1024>);
static_assert(cIsInteger<int512>);
static_assert(cIsInteger<int256>);
static_assert(cIsInteger<int160>);
static_assert(cIsInteger<int192>);
static_assert(cIsInteger<int128>);
static_assert(cIsInteger<int80>);
static_assert(cIsInteger<int96>);
static_assert(cIsInteger<int64>);
static_assert(cIsInteger<int32>);
static_assert(cIsInteger<int16>);
static_assert(cIsInteger<int8>);

static_assert(cIsInteger<aint>);
static_assert(cIsInteger<uaint>);
static_assert(cIsInteger<smint>);
static_assert(cIsInteger<umint>);

static_assert(cIsInteger<uint4096>);
static_assert(cIsInteger<uint2048>);
static_assert(cIsInteger<uint1024>);
static_assert(cIsInteger<uint512>);
static_assert(cIsInteger<uint256>);
static_assert(cIsInteger<uint160>);
static_assert(cIsInteger<uint192>);
static_assert(cIsInteger<uint128>);
static_assert(cIsInteger<uint80>);
static_assert(cIsInteger<uint96>);
static_assert(cIsInteger<uint64>);
static_assert(cIsInteger<uint32>);
static_assert(cIsInteger<uint16>);
static_assert(cIsInteger<uint8>);

static_assert(!cIsInteger<fp4096>);
static_assert(!cIsInteger<fp2048>);
static_assert(!cIsInteger<fp1024>);
static_assert(!cIsInteger<fp512>);
static_assert(!cIsInteger<fp256>);
static_assert(!cIsInteger<fp128>);
static_assert(!cIsInteger<fp80>);
static_assert(!cIsInteger<fp64>);
static_assert(!cIsInteger<fp32>);
static_assert(!cIsInteger<fp16>);
static_assert(!cIsInteger<fp8>);

static_assert(cIsInteger<const int16384>);
static_assert(cIsInteger<const int8192>);
static_assert(cIsInteger<const int4096>);
static_assert(cIsInteger<const int2048>);
static_assert(cIsInteger<const int1024>);
static_assert(cIsInteger<const int512>);
static_assert(cIsInteger<const int256>);
static_assert(cIsInteger<const int160>);
static_assert(cIsInteger<const int192>);
static_assert(cIsInteger<const int128>);
static_assert(cIsInteger<const int80>);
static_assert(cIsInteger<const int96>);
static_assert(cIsInteger<const int64>);
static_assert(cIsInteger<const int32>);
static_assert(cIsInteger<const int16>);
static_assert(cIsInteger<const int8>);

static_assert(cIsInteger<const uint4096>);
static_assert(cIsInteger<const uint2048>);
static_assert(cIsInteger<const uint1024>);
static_assert(cIsInteger<const uint512>);
static_assert(cIsInteger<const uint256>);
static_assert(cIsInteger<const uint160>);
static_assert(cIsInteger<const uint192>);
static_assert(cIsInteger<const uint128>);
static_assert(cIsInteger<const uint80>);
static_assert(cIsInteger<const uint96>);
static_assert(cIsInteger<const uint64>);
static_assert(cIsInteger<const uint32>);
static_assert(cIsInteger<const uint16>);
static_assert(cIsInteger<const uint8>);

static_assert(!cIsInteger<const fp4096>);
static_assert(!cIsInteger<const fp2048>);
static_assert(!cIsInteger<const fp1024>);
static_assert(!cIsInteger<const fp512>);
static_assert(!cIsInteger<const fp256>);
static_assert(!cIsInteger<const fp128>);
static_assert(!cIsInteger<const fp80>);
static_assert(!cIsInteger<const fp64>);
static_assert(!cIsInteger<const fp32>);
static_assert(!cIsInteger<const fp16>);
static_assert(!cIsInteger<const fp8>);

static_assert(!cIsInteger<CTestUnion>);
static_assert(!cIsInteger<CTestClass0>);
static_assert(!cIsInteger<CTestClass1>);
static_assert(!cIsInteger<CTestStruct0>);
static_assert(!cIsInteger<CTestStruct1>);
static_assert(!cIsInteger<ETestEnum>);
static_assert(!cIsInteger<CTestClass>);
static_assert(!cIsInteger<CTestC>);
static_assert(!cIsInteger<CTestPtr>);
static_assert(!cIsInteger<CTestCPtr>);
static_assert(!cIsInteger<CTestPtrC>);
static_assert(!cIsInteger<CTestCPtrC>);
static_assert(!cIsInteger<CTestRef>);
static_assert(!cIsInteger<CTestCRef>);
static_assert(!cIsInteger<CTestRRef>);
static_assert(!cIsInteger<CTestCRRef>);
static_assert(!cIsInteger<PFFunc0>);
static_assert(!cIsInteger<PFFunc1>);
static_assert(!cIsInteger<PFFunc2>);
static_assert(!cIsInteger<FFunc0Ref>);
static_assert(!cIsInteger<FFunc1Ref>);
static_assert(!cIsInteger<FFunc2Ref>);
static_assert(!cIsInteger<FFunc0RRef>);
static_assert(!cIsInteger<FFunc1RRef>);
static_assert(!cIsInteger<FFunc2RRef>);
static_assert(!cIsInteger<FFunc0Ptr>);
static_assert(!cIsInteger<FFunc1Ptr>);
static_assert(!cIsInteger<FFunc2Ptr>);
static_assert(!cIsInteger<FFunc0PtrC>);
static_assert(!cIsInteger<FFunc1PtrC>);
static_assert(!cIsInteger<FFunc2PtrC>);
static_assert(!cIsInteger<FMFunc0Ptr>);
static_assert(!cIsInteger<FMFunc1Ptr>);
static_assert(!cIsInteger<FMFunc2Ptr>);
static_assert(!cIsInteger<FMFunc0PtrC>);
static_assert(!cIsInteger<FMFunc1PtrC>);
static_assert(!cIsInteger<FMFunc2PtrC>);
static_assert(!cIsInteger<FMFunc0CPtr>);
static_assert(!cIsInteger<FMFunc1CPtr>);
static_assert(!cIsInteger<FMFunc2CPtr>);
static_assert(!cIsInteger<FMFunc0CPtrC>);
static_assert(!cIsInteger<FMFunc1CPtrC>);
static_assert(!cIsInteger<FMFunc2CPtrC>);
static_assert(!cIsInteger<PFFunc0El>);
static_assert(!cIsInteger<PFFunc1El>);
static_assert(!cIsInteger<PFFunc2El>);
static_assert(!cIsInteger<FFunc0ElRef>);
static_assert(!cIsInteger<FFunc1ElRef>);
static_assert(!cIsInteger<FFunc2ElRef>);
static_assert(!cIsInteger<FFunc0ElRRef>);
static_assert(!cIsInteger<FFunc1ElRRef>);
static_assert(!cIsInteger<FFunc2ElRRef>);
static_assert(!cIsInteger<FFunc0ElPtr>);
static_assert(!cIsInteger<FFunc1ElPtr>);
static_assert(!cIsInteger<FFunc2ElPtr>);
static_assert(!cIsInteger<FFunc0ElPtrC>);
static_assert(!cIsInteger<FFunc1ElPtrC>);
static_assert(!cIsInteger<FFunc2ElPtrC>);
static_assert(!cIsInteger<FMFunc0ElPtr>);
static_assert(!cIsInteger<FMFunc1ElPtr>);
static_assert(!cIsInteger<FMFunc2ElPtr>);
static_assert(!cIsInteger<FMFunc0ElPtrC>);
static_assert(!cIsInteger<FMFunc1ElPtrC>);
static_assert(!cIsInteger<FMFunc2ElPtrC>);
static_assert(!cIsInteger<FMFunc0ElCPtr>);
static_assert(!cIsInteger<FMFunc1ElCPtr>);
static_assert(!cIsInteger<FMFunc2ElCPtr>);
static_assert(!cIsInteger<FMFunc0ElCPtrC>);
static_assert(!cIsInteger<FMFunc1ElCPtrC>);
static_assert(!cIsInteger<FMFunc2ElCPtrC>);
static_assert(!cIsInteger<CMPtr>);
static_assert(!cIsInteger<CMCPtr>);
static_assert(!cIsInteger<CMPtrC>);
static_assert(!cIsInteger<CMCPtrC>);
static_assert(!cIsInteger<CTestArray2>);
static_assert(!cIsInteger<CTestArray2C>);
static_assert(!cIsInteger<CTestArray>);
static_assert(!cIsInteger<CTestArrayC>);
static_assert(!cIsInteger<CTest2DArray2>);
static_assert(!cIsInteger<CTest2DArray2C>);
static_assert(!cIsInteger<CTest2DArray>);
static_assert(!cIsInteger<CTest2DArrayC>);
static_assert(!cIsInteger<CTest3DArray2>);
static_assert(!cIsInteger<CTest3DArray2C>);
static_assert(!cIsInteger<CTest3DArray>);
static_assert(!cIsInteger<CTest3DArrayC>);
static_assert(!cIsInteger<void *>);
static_assert(!cIsInteger<void>);

// Is Float
static_assert(cIsFloat<ufp32>);

static_assert(!cIsFloat<int16384>);
static_assert(!cIsFloat<int8192>);
static_assert(!cIsFloat<int4096>);
static_assert(!cIsFloat<int2048>);
static_assert(!cIsFloat<int1024>);
static_assert(!cIsFloat<int512>);
static_assert(!cIsFloat<int256>);
static_assert(!cIsFloat<int160>);
static_assert(!cIsFloat<int192>);
static_assert(!cIsFloat<int128>);
static_assert(!cIsFloat<int80>);
static_assert(!cIsFloat<int96>);
static_assert(!cIsFloat<int64>);
static_assert(!cIsFloat<int32>);
static_assert(!cIsFloat<int16>);
static_assert(!cIsFloat<int8>);

static_assert(!cIsFloat<aint>);
static_assert(!cIsFloat<uaint>);
static_assert(!cIsFloat<smint>);
static_assert(!cIsFloat<umint>);

static_assert(!cIsFloat<uint4096>);
static_assert(!cIsFloat<uint2048>);
static_assert(!cIsFloat<uint1024>);
static_assert(!cIsFloat<uint512>);
static_assert(!cIsFloat<uint256>);
static_assert(!cIsFloat<uint160>);
static_assert(!cIsFloat<uint192>);
static_assert(!cIsFloat<uint128>);
static_assert(!cIsFloat<uint80>);
static_assert(!cIsFloat<uint96>);
static_assert(!cIsFloat<uint64>);
static_assert(!cIsFloat<uint32>);
static_assert(!cIsFloat<uint16>);
static_assert(!cIsFloat<uint8>);

static_assert(cIsFloat<fp4096>);
static_assert(cIsFloat<fp2048>);
static_assert(cIsFloat<fp1024>);
static_assert(cIsFloat<fp512>);
static_assert(cIsFloat<fp256>);
static_assert(cIsFloat<fp128>);
static_assert(cIsFloat<fp80>);
static_assert(cIsFloat<fp64>);
static_assert(cIsFloat<fp32>);
static_assert(cIsFloat<fp16>);
static_assert(cIsFloat<fp8>);


static_assert(!cIsFloat<const int16384>);
static_assert(!cIsFloat<const int8192>);
static_assert(!cIsFloat<const int4096>);
static_assert(!cIsFloat<const int2048>);
static_assert(!cIsFloat<const int1024>);
static_assert(!cIsFloat<const int512>);
static_assert(!cIsFloat<const int256>);
static_assert(!cIsFloat<const int160>);
static_assert(!cIsFloat<const int192>);
static_assert(!cIsFloat<const int128>);
static_assert(!cIsFloat<const int80>);
static_assert(!cIsFloat<const int96>);
static_assert(!cIsFloat<const int64>);
static_assert(!cIsFloat<const int32>);
static_assert(!cIsFloat<const int16>);
static_assert(!cIsFloat<const int8>);

static_assert(!cIsFloat<const uint4096>);
static_assert(!cIsFloat<const uint2048>);
static_assert(!cIsFloat<const uint1024>);
static_assert(!cIsFloat<const uint512>);
static_assert(!cIsFloat<const uint256>);
static_assert(!cIsFloat<const uint160>);
static_assert(!cIsFloat<const uint192>);
static_assert(!cIsFloat<const uint128>);
static_assert(!cIsFloat<const uint80>);
static_assert(!cIsFloat<const uint96>);
static_assert(!cIsFloat<const uint64>);
static_assert(!cIsFloat<const uint32>);
static_assert(!cIsFloat<const uint16>);
static_assert(!cIsFloat<const uint8>);

static_assert(cIsFloat<const fp4096>);
static_assert(cIsFloat<const fp2048>);
static_assert(cIsFloat<const fp1024>);
static_assert(cIsFloat<const fp512>);
static_assert(cIsFloat<const fp256>);
static_assert(cIsFloat<const fp128>);
static_assert(cIsFloat<const fp80>);
static_assert(cIsFloat<const fp64>);
static_assert(cIsFloat<const fp32>);
static_assert(cIsFloat<const fp16>);
static_assert(cIsFloat<const fp8>);

static_assert(!cIsFloat<CTestUnion>);
static_assert(!cIsFloat<CTestClass0>);
static_assert(!cIsFloat<CTestClass1>);
static_assert(!cIsFloat<CTestStruct0>);
static_assert(!cIsFloat<CTestStruct1>);
static_assert(!cIsFloat<ETestEnum>);
static_assert(!cIsFloat<CTestClass>);
static_assert(!cIsFloat<CTestC>);
static_assert(!cIsFloat<CTestPtr>);
static_assert(!cIsFloat<CTestCPtr>);
static_assert(!cIsFloat<CTestPtrC>);
static_assert(!cIsFloat<CTestCPtrC>);
static_assert(!cIsFloat<CTestRef>);
static_assert(!cIsFloat<CTestCRef>);
static_assert(!cIsFloat<CTestRRef>);
static_assert(!cIsFloat<CTestCRRef>);
static_assert(!cIsFloat<PFFunc0>);
static_assert(!cIsFloat<PFFunc1>);
static_assert(!cIsFloat<PFFunc2>);
static_assert(!cIsFloat<FFunc0Ref>);
static_assert(!cIsFloat<FFunc1Ref>);
static_assert(!cIsFloat<FFunc2Ref>);
static_assert(!cIsFloat<FFunc0RRef>);
static_assert(!cIsFloat<FFunc1RRef>);
static_assert(!cIsFloat<FFunc2RRef>);
static_assert(!cIsFloat<FFunc0Ptr>);
static_assert(!cIsFloat<FFunc1Ptr>);
static_assert(!cIsFloat<FFunc2Ptr>);
static_assert(!cIsFloat<FFunc0PtrC>);
static_assert(!cIsFloat<FFunc1PtrC>);
static_assert(!cIsFloat<FFunc2PtrC>);
static_assert(!cIsFloat<FMFunc0Ptr>);
static_assert(!cIsFloat<FMFunc1Ptr>);
static_assert(!cIsFloat<FMFunc2Ptr>);
static_assert(!cIsFloat<FMFunc0PtrC>);
static_assert(!cIsFloat<FMFunc1PtrC>);
static_assert(!cIsFloat<FMFunc2PtrC>);
static_assert(!cIsFloat<FMFunc0CPtr>);
static_assert(!cIsFloat<FMFunc1CPtr>);
static_assert(!cIsFloat<FMFunc2CPtr>);
static_assert(!cIsFloat<FMFunc0CPtrC>);
static_assert(!cIsFloat<FMFunc1CPtrC>);
static_assert(!cIsFloat<FMFunc2CPtrC>);
static_assert(!cIsFloat<PFFunc0El>);
static_assert(!cIsFloat<PFFunc1El>);
static_assert(!cIsFloat<PFFunc2El>);
static_assert(!cIsFloat<FFunc0ElRef>);
static_assert(!cIsFloat<FFunc1ElRef>);
static_assert(!cIsFloat<FFunc2ElRef>);
static_assert(!cIsFloat<FFunc0ElRRef>);
static_assert(!cIsFloat<FFunc1ElRRef>);
static_assert(!cIsFloat<FFunc2ElRRef>);
static_assert(!cIsFloat<FFunc0ElPtr>);
static_assert(!cIsFloat<FFunc1ElPtr>);
static_assert(!cIsFloat<FFunc2ElPtr>);
static_assert(!cIsFloat<FFunc0ElPtrC>);
static_assert(!cIsFloat<FFunc1ElPtrC>);
static_assert(!cIsFloat<FFunc2ElPtrC>);
static_assert(!cIsFloat<FMFunc0ElPtr>);
static_assert(!cIsFloat<FMFunc1ElPtr>);
static_assert(!cIsFloat<FMFunc2ElPtr>);
static_assert(!cIsFloat<FMFunc0ElPtrC>);
static_assert(!cIsFloat<FMFunc1ElPtrC>);
static_assert(!cIsFloat<FMFunc2ElPtrC>);
static_assert(!cIsFloat<FMFunc0ElCPtr>);
static_assert(!cIsFloat<FMFunc1ElCPtr>);
static_assert(!cIsFloat<FMFunc2ElCPtr>);
static_assert(!cIsFloat<FMFunc0ElCPtrC>);
static_assert(!cIsFloat<FMFunc1ElCPtrC>);
static_assert(!cIsFloat<FMFunc2ElCPtrC>);
static_assert(!cIsFloat<CMPtr>);
static_assert(!cIsFloat<CMCPtr>);
static_assert(!cIsFloat<CMPtrC>);
static_assert(!cIsFloat<CMCPtrC>);
static_assert(!cIsFloat<CTestArray2>);
static_assert(!cIsFloat<CTestArray2C>);
static_assert(!cIsFloat<CTestArray>);
static_assert(!cIsFloat<CTestArrayC>);
static_assert(!cIsFloat<CTest2DArray2>);
static_assert(!cIsFloat<CTest2DArray2C>);
static_assert(!cIsFloat<CTest2DArray>);
static_assert(!cIsFloat<CTest2DArrayC>);
static_assert(!cIsFloat<CTest3DArray2>);
static_assert(!cIsFloat<CTest3DArray2C>);
static_assert(!cIsFloat<CTest3DArray>);
static_assert(!cIsFloat<CTest3DArrayC>);
static_assert(!cIsFloat<void *>);
static_assert(!cIsFloat<void>);


// Is Float
static_assert(cIsArithmetic<ufp32>);

static_assert(cIsArithmetic<int16384>);
static_assert(cIsArithmetic<int8192>);
static_assert(cIsArithmetic<int4096>);
static_assert(cIsArithmetic<int2048>);
static_assert(cIsArithmetic<int1024>);
static_assert(cIsArithmetic<int512>);
static_assert(cIsArithmetic<int256>);
static_assert(cIsArithmetic<int160>);
static_assert(cIsArithmetic<int192>);
static_assert(cIsArithmetic<int128>);
static_assert(cIsArithmetic<int80>);
static_assert(cIsArithmetic<int96>);
static_assert(cIsArithmetic<int64>);
static_assert(cIsArithmetic<int32>);
static_assert(cIsArithmetic<int16>);
static_assert(cIsArithmetic<int8>);

static_assert(cIsArithmetic<aint>);
static_assert(cIsArithmetic<uaint>);
static_assert(cIsArithmetic<smint>);
static_assert(cIsArithmetic<umint>);

static_assert(cIsArithmetic<uint4096>);
static_assert(cIsArithmetic<uint2048>);
static_assert(cIsArithmetic<uint1024>);
static_assert(cIsArithmetic<uint512>);
static_assert(cIsArithmetic<uint256>);
static_assert(cIsArithmetic<uint160>);
static_assert(cIsArithmetic<uint192>);
static_assert(cIsArithmetic<uint128>);
static_assert(cIsArithmetic<uint80>);
static_assert(cIsArithmetic<uint96>);
static_assert(cIsArithmetic<uint64>);
static_assert(cIsArithmetic<uint32>);
static_assert(cIsArithmetic<uint16>);
static_assert(cIsArithmetic<uint8>);

static_assert(cIsArithmetic<fp4096>);
static_assert(cIsArithmetic<fp2048>);
static_assert(cIsArithmetic<fp1024>);
static_assert(cIsArithmetic<fp512>);
static_assert(cIsArithmetic<fp256>);
static_assert(cIsArithmetic<fp128>);
static_assert(cIsArithmetic<fp80>);
static_assert(cIsArithmetic<fp64>);
static_assert(cIsArithmetic<fp32>);
static_assert(cIsArithmetic<fp16>);
static_assert(cIsArithmetic<fp8>);

static_assert(cIsArithmetic<const int16384>);
static_assert(cIsArithmetic<const int8192>);
static_assert(cIsArithmetic<const int4096>);
static_assert(cIsArithmetic<const int2048>);
static_assert(cIsArithmetic<const int1024>);
static_assert(cIsArithmetic<const int512>);
static_assert(cIsArithmetic<const int256>);
static_assert(cIsArithmetic<const int160>);
static_assert(cIsArithmetic<const int192>);
static_assert(cIsArithmetic<const int128>);
static_assert(cIsArithmetic<const int80>);
static_assert(cIsArithmetic<const int96>);
static_assert(cIsArithmetic<const int64>);
static_assert(cIsArithmetic<const int32>);
static_assert(cIsArithmetic<const int16>);
static_assert(cIsArithmetic<const int8>);

static_assert(cIsArithmetic<const uint4096>);
static_assert(cIsArithmetic<const uint2048>);
static_assert(cIsArithmetic<const uint1024>);
static_assert(cIsArithmetic<const uint512>);
static_assert(cIsArithmetic<const uint256>);
static_assert(cIsArithmetic<const uint160>);
static_assert(cIsArithmetic<const uint192>);
static_assert(cIsArithmetic<const uint128>);
static_assert(cIsArithmetic<const uint80>);
static_assert(cIsArithmetic<const uint96>);
static_assert(cIsArithmetic<const uint64>);
static_assert(cIsArithmetic<const uint32>);
static_assert(cIsArithmetic<const uint16>);
static_assert(cIsArithmetic<const uint8>);

static_assert(cIsArithmetic<const fp4096>);
static_assert(cIsArithmetic<const fp2048>);
static_assert(cIsArithmetic<const fp1024>);
static_assert(cIsArithmetic<const fp512>);
static_assert(cIsArithmetic<const fp256>);
static_assert(cIsArithmetic<const fp128>);
static_assert(cIsArithmetic<const fp80>);
static_assert(cIsArithmetic<const fp64>);
static_assert(cIsArithmetic<const fp32>);
static_assert(cIsArithmetic<const fp16>);
static_assert(cIsArithmetic<const fp8>);

static_assert(!cIsArithmetic<CTestUnion>);
static_assert(!cIsArithmetic<CTestClass0>);
static_assert(!cIsArithmetic<CTestClass1>);
static_assert(!cIsArithmetic<CTestStruct0>);
static_assert(!cIsArithmetic<CTestStruct1>);
static_assert(!cIsArithmetic<ETestEnum>);
static_assert(!cIsArithmetic<CTestClass>);
static_assert(!cIsArithmetic<CTestC>);
static_assert(!cIsArithmetic<CTestPtr>);
static_assert(!cIsArithmetic<CTestCPtr>);
static_assert(!cIsArithmetic<CTestPtrC>);
static_assert(!cIsArithmetic<CTestCPtrC>);
static_assert(!cIsArithmetic<CTestRef>);
static_assert(!cIsArithmetic<CTestCRef>);
static_assert(!cIsArithmetic<CTestRRef>);
static_assert(!cIsArithmetic<CTestCRRef>);
static_assert(!cIsArithmetic<PFFunc0>);
static_assert(!cIsArithmetic<PFFunc1>);
static_assert(!cIsArithmetic<PFFunc2>);
static_assert(!cIsArithmetic<FFunc0Ref>);
static_assert(!cIsArithmetic<FFunc1Ref>);
static_assert(!cIsArithmetic<FFunc2Ref>);
static_assert(!cIsArithmetic<FFunc0RRef>);
static_assert(!cIsArithmetic<FFunc1RRef>);
static_assert(!cIsArithmetic<FFunc2RRef>);
static_assert(!cIsArithmetic<FFunc0Ptr>);
static_assert(!cIsArithmetic<FFunc1Ptr>);
static_assert(!cIsArithmetic<FFunc2Ptr>);
static_assert(!cIsArithmetic<FFunc0PtrC>);
static_assert(!cIsArithmetic<FFunc1PtrC>);
static_assert(!cIsArithmetic<FFunc2PtrC>);
static_assert(!cIsArithmetic<FMFunc0Ptr>);
static_assert(!cIsArithmetic<FMFunc1Ptr>);
static_assert(!cIsArithmetic<FMFunc2Ptr>);
static_assert(!cIsArithmetic<FMFunc0PtrC>);
static_assert(!cIsArithmetic<FMFunc1PtrC>);
static_assert(!cIsArithmetic<FMFunc2PtrC>);
static_assert(!cIsArithmetic<FMFunc0CPtr>);
static_assert(!cIsArithmetic<FMFunc1CPtr>);
static_assert(!cIsArithmetic<FMFunc2CPtr>);
static_assert(!cIsArithmetic<FMFunc0CPtrC>);
static_assert(!cIsArithmetic<FMFunc1CPtrC>);
static_assert(!cIsArithmetic<FMFunc2CPtrC>);
static_assert(!cIsArithmetic<PFFunc0El>);
static_assert(!cIsArithmetic<PFFunc1El>);
static_assert(!cIsArithmetic<PFFunc2El>);
static_assert(!cIsArithmetic<FFunc0ElRef>);
static_assert(!cIsArithmetic<FFunc1ElRef>);
static_assert(!cIsArithmetic<FFunc2ElRef>);
static_assert(!cIsArithmetic<FFunc0ElRRef>);
static_assert(!cIsArithmetic<FFunc1ElRRef>);
static_assert(!cIsArithmetic<FFunc2ElRRef>);
static_assert(!cIsArithmetic<FFunc0ElPtr>);
static_assert(!cIsArithmetic<FFunc1ElPtr>);
static_assert(!cIsArithmetic<FFunc2ElPtr>);
static_assert(!cIsArithmetic<FFunc0ElPtrC>);
static_assert(!cIsArithmetic<FFunc1ElPtrC>);
static_assert(!cIsArithmetic<FFunc2ElPtrC>);
static_assert(!cIsArithmetic<FMFunc0ElPtr>);
static_assert(!cIsArithmetic<FMFunc1ElPtr>);
static_assert(!cIsArithmetic<FMFunc2ElPtr>);
static_assert(!cIsArithmetic<FMFunc0ElPtrC>);
static_assert(!cIsArithmetic<FMFunc1ElPtrC>);
static_assert(!cIsArithmetic<FMFunc2ElPtrC>);
static_assert(!cIsArithmetic<FMFunc0ElCPtr>);
static_assert(!cIsArithmetic<FMFunc1ElCPtr>);
static_assert(!cIsArithmetic<FMFunc2ElCPtr>);
static_assert(!cIsArithmetic<FMFunc0ElCPtrC>);
static_assert(!cIsArithmetic<FMFunc1ElCPtrC>);
static_assert(!cIsArithmetic<FMFunc2ElCPtrC>);
static_assert(!cIsArithmetic<CMPtr>);
static_assert(!cIsArithmetic<CMCPtr>);
static_assert(!cIsArithmetic<CMPtrC>);
static_assert(!cIsArithmetic<CMCPtrC>);
static_assert(!cIsArithmetic<CTestArray2>);
static_assert(!cIsArithmetic<CTestArray2C>);
static_assert(!cIsArithmetic<CTestArray>);
static_assert(!cIsArithmetic<CTestArrayC>);
static_assert(!cIsArithmetic<CTest2DArray2>);
static_assert(!cIsArithmetic<CTest2DArray2C>);
static_assert(!cIsArithmetic<CTest2DArray>);
static_assert(!cIsArithmetic<CTest2DArrayC>);
static_assert(!cIsArithmetic<CTest3DArray2>);
static_assert(!cIsArithmetic<CTest3DArray2C>);
static_assert(!cIsArithmetic<CTest3DArray>);
static_assert(!cIsArithmetic<CTest3DArrayC>);
static_assert(!cIsArithmetic<void *>);
static_assert(!cIsArithmetic<void>);
