// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

static_assert(!cIsLValueReference<CTestUnion>);
static_assert(!cIsLValueReference<CTestClass0>);
static_assert(!cIsLValueReference<CTestClass1>);
static_assert(!cIsLValueReference<CTestStruct0>);
static_assert(!cIsLValueReference<CTestStruct1>);
static_assert(!cIsLValueReference<ETestEnum>);
static_assert(!cIsLValueReference<CTestClass>);
static_assert(!cIsLValueReference<CTestC>);
static_assert(!cIsLValueReference<CTestPtr>);
static_assert(!cIsLValueReference<CTestCPtr>);
static_assert(!cIsLValueReference<CTestPtrC>);
static_assert(!cIsLValueReference<CTestCPtrC>);
static_assert(cIsLValueReference<CTestRef>);
static_assert(cIsLValueReference<CTestCRef>);
static_assert(!cIsLValueReference<CTestRRef>);
static_assert(!cIsLValueReference<CTestCRRef>);
static_assert(!cIsLValueReference<PFFunc0>);
static_assert(!cIsLValueReference<PFFunc1>);
static_assert(!cIsLValueReference<PFFunc2>);
static_assert(cIsLValueReference<FFunc0Ref>);
static_assert(cIsLValueReference<FFunc1Ref>);
static_assert(cIsLValueReference<FFunc2Ref>);
static_assert(!cIsLValueReference<FFunc0RRef>);
static_assert(!cIsLValueReference<FFunc1RRef>);
static_assert(!cIsLValueReference<FFunc2RRef>);
static_assert(!cIsLValueReference<FFunc0Ptr>);
static_assert(!cIsLValueReference<FFunc1Ptr>);
static_assert(!cIsLValueReference<FFunc2Ptr>);
static_assert(!cIsLValueReference<FFunc0PtrC>);
static_assert(!cIsLValueReference<FFunc1PtrC>);
static_assert(!cIsLValueReference<FFunc2PtrC>);
static_assert(!cIsLValueReference<FMFunc0Ptr>);
static_assert(!cIsLValueReference<FMFunc1Ptr>);
static_assert(!cIsLValueReference<FMFunc2Ptr>);
static_assert(!cIsLValueReference<FMFunc0PtrC>);
static_assert(!cIsLValueReference<FMFunc1PtrC>);
static_assert(!cIsLValueReference<FMFunc2PtrC>);
static_assert(!cIsLValueReference<FMFunc0CPtr>);
static_assert(!cIsLValueReference<FMFunc1CPtr>);
static_assert(!cIsLValueReference<FMFunc2CPtr>);
static_assert(!cIsLValueReference<FMFunc0CPtrC>);
static_assert(!cIsLValueReference<FMFunc1CPtrC>);
static_assert(!cIsLValueReference<FMFunc2CPtrC>);
static_assert(!cIsLValueReference<PFFunc0El>);
static_assert(!cIsLValueReference<PFFunc1El>);
static_assert(!cIsLValueReference<PFFunc2El>);
static_assert(cIsLValueReference<FFunc0ElRef>);
static_assert(cIsLValueReference<FFunc1ElRef>);
static_assert(cIsLValueReference<FFunc2ElRef>);
static_assert(!cIsLValueReference<FFunc0ElRRef>);
static_assert(!cIsLValueReference<FFunc1ElRRef>);
static_assert(!cIsLValueReference<FFunc2ElRRef>);
static_assert(!cIsLValueReference<FFunc0ElPtr>);
static_assert(!cIsLValueReference<FFunc1ElPtr>);
static_assert(!cIsLValueReference<FFunc2ElPtr>);
static_assert(!cIsLValueReference<FFunc0ElPtrC>);
static_assert(!cIsLValueReference<FFunc1ElPtrC>);
static_assert(!cIsLValueReference<FFunc2ElPtrC>);
static_assert(!cIsLValueReference<FMFunc0ElPtr>);
static_assert(!cIsLValueReference<FMFunc1ElPtr>);
static_assert(!cIsLValueReference<FMFunc2ElPtr>);
static_assert(!cIsLValueReference<FMFunc0ElPtrC>);
static_assert(!cIsLValueReference<FMFunc1ElPtrC>);
static_assert(!cIsLValueReference<FMFunc2ElPtrC>);
static_assert(!cIsLValueReference<FMFunc0ElCPtr>);
static_assert(!cIsLValueReference<FMFunc1ElCPtr>);
static_assert(!cIsLValueReference<FMFunc2ElCPtr>);
static_assert(!cIsLValueReference<FMFunc0ElCPtrC>);
static_assert(!cIsLValueReference<FMFunc1ElCPtrC>);
static_assert(!cIsLValueReference<FMFunc2ElCPtrC>);
static_assert(!cIsLValueReference<CMPtr>);
static_assert(!cIsLValueReference<CMCPtr>);
static_assert(!cIsLValueReference<CMPtrC>);
static_assert(!cIsLValueReference<CMCPtrC>);
static_assert(!cIsLValueReference<CTestArray2>);
static_assert(!cIsLValueReference<CTestArray2C>);
static_assert(!cIsLValueReference<CTestArray>);
static_assert(!cIsLValueReference<CTestArrayC>);
static_assert(!cIsLValueReference<CTest2DArray2>);
static_assert(!cIsLValueReference<CTest2DArray2C>);
static_assert(!cIsLValueReference<CTest2DArray>);
static_assert(!cIsLValueReference<CTest2DArrayC>);
static_assert(!cIsLValueReference<CTest3DArray2>);
static_assert(!cIsLValueReference<CTest3DArray2C>);
static_assert(!cIsLValueReference<CTest3DArray>);
static_assert(!cIsLValueReference<CTest3DArrayC>);
static_assert(!cIsLValueReference<void *>);
static_assert(!cIsLValueReference<void>);

static_assert(cIsSame<TCAddLValueReference<CTestUnion>, CTestUnion &>);
static_assert(cIsSame<TCAddLValueReference<CTestClass0>, CTestClass0 &>);
static_assert(cIsSame<TCAddLValueReference<CTestClass1>, CTestClass1 &>);
static_assert(cIsSame<TCAddLValueReference<CTestStruct0>, CTestStruct0 &>);
static_assert(cIsSame<TCAddLValueReference<CTestStruct1>, CTestStruct1 &>);
static_assert(cIsSame<TCAddLValueReference<ETestEnum>, ETestEnum &>);
static_assert(cIsSame<TCAddLValueReference<CTestClass>, CTestClass &>);
static_assert(cIsSame<TCAddLValueReference<CTestC>, CTestC &>);
static_assert(cIsSame<TCAddLValueReference<CTestPtr>, CTestPtr &>);
static_assert(cIsSame<TCAddLValueReference<CTestCPtr>, CTestCPtr &>);
static_assert(cIsSame<TCAddLValueReference<CTestPtrC>, CTestPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CTestCPtrC>, CTestCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CTestRef>, CTestRef>);
static_assert(cIsSame<TCAddLValueReference<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCAddLValueReference<CTestRRef>, CTestRef>);
static_assert(cIsSame<TCAddLValueReference<CTestCRRef>, CTestCRef>);
static_assert(cIsSame<TCAddLValueReference<PFFunc0>, PFFunc0 &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc1>, PFFunc1 &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc2>, PFFunc2 &>);
static_assert(cIsSame<TCAddLValueReference<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc0RRef>, FFunc0Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc1RRef>, FFunc1Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc2RRef>, FFunc2Ref>);
static_assert(cIsSame<TCAddLValueReference<FFunc0Ptr>, FFunc0Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc1Ptr>, FFunc1Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc2Ptr>, FFunc2Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc0PtrC>, FFunc0PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FFunc1PtrC>, FFunc1PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FFunc2PtrC>, FFunc2PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0Ptr>, FMFunc0Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1Ptr>, FMFunc1Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2Ptr>, FMFunc2Ptr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0PtrC>, FMFunc0PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1PtrC>, FMFunc1PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2PtrC>, FMFunc2PtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0CPtr>, FMFunc0CPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1CPtr>, FMFunc1CPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2CPtr>, FMFunc2CPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0CPtrC>, FMFunc0CPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1CPtrC>, FMFunc1CPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2CPtrC>, FMFunc2CPtrC &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc0El>, PFFunc0El &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc1El>, PFFunc1El &>);
static_assert(cIsSame<TCAddLValueReference<PFFunc2El>, PFFunc2El &>);
static_assert(cIsSame<TCAddLValueReference<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc0ElRRef>, FFunc0ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc1ElRRef>, FFunc1ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc2ElRRef>, FFunc2ElRef>);
static_assert(cIsSame<TCAddLValueReference<FFunc0ElPtr>, FFunc0ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc1ElPtr>, FFunc1ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc2ElPtr>, FFunc2ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FFunc0ElPtrC>, FFunc0ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FFunc1ElPtrC>, FFunc1ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FFunc2ElPtrC>, FFunc2ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0ElPtr>, FMFunc0ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1ElPtr>, FMFunc1ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2ElPtr>, FMFunc2ElPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0ElPtrC>, FMFunc0ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1ElPtrC>, FMFunc1ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2ElPtrC>, FMFunc2ElPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0ElCPtr>, FMFunc0ElCPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1ElCPtr>, FMFunc1ElCPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2ElCPtr>, FMFunc2ElCPtr &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc0ElCPtrC>, FMFunc0ElCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc1ElCPtrC>, FMFunc1ElCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<FMFunc2ElCPtrC>, FMFunc2ElCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CMPtr>, CMPtr &>);
static_assert(cIsSame<TCAddLValueReference<CMCPtr>, CMCPtr &>);
static_assert(cIsSame<TCAddLValueReference<CMPtrC>, CMPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CMCPtrC>, CMCPtrC &>);
static_assert(cIsSame<TCAddLValueReference<CTestArray2>, CTestArray2 &>);
static_assert(cIsSame<TCAddLValueReference<CTestArray2C>, CTestArray2C &>);
static_assert(cIsSame<TCAddLValueReference<CTestArray>, CTestArray &>);
static_assert(cIsSame<TCAddLValueReference<CTestArrayC>, CTestArrayC &>);
static_assert(cIsSame<TCAddLValueReference<CTest2DArray2>, CTest2DArray2 &>);
static_assert(cIsSame<TCAddLValueReference<CTest2DArray2C>, CTest2DArray2C &>);
static_assert(cIsSame<TCAddLValueReference<CTest2DArray>, CTest2DArray &>);
static_assert(cIsSame<TCAddLValueReference<CTest2DArrayC>, CTest2DArrayC &>);
static_assert(cIsSame<TCAddLValueReference<CTest3DArray2>, CTest3DArray2 &>);
static_assert(cIsSame<TCAddLValueReference<CTest3DArray2C>, CTest3DArray2C &>);
static_assert(cIsSame<TCAddLValueReference<CTest3DArray>, CTest3DArray &>);
static_assert(cIsSame<TCAddLValueReference<CTest3DArrayC>, CTest3DArrayC &>);
static_assert(cIsSame<TCAddLValueReference<void *>, void *&>);
static_assert(cIsSame<TCAddLValueReference<void>, void>);

// Remove pointer
static_assert(cIsSame<TCRemoveLValueReference<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCRemoveLValueReference<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCRemoveLValueReference<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCRemoveLValueReference<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCRemoveLValueReference<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCRemoveLValueReference<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCRemoveLValueReference<CTestClass>, CTestClass>);
static_assert(cIsSame<TCRemoveLValueReference<CTestC>, CTestC>);
static_assert(cIsSame<TCRemoveLValueReference<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCRemoveLValueReference<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCRemoveLValueReference<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<CTestRef>, CTestClass>);
static_assert(cIsSame<TCRemoveLValueReference<CTestCRef>, CTestC>);
static_assert(cIsSame<TCRemoveLValueReference<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCRemoveLValueReference<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCRemoveLValueReference<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCRemoveLValueReference<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCRemoveLValueReference<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc0Ref>, PFFunc0>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc1Ref>, PFFunc1>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc2Ref>, PFFunc2>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCRemoveLValueReference<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCRemoveLValueReference<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc0ElRef>, PFFunc0El>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc1ElRef>, PFFunc1El>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc2ElRef>, PFFunc2El>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<CMPtr>, CMPtr>);
static_assert(cIsSame<TCRemoveLValueReference<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCRemoveLValueReference<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCRemoveLValueReference<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCRemoveLValueReference<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCRemoveLValueReference<CTestArray>, CTestArray>);
static_assert(cIsSame<TCRemoveLValueReference<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCRemoveLValueReference<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCRemoveLValueReference<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCRemoveLValueReference<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCRemoveLValueReference<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCRemoveLValueReference<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCRemoveLValueReference<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCRemoveLValueReference<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCRemoveLValueReference<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCRemoveLValueReference<void *>, void *>);
static_assert(cIsSame<TCRemoveLValueReference<void *&>, void *>);
static_assert(cIsSame<TCRemoveLValueReference<void>, void>);
