// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

// Object
static_assert(cIsUnion<CTestUnion>);
static_assert(!cIsUnion<CTestClass0>);
static_assert(!cIsUnion<CTestClass1>);
static_assert(!cIsUnion<CTestStruct0>);
static_assert(!cIsUnion<CTestStruct1>);
static_assert(!cIsUnion<ETestEnum>);
static_assert(!cIsUnion<CTestClass>);
static_assert(!cIsUnion<CTestC>);
static_assert(!cIsUnion<CTestPtr>);
static_assert(!cIsUnion<CTestCPtr>);
static_assert(!cIsUnion<CTestPtrC>);
static_assert(!cIsUnion<CTestCPtrC>);
static_assert(!cIsUnion<CTestRef>);
static_assert(!cIsUnion<CTestCRef>);
static_assert(!cIsUnion<CTestRRef>);
static_assert(!cIsUnion<CTestCRRef>);
static_assert(!cIsUnion<PFFunc0>);
static_assert(!cIsUnion<PFFunc1>);
static_assert(!cIsUnion<PFFunc2>);
static_assert(!cIsUnion<FFunc0Ref>);
static_assert(!cIsUnion<FFunc1Ref>);
static_assert(!cIsUnion<FFunc2Ref>);
static_assert(!cIsUnion<FFunc0RRef>);
static_assert(!cIsUnion<FFunc1RRef>);
static_assert(!cIsUnion<FFunc2RRef>);
static_assert(!cIsUnion<FFunc0Ptr>);
static_assert(!cIsUnion<FFunc1Ptr>);
static_assert(!cIsUnion<FFunc2Ptr>);
static_assert(!cIsUnion<FFunc0PtrC>);
static_assert(!cIsUnion<FFunc1PtrC>);
static_assert(!cIsUnion<FFunc2PtrC>);
static_assert(!cIsUnion<FMFunc0Ptr>);
static_assert(!cIsUnion<FMFunc1Ptr>);
static_assert(!cIsUnion<FMFunc2Ptr>);
static_assert(!cIsUnion<FMFunc0PtrC>);
static_assert(!cIsUnion<FMFunc1PtrC>);
static_assert(!cIsUnion<FMFunc2PtrC>);
static_assert(!cIsUnion<FMFunc0CPtr>);
static_assert(!cIsUnion<FMFunc1CPtr>);
static_assert(!cIsUnion<FMFunc2CPtr>);
static_assert(!cIsUnion<FMFunc0CPtrC>);
static_assert(!cIsUnion<FMFunc1CPtrC>);
static_assert(!cIsUnion<FMFunc2CPtrC>);
static_assert(!cIsUnion<PFFunc0El>);
static_assert(!cIsUnion<PFFunc1El>);
static_assert(!cIsUnion<PFFunc2El>);
static_assert(!cIsUnion<FFunc0ElRef>);
static_assert(!cIsUnion<FFunc1ElRef>);
static_assert(!cIsUnion<FFunc2ElRef>);
static_assert(!cIsUnion<FFunc0ElRRef>);
static_assert(!cIsUnion<FFunc1ElRRef>);
static_assert(!cIsUnion<FFunc2ElRRef>);
static_assert(!cIsUnion<FFunc0ElPtr>);
static_assert(!cIsUnion<FFunc1ElPtr>);
static_assert(!cIsUnion<FFunc2ElPtr>);
static_assert(!cIsUnion<FFunc0ElPtrC>);
static_assert(!cIsUnion<FFunc1ElPtrC>);
static_assert(!cIsUnion<FFunc2ElPtrC>);
static_assert(!cIsUnion<FMFunc0ElPtr>);
static_assert(!cIsUnion<FMFunc1ElPtr>);
static_assert(!cIsUnion<FMFunc2ElPtr>);
static_assert(!cIsUnion<FMFunc0ElPtrC>);
static_assert(!cIsUnion<FMFunc1ElPtrC>);
static_assert(!cIsUnion<FMFunc2ElPtrC>);
static_assert(!cIsUnion<FMFunc0ElCPtr>);
static_assert(!cIsUnion<FMFunc1ElCPtr>);
static_assert(!cIsUnion<FMFunc2ElCPtr>);
static_assert(!cIsUnion<FMFunc0ElCPtrC>);
static_assert(!cIsUnion<FMFunc1ElCPtrC>);
static_assert(!cIsUnion<FMFunc2ElCPtrC>);
static_assert(!cIsUnion<CMPtr>);
static_assert(!cIsUnion<CMCPtr>);
static_assert(!cIsUnion<CMPtrC>);
static_assert(!cIsUnion<CMCPtrC>);
static_assert(!cIsUnion<CTestArray2>);
static_assert(!cIsUnion<CTestArray2C>);
static_assert(!cIsUnion<CTestArray>);
static_assert(!cIsUnion<CTestArrayC>);
static_assert(!cIsUnion<CTest2DArray2>);
static_assert(!cIsUnion<CTest2DArray2C>);
static_assert(!cIsUnion<CTest2DArray>);
static_assert(!cIsUnion<CTest2DArrayC>);
static_assert(!cIsUnion<CTest3DArray2>);
static_assert(!cIsUnion<CTest3DArray2C>);
static_assert(!cIsUnion<CTest3DArray>);
static_assert(!cIsUnion<CTest3DArrayC>);
static_assert(!cIsUnion<void *>);
static_assert(!cIsUnion<void>);


