// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NTrivial
{

	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialAssignment>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialAssignmentInt>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialAssignmentBoth>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialAssignmentDerived>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialAssignmentDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	!TCHasTrivialCopyConstructor<CNonTrivialCopy>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialCopyInt>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialCopyConstructor<CNonTrivialCopyBoth>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialCopyConstructor<CNonTrivialCopyDerived>::mc_Value						));
	DMibStaticCheck((	!TCHasTrivialCopyConstructor<CNonTrivialCopyDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialConstruct>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialConstructDerived>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CNonTrivialConstructDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasTrivialCopyConstructor<CTrivial>::mc_Value						));

	DMibStaticCheck((	!TCHasTrivialCopyConstructor<CTestClassVirtual>::mc_Value						));

}

// Void
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestUnion>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	TCHasTrivialCopyConstructor<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCHasTrivialCopyConstructor<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCHasTrivialCopyConstructor<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCHasTrivialCopyConstructor<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	TCHasTrivialCopyConstructor<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCHasTrivialCopyConstructor<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	TCHasTrivialCopyConstructor<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCHasTrivialCopyConstructor<ETestEnum>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<int>::mc_Value							));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestClass>::mc_Value							));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestC>::mc_Value							));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestV>::mc_Value							));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestVRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCVRef>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestRRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCRRef>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestVRRef>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCHasTrivialCopyConstructor<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialCopyConstructor<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialCopyConstructor<PFFunc2>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2RRef>::mc_Value						));
#endif
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCHasTrivialCopyConstructor<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialCopyConstructor<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCHasTrivialCopyConstructor<PFFunc2El>::mc_Value						));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2ElRRef>::mc_Value						));
#endif
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMPtr>::mc_Value							));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMCPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestArray2C>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestArray2V>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest2DArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest3DArray>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasTrivialCopyConstructor<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasTrivialCopyConstructor<void *>::mc_Value						));
DMibStaticCheck((	TCHasTrivialCopyConstructor<void>::mc_Value							));

