// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NNothrow
{
	//
	DMibStaticCheck((	!TCHasNothrowAssignmentOperator<CThrowsAssignment>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsAssignmentInt>::mc_Value						));
	DMibStaticCheck((	!TCHasNothrowAssignmentOperator<CThrowsAssignmentBoth>::mc_Value						));
#ifndef DMibCompiler_GCC
	DMibStaticCheck((	!TCHasNothrowAssignmentOperator<CThrowsAssignmentDerived>::mc_Value						));
#endif
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsAssignmentDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CNothrow>::mc_Value						));

	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsCopy>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsCopyInt>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsCopyBoth>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsCopyDerived>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsCopyDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CNothrow>::mc_Value						));

	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsConstruct>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsConstructDerived>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CThrowsConstructDerivedOverride>::mc_Value						));
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CNothrow>::mc_Value						));
	
	DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestClassVirtual>::mc_Value						));


}

// Void
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestUnion>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestClass0>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestClass1>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestStruct0>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestStruct1>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<const CTestClass0>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<const CTestClass1>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<ETestEnum>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<int>::mc_Value							));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestClass>::mc_Value							));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestC>::mc_Value							));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestV>::mc_Value							));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestVPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestBase>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<CTestCRef>::mc_Value						));
#ifndef DCompiler_MSVC
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestVRef>::mc_Value						));
#endif
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<CTestCVRef>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<CTestCRRef>::mc_Value					));
#ifndef DCompiler_MSVC
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestVRRef>::mc_Value					));
#endif
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCHasNothrowAssignmentOperator<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMPtr>::mc_Value							));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMCPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMVPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMCVPtr>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMCPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestArray2>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestArray2C>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestArray2V>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestArray>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestArrayC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestArrayV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest2DArray>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest3DArray>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<void *>::mc_Value						));
DMibStaticCheck((	TCHasNothrowAssignmentOperator<void>::mc_Value							));

