// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck(	(sizeof(ch8) == 1)	);
DMibStaticCheck(	(sizeof(ch16) == 2)	);
DMibStaticCheck(	(sizeof(ch32) == 4)	);

#ifdef DMibPSignedType_ch8
	DMibStaticCheck(int32(ch8(uint8(0xffu))) == -1);
#else
	DMibStaticCheck(int32(ch8(uint8(0xffu))) == 0xffu);
#endif

#ifdef DMibPSignedType_ch16
	DMibStaticCheck(int32(ch16(uint16(0xffffu))) == -1);
#else
	DMibStaticCheck(int32(ch16(uint16(0xffffu))) == 0xffffu);
#endif

#ifdef DMibPSignedType_ch32
	DMibStaticCheck(int64(ch32(uint32(0xffffffffu))) == -1);
#else
	DMibStaticCheck(int64(ch32(uint32(0xffffffffu))) == 0xffffffffu);
#endif

// Is Signed
DMibStaticCheck((	!TCIsSigned<ufp32>::mc_Value	));

	
DMibStaticCheck((	TCIsSigned<int8192>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int4096>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int2048>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int1024>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int512>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int256>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int160>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int128>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int80>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int64>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int32>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int16>::mc_Value	));
DMibStaticCheck((	TCIsSigned<int8>::mc_Value	));

DMibStaticCheck((	TCIsSigned<aint>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<uaint>::mc_Value	));
DMibStaticCheck((	TCIsSigned<smint>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<mint>::mc_Value		));

DMibStaticCheck((	!TCIsSigned<uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint512>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint256>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint160>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint128>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint80>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint64>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint32>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint16>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<uint8>::mc_Value	));

DMibStaticCheck((	TCIsSigned<fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp512>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp256>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp128>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp80>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp64>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp32>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp16>::mc_Value	));
DMibStaticCheck((	TCIsSigned<fp8>::mc_Value	));

DMibStaticCheck((	TCIsSigned<const int8192>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int4096>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int2048>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int1024>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int512>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int256>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int160>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int128>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int80>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int64>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int32>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int16>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const int8>::mc_Value	));

DMibStaticCheck((	!TCIsSigned<const uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint512>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint256>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint160>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint128>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint80>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint64>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint32>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint16>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const uint8>::mc_Value	));

DMibStaticCheck((	TCIsSigned<const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp512>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp256>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp128>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp80>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp64>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp32>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp16>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const fp8>::mc_Value	));

DMibStaticCheck((	TCIsSigned<volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile int8>::mc_Value	));

DMibStaticCheck((	!TCIsSigned<volatile uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint512>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint256>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint160>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint128>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint80>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint64>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint32>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint16>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsSigned<volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsSigned<volatile fp8>::mc_Value	));

DMibStaticCheck((	TCIsSigned<const volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile int8>::mc_Value	));

DMibStaticCheck((	!TCIsSigned<const volatile uint4096>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint2048>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint1024>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint512>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint256>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint160>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint128>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint80>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint64>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint32>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint16>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<const volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsSigned<const volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsSigned<const volatile fp8>::mc_Value	));

DMibStaticCheck((	!TCIsSigned<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsSigned<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestCV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestVRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestCVRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestCVRRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<PFFunc2>::mc_Value			));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	!TCIsSigned<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2RRef>::mc_Value		));
#endif
DMibStaticCheck((	!TCIsSigned<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2PtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2VPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<PFFunc2El>::mc_Value			));
#if !defined(DCompiler_MSVC) || DMibCompilerVersion >= 1700
DMibStaticCheck((	!TCIsSigned<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2ElRRef>::mc_Value		));
#endif
DMibStaticCheck((	!TCIsSigned<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsSigned<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMCVPtr>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMCVPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMCPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMCVPtrV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMCPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CMCVPtrCV>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestArray2V>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestArray2CV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTestArrayCV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	!TCIsSigned<CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	!TCIsSigned<void *>::mc_Value			));
DMibStaticCheck((	!TCIsSigned<void>::mc_Value				));

// Types
DMibStaticCheck((	TCIsSame<TCSigned<int8192>::CType, int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int4096>::CType, int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int2048>::CType, int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int1024>::CType, int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int512>::CType, int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int256>::CType, int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int160>::CType, int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int128>::CType, int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int80>::CType, int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int64>::CType, int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int32>::CType, int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int16>::CType, int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<int8>::CType, int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<aint>::CType, aint>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uaint>::CType, aint>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<smint>::CType, smint>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<mint>::CType, smint>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<uint8192>::CType, int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint4096>::CType, int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint2048>::CType, int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint1024>::CType, int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint512>::CType, int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint256>::CType, int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint160>::CType, int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint128>::CType, int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint80>::CType, int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint64>::CType, int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint32>::CType, int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint16>::CType, int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<uint8>::CType, int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<fp4096>::CType, fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp2048>::CType, fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp1024>::CType, fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp512>::CType, fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp256>::CType, fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp128>::CType, fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp80>::CType, fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp64>::CType, fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp32>::CType, fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp16>::CType, fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<fp8>::CType, fp8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<const int8192>::CType, const int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int4096>::CType, const int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int2048>::CType, const int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int1024>::CType, const int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int512>::CType, const int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int256>::CType, const int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int160>::CType, const int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int128>::CType, const int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int80>::CType, const int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int64>::CType, const int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int32>::CType, const int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int16>::CType, const int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const int8>::CType, const int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<const uint8192>::CType, const int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint4096>::CType, const int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint2048>::CType, const int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint1024>::CType, const int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint512>::CType, const int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint256>::CType, const int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint160>::CType, const int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint128>::CType, const int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint80>::CType, const int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint64>::CType, const int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint32>::CType, const int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint16>::CType, const int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const uint8>::CType, const int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<const fp4096>::CType, const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp2048>::CType, const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp1024>::CType, const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp512>::CType, const fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp256>::CType, const fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp128>::CType, const fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp80>::CType, const fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp64>::CType, const fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp32>::CType, const fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp16>::CType, const fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const fp8>::CType, const fp8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<volatile int8192>::CType, volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int4096>::CType, volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int2048>::CType, volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int1024>::CType, volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int512>::CType, volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int256>::CType, volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int160>::CType, volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int128>::CType, volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int80>::CType, volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int64>::CType, volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int32>::CType, volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int16>::CType, volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile int8>::CType, volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<volatile uint8192>::CType, volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint4096>::CType, volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint2048>::CType, volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint1024>::CType, volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint512>::CType, volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint256>::CType, volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint160>::CType, volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint128>::CType, volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint80>::CType, volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint64>::CType, volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint32>::CType, volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint16>::CType, volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile uint8>::CType, volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<volatile fp4096>::CType, volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp2048>::CType, volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp1024>::CType, volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp512>::CType, volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp256>::CType, volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp128>::CType, volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp80>::CType, volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp64>::CType, volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp32>::CType, volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp16>::CType, volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<volatile fp8>::CType, volatile fp8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<const volatile int8192>::CType, const volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int4096>::CType, const volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int2048>::CType, const volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int1024>::CType, const volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int512>::CType, const volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int256>::CType, const volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int160>::CType, const volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int128>::CType, const volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int80>::CType, const volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int64>::CType, const volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int32>::CType, const volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int16>::CType, const volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile int8>::CType, const volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint8192>::CType, const volatile int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint4096>::CType, const volatile int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint2048>::CType, const volatile int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint1024>::CType, const volatile int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint512>::CType, const volatile int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint256>::CType, const volatile int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint160>::CType, const volatile int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint128>::CType, const volatile int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint80>::CType, const volatile int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint64>::CType, const volatile int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint32>::CType, const volatile int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint16>::CType, const volatile int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile uint8>::CType, const volatile int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp4096>::CType, const volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp2048>::CType, const volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp1024>::CType, const volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp512>::CType, const volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp256>::CType, const volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp128>::CType, const volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp80>::CType, const volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp64>::CType, const volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp32>::CType, const volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp16>::CType, const volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<const volatile fp8>::CType, const volatile fp8>::mc_Value	));



DMibStaticCheck((	TCIsSame<TCSigned<CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCSigned<CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CTestV>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCV>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestVPtr>::CType, CTestVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCVPtr>::CType, CTestCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestVPtrC>::CType, CTestVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCVPtrC>::CType, CTestCVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestPtrV>::CType, CTestPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCPtrV>::CType, CTestCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestVPtrV>::CType, CTestVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCVPtrV>::CType, CTestCVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestPtrCV>::CType, CTestPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCPtrCV>::CType, CTestCPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestVPtrCV>::CType, CTestVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCVPtrCV>::CType, CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestVRef>::CType, CTestVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCVRef>::CType, CTestCVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestVRRef>::CType, CTestVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestCVRRef>::CType, CTestCVRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<PFFunc2>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0PtrV>::CType, FFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1PtrV>::CType, FFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2PtrV>::CType, FFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0PtrCV>::CType, FFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1PtrCV>::CType, FFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2PtrCV>::CType, FFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0PtrV>::CType, FMFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1PtrV>::CType, FMFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2PtrV>::CType, FMFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0PtrCV>::CType, FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1PtrCV>::CType, FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2PtrCV>::CType, FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0CPtrV>::CType, FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1CPtrV>::CType, FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2CPtrV>::CType, FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0VPtr>::CType, FMFunc0VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1VPtr>::CType, FMFunc1VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2VPtr>::CType, FMFunc2VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0VPtrC>::CType, FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1VPtrC>::CType, FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2VPtrC>::CType, FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0VPtrV>::CType, FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1VPtrV>::CType, FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2VPtrV>::CType, FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0CVPtr>::CType, FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1CVPtr>::CType, FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2CVPtr>::CType, FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<PFFunc2El>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0ElPtrV>::CType, FFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1ElPtrV>::CType, FFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2ElPtrV>::CType, FFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCSigned<CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMVPtr>::CType, CMVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMCVPtr>::CType, CMCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMVPtrC>::CType, CMVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMCVPtrC>::CType, CMCVPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CMPtrV>::CType, CMPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMCPtrV>::CType, CMCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMVPtrV>::CType, CMVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMCVPtrV>::CType, CMCVPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CMPtrCV>::CType, CMPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<CMCPtrCV>::CType, CMCPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CMVPtrCV>::CType, CMVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CMCVPtrCV>::CType, CMCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCSigned<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestArray2C>::CType, CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTestArray2V>::CType, CTestArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTestArray2CV>::CType, CTestArray2CV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTestArray>::CType, CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestArrayV>::CType, CTestArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCSigned<CTestArrayCV>::CType, CTestArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<CTest2DArray2V>::CType, CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<CTest2DArray2CV>::CType, CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<CTest2DArray>::CType, CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<CTest3DArray2V>::CType, CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<CTest3DArray2CV>::CType, CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<CTest3DArray>::CType, CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCSigned<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCSigned<void *>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCSigned<void>::CType, void>::mc_Value						));

// Types
DMibStaticCheck((	TCIsSame<TCUnsigned<int8192>::CType, uint8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int4096>::CType, uint4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int2048>::CType, uint2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int1024>::CType, uint1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int512>::CType, uint512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int256>::CType, uint256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int160>::CType, uint160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int128>::CType, uint128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int80>::CType, uint80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int64>::CType, uint64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int32>::CType, uint32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int16>::CType, uint16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<int8>::CType, uint8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<aint>::CType, uaint>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uaint>::CType, uaint>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<smint>::CType, mint>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<mint>::CType, mint>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<uint4096>::CType, uint4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint2048>::CType, uint2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint1024>::CType, uint1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint512>::CType, uint512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint256>::CType, uint256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint160>::CType, uint160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint128>::CType, uint128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint80>::CType, uint80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint64>::CType, uint64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint32>::CType, uint32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint16>::CType, uint16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<uint8>::CType, uint8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<fp4096>::CType, fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp2048>::CType, fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp1024>::CType, fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp512>::CType, fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp256>::CType, fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp128>::CType, fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp80>::CType, fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp64>::CType, fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp32>::CType, fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp16>::CType, fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<fp8>::CType, fp8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<const int8192>::CType, const uint8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int4096>::CType, const uint4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int2048>::CType, const uint2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int1024>::CType, const uint1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int512>::CType, const uint512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int256>::CType, const uint256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int160>::CType, const uint160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int128>::CType, const uint128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int80>::CType, const uint80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int64>::CType, const uint64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int32>::CType, const uint32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int16>::CType, const uint16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const int8>::CType, const uint8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<const uint4096>::CType, const uint4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint2048>::CType, const uint2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint1024>::CType, const uint1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint512>::CType, const uint512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint256>::CType, const uint256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint160>::CType, const uint160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint128>::CType, const uint128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint80>::CType, const uint80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint64>::CType, const uint64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint32>::CType, const uint32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint16>::CType, const uint16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const uint8>::CType, const uint8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<const fp4096>::CType, const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp2048>::CType, const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp1024>::CType, const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp512>::CType, const fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp256>::CType, const fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp128>::CType, const fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp80>::CType, const fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp64>::CType, const fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp32>::CType, const fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp16>::CType, const fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const fp8>::CType, const fp8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int8192>::CType, volatile uint8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int4096>::CType, volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int2048>::CType, volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int1024>::CType, volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int512>::CType, volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int256>::CType, volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int160>::CType, volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int128>::CType, volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int80>::CType, volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int64>::CType, volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int32>::CType, volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int16>::CType, volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile int8>::CType, volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint4096>::CType, volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint2048>::CType, volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint1024>::CType, volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint512>::CType, volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint256>::CType, volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint160>::CType, volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint128>::CType, volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint80>::CType, volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint64>::CType, volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint32>::CType, volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint16>::CType, volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile uint8>::CType, volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp4096>::CType, volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp2048>::CType, volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp1024>::CType, volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp512>::CType, volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp256>::CType, volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp128>::CType, volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp80>::CType, volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp64>::CType, volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp32>::CType, volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp16>::CType, volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<volatile fp8>::CType, volatile fp8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int8192>::CType, const volatile uint8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int4096>::CType, const volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int2048>::CType, const volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int1024>::CType, const volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int512>::CType, const volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int256>::CType, const volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int160>::CType, const volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int128>::CType, const volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int80>::CType, const volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int64>::CType, const volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int32>::CType, const volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int16>::CType, const volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile int8>::CType, const volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint4096>::CType, const volatile uint4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint2048>::CType, const volatile uint2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint1024>::CType, const volatile uint1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint512>::CType, const volatile uint512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint256>::CType, const volatile uint256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint160>::CType, const volatile uint160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint128>::CType, const volatile uint128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint80>::CType, const volatile uint80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint64>::CType, const volatile uint64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint32>::CType, const volatile uint32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint16>::CType, const volatile uint16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile uint8>::CType, const volatile uint8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp4096>::CType, const volatile fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp2048>::CType, const volatile fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp1024>::CType, const volatile fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp512>::CType, const volatile fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp256>::CType, const volatile fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp128>::CType, const volatile fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp80>::CType, const volatile fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp64>::CType, const volatile fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp32>::CType, const volatile fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp16>::CType, const volatile fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<const volatile fp8>::CType, const volatile fp8>::mc_Value	));


DMibStaticCheck((	TCIsSame<TCUnsigned<CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestV>::CType, CTestV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCV>::CType, CTestCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestVPtr>::CType, CTestVPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCVPtr>::CType, CTestCVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestVPtrC>::CType, CTestVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCVPtrC>::CType, CTestCVPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestPtrV>::CType, CTestPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCPtrV>::CType, CTestCPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestVPtrV>::CType, CTestVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCVPtrV>::CType, CTestCVPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestPtrCV>::CType, CTestPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCPtrCV>::CType, CTestCPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestVPtrCV>::CType, CTestVPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCVPtrCV>::CType, CTestCVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestVRef>::CType, CTestVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCVRef>::CType, CTestCVRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestVRRef>::CType, CTestVRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestCVRRef>::CType, CTestCVRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<PFFunc2>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0PtrV>::CType, FFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1PtrV>::CType, FFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2PtrV>::CType, FFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0PtrCV>::CType, FFunc0PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1PtrCV>::CType, FFunc1PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2PtrCV>::CType, FFunc2PtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0PtrV>::CType, FMFunc0PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1PtrV>::CType, FMFunc1PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2PtrV>::CType, FMFunc2PtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0PtrCV>::CType, FMFunc0PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1PtrCV>::CType, FMFunc1PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2PtrCV>::CType, FMFunc2PtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0CPtrV>::CType, FMFunc0CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1CPtrV>::CType, FMFunc1CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2CPtrV>::CType, FMFunc2CPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0CPtrCV>::CType, FMFunc0CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1CPtrCV>::CType, FMFunc1CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2CPtrCV>::CType, FMFunc2CPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0VPtr>::CType, FMFunc0VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1VPtr>::CType, FMFunc1VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2VPtr>::CType, FMFunc2VPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0VPtrC>::CType, FMFunc0VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1VPtrC>::CType, FMFunc1VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2VPtrC>::CType, FMFunc2VPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0VPtrV>::CType, FMFunc0VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1VPtrV>::CType, FMFunc1VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2VPtrV>::CType, FMFunc2VPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0VPtrCV>::CType, FMFunc0VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1VPtrCV>::CType, FMFunc1VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2VPtrCV>::CType, FMFunc2VPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0CVPtr>::CType, FMFunc0CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1CVPtr>::CType, FMFunc1CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2CVPtr>::CType, FMFunc2CVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0CVPtrC>::CType, FMFunc0CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1CVPtrC>::CType, FMFunc1CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2CVPtrC>::CType, FMFunc2CVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0CVPtrV>::CType, FMFunc0CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1CVPtrV>::CType, FMFunc1CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2CVPtrV>::CType, FMFunc2CVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0CVPtrCV>::CType, FMFunc0CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1CVPtrCV>::CType, FMFunc1CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2CVPtrCV>::CType, FMFunc2CVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<PFFunc2El>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0ElPtrV>::CType, FFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1ElPtrV>::CType, FFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2ElPtrV>::CType, FFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc0ElPtrCV>::CType, FFunc0ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc1ElPtrCV>::CType, FFunc1ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FFunc2ElPtrCV>::CType, FFunc2ElPtrCV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElPtrV>::CType, FMFunc0ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElPtrV>::CType, FMFunc1ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElPtrV>::CType, FMFunc2ElPtrV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElPtrCV>::CType, FMFunc0ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElPtrCV>::CType, FMFunc1ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElPtrCV>::CType, FMFunc2ElPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElCPtrV>::CType, FMFunc0ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElCPtrV>::CType, FMFunc1ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElCPtrV>::CType, FMFunc2ElCPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElCPtrCV>::CType, FMFunc0ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElCPtrCV>::CType, FMFunc1ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElCPtrCV>::CType, FMFunc2ElCPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElVPtr>::CType, FMFunc0ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElVPtr>::CType, FMFunc1ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElVPtr>::CType, FMFunc2ElVPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElVPtrC>::CType, FMFunc0ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElVPtrC>::CType, FMFunc1ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElVPtrC>::CType, FMFunc2ElVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElVPtrV>::CType, FMFunc0ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElVPtrV>::CType, FMFunc1ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElVPtrV>::CType, FMFunc2ElVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElVPtrCV>::CType, FMFunc0ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElVPtrCV>::CType, FMFunc1ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElVPtrCV>::CType, FMFunc2ElVPtrCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElCVPtr>::CType, FMFunc0ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElCVPtr>::CType, FMFunc1ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElCVPtr>::CType, FMFunc2ElCVPtr>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElCVPtrC>::CType, FMFunc0ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElCVPtrC>::CType, FMFunc1ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElCVPtrC>::CType, FMFunc2ElCVPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElCVPtrV>::CType, FMFunc0ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElCVPtrV>::CType, FMFunc1ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElCVPtrV>::CType, FMFunc2ElCVPtrV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc0ElCVPtrCV>::CType, FMFunc0ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc1ElCVPtrCV>::CType, FMFunc1ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<FMFunc2ElCVPtrCV>::CType, FMFunc2ElCVPtrCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMVPtr>::CType, CMVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMCVPtr>::CType, CMCVPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMVPtrC>::CType, CMVPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMCVPtrC>::CType, CMCVPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMPtrV>::CType, CMPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMCPtrV>::CType, CMCPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMVPtrV>::CType, CMVPtrV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMCVPtrV>::CType, CMCVPtrV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMPtrCV>::CType, CMPtrCV>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMCPtrCV>::CType, CMCPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMVPtrCV>::CType, CMVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CMCVPtrCV>::CType, CMCVPtrCV>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestArray2C>::CType, CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestArray2V>::CType, CTestArray2V>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestArray2CV>::CType, CTestArray2CV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestArray>::CType, CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestArrayV>::CType, CTestArrayV>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTestArrayCV>::CType, CTestArrayCV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest2DArray2V>::CType, CTest2DArray2V>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest2DArray2CV>::CType, CTest2DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest2DArray>::CType, CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest2DArrayV>::CType, CTest2DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest2DArrayCV>::CType, CTest2DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest3DArray2V>::CType, CTest3DArray2V>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest3DArray2CV>::CType, CTest3DArray2CV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest3DArray>::CType, CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest3DArrayV>::CType, CTest3DArrayV>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCUnsigned<CTest3DArrayCV>::CType, CTest3DArrayCV>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCUnsigned<void *>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCUnsigned<void>::CType, void>::mc_Value						));


// From size
DMibStaticCheck((	TCIsSame<TCIntFromSize<8192/8>::CType, int8192>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<4096/8>::CType, int4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<2048/8>::CType, int2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<1024/8>::CType, int1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<512/8>::CType, int512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<256/8>::CType, int256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<160/8>::CType, int160>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<128/8>::CType, int128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<64/8>::CType, int64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<80/8>::CType, int80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<32/8>::CType, int32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<16/8>::CType, int16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCIntFromSize<8/8>::CType, int8>::mc_Value	));

DMibStaticCheck((	TCIsSame<TCFloatFromSize<4096/8>::CType, fp4096>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<2048/8>::CType, fp2048>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<1024/8>::CType, fp1024>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<512/8>::CType, fp512>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<256/8>::CType, fp256>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<128/8>::CType, fp128>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<80/8>::CType, fp80>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<64/8>::CType, fp64>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<32/8>::CType, fp32>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<16/8>::CType, fp16>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCFloatFromSize<8/8>::CType, fp8>::mc_Value	));

