// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

static_assert(!cIsRValueReference<CTestUnion>);
static_assert(!cIsRValueReference<CTestClass0>);
static_assert(!cIsRValueReference<CTestClass1>);
static_assert(!cIsRValueReference<CTestStruct0>);
static_assert(!cIsRValueReference<CTestStruct1>);
static_assert(!cIsRValueReference<ETestEnum>);
static_assert(!cIsRValueReference<CTestClass>);
static_assert(!cIsRValueReference<CTestC>);
static_assert(!cIsRValueReference<CTestPtr>);
static_assert(!cIsRValueReference<CTestCPtr>);
static_assert(!cIsRValueReference<CTestPtrC>);
static_assert(!cIsRValueReference<CTestCPtrC>);
static_assert(!cIsRValueReference<CTestRef>);
static_assert(!cIsRValueReference<CTestCRef>);
static_assert(cIsRValueReference<CTestRRef>);
static_assert(cIsRValueReference<CTestCRRef>);
static_assert(!cIsRValueReference<PFFunc0>);
static_assert(!cIsRValueReference<PFFunc1>);
static_assert(!cIsRValueReference<PFFunc2>);
static_assert(!cIsRValueReference<FFunc0Ref>);
static_assert(!cIsRValueReference<FFunc1Ref>);
static_assert(!cIsRValueReference<FFunc2Ref>);
static_assert(cIsRValueReference<FFunc0RRef>);
static_assert(cIsRValueReference<FFunc1RRef>);
static_assert(cIsRValueReference<FFunc2RRef>);
static_assert(!cIsRValueReference<FFunc0Ptr>);
static_assert(!cIsRValueReference<FFunc1Ptr>);
static_assert(!cIsRValueReference<FFunc2Ptr>);
static_assert(!cIsRValueReference<FFunc0PtrC>);
static_assert(!cIsRValueReference<FFunc1PtrC>);
static_assert(!cIsRValueReference<FFunc2PtrC>);
static_assert(!cIsRValueReference<FMFunc0Ptr>);
static_assert(!cIsRValueReference<FMFunc1Ptr>);
static_assert(!cIsRValueReference<FMFunc2Ptr>);
static_assert(!cIsRValueReference<FMFunc0PtrC>);
static_assert(!cIsRValueReference<FMFunc1PtrC>);
static_assert(!cIsRValueReference<FMFunc2PtrC>);
static_assert(!cIsRValueReference<FMFunc0CPtr>);
static_assert(!cIsRValueReference<FMFunc1CPtr>);
static_assert(!cIsRValueReference<FMFunc2CPtr>);
static_assert(!cIsRValueReference<FMFunc0CPtrC>);
static_assert(!cIsRValueReference<FMFunc1CPtrC>);
static_assert(!cIsRValueReference<FMFunc2CPtrC>);
static_assert(!cIsRValueReference<PFFunc0El>);
static_assert(!cIsRValueReference<PFFunc1El>);
static_assert(!cIsRValueReference<PFFunc2El>);
static_assert(!cIsRValueReference<FFunc0ElRef>);
static_assert(!cIsRValueReference<FFunc1ElRef>);
static_assert(!cIsRValueReference<FFunc2ElRef>);
static_assert(cIsRValueReference<FFunc0ElRRef>);
static_assert(cIsRValueReference<FFunc1ElRRef>);
static_assert(cIsRValueReference<FFunc2ElRRef>);
static_assert(!cIsRValueReference<FFunc0ElPtr>);
static_assert(!cIsRValueReference<FFunc1ElPtr>);
static_assert(!cIsRValueReference<FFunc2ElPtr>);
static_assert(!cIsRValueReference<FFunc0ElPtrC>);
static_assert(!cIsRValueReference<FFunc1ElPtrC>);
static_assert(!cIsRValueReference<FFunc2ElPtrC>);
static_assert(!cIsRValueReference<FMFunc0ElPtr>);
static_assert(!cIsRValueReference<FMFunc1ElPtr>);
static_assert(!cIsRValueReference<FMFunc2ElPtr>);
static_assert(!cIsRValueReference<FMFunc0ElPtrC>);
static_assert(!cIsRValueReference<FMFunc1ElPtrC>);
static_assert(!cIsRValueReference<FMFunc2ElPtrC>);
static_assert(!cIsRValueReference<FMFunc0ElCPtr>);
static_assert(!cIsRValueReference<FMFunc1ElCPtr>);
static_assert(!cIsRValueReference<FMFunc2ElCPtr>);
static_assert(!cIsRValueReference<FMFunc0ElCPtrC>);
static_assert(!cIsRValueReference<FMFunc1ElCPtrC>);
static_assert(!cIsRValueReference<FMFunc2ElCPtrC>);
static_assert(!cIsRValueReference<CMPtr>);
static_assert(!cIsRValueReference<CMCPtr>);
static_assert(!cIsRValueReference<CMPtrC>);
static_assert(!cIsRValueReference<CMCPtrC>);
static_assert(!cIsRValueReference<CTestArray2>);
static_assert(!cIsRValueReference<CTestArray2C>);
static_assert(!cIsRValueReference<CTestArray>);
static_assert(!cIsRValueReference<CTestArrayC>);
static_assert(!cIsRValueReference<CTest2DArray2>);
static_assert(!cIsRValueReference<CTest2DArray2C>);
static_assert(!cIsRValueReference<CTest2DArray>);
static_assert(!cIsRValueReference<CTest2DArrayC>);
static_assert(!cIsRValueReference<CTest3DArray2>);
static_assert(!cIsRValueReference<CTest3DArray2C>);
static_assert(!cIsRValueReference<CTest3DArray>);
static_assert(!cIsRValueReference<CTest3DArrayC>);
static_assert(!cIsRValueReference<void *>);
static_assert(!cIsRValueReference<void>);

static_assert(cIsSame<TCAddRValueReference<CTestUnion>, CTestUnion &&>);
static_assert(cIsSame<TCAddRValueReference<CTestClass0>, CTestClass0 &&>);
static_assert(cIsSame<TCAddRValueReference<CTestClass1>, CTestClass1 &&>);
static_assert(cIsSame<TCAddRValueReference<CTestStruct0>, CTestStruct0 &&>);
static_assert(cIsSame<TCAddRValueReference<CTestStruct1>, CTestStruct1 &&>);
static_assert(cIsSame<TCAddRValueReference<ETestEnum>, ETestEnum &&>);
static_assert(cIsSame<TCAddRValueReference<CTestClass>, CTestClass &&>);
static_assert(cIsSame<TCAddRValueReference<CTestC>, CTestC &&>);
static_assert(cIsSame<TCAddRValueReference<CTestPtr>, CTestPtr &&>);
static_assert(cIsSame<TCAddRValueReference<CTestCPtr>, CTestCPtr &&>);
static_assert(cIsSame<TCAddRValueReference<CTestPtrC>, CTestPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<CTestCPtrC>, CTestCPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<CTestRef>, CTestRRef>);
static_assert(cIsSame<TCAddRValueReference<CTestCRef>, CTestCRRef>);
static_assert(cIsSame<TCAddRValueReference<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCAddRValueReference<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCAddRValueReference<PFFunc0>, PFFunc0 &&>);
static_assert(cIsSame<TCAddRValueReference<PFFunc1>, PFFunc1 &&>);
static_assert(cIsSame<TCAddRValueReference<PFFunc2>, PFFunc2 &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc0Ref>, FFunc0RRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc1Ref>, FFunc1RRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc2Ref>, FFunc2RRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc0Ptr>, FFunc0Ptr &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc1Ptr>, FFunc1Ptr &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc2Ptr>, FFunc2Ptr &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc0PtrC>, FFunc0PtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc1PtrC>, FFunc1PtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc2PtrC>, FFunc2PtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc0Ptr>, FMFunc0Ptr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc1Ptr>, FMFunc1Ptr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc2Ptr>, FMFunc2Ptr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc0PtrC>, FMFunc0PtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc1PtrC>, FMFunc1PtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc2PtrC>, FMFunc2PtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc0CPtr>, FMFunc0CPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc1CPtr>, FMFunc1CPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc2CPtr>, FMFunc2CPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc0CPtrC>, FMFunc0CPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc1CPtrC>, FMFunc1CPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc2CPtrC>, FMFunc2CPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<PFFunc0El>, PFFunc0El &&>);
static_assert(cIsSame<TCAddRValueReference<PFFunc1El>, PFFunc1El &&>);
static_assert(cIsSame<TCAddRValueReference<PFFunc2El>, PFFunc2El &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc0ElRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc1ElRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc2ElRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCAddRValueReference<FFunc0ElPtr>, FFunc0ElPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc1ElPtr>, FFunc1ElPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc2ElPtr>, FFunc2ElPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc0ElPtrC>, FFunc0ElPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc1ElPtrC>, FFunc1ElPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FFunc2ElPtrC>, FFunc2ElPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc0ElPtr>, FMFunc0ElPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc1ElPtr>, FMFunc1ElPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc2ElPtr>, FMFunc2ElPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc0ElPtrC>, FMFunc0ElPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc1ElPtrC>, FMFunc1ElPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc2ElPtrC>, FMFunc2ElPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc0ElCPtr>, FMFunc0ElCPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc1ElCPtr>, FMFunc1ElCPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc2ElCPtr>, FMFunc2ElCPtr &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc0ElCPtrC>, FMFunc0ElCPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc1ElCPtrC>, FMFunc1ElCPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<FMFunc2ElCPtrC>, FMFunc2ElCPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<CMPtr>, CMPtr &&>);
static_assert(cIsSame<TCAddRValueReference<CMCPtr>, CMCPtr &&>);
static_assert(cIsSame<TCAddRValueReference<CMPtrC>, CMPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<CMCPtrC>, CMCPtrC &&>);
static_assert(cIsSame<TCAddRValueReference<CTestArray2>, CTestArray2 &&>);
static_assert(cIsSame<TCAddRValueReference<CTestArray2C>, CTestArray2C &&>);
static_assert(cIsSame<TCAddRValueReference<CTestArray>, CTestArray &&>);
static_assert(cIsSame<TCAddRValueReference<CTestArrayC>, CTestArrayC &&>);
static_assert(cIsSame<TCAddRValueReference<CTest2DArray2>, CTest2DArray2 &&>);
static_assert(cIsSame<TCAddRValueReference<CTest2DArray2C>, CTest2DArray2C &&>);
static_assert(cIsSame<TCAddRValueReference<CTest2DArray>, CTest2DArray &&>);
static_assert(cIsSame<TCAddRValueReference<CTest2DArrayC>, CTest2DArrayC &&>);
static_assert(cIsSame<TCAddRValueReference<CTest3DArray2>, CTest3DArray2 &&>);
static_assert(cIsSame<TCAddRValueReference<CTest3DArray2C>, CTest3DArray2C &&>);
static_assert(cIsSame<TCAddRValueReference<CTest3DArray>, CTest3DArray &&>);
static_assert(cIsSame<TCAddRValueReference<CTest3DArrayC>, CTest3DArrayC &&>);
static_assert(cIsSame<TCAddRValueReference<void *>, void *&&>);
static_assert(cIsSame<TCAddRValueReference<void>, void>);

// Remove pointer
static_assert(cIsSame<TCRemoveRValueReference<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCRemoveRValueReference<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCRemoveRValueReference<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCRemoveRValueReference<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCRemoveRValueReference<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCRemoveRValueReference<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCRemoveRValueReference<CTestClass>, CTestClass>);
static_assert(cIsSame<TCRemoveRValueReference<CTestC>, CTestC>);
static_assert(cIsSame<TCRemoveRValueReference<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCRemoveRValueReference<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCRemoveRValueReference<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<CTestRef>, CTestRef>);
static_assert(cIsSame<TCRemoveRValueReference<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCRemoveRValueReference<CTestRRef>, CTestClass>);
static_assert(cIsSame<TCRemoveRValueReference<CTestCRRef>, CTestC>);
static_assert(cIsSame<TCRemoveRValueReference<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCRemoveRValueReference<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCRemoveRValueReference<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc0RRef>, PFFunc0>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc1RRef>, PFFunc1>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc2RRef>, PFFunc2>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCRemoveRValueReference<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCRemoveRValueReference<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc0ElRRef>, PFFunc0El>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc1ElRRef>, PFFunc1El>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc2ElRRef>, PFFunc2El>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<CMPtr>, CMPtr>);
static_assert(cIsSame<TCRemoveRValueReference<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCRemoveRValueReference<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCRemoveRValueReference<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCRemoveRValueReference<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCRemoveRValueReference<CTestArray>, CTestArray>);
static_assert(cIsSame<TCRemoveRValueReference<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCRemoveRValueReference<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCRemoveRValueReference<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCRemoveRValueReference<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCRemoveRValueReference<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCRemoveRValueReference<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCRemoveRValueReference<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCRemoveRValueReference<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCRemoveRValueReference<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCRemoveRValueReference<void *>, void *>);
static_assert(cIsSame<TCRemoveRValueReference<void *&&>, void *>);
static_assert(cIsSame<TCRemoveRValueReference<void>, void>);
