// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsMemberObjectPointer<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<ETestEnum>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestClass>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc0ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc1ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<FMFunc2ElCPtrC>::mc_Value	));
DMibStaticCheck((	TCIsMemberObjectPointer<CMPtr>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCPtr>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMPtrC>::mc_Value			));
DMibStaticCheck((	TCIsMemberObjectPointer<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArray>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest2DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArray>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<CTest3DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsMemberObjectPointer<void *>::mc_Value			));
DMibStaticCheck((	!TCIsMemberObjectPointer<void>::mc_Value			));

// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestPtr>::CType, CTestPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCPtr>::CType, CTestCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestPtrC>::CType, CTestPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCPtrC>::CType, CTestCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCRef>::CType, CTestCRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0Ref>::CType, FFunc0Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1Ref>::CType, FFunc1Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2Ref>::CType, FFunc2Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0RRef>::CType, FFunc0RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1RRef>::CType, FFunc1RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2RRef>::CType, FFunc2RRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMPtr>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCPtr>::CType, CTestBase const>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMPtrC>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CMCPtrC>::CType, CTestBase const>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveMemberObjectPointer<void>::CType, void>::mc_Value							));


// Class
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestUnion>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestClass0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestClass1>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestStruct0>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestStruct1>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<ETestEnum>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestClass>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestC>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestPtr>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestRef>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestCRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc0>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc1>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc2>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0Ref>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1Ref>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2Ref>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0RRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1RRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2RRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2Ptr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2PtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0Ptr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1Ptr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2Ptr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0PtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1PtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2PtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0CPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1CPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2CPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc0El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc1El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<PFFunc2El>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElRRef>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElPtr>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc0ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc1ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FFunc2ElPtrC>::CType, void>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElPtr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElPtr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElPtr>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCPtr>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc0ElCPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc1ElCPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<FMFunc2ElCPtrC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMPtr>::CType, CTestClass0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCPtr>::CType, CTestClass0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMPtrC>::CType, CTestClass0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CMCPtrC>::CType, CTestClass0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArray2>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArray2C>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArray>::CType, void>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTestArrayC>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArray2>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArray2C>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArray>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest2DArrayC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArray2>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArray2C>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArray>::CType, void>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<CTest3DArrayC>::CType, void>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<void *>::CType, void>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCMemberObjectPointerClass<void>::CType, void>::mc_Value							));




