// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NAbstract
{
	class CAbstract
	{
		virtual void f_Test() = 0;
	};
	class CInheritAbstract : private CAbstract
	{
	};
	class CNonAbstract
	{
		virtual void f_Test();
	};
	class CNonVirtual
	{
		void f_Test();
	};
	DMibStaticCheck((	TCIsAbstract<CAbstract>::mc_Value						));
	DMibStaticCheck((	TCIsAbstract<CInheritAbstract>::mc_Value						));
	DMibStaticCheck((	!TCIsAbstract<CNonAbstract>::mc_Value						));
	DMibStaticCheck((	!TCIsAbstract<CNonVirtual>::mc_Value						));
	
}

// Void
DMibStaticCheck((	!TCIsAbstract<CTestUnion>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestClass0>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestClass1>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestStruct0>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestStruct1>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<const CTestClass0>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<const CTestClass1>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	!TCIsAbstract<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	!TCIsAbstract<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	!TCIsAbstract<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	!TCIsAbstract<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsAbstract<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsAbstract<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsAbstract<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsAbstract<ETestEnum>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<int>::mc_Value							));
DMibStaticCheck((	!TCIsAbstract<CTestClass>::mc_Value							));
DMibStaticCheck((	!TCIsAbstract<CTestC>::mc_Value							));
DMibStaticCheck((	!TCIsAbstract<CTestV>::mc_Value							));
DMibStaticCheck((	!TCIsAbstract<CTestCV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestVRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestCVRef>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<CMPtr>::mc_Value							));
DMibStaticCheck((	!TCIsAbstract<CMCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMCVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMCPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMVPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMCPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMVPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<CTestArray2>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestArray2C>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestArray2V>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestArray>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<CTest2DArray>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<CTest3DArray>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsAbstract<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	!TCIsAbstract<void *>::mc_Value						));
DMibStaticCheck((	!TCIsAbstract<void>::mc_Value							));

