// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

static_assert((sizeof(ch8) == 1));
static_assert((sizeof(ch16) == 2));
static_assert((sizeof(ch32) == 4));

#ifdef DMibPSignedType_ch8
	static_assert(int32(ch8(uint8(0xffu))) == -1);
#else
	static_assert(int32(ch8(uint8(0xffu))) == 0xffu);
#endif

#ifdef DMibPSignedType_ch16
	static_assert(int32(ch16(uint16(0xffffu))) == -1);
#else
	static_assert(int32(ch16(uint16(0xffffu))) == 0xffffu);
#endif

#ifdef DMibPSignedType_ch32
	static_assert(int64(ch32(uint32(0xffffffffu))) == -1);
#else
	static_assert(int64(ch32(uint32(0xffffffffu))) == 0xffffffffu);
#endif

// Is Signed
static_assert(!cIsSigned<ufp32>);

static_assert(cIsSigned<int16384>);
static_assert(cIsSigned<int8192>);
static_assert(cIsSigned<int4096>);
static_assert(cIsSigned<int2048>);
static_assert(cIsSigned<int1024>);
static_assert(cIsSigned<int512>);
static_assert(cIsSigned<int256>);
static_assert(cIsSigned<int160>);
static_assert(cIsSigned<int192>);
static_assert(cIsSigned<int128>);
static_assert(cIsSigned<int80>);
static_assert(cIsSigned<int96>);
static_assert(cIsSigned<int64>);
static_assert(cIsSigned<int32>);
static_assert(cIsSigned<int16>);
static_assert(cIsSigned<int8>);

static_assert(cIsSigned<aint>);
static_assert(!cIsSigned<uaint>);
static_assert(cIsSigned<smint>);
static_assert(!cIsSigned<umint>);

static_assert(!cIsSigned<uint4096>);
static_assert(!cIsSigned<uint2048>);
static_assert(!cIsSigned<uint1024>);
static_assert(!cIsSigned<uint512>);
static_assert(!cIsSigned<uint256>);
static_assert(!cIsSigned<uint160>);
static_assert(!cIsSigned<uint192>);
static_assert(!cIsSigned<uint128>);
static_assert(!cIsSigned<uint80>);
static_assert(!cIsSigned<uint96>);
static_assert(!cIsSigned<uint64>);
static_assert(!cIsSigned<uint32>);
static_assert(!cIsSigned<uint16>);
static_assert(!cIsSigned<uint8>);

static_assert(cIsSigned<fp4096>);
static_assert(cIsSigned<fp2048>);
static_assert(cIsSigned<fp1024>);
static_assert(cIsSigned<fp512>);
static_assert(cIsSigned<fp256>);
static_assert(cIsSigned<fp128>);
static_assert(cIsSigned<fp80>);
static_assert(cIsSigned<fp64>);
static_assert(cIsSigned<fp32>);
static_assert(cIsSigned<fp16>);
static_assert(cIsSigned<fp8>);

static_assert(cIsSigned<const int16384>);
static_assert(cIsSigned<const int8192>);
static_assert(cIsSigned<const int4096>);
static_assert(cIsSigned<const int2048>);
static_assert(cIsSigned<const int1024>);
static_assert(cIsSigned<const int512>);
static_assert(cIsSigned<const int256>);
static_assert(cIsSigned<const int160>);
static_assert(cIsSigned<const int192>);
static_assert(cIsSigned<const int128>);
static_assert(cIsSigned<const int80>);
static_assert(cIsSigned<const int96>);
static_assert(cIsSigned<const int64>);
static_assert(cIsSigned<const int32>);
static_assert(cIsSigned<const int16>);
static_assert(cIsSigned<const int8>);

static_assert(!cIsSigned<const uint4096>);
static_assert(!cIsSigned<const uint2048>);
static_assert(!cIsSigned<const uint1024>);
static_assert(!cIsSigned<const uint512>);
static_assert(!cIsSigned<const uint256>);
static_assert(!cIsSigned<const uint160>);
static_assert(!cIsSigned<const uint192>);
static_assert(!cIsSigned<const uint128>);
static_assert(!cIsSigned<const uint80>);
static_assert(!cIsSigned<const uint96>);
static_assert(!cIsSigned<const uint64>);
static_assert(!cIsSigned<const uint32>);
static_assert(!cIsSigned<const uint16>);
static_assert(!cIsSigned<const uint8>);

static_assert(cIsSigned<const fp4096>);
static_assert(cIsSigned<const fp2048>);
static_assert(cIsSigned<const fp1024>);
static_assert(cIsSigned<const fp512>);
static_assert(cIsSigned<const fp256>);
static_assert(cIsSigned<const fp128>);
static_assert(cIsSigned<const fp80>);
static_assert(cIsSigned<const fp64>);
static_assert(cIsSigned<const fp32>);
static_assert(cIsSigned<const fp16>);
static_assert(cIsSigned<const fp8>);

static_assert(!cIsSigned<const ufp32>);

static_assert(!cIsSigned<CTestUnion>);
static_assert(!cIsSigned<CTestClass0>);
static_assert(!cIsSigned<CTestClass1>);
static_assert(!cIsSigned<CTestStruct0>);
static_assert(!cIsSigned<CTestStruct1>);
static_assert(!cIsSigned<ETestEnum>);
static_assert(!cIsSigned<CTestClass>);
static_assert(!cIsSigned<CTestC>);
static_assert(!cIsSigned<CTestPtr>);
static_assert(!cIsSigned<CTestCPtr>);
static_assert(!cIsSigned<CTestPtrC>);
static_assert(!cIsSigned<CTestCPtrC>);
static_assert(!cIsSigned<CTestRef>);
static_assert(!cIsSigned<CTestCRef>);
static_assert(!cIsSigned<CTestRRef>);
static_assert(!cIsSigned<CTestCRRef>);
static_assert(!cIsSigned<PFFunc0>);
static_assert(!cIsSigned<PFFunc1>);
static_assert(!cIsSigned<PFFunc2>);
static_assert(!cIsSigned<FFunc0Ref>);
static_assert(!cIsSigned<FFunc1Ref>);
static_assert(!cIsSigned<FFunc2Ref>);
static_assert(!cIsSigned<FFunc0RRef>);
static_assert(!cIsSigned<FFunc1RRef>);
static_assert(!cIsSigned<FFunc2RRef>);
static_assert(!cIsSigned<FFunc0Ptr>);
static_assert(!cIsSigned<FFunc1Ptr>);
static_assert(!cIsSigned<FFunc2Ptr>);
static_assert(!cIsSigned<FFunc0PtrC>);
static_assert(!cIsSigned<FFunc1PtrC>);
static_assert(!cIsSigned<FFunc2PtrC>);
static_assert(!cIsSigned<FMFunc0Ptr>);
static_assert(!cIsSigned<FMFunc1Ptr>);
static_assert(!cIsSigned<FMFunc2Ptr>);
static_assert(!cIsSigned<FMFunc0PtrC>);
static_assert(!cIsSigned<FMFunc1PtrC>);
static_assert(!cIsSigned<FMFunc2PtrC>);
static_assert(!cIsSigned<FMFunc0CPtr>);
static_assert(!cIsSigned<FMFunc1CPtr>);
static_assert(!cIsSigned<FMFunc2CPtr>);
static_assert(!cIsSigned<FMFunc0CPtrC>);
static_assert(!cIsSigned<FMFunc1CPtrC>);
static_assert(!cIsSigned<FMFunc2CPtrC>);
static_assert(!cIsSigned<PFFunc0El>);
static_assert(!cIsSigned<PFFunc1El>);
static_assert(!cIsSigned<PFFunc2El>);
static_assert(!cIsSigned<FFunc0ElRef>);
static_assert(!cIsSigned<FFunc1ElRef>);
static_assert(!cIsSigned<FFunc2ElRef>);
static_assert(!cIsSigned<FFunc0ElRRef>);
static_assert(!cIsSigned<FFunc1ElRRef>);
static_assert(!cIsSigned<FFunc2ElRRef>);
static_assert(!cIsSigned<FFunc0ElPtr>);
static_assert(!cIsSigned<FFunc1ElPtr>);
static_assert(!cIsSigned<FFunc2ElPtr>);
static_assert(!cIsSigned<FFunc0ElPtrC>);
static_assert(!cIsSigned<FFunc1ElPtrC>);
static_assert(!cIsSigned<FFunc2ElPtrC>);
static_assert(!cIsSigned<FMFunc0ElPtr>);
static_assert(!cIsSigned<FMFunc1ElPtr>);
static_assert(!cIsSigned<FMFunc2ElPtr>);
static_assert(!cIsSigned<FMFunc0ElPtrC>);
static_assert(!cIsSigned<FMFunc1ElPtrC>);
static_assert(!cIsSigned<FMFunc2ElPtrC>);
static_assert(!cIsSigned<FMFunc0ElCPtr>);
static_assert(!cIsSigned<FMFunc1ElCPtr>);
static_assert(!cIsSigned<FMFunc2ElCPtr>);
static_assert(!cIsSigned<FMFunc0ElCPtrC>);
static_assert(!cIsSigned<FMFunc1ElCPtrC>);
static_assert(!cIsSigned<FMFunc2ElCPtrC>);
static_assert(!cIsSigned<CMPtr>);
static_assert(!cIsSigned<CMCPtr>);
static_assert(!cIsSigned<CMPtrC>);
static_assert(!cIsSigned<CMCPtrC>);
static_assert(!cIsSigned<CTestArray2>);
static_assert(!cIsSigned<CTestArray2C>);
static_assert(!cIsSigned<CTestArray>);
static_assert(!cIsSigned<CTestArrayC>);
static_assert(!cIsSigned<CTest2DArray2>);
static_assert(!cIsSigned<CTest2DArray2C>);
static_assert(!cIsSigned<CTest2DArray>);
static_assert(!cIsSigned<CTest2DArrayC>);
static_assert(!cIsSigned<CTest3DArray2>);
static_assert(!cIsSigned<CTest3DArray2C>);
static_assert(!cIsSigned<CTest3DArray>);
static_assert(!cIsSigned<CTest3DArrayC>);
static_assert(!cIsSigned<void *>);
static_assert(!cIsSigned<void>);

// Types
static_assert(cIsSame<TCSigned<int16384>, int16384>);
static_assert(cIsSame<TCSigned<int8192>, int8192>);
static_assert(cIsSame<TCSigned<int4096>, int4096>);
static_assert(cIsSame<TCSigned<int2048>, int2048>);
static_assert(cIsSame<TCSigned<int1024>, int1024>);
static_assert(cIsSame<TCSigned<int512>, int512>);
static_assert(cIsSame<TCSigned<int256>, int256>);
static_assert(cIsSame<TCSigned<int160>, int160>);
static_assert(cIsSame<TCSigned<int192>, int192>);
static_assert(cIsSame<TCSigned<int128>, int128>);
static_assert(cIsSame<TCSigned<int80>, int80>);
static_assert(cIsSame<TCSigned<int96>, int96>);
static_assert(cIsSame<TCSigned<int64>, int64>);
static_assert(cIsSame<TCSigned<int32>, int32>);
static_assert(cIsSame<TCSigned<int16>, int16>);
static_assert(cIsSame<TCSigned<int8>, int8>);

static_assert(cIsSame<TCSigned<aint>, aint>);
static_assert(cIsSame<TCSigned<uaint>, aint>);
static_assert(cIsSame<TCSigned<smint>, smint>);
static_assert(cIsSame<TCSigned<umint>, smint>);

static_assert(cIsSame<TCSigned<uint16384>, int16384>);
static_assert(cIsSame<TCSigned<uint8192>, int8192>);
static_assert(cIsSame<TCSigned<uint4096>, int4096>);
static_assert(cIsSame<TCSigned<uint2048>, int2048>);
static_assert(cIsSame<TCSigned<uint1024>, int1024>);
static_assert(cIsSame<TCSigned<uint512>, int512>);
static_assert(cIsSame<TCSigned<uint256>, int256>);
static_assert(cIsSame<TCSigned<uint160>, int160>);
static_assert(cIsSame<TCSigned<uint192>, int192>);
static_assert(cIsSame<TCSigned<uint128>, int128>);
static_assert(cIsSame<TCSigned<uint80>, int80>);
static_assert(cIsSame<TCSigned<uint96>, int96>);
static_assert(cIsSame<TCSigned<uint64>, int64>);
static_assert(cIsSame<TCSigned<uint32>, int32>);
static_assert(cIsSame<TCSigned<uint16>, int16>);
static_assert(cIsSame<TCSigned<uint8>, int8>);

static_assert(cIsSame<TCSigned<fp4096>, fp4096>);
static_assert(cIsSame<TCSigned<fp2048>, fp2048>);
static_assert(cIsSame<TCSigned<fp1024>, fp1024>);
static_assert(cIsSame<TCSigned<fp512>, fp512>);
static_assert(cIsSame<TCSigned<fp256>, fp256>);
static_assert(cIsSame<TCSigned<fp128>, fp128>);
static_assert(cIsSame<TCSigned<fp80>, fp80>);
static_assert(cIsSame<TCSigned<fp64>, fp64>);
static_assert(cIsSame<TCSigned<fp32>, fp32>);
static_assert(cIsSame<TCSigned<fp16>, fp16>);
static_assert(cIsSame<TCSigned<fp8>, fp8>);

static_assert(cIsSame<TCSigned<const int16384>, const int16384>);
static_assert(cIsSame<TCSigned<const int8192>, const int8192>);
static_assert(cIsSame<TCSigned<const int4096>, const int4096>);
static_assert(cIsSame<TCSigned<const int2048>, const int2048>);
static_assert(cIsSame<TCSigned<const int1024>, const int1024>);
static_assert(cIsSame<TCSigned<const int512>, const int512>);
static_assert(cIsSame<TCSigned<const int256>, const int256>);
static_assert(cIsSame<TCSigned<const int160>, const int160>);
static_assert(cIsSame<TCSigned<const int192>, const int192>);
static_assert(cIsSame<TCSigned<const int128>, const int128>);
static_assert(cIsSame<TCSigned<const int80>, const int80>);
static_assert(cIsSame<TCSigned<const int96>, const int96>);
static_assert(cIsSame<TCSigned<const int64>, const int64>);
static_assert(cIsSame<TCSigned<const int32>, const int32>);
static_assert(cIsSame<TCSigned<const int16>, const int16>);
static_assert(cIsSame<TCSigned<const int8>, const int8>);

static_assert(cIsSame<TCSigned<const uint16384>, const int16384>);
static_assert(cIsSame<TCSigned<const uint8192>, const int8192>);
static_assert(cIsSame<TCSigned<const uint4096>, const int4096>);
static_assert(cIsSame<TCSigned<const uint2048>, const int2048>);
static_assert(cIsSame<TCSigned<const uint1024>, const int1024>);
static_assert(cIsSame<TCSigned<const uint512>, const int512>);
static_assert(cIsSame<TCSigned<const uint256>, const int256>);
static_assert(cIsSame<TCSigned<const uint160>, const int160>);
static_assert(cIsSame<TCSigned<const uint192>, const int192>);
static_assert(cIsSame<TCSigned<const uint128>, const int128>);
static_assert(cIsSame<TCSigned<const uint80>, const int80>);
static_assert(cIsSame<TCSigned<const uint96>, const int96>);
static_assert(cIsSame<TCSigned<const uint64>, const int64>);
static_assert(cIsSame<TCSigned<const uint32>, const int32>);
static_assert(cIsSame<TCSigned<const uint16>, const int16>);
static_assert(cIsSame<TCSigned<const uint8>, const int8>);

static_assert(cIsSame<TCSigned<const fp4096>, const fp4096>);
static_assert(cIsSame<TCSigned<const fp2048>, const fp2048>);
static_assert(cIsSame<TCSigned<const fp1024>, const fp1024>);
static_assert(cIsSame<TCSigned<const fp512>, const fp512>);
static_assert(cIsSame<TCSigned<const fp256>, const fp256>);
static_assert(cIsSame<TCSigned<const fp128>, const fp128>);
static_assert(cIsSame<TCSigned<const fp80>, const fp80>);
static_assert(cIsSame<TCSigned<const fp64>, const fp64>);
static_assert(cIsSame<TCSigned<const fp32>, const fp32>);
static_assert(cIsSame<TCSigned<const fp16>, const fp16>);
static_assert(cIsSame<TCSigned<const fp8>, const fp8>);

static_assert(cIsSame<TCSigned<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCSigned<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCSigned<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCSigned<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCSigned<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCSigned<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCSigned<CTestClass>, CTestClass>);
static_assert(cIsSame<TCSigned<CTestC>, CTestC>);
static_assert(cIsSame<TCSigned<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCSigned<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCSigned<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCSigned<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCSigned<CTestRef>, CTestRef>);
static_assert(cIsSame<TCSigned<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCSigned<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCSigned<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCSigned<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCSigned<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCSigned<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCSigned<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCSigned<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCSigned<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCSigned<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCSigned<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCSigned<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCSigned<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCSigned<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCSigned<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCSigned<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCSigned<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCSigned<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCSigned<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCSigned<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCSigned<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCSigned<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCSigned<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCSigned<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCSigned<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCSigned<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCSigned<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCSigned<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCSigned<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCSigned<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCSigned<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCSigned<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCSigned<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCSigned<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCSigned<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCSigned<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCSigned<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCSigned<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCSigned<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCSigned<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCSigned<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCSigned<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCSigned<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCSigned<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCSigned<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCSigned<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCSigned<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCSigned<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCSigned<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCSigned<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCSigned<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCSigned<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCSigned<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCSigned<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCSigned<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCSigned<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCSigned<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCSigned<CMPtr>, CMPtr>);
static_assert(cIsSame<TCSigned<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCSigned<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCSigned<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCSigned<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCSigned<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCSigned<CTestArray>, CTestArray>);
static_assert(cIsSame<TCSigned<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCSigned<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCSigned<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCSigned<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCSigned<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCSigned<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCSigned<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCSigned<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCSigned<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCSigned<void *>, void *>);
static_assert(cIsSame<TCSigned<void>, void>);

// Types
static_assert(cIsSame<TCUnsigned<int16384>, uint16384>);
static_assert(cIsSame<TCUnsigned<int8192>, uint8192>);
static_assert(cIsSame<TCUnsigned<int4096>, uint4096>);
static_assert(cIsSame<TCUnsigned<int2048>, uint2048>);
static_assert(cIsSame<TCUnsigned<int1024>, uint1024>);
static_assert(cIsSame<TCUnsigned<int512>, uint512>);
static_assert(cIsSame<TCUnsigned<int256>, uint256>);
static_assert(cIsSame<TCUnsigned<int160>, uint160>);
static_assert(cIsSame<TCUnsigned<int192>, uint192>);
static_assert(cIsSame<TCUnsigned<int128>, uint128>);
static_assert(cIsSame<TCUnsigned<int80>, uint80>);
static_assert(cIsSame<TCUnsigned<int96>, uint96>);
static_assert(cIsSame<TCUnsigned<int64>, uint64>);
static_assert(cIsSame<TCUnsigned<int32>, uint32>);
static_assert(cIsSame<TCUnsigned<int16>, uint16>);
static_assert(cIsSame<TCUnsigned<int8>, uint8>);

static_assert(cIsSame<TCUnsigned<aint>, uaint>);
static_assert(cIsSame<TCUnsigned<uaint>, uaint>);
static_assert(cIsSame<TCUnsigned<smint>, umint>);
static_assert(cIsSame<TCUnsigned<umint>, umint>);

static_assert(cIsSame<TCUnsigned<uint4096>, uint4096>);
static_assert(cIsSame<TCUnsigned<uint2048>, uint2048>);
static_assert(cIsSame<TCUnsigned<uint1024>, uint1024>);
static_assert(cIsSame<TCUnsigned<uint512>, uint512>);
static_assert(cIsSame<TCUnsigned<uint256>, uint256>);
static_assert(cIsSame<TCUnsigned<uint160>, uint160>);
static_assert(cIsSame<TCUnsigned<uint192>, uint192>);
static_assert(cIsSame<TCUnsigned<uint128>, uint128>);
static_assert(cIsSame<TCUnsigned<uint80>, uint80>);
static_assert(cIsSame<TCUnsigned<uint96>, uint96>);
static_assert(cIsSame<TCUnsigned<uint64>, uint64>);
static_assert(cIsSame<TCUnsigned<uint32>, uint32>);
static_assert(cIsSame<TCUnsigned<uint16>, uint16>);
static_assert(cIsSame<TCUnsigned<uint8>, uint8>);

static_assert(cIsSame<TCUnsigned<fp4096>, ufp4096>);
static_assert(cIsSame<TCUnsigned<fp2048>, ufp2048>);
static_assert(cIsSame<TCUnsigned<fp1024>, ufp1024>);
static_assert(cIsSame<TCUnsigned<fp512>, ufp512>);
static_assert(cIsSame<TCUnsigned<fp256>, ufp256>);
static_assert(cIsSame<TCUnsigned<fp128>, ufp128>);
static_assert(cIsSame<TCUnsigned<fp80>, ufp80>);
static_assert(cIsSame<TCUnsigned<fp64>, ufp64>);
static_assert(cIsSame<TCUnsigned<fp32>, ufp32>);
static_assert(cIsSame<TCUnsigned<fp16>, ufp16>);
static_assert(cIsSame<TCUnsigned<fp8>, ufp8>);

static_assert(cIsSame<TCUnsigned<const int16384>, const uint16384>);
static_assert(cIsSame<TCUnsigned<const int8192>, const uint8192>);
static_assert(cIsSame<TCUnsigned<const int4096>, const uint4096>);
static_assert(cIsSame<TCUnsigned<const int2048>, const uint2048>);
static_assert(cIsSame<TCUnsigned<const int1024>, const uint1024>);
static_assert(cIsSame<TCUnsigned<const int512>, const uint512>);
static_assert(cIsSame<TCUnsigned<const int256>, const uint256>);
static_assert(cIsSame<TCUnsigned<const int160>, const uint160>);
static_assert(cIsSame<TCUnsigned<const int192>, const uint192>);
static_assert(cIsSame<TCUnsigned<const int128>, const uint128>);
static_assert(cIsSame<TCUnsigned<const int80>, const uint80>);
static_assert(cIsSame<TCUnsigned<const int96>, const uint96>);
static_assert(cIsSame<TCUnsigned<const int64>, const uint64>);
static_assert(cIsSame<TCUnsigned<const int32>, const uint32>);
static_assert(cIsSame<TCUnsigned<const int16>, const uint16>);
static_assert(cIsSame<TCUnsigned<const int8>, const uint8>);

static_assert(cIsSame<TCUnsigned<const uint4096>, const uint4096>);
static_assert(cIsSame<TCUnsigned<const uint2048>, const uint2048>);
static_assert(cIsSame<TCUnsigned<const uint1024>, const uint1024>);
static_assert(cIsSame<TCUnsigned<const uint512>, const uint512>);
static_assert(cIsSame<TCUnsigned<const uint256>, const uint256>);
static_assert(cIsSame<TCUnsigned<const uint160>, const uint160>);
static_assert(cIsSame<TCUnsigned<const uint192>, const uint192>);
static_assert(cIsSame<TCUnsigned<const uint128>, const uint128>);
static_assert(cIsSame<TCUnsigned<const uint80>, const uint80>);
static_assert(cIsSame<TCUnsigned<const uint96>, const uint96>);
static_assert(cIsSame<TCUnsigned<const uint64>, const uint64>);
static_assert(cIsSame<TCUnsigned<const uint32>, const uint32>);
static_assert(cIsSame<TCUnsigned<const uint16>, const uint16>);
static_assert(cIsSame<TCUnsigned<const uint8>, const uint8>);

static_assert(cIsSame<TCUnsigned<const fp4096>, const ufp4096>);
static_assert(cIsSame<TCUnsigned<const fp2048>, const ufp2048>);
static_assert(cIsSame<TCUnsigned<const fp1024>, const ufp1024>);
static_assert(cIsSame<TCUnsigned<const fp512>, const ufp512>);
static_assert(cIsSame<TCUnsigned<const fp256>, const ufp256>);
static_assert(cIsSame<TCUnsigned<const fp128>, const ufp128>);
static_assert(cIsSame<TCUnsigned<const fp80>, const ufp80>);
static_assert(cIsSame<TCUnsigned<const fp64>, const ufp64>);
static_assert(cIsSame<TCUnsigned<const fp32>, const ufp32>);
static_assert(cIsSame<TCUnsigned<const fp16>, const ufp16>);
static_assert(cIsSame<TCUnsigned<const fp8>, const ufp8>);

static_assert(cIsSame<TCUnsigned<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCUnsigned<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCUnsigned<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCUnsigned<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCUnsigned<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCUnsigned<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCUnsigned<CTestClass>, CTestClass>);
static_assert(cIsSame<TCUnsigned<CTestC>, CTestC>);
static_assert(cIsSame<TCUnsigned<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCUnsigned<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCUnsigned<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCUnsigned<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCUnsigned<CTestRef>, CTestRef>);
static_assert(cIsSame<TCUnsigned<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCUnsigned<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCUnsigned<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCUnsigned<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCUnsigned<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCUnsigned<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCUnsigned<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCUnsigned<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCUnsigned<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCUnsigned<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCUnsigned<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCUnsigned<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCUnsigned<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCUnsigned<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCUnsigned<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCUnsigned<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCUnsigned<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCUnsigned<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCUnsigned<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCUnsigned<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCUnsigned<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCUnsigned<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCUnsigned<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCUnsigned<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCUnsigned<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCUnsigned<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCUnsigned<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCUnsigned<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCUnsigned<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCUnsigned<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCUnsigned<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCUnsigned<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCUnsigned<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCUnsigned<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCUnsigned<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCUnsigned<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCUnsigned<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCUnsigned<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCUnsigned<CMPtr>, CMPtr>);
static_assert(cIsSame<TCUnsigned<CMCPtr>, CMCPtr>);
static_assert(cIsSame<TCUnsigned<CMPtrC>, CMPtrC>);
static_assert(cIsSame<TCUnsigned<CMCPtrC>, CMCPtrC>);
static_assert(cIsSame<TCUnsigned<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCUnsigned<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCUnsigned<CTestArray>, CTestArray>);
static_assert(cIsSame<TCUnsigned<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCUnsigned<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCUnsigned<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCUnsigned<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCUnsigned<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCUnsigned<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCUnsigned<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCUnsigned<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCUnsigned<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCUnsigned<void *>, void *>);
static_assert(cIsSame<TCUnsigned<void>, void>);

// From size
static_assert(cIsSame<TCIntFromSize<16384/8>, int16384>);
static_assert(cIsSame<TCIntFromSize<8192/8>, int8192>);
static_assert(cIsSame<TCIntFromSize<4096/8>, int4096>);
static_assert(cIsSame<TCIntFromSize<2048/8>, int2048>);
static_assert(cIsSame<TCIntFromSize<1024/8>, int1024>);
static_assert(cIsSame<TCIntFromSize<512/8>, int512>);
static_assert(cIsSame<TCIntFromSize<256/8>, int256>);
static_assert(cIsSame<TCIntFromSize<160/8>, int160>);
static_assert(cIsSame<TCIntFromSize<192/8>, int192>);
static_assert(cIsSame<TCIntFromSize<128/8>, int128>);
static_assert(cIsSame<TCIntFromSize<64/8>, int64>);
static_assert(cIsSame<TCIntFromSize<80/8>, int80>);
static_assert(cIsSame<TCIntFromSize<96/8>, int96>);
static_assert(cIsSame<TCIntFromSize<32/8>, int32>);
static_assert(cIsSame<TCIntFromSize<16/8>, int16>);
static_assert(cIsSame<TCIntFromSize<8/8>, int8>);

static_assert(cIsSame<TCFloatFromSize<4096/8>, fp4096>);
static_assert(cIsSame<TCFloatFromSize<2048/8>, fp2048>);
static_assert(cIsSame<TCFloatFromSize<1024/8>, fp1024>);
static_assert(cIsSame<TCFloatFromSize<512/8>, fp512>);
static_assert(cIsSame<TCFloatFromSize<256/8>, fp256>);
static_assert(cIsSame<TCFloatFromSize<128/8>, fp128>);
static_assert(cIsSame<TCFloatFromSize<80/8>, fp80>);
static_assert(cIsSame<TCFloatFromSize<64/8>, fp64>);
static_assert(cIsSame<TCFloatFromSize<32/8>, fp32>);
static_assert(cIsSame<TCFloatFromSize<16/8>, fp16>);
static_assert(cIsSame<TCFloatFromSize<8/8>, fp8>);
