// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	TCIsScalar<int8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<int8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<aint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uaint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<smint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<mint>::mc_Value	));

DMibStaticCheck((	TCIsScalar<uint8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<uint8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<fp4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<fp8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const int8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const int8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const aint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uaint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const smint>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const mint>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const uint8192>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint160>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const uint8>::mc_Value	));

DMibStaticCheck((	TCIsScalar<const fp4096>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp2048>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp1024>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp512>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp256>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp128>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp80>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp64>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp32>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp16>::mc_Value	));
DMibStaticCheck((	TCIsScalar<const fp8>::mc_Value	));

DMibStaticCheck((	!TCIsScalar<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsScalar<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsScalar<CTestC>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestCPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestPtrC>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<CMPtr>::mc_Value				));
DMibStaticCheck((	TCIsScalar<CMCPtr>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMPtrC>::mc_Value			));
DMibStaticCheck((	TCIsScalar<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsScalar<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsScalar<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsScalar<void *>::mc_Value			));
DMibStaticCheck((	!TCIsScalar<void>::mc_Value				));

