// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

namespace NPolymorphic
{

	class CAbstract
	{
		virtual void f_Test() = 0;
	};
	class CInheritAbstract : private CAbstract
	{
	};
	class CNonAbstract
	{
		virtual void f_Test();
	};
	class CNonVirtual
	{
		void f_Test();
	};

	DMibStaticCheck((	TCIsPolymorphic<CAbstract>::mc_Value						));
	DMibStaticCheck((	TCIsPolymorphic<CInheritAbstract>::mc_Value						));
	DMibStaticCheck((	TCIsPolymorphic<CNonAbstract>::mc_Value						));
	DMibStaticCheck((	!TCIsPolymorphic<CNonVirtual>::mc_Value						));
}

DMibStaticCheck((	!TCIsPolymorphic<CTestCV>::mc_Value	));
DMibStaticCheck((	!TCIsPolymorphic<ETestEnum>::mc_Value	));

// Void
DMibStaticCheck((	!TCIsPolymorphic<CTestUnion>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestClass0>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestClass1>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestStruct0>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestStruct1>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<const CTestClass0>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<const CTestClass1>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<const CTestStruct0>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<const CTestStruct1>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<volatile CTestClass0>::mc_Value			));
DMibStaticCheck((	!TCIsPolymorphic<volatile CTestClass1>::mc_Value			));
DMibStaticCheck((	!TCIsPolymorphic<volatile CTestStruct0>::mc_Value			));
DMibStaticCheck((	!TCIsPolymorphic<volatile CTestStruct1>::mc_Value			));
DMibStaticCheck((	!TCIsPolymorphic<const volatile CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsPolymorphic<const volatile CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsPolymorphic<const volatile CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsPolymorphic<const volatile CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsPolymorphic<ETestEnum>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<int>::mc_Value							));
DMibStaticCheck((	!TCIsPolymorphic<CTestClass>::mc_Value							));
DMibStaticCheck((	!TCIsPolymorphic<CTestC>::mc_Value							));
DMibStaticCheck((	!TCIsPolymorphic<CTestV>::mc_Value							));
DMibStaticCheck((	!TCIsPolymorphic<CTestCV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestCVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestCRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestVRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestCVRef>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestRRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestCRRef>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestCVRRef>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<PFFunc0>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<PFFunc1>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<PFFunc2>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0Ref>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1Ref>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2Ref>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0RRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1RRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2RRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2Ptr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2Ptr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2PtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2PtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2PtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2CPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2CPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2CPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2CPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2VPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2VPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2VPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2VPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2CVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2CVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2CVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2CVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<PFFunc0El>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<PFFunc1El>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<PFFunc2El>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2ElRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2ElRRef>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2ElPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElCPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElCPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElCPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElCPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElVPtrCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElCVPtr>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElCVPtrC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElCVPtrV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc0ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc1ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<FMFunc2ElCVPtrCV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<CMPtr>::mc_Value							));
DMibStaticCheck((	!TCIsPolymorphic<CMCPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMCVPtr>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMCPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMVPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMCVPtrC>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMCPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMVPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMCVPtrV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMCPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMVPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CMCVPtrCV>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<CTestArray2>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestArray2C>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestArray2V>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestArray2CV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestArray>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTestArrayCV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest2DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest2DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<CTest2DArray2V>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<CTest2DArray2CV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<CTest2DArray>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest2DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest2DArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest2DArrayCV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<CTest3DArray2>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest3DArray2C>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<CTest3DArray2V>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<CTest3DArray2CV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<CTest3DArray>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest3DArrayC>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest3DArrayV>::mc_Value					));
DMibStaticCheck((	!TCIsPolymorphic<CTest3DArrayCV>::mc_Value				));
DMibStaticCheck((	!TCIsPolymorphic<void *>::mc_Value						));
DMibStaticCheck((	!TCIsPolymorphic<void>::mc_Value							));

