// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClassVirtual, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<int, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestUnion, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClassWithPrivateConstructor, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClassWithPrivateDestructor, 128>::CType>::mc_Value == 128		));


DMibStaticCheck((	TCAlignmentOf<CTestUnion>::mc_Value != 0			));
DMibStaticCheck((	TCAlignmentOf<CTestClass0>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestClass1>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestStruct0>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestStruct1>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<const CTestClass0>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<const CTestClass1>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<const CTestStruct0>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<const CTestStruct1>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<volatile CTestClass0>::mc_Value != 0			));
DMibStaticCheck((	TCAlignmentOf<volatile CTestClass1>::mc_Value != 0			));
DMibStaticCheck((	TCAlignmentOf<volatile CTestStruct0>::mc_Value != 0			));
DMibStaticCheck((	TCAlignmentOf<volatile CTestStruct1>::mc_Value != 0			));
DMibStaticCheck((	TCAlignmentOf<const volatile CTestClass0>::mc_Value != 0		));
DMibStaticCheck((	TCAlignmentOf<const volatile CTestClass1>::mc_Value != 0		));
DMibStaticCheck((	TCAlignmentOf<const volatile CTestStruct0>::mc_Value != 0	));
DMibStaticCheck((	TCAlignmentOf<const volatile CTestStruct1>::mc_Value != 0	));
DMibStaticCheck((	TCAlignmentOf<ETestEnum>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<int>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CTestClass>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CTestC>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CTestV>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CTestCV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestVPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestPtrC>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestCVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestPtrV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestCVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestCPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestVPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestCVPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestVRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCVRef>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestRRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCRRef>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestVRRef>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestCVRRef>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<PFFunc0>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<PFFunc1>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<PFFunc2>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0Ref>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1Ref>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2Ref>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0RRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1RRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2RRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0Ptr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1Ptr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2Ptr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc1PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc2PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc0PtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc1PtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc2PtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc0PtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc1PtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc2PtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0Ptr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1Ptr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2Ptr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0PtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1PtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2PtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0PtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1PtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2PtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0VPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1VPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2VPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0VPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1VPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2VPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0VPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1VPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2VPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0VPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1VPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2VPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CVPtrCV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CVPtrCV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CVPtrCV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<PFFunc0El>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<PFFunc1El>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<PFFunc2El>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElRRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElRRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElRRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElVPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElVPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElVPtrCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCVPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCVPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCVPtrV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCVPtrCV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCVPtrCV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCVPtrCV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CMPtr>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CMCPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMVPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMCVPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMPtrC>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMCPtrC>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMVPtrC>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMCVPtrC>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMPtrV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMCPtrV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMVPtrV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMCVPtrV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMPtrCV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMCPtrCV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMVPtrCV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMCVPtrCV>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestArray2>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArray2C>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArray2V>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArray2CV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArray>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArrayC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArrayV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArrayCV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest2DArray2>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest2DArray2C>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest2DArray2V>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest2DArray2CV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest2DArray>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest2DArrayC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest2DArrayV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest2DArrayCV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest3DArray2>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest3DArray2C>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest3DArray2V>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest3DArray2CV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest3DArray>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest3DArrayC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest3DArrayV>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest3DArrayCV>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<void *>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<void>::mc_Value == 0							));


DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestUnion, 128>::CType>::mc_Value == 128			));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClass0, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClass1, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestStruct0, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestStruct1, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const CTestClass0, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const CTestClass1, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const CTestStruct0, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const CTestStruct1, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<volatile CTestClass0, 128>::CType>::mc_Value == 128			));
DMibStaticCheck((	TCAlignmentOf<TCAlign<volatile CTestClass1, 128>::CType>::mc_Value == 128			));
DMibStaticCheck((	TCAlignmentOf<TCAlign<volatile CTestStruct0, 128>::CType>::mc_Value == 128			));
DMibStaticCheck((	TCAlignmentOf<TCAlign<volatile CTestStruct1, 128>::CType>::mc_Value == 128			));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const volatile CTestClass0, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const volatile CTestClass1, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const volatile CTestStruct0, 128>::CType>::mc_Value == 128	));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const volatile CTestStruct1, 128>::CType>::mc_Value == 128	));
DMibStaticCheck((	TCAlignmentOf<TCAlign<ETestEnum, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<int, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClass, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestC, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestV, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestVPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestPtrC, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestPtrV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestVPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCVPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestVRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCVRef, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestRRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCRRef, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestVRRef, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCVRRef, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc0, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc1, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc2, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0Ref, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1Ref, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2Ref, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0RRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1RRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2RRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0Ptr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1Ptr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2Ptr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0PtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1PtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2PtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0PtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1PtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2PtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0Ptr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1Ptr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2Ptr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0PtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1PtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2PtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0PtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1PtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2PtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0VPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1VPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2VPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0VPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1VPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2VPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0VPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1VPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2VPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0VPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1VPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2VPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CVPtrCV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CVPtrCV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CVPtrCV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc0El, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc1El, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc2El, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElRRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElRRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElRRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElVPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElVPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElVPtrCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCVPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCVPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCVPtrV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCVPtrCV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCVPtrCV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCVPtrCV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMPtr, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMVPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCVPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMPtrC, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCPtrC, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMVPtrC, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCVPtrC, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMPtrV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCPtrV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMVPtrV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCVPtrV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMPtrCV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCPtrCV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMVPtrCV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCVPtrCV, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArray2, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArray2C, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArray2V, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArray2CV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArray, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArrayC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArrayV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArrayCV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArray2, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArray2C, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArray2V, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArray2CV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArray, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArrayC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArrayV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArrayCV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArray2, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArray2C, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArray2V, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArray2CV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArray, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArrayC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArrayV, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArrayCV, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<void *, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<void, 128>::CType>::mc_Value != 128							));

