// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsLValueReference<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestStruct0>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTestStruct1>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<ETestEnum>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestClass>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CTestPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsLValueReference<CTestRef>::mc_Value			));
DMibStaticCheck((	TCIsLValueReference<CTestCRef>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestRRef>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsLValueReference<FFunc0Ref>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<FFunc1Ref>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<FFunc2Ref>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc0RRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc1RRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc2RRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2CPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsLValueReference<FFunc0ElRef>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<FFunc1ElRef>::mc_Value	));
DMibStaticCheck((	TCIsLValueReference<FFunc2ElRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc0ElRRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc1ElRRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc2ElRRef>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<FMFunc0ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc1ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<FMFunc2ElCPtrC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CMPtr>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArray>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest2DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArray2>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArray>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<CTest3DArrayC>::mc_Value	));
DMibStaticCheck((	!TCIsLValueReference<void *>::mc_Value			));
DMibStaticCheck((	!TCIsLValueReference<void>::mc_Value			));



DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestUnion>::CType, CTestUnion &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestClass0>::CType, CTestClass0 &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestClass1>::CType, CTestClass1 &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestStruct0>::CType, CTestStruct0 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestStruct1>::CType, CTestStruct1 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<ETestEnum>::CType, ETestEnum &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestClass>::CType, CTestClass &>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestC>::CType, CTestC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestPtr>::CType, CTestPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCPtr>::CType, CTestCPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestPtrC>::CType, CTestPtrC &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCPtrC>::CType, CTestCPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestRef>::CType, CTestRef>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCRef>::CType, CTestCRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestRRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestCRRef>::CType, CTestCRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc0>::CType, PFFunc0 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc1>::CType, PFFunc1 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc2>::CType, PFFunc2 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0Ref>::CType, FFunc0Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1Ref>::CType, FFunc1Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2Ref>::CType, FFunc2Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0RRef>::CType, FFunc0Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1RRef>::CType, FFunc1Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2RRef>::CType, FFunc2Ref>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0Ptr>::CType, FFunc0Ptr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1Ptr>::CType, FFunc1Ptr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2Ptr>::CType, FFunc2Ptr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0PtrC>::CType, FFunc0PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1PtrC>::CType, FFunc1PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2PtrC>::CType, FFunc2PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0Ptr>::CType, FMFunc0Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1Ptr>::CType, FMFunc1Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2Ptr>::CType, FMFunc2Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0PtrC>::CType, FMFunc0PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1PtrC>::CType, FMFunc1PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2PtrC>::CType, FMFunc2PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CPtr>::CType, FMFunc0CPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CPtr>::CType, FMFunc1CPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CPtr>::CType, FMFunc2CPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc0El>::CType, PFFunc0El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc1El>::CType, PFFunc1El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<PFFunc2El>::CType, PFFunc2El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElRRef>::CType, FFunc0ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElRRef>::CType, FFunc1ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElRRef>::CType, FFunc2ElRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElPtr>::CType, FFunc0ElPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElPtr>::CType, FFunc1ElPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElPtr>::CType, FFunc2ElPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMPtr>::CType, CMPtr &>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCPtr>::CType, CMCPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMPtrC>::CType, CMPtrC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CMCPtrC>::CType, CMCPtrC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArray2>::CType, CTestArray2 &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArray2C>::CType, CTestArray2C &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArray>::CType, CTestArray>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTestArrayC>::CType, CTestArrayC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArray2>::CType, CTest2DArray2 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArray2C>::CType, CTest2DArray2C &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArray>::CType, CTest2DArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArray2>::CType, CTest3DArray2 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArray2C>::CType, CTest3DArray2C &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArray>::CType, CTest3DArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<void *>::CType, void *&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddLValueReference<void>::CType, void>::mc_Value								));

// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestPtr>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCPtrC>::CType, CTestCPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestRef>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCRef>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestRRef>::CType, CTestRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0Ref>::CType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1Ref>::CType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2Ref>::CType, PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElRef>::CType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElRef>::CType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElRef>::CType, PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMPtrC>::CType, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<void *&>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveLValueReference<void>::CType, void>::mc_Value							));
