// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsArray<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsArray<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsArray<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsArray<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsArray<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsArray<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsArray<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CTestCRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CTestRRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArray<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsArray<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsArray<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc0Ref>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc1Ref>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc2Ref>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc0RRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc1RRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc2RRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsArray<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsArray<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsArray<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArray<CMCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsArray<CTestArray2>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsArray<CTestArrayC>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsArray<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArray<void *>::mc_Value			));
DMibStaticCheck((	!TCIsArray<void>::mc_Value				));


DMibStaticCheck((	!TCIsArrayUnbounded<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestCRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestRRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestCRRef>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<PFFunc2>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc0Ref>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc1Ref>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc2Ref>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc0RRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc1RRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc2RRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<PFFunc2El>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsArrayUnbounded<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsArrayUnbounded<CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsArrayUnbounded<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsArrayUnbounded<CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsArrayUnbounded<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<CTest3DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsArrayUnbounded<CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsArrayUnbounded<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsArrayUnbounded<void *>::mc_Value			));
DMibStaticCheck((	!TCIsArrayUnbounded<void>::mc_Value				));


DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestClass0>::CType, CTestClass0>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestClass1>::CType, CTestClass1>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<ETestEnum>::CType, ETestEnum>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestClass>::CType, CTestClass>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestPtr>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestCPtr>::CType, CTestCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestPtrC>::CType, CTestPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestCPtrC>::CType, CTestCPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestCRef>::CType, CTestCRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestRRef>::CType, CTestRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc0Ref>::CType, FFunc0Ref>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc1Ref>::CType, FFunc1Ref>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc2Ref>::CType, FFunc2Ref>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc0RRef>::CType, FFunc0RRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc1RRef>::CType, FFunc1RRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc2RRef>::CType, FFunc2RRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CMPtr>::CType, CMPtr>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CMPtrC>::CType, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CMCPtrC>::CType, CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestArray2>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestArray2C>::CType, CTestBase const>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestArray>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTestArrayC>::CType, CTestBase const>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTest2DArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTest2DArray2C>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTest2DArray>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTest2DArrayC>::CType, CTestArray2C>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTest3DArray2>::CType, CTest2DArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTest3DArray2C>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTest3DArray>::CType, CTest2DArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<CTest3DArrayC>::CType, CTest2DArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveExtent<void>::CType, void>::mc_Value							));


// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestClass0>::CType, CTestClass0>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestClass1>::CType, CTestClass1>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<ETestEnum>::CType, ETestEnum>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestClass>::CType, CTestClass>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestC>::CType, CTestC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestPtr>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestCPtr>::CType, CTestCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestPtrC>::CType, CTestPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestCPtrC>::CType, CTestCPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestCRef>::CType, CTestCRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestRRef>::CType, CTestRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<PFFunc0>::CType, PFFunc0>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<PFFunc1>::CType, PFFunc1>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<PFFunc2>::CType, PFFunc2>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc0Ref>::CType, FFunc0Ref>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc1Ref>::CType, FFunc1Ref>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc2Ref>::CType, FFunc2Ref>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc0RRef>::CType, FFunc0RRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc1RRef>::CType, FFunc1RRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc2RRef>::CType, FFunc2RRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<PFFunc0El>::CType, PFFunc0El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<PFFunc1El>::CType, PFFunc1El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<PFFunc2El>::CType, PFFunc2El>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CMPtr>::CType, CMPtr>::mc_Value							));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CMPtrC>::CType, CMPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CMCPtrC>::CType, CMCPtrC>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestArray2>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestArray2C>::CType, CTestBase const>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestArray>::CType, CTestBase>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTestArrayC>::CType, CTestBase const>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTest2DArray2>::CType, CTestBase>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTest2DArray2C>::CType, CTestBase const>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTest2DArray>::CType, CTestBase>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTest2DArrayC>::CType, CTestBase const>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTest3DArray2>::CType, CTestBase>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTest3DArray2C>::CType, CTestBase const>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTest3DArray>::CType, CTestBase>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<CTest3DArrayC>::CType, CTestBase const>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveAllExtents<void>::CType, void>::mc_Value							));


// Remove pointer
DMibStaticCheck((	TCIsSame<TCDecay<CTestUnion>::CType, CTestUnion>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<CTestStruct0>::CType, CTestStruct0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<CTestStruct1>::CType, CTestStruct1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCDecay<CTestC>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCDecay<CTestPtr>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<CTestPtrC>::CType, CTestPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<CTestCPtrC>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<CTestRef>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCDecay<CTestCRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<CTestRRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<CTestCRRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<PFFunc0>::CType, FFunc0Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<PFFunc1>::CType, FFunc1Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<PFFunc2>::CType, FFunc2Ptr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc0Ref>::CType, FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc1Ref>::CType, FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc2Ref>::CType, FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc0RRef>::CType, FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc1RRef>::CType, FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc2RRef>::CType, FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc0PtrC>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc1PtrC>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc2PtrC>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc0PtrC>::CType, FMFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc1PtrC>::CType, FMFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc2PtrC>::CType, FMFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc0CPtrC>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc1CPtrC>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc2CPtrC>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<PFFunc0El>::CType, FFunc0ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<PFFunc1El>::CType, FFunc1ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<PFFunc2El>::CType, FFunc2ElPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc0ElRef>::CType, FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc1ElRef>::CType, FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc2ElRef>::CType, FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc0ElRRef>::CType, FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc1ElRRef>::CType, FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc2ElRRef>::CType, FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc0ElPtrC>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc1ElPtrC>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FFunc2ElPtrC>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc0ElPtrC>::CType, FMFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc1ElPtrC>::CType, FMFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc2ElPtrC>::CType, FMFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCDecay<CMCPtr>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCDecay<CMPtrC>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCDecay<CMCPtrC>::CType, CMCPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCDecay<CTestArray2>::CType, CTestBase *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<CTestArray2C>::CType, CTestBase const *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<CTestArray>::CType, CTestBase *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCDecay<CTestArrayC>::CType, CTestBase const *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<CTest2DArray2>::CType, CTestArray2 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCDecay<CTest2DArray2C>::CType, CTestArray2C *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCDecay<CTest2DArray>::CType, CTestArray2 *>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCDecay<CTest2DArrayC>::CType, CTestArray2C *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCDecay<CTest3DArray2>::CType, CTest2DArray2 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCDecay<CTest3DArray2C>::CType, CTest2DArray2C *>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCDecay<CTest3DArray>::CType, CTest2DArray2 *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCDecay<CTest3DArrayC>::CType, CTest2DArray2C *>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCDecay<void *>::CType, void *>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCDecay<void>::CType, void>::mc_Value							));


// Extent
DMibStaticCheck((	TCExtent<CTestUnion>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestClass0>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTestClass1>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTestStruct0>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTestStruct1>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<ETestEnum>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestClass>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<CTestC>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<CTestPtr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestCPtr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestCPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestCRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestRRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestCRRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<PFFunc0>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<PFFunc1>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<PFFunc2>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<FFunc0Ref>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc1Ref>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc2Ref>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc0RRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc1RRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc2RRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc0Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc1Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc2Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc0PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc1PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc2PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FMFunc0Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FMFunc1Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FMFunc2Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FMFunc0PtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc1PtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc2PtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc0CPtr>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc1CPtr>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc2CPtr>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc0CPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc1CPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc2CPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<PFFunc0El>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<PFFunc1El>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<PFFunc2El>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<FFunc0ElRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc1ElRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc2ElRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc0ElRRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc1ElRRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc2ElRRef>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc0ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc1ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc2ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc0ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc1ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FFunc2ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FMFunc0ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FMFunc1ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FMFunc2ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<FMFunc0ElPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc1ElPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc2ElPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc0ElCPtr>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc1ElCPtr>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc2ElCPtr>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc0ElCPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc1ElCPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<FMFunc2ElCPtrC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CMPtr>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<CMCPtr>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<CMPtrC>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<CMCPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestArray2>::mc_Value == 2		));
DMibStaticCheck((	TCExtent<CTestArray2C>::mc_Value == 2		));
DMibStaticCheck((	TCExtent<CTestArray>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<CTestArrayC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTest2DArray2>::mc_Value == 3		));
DMibStaticCheck((	TCExtent<CTest2DArray2C>::mc_Value == 3		));
DMibStaticCheck((	TCExtent<CTest2DArray>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTest2DArrayC>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTest3DArray2>::mc_Value == 4		));
DMibStaticCheck((	TCExtent<CTest3DArray2C>::mc_Value == 4		));
DMibStaticCheck((	TCExtent<CTest3DArray>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTest3DArrayC>::mc_Value == 0		));

DMibStaticCheck((	TCExtent<CTestArray2, 1>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTestArray2C, 1>::mc_Value == 0	));
DMibStaticCheck((	TCExtent<CTestArray, 1>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTestArrayC, 1>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTest2DArray2, 1>::mc_Value == 2	));
DMibStaticCheck((	TCExtent<CTest2DArray2C, 1>::mc_Value == 2	));
DMibStaticCheck((	TCExtent<CTest2DArray, 1>::mc_Value == 2	));
DMibStaticCheck((	TCExtent<CTest2DArrayC, 1>::mc_Value == 2	));
DMibStaticCheck((	TCExtent<CTest3DArray2, 1>::mc_Value == 3	));
DMibStaticCheck((	TCExtent<CTest3DArray2C, 1>::mc_Value == 3	));
DMibStaticCheck((	TCExtent<CTest3DArray, 1>::mc_Value == 3	));
DMibStaticCheck((	TCExtent<CTest3DArrayC, 1>::mc_Value == 3	));

DMibStaticCheck((	TCExtent<CTestArray2, 2>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTestArray2C, 2>::mc_Value == 0	));
DMibStaticCheck((	TCExtent<CTestArray, 2>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTestArrayC, 2>::mc_Value == 0		));
DMibStaticCheck((	TCExtent<CTest2DArray2, 2>::mc_Value == 0	));
DMibStaticCheck((	TCExtent<CTest2DArray2C, 2>::mc_Value == 0	));
DMibStaticCheck((	TCExtent<CTest2DArray, 2>::mc_Value == 0	));
DMibStaticCheck((	TCExtent<CTest2DArrayC, 2>::mc_Value == 0	));
DMibStaticCheck((	TCExtent<CTest3DArray2, 2>::mc_Value == 2	));
DMibStaticCheck((	TCExtent<CTest3DArray2C, 2>::mc_Value == 2	));
DMibStaticCheck((	TCExtent<CTest3DArray, 2>::mc_Value == 2	));
DMibStaticCheck((	TCExtent<CTest3DArrayC, 2>::mc_Value == 2	));

DMibStaticCheck((	TCExtent<void>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<void *>::mc_Value == 0				));
DMibStaticCheck((	TCExtent<void, 1>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<void *, 1>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<void, 2>::mc_Value == 0			));
DMibStaticCheck((	TCExtent<void *, 2>::mc_Value == 0			));


// Rank
DMibStaticCheck((	TCRank<CTestUnion>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestClass0>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestClass1>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestStruct0>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestStruct1>::mc_Value == 0			));
DMibStaticCheck((	TCRank<ETestEnum>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestClass>::mc_Value == 0				));
DMibStaticCheck((	TCRank<CTestC>::mc_Value == 0				));
DMibStaticCheck((	TCRank<CTestPtr>::mc_Value == 0				));
DMibStaticCheck((	TCRank<CTestCPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestCPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestRef>::mc_Value == 0				));
DMibStaticCheck((	TCRank<CTestCRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestRRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CTestCRRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<PFFunc0>::mc_Value == 0				));
DMibStaticCheck((	TCRank<PFFunc1>::mc_Value == 0				));
DMibStaticCheck((	TCRank<PFFunc2>::mc_Value == 0				));
DMibStaticCheck((	TCRank<FFunc0Ref>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc1Ref>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc2Ref>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc0RRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc1RRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc2RRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc0Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc1Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc2Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc0PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc1PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc2PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc0Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc1Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc2Ptr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc0PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc1PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc2PtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc0CPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc1CPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc2CPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc0CPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc1CPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc2CPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<PFFunc0El>::mc_Value == 0				));
DMibStaticCheck((	TCRank<PFFunc1El>::mc_Value == 0				));
DMibStaticCheck((	TCRank<PFFunc2El>::mc_Value == 0				));
DMibStaticCheck((	TCRank<FFunc0ElRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc1ElRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc2ElRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc0ElRRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc1ElRRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc2ElRRef>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc0ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc1ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc2ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc0ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc1ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FFunc2ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc0ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc1ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc2ElPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc0ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc1ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc2ElPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc0ElCPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc1ElCPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc2ElCPtr>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc0ElCPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc1ElCPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<FMFunc2ElCPtrC>::mc_Value == 0			));
DMibStaticCheck((	TCRank<CMPtr>::mc_Value == 0				));
DMibStaticCheck((	TCRank<CMCPtr>::mc_Value == 0				));
DMibStaticCheck((	TCRank<CMPtrC>::mc_Value == 0				));
DMibStaticCheck((	TCRank<CMCPtrC>::mc_Value == 0				));
DMibStaticCheck((	TCRank<CTestArray2>::mc_Value == 1			));
DMibStaticCheck((	TCRank<CTestArray2C>::mc_Value == 1			));
DMibStaticCheck((	TCRank<CTestArray>::mc_Value == 1			));
DMibStaticCheck((	TCRank<CTestArrayC>::mc_Value == 1			));
DMibStaticCheck((	TCRank<CTest2DArray2>::mc_Value == 2		));
DMibStaticCheck((	TCRank<CTest2DArray2C>::mc_Value == 2		));
DMibStaticCheck((	TCRank<CTest2DArray>::mc_Value == 2			));
DMibStaticCheck((	TCRank<CTest2DArrayC>::mc_Value == 2		));
DMibStaticCheck((	TCRank<CTest3DArray2>::mc_Value == 3		));
DMibStaticCheck((	TCRank<CTest3DArray2C>::mc_Value == 3		));
DMibStaticCheck((	TCRank<CTest3DArray>::mc_Value == 3			));
DMibStaticCheck((	TCRank<CTest3DArrayC>::mc_Value == 3		));
DMibStaticCheck((	TCRank<void>::mc_Value == 0					));
DMibStaticCheck((	TCRank<void *>::mc_Value == 0				));
