// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	!TCIsReference<CTestUnion>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestClass0>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestClass1>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestStruct0>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestStruct1>::mc_Value		));
DMibStaticCheck((	!TCIsReference<ETestEnum>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestClass>::mc_Value				));
DMibStaticCheck((	!TCIsReference<CTestC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsReference<CTestRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestCRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestRRef>::mc_Value			));
DMibStaticCheck((	TCIsReference<CTestCRRef>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc0>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc1>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsReference<FFunc0Ref>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc1Ref>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc2Ref>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc0RRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc1RRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc2RRef>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc0Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc1Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc2Ptr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2Ptr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2PtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<PFFunc0El>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc1El>::mc_Value			));
DMibStaticCheck((	!TCIsReference<PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsReference<FFunc0ElRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc1ElRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc2ElRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc0ElRRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc1ElRRef>::mc_Value		));
DMibStaticCheck((	TCIsReference<FFunc2ElRRef>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<FFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCPtr>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CMPtr>::mc_Value				));
DMibStaticCheck((	!TCIsReference<CMCPtr>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CMCPtrC>::mc_Value			));
DMibStaticCheck((	!TCIsReference<CTestArray2>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArray2C>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArray>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTestArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest2DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest2DArray>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest3DArray2>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	!TCIsReference<CTest3DArray>::mc_Value		));
DMibStaticCheck((	!TCIsReference<CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	!TCIsReference<void *>::mc_Value			));
DMibStaticCheck((	!TCIsReference<void>::mc_Value				));



DMibStaticCheck((	TCIsSame<TCAddReference<CTestUnion>::CType, CTestUnion &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestClass0>::CType, CTestClass0 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestClass1>::CType, CTestClass1 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestStruct0>::CType, CTestStruct0 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestStruct1>::CType, CTestStruct1 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<ETestEnum>::CType, ETestEnum &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestClass>::CType, CTestClass &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestC>::CType, CTestC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestPtr>::CType, CTestPtr &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCPtr>::CType, CTestCPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestPtrC>::CType, CTestPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCPtrC>::CType, CTestCPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestRef>::CType, CTestRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCRef>::CType, CTestCRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestRRef>::CType, CTestRRef>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestCRRef>::CType, CTestCRRef>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc0>::CType, PFFunc0 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc1>::CType, PFFunc1 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc2>::CType, PFFunc2 &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0Ptr>::CType, FFunc0Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1Ptr>::CType, FFunc1Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2Ptr>::CType, FFunc2Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0PtrC>::CType, FFunc0PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1PtrC>::CType, FFunc1PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2PtrC>::CType, FFunc2PtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0Ptr>::CType, FMFunc0Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1Ptr>::CType, FMFunc1Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2Ptr>::CType, FMFunc2Ptr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0PtrC>::CType, FMFunc0PtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1PtrC>::CType, FMFunc1PtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2PtrC>::CType, FMFunc2PtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CPtr>::CType, FMFunc0CPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CPtr>::CType, FMFunc1CPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CPtr>::CType, FMFunc2CPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc0El>::CType, PFFunc0El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc1El>::CType, PFFunc1El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<PFFunc2El>::CType, PFFunc2El &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElPtr>::CType, FFunc0ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElPtr>::CType, FFunc1ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElPtr>::CType, FFunc2ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr &>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CMPtr>::CType, CMPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCPtr>::CType, CMCPtr &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CMPtrC>::CType, CMPtrC &>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<CMCPtrC>::CType, CMCPtrC &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArray2>::CType, CTestArray2 &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArray2C>::CType, CTestArray2C &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArray>::CType, CTestArray>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTestArrayC>::CType, CTestArrayC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArray2>::CType, CTest2DArray2 &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArray2C>::CType, CTest2DArray2C &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArray>::CType, CTest2DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArray2>::CType, CTest3DArray2 &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArray2C>::CType, CTest3DArray2C &>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArray>::CType, CTest3DArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCAddReference<void *>::CType, void *&>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCAddReference<void>::CType, void>::mc_Value							));

// Remove pointer
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCRef>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestRRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestCRRef>::CType, CTestC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc2>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0Ref>::CType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1Ref>::CType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2Ref>::CType, PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0RRef>::CType, PFFunc0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1RRef>::CType, PFFunc1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2RRef>::CType, PFFunc2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<PFFunc2El>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElRef>::CType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElRef>::CType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElRef>::CType, PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElRRef>::CType, PFFunc0El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElRRef>::CType, PFFunc1El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElRRef>::CType, PFFunc2El>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArray2C>::CType, CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArray>::CType, CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArray>::CType, CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArray>::CType, CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReference<void *>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<void *&>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReference<void>::CType, void>::mc_Value						));


// Storable
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestUnion>::CType, CTestUnion>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestClass0>::CType, CTestClass0>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestClass1>::CType, CTestClass1>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestStruct0>::CType, CTestStruct0>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestStruct1>::CType, CTestStruct1>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<ETestEnum>::CType, ETestEnum>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestClass>::CType, CTestClass>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestC>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestPtr>::CType, CTestPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCPtr>::CType, CTestCPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestPtrC>::CType, CTestPtrC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCPtrC>::CType, CTestCPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCRef>::CType, CTestC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestRRef>::CType, CTestClass>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestCRRef>::CType, CTestC>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc0>::CType, PFFunc0>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc1>::CType, PFFunc1>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc2>::CType, PFFunc2>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0Ref>::CType, FFunc0Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1Ref>::CType, FFunc1Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2Ref>::CType, FFunc2Ref>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0RRef>::CType, FFunc0RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1RRef>::CType, FFunc1RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2RRef>::CType, FFunc2RRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0Ptr>::CType, FFunc0Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1Ptr>::CType, FFunc1Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2Ptr>::CType, FFunc2Ptr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0PtrC>::CType, FFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1PtrC>::CType, FFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2PtrC>::CType, FFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0Ptr>::CType, FMFunc0Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1Ptr>::CType, FMFunc1Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2Ptr>::CType, FMFunc2Ptr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0PtrC>::CType, FMFunc0PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1PtrC>::CType, FMFunc1PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2PtrC>::CType, FMFunc2PtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CPtr>::CType, FMFunc0CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CPtr>::CType, FMFunc1CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CPtr>::CType, FMFunc2CPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0CPtrC>::CType, FMFunc0CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1CPtrC>::CType, FMFunc1CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2CPtrC>::CType, FMFunc2CPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc0El>::CType, PFFunc0El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc1El>::CType, PFFunc1El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<PFFunc2El>::CType, PFFunc2El>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElRef>::CType, FFunc0ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElRef>::CType, FFunc1ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElRef>::CType, FFunc2ElRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElRRef>::CType, FFunc0ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElRRef>::CType, FFunc1ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElRRef>::CType, FFunc2ElRRef>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElPtr>::CType, FFunc0ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElPtr>::CType, FFunc1ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElPtr>::CType, FFunc2ElPtr>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc0ElPtrC>::CType, FFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc1ElPtrC>::CType, FFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FFunc2ElPtrC>::CType, FFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElPtr>::CType, FMFunc0ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElPtr>::CType, FMFunc1ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElPtr>::CType, FMFunc2ElPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElPtrC>::CType, FMFunc0ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElPtrC>::CType, FMFunc1ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElPtrC>::CType, FMFunc2ElPtrC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCPtr>::CType, FMFunc0ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCPtr>::CType, FMFunc1ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCPtr>::CType, FMFunc2ElCPtr>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc0ElCPtrC>::CType, FMFunc0ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc1ElCPtrC>::CType, FMFunc1ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<FMFunc2ElCPtrC>::CType, FMFunc2ElCPtrC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMPtr>::CType, CMPtr>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCPtr>::CType, CMCPtr>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMPtrC>::CType, CMPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CMCPtrC>::CType, CMCPtrC>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArray2>::CType, CTestArray2>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArray2C>::CType, CTestArray2C>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArray>::CType, CTestArray>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTestArrayC>::CType, CTestArrayC>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArray2>::CType, CTest2DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArray2C>::CType, CTest2DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArray>::CType, CTest2DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest2DArrayC>::CType, CTest2DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArray2>::CType, CTest3DArray2>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArray2C>::CType, CTest3DArray2C>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArray>::CType, CTest3DArray>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<CTest3DArrayC>::CType, CTest3DArrayC>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<void *>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<void *&>::CType, void *>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCRemoveReferenceStorable<void>::CType, void>::mc_Value						));



// Copy refernce

DMibStaticCheck((	TCIsSame<TCCopyReference<int, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int, int &>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int, int &&>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &, int &>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &, int &&>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &&, int>::CType, int &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &&, int &>::CType, int &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<int &&, int &&>::CType, int &&>::mc_Value					));

DMibStaticCheck((	TCIsSame<TCCopyReference<CTestUnion, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestClass0, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestClass1, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestStruct0, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestStruct1, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<ETestEnum, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestClass, int>::CType, int>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestC, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestPtrC, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestRef, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCRef, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestRRef, int>::CType, int &&>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestCRRef, int>::CType, int &&>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc0, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc1, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc2, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0Ref, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1Ref, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2Ref, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0RRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1RRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2RRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0Ptr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1Ptr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2Ptr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0Ptr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1Ptr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2Ptr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2PtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0CPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1CPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2CPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc0El, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc1El, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<PFFunc2El, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElRef, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElRef, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElRef, int>::CType, int &>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElRRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElRRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElRRef, int>::CType, int &&>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElPtr, int>::CType, int>::mc_Value				));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc0ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc1ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FFunc2ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElPtrC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCPtr, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc0ElCPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc1ElCPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<FMFunc2ElCPtrC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMPtr, int>::CType, int>::mc_Value						));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCPtr, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMPtrC, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CMCPtrC, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArray2, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArray2C, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArray, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTestArrayC, int>::CType, int>::mc_Value			));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArray2, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArray2C, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArray, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest2DArrayC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArray2, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArray2C, int>::CType, int>::mc_Value	));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArray, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<CTest3DArrayC, int>::CType, int>::mc_Value		));
DMibStaticCheck((	TCIsSame<TCCopyReference<void *, int>::CType, int>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<void *&, int>::CType, int &>::mc_Value					));
DMibStaticCheck((	TCIsSame<TCCopyReference<void, int>::CType, int>::mc_Value						));
