// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

static_assert(!cIsMemberObjectPointer<CTestUnion>);
static_assert(!cIsMemberObjectPointer<CTestClass0>);
static_assert(!cIsMemberObjectPointer<CTestClass1>);
static_assert(!cIsMemberObjectPointer<CTestStruct0>);
static_assert(!cIsMemberObjectPointer<CTestStruct1>);
static_assert(!cIsMemberObjectPointer<ETestEnum>);
static_assert(!cIsMemberObjectPointer<CTestClass>);
static_assert(!cIsMemberObjectPointer<CTestC>);
static_assert(!cIsMemberObjectPointer<CTestPtr>);
static_assert(!cIsMemberObjectPointer<CTestCPtr>);
static_assert(!cIsMemberObjectPointer<CTestPtrC>);
static_assert(!cIsMemberObjectPointer<CTestCPtrC>);
static_assert(!cIsMemberObjectPointer<CTestRef>);
static_assert(!cIsMemberObjectPointer<CTestCRef>);
static_assert(!cIsMemberObjectPointer<CTestRRef>);
static_assert(!cIsMemberObjectPointer<CTestCRRef>);
static_assert(!cIsMemberObjectPointer<PFFunc0>);
static_assert(!cIsMemberObjectPointer<PFFunc1>);
static_assert(!cIsMemberObjectPointer<PFFunc2>);
static_assert(!cIsMemberObjectPointer<FFunc0Ref>);
static_assert(!cIsMemberObjectPointer<FFunc1Ref>);
static_assert(!cIsMemberObjectPointer<FFunc2Ref>);
static_assert(!cIsMemberObjectPointer<FFunc0RRef>);
static_assert(!cIsMemberObjectPointer<FFunc1RRef>);
static_assert(!cIsMemberObjectPointer<FFunc2RRef>);
static_assert(!cIsMemberObjectPointer<FFunc0Ptr>);
static_assert(!cIsMemberObjectPointer<FFunc1Ptr>);
static_assert(!cIsMemberObjectPointer<FFunc2Ptr>);
static_assert(!cIsMemberObjectPointer<FFunc0PtrC>);
static_assert(!cIsMemberObjectPointer<FFunc1PtrC>);
static_assert(!cIsMemberObjectPointer<FFunc2PtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc0Ptr>);
static_assert(!cIsMemberObjectPointer<FMFunc1Ptr>);
static_assert(!cIsMemberObjectPointer<FMFunc2Ptr>);
static_assert(!cIsMemberObjectPointer<FMFunc0PtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc1PtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc2PtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc0CPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc1CPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc2CPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc0CPtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc1CPtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc2CPtrC>);
static_assert(!cIsMemberObjectPointer<PFFunc0El>);
static_assert(!cIsMemberObjectPointer<PFFunc1El>);
static_assert(!cIsMemberObjectPointer<PFFunc2El>);
static_assert(!cIsMemberObjectPointer<FFunc0ElRef>);
static_assert(!cIsMemberObjectPointer<FFunc1ElRef>);
static_assert(!cIsMemberObjectPointer<FFunc2ElRef>);
static_assert(!cIsMemberObjectPointer<FFunc0ElRRef>);
static_assert(!cIsMemberObjectPointer<FFunc1ElRRef>);
static_assert(!cIsMemberObjectPointer<FFunc2ElRRef>);
static_assert(!cIsMemberObjectPointer<FFunc0ElPtr>);
static_assert(!cIsMemberObjectPointer<FFunc1ElPtr>);
static_assert(!cIsMemberObjectPointer<FFunc2ElPtr>);
static_assert(!cIsMemberObjectPointer<FFunc0ElPtrC>);
static_assert(!cIsMemberObjectPointer<FFunc1ElPtrC>);
static_assert(!cIsMemberObjectPointer<FFunc2ElPtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc0ElPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc1ElPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc2ElPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc0ElPtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc1ElPtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc2ElPtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc0ElCPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc1ElCPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc2ElCPtr>);
static_assert(!cIsMemberObjectPointer<FMFunc0ElCPtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc1ElCPtrC>);
static_assert(!cIsMemberObjectPointer<FMFunc2ElCPtrC>);
static_assert(cIsMemberObjectPointer<CMPtr>);
static_assert(cIsMemberObjectPointer<CMCPtr>);
static_assert(cIsMemberObjectPointer<CMPtrC>);
static_assert(cIsMemberObjectPointer<CMCPtrC>);
static_assert(!cIsMemberObjectPointer<CTestArray2>);
static_assert(!cIsMemberObjectPointer<CTestArray2C>);
static_assert(!cIsMemberObjectPointer<CTestArray>);
static_assert(!cIsMemberObjectPointer<CTestArrayC>);
static_assert(!cIsMemberObjectPointer<CTest2DArray2>);
static_assert(!cIsMemberObjectPointer<CTest2DArray2C>);
static_assert(!cIsMemberObjectPointer<CTest2DArray>);
static_assert(!cIsMemberObjectPointer<CTest2DArrayC>);
static_assert(!cIsMemberObjectPointer<CTest3DArray2>);
static_assert(!cIsMemberObjectPointer<CTest3DArray2C>);
static_assert(!cIsMemberObjectPointer<CTest3DArray>);
static_assert(!cIsMemberObjectPointer<CTest3DArrayC>);
static_assert(!cIsMemberObjectPointer<void *>);
static_assert(!cIsMemberObjectPointer<void>);

// Remove pointer
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestUnion>, CTestUnion>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestClass0>, CTestClass0>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestClass1>, CTestClass1>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestStruct0>, CTestStruct0>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestStruct1>, CTestStruct1>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<ETestEnum>, ETestEnum>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestClass>, CTestClass>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestC>, CTestC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestPtr>, CTestPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestCPtr>, CTestCPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestPtrC>, CTestPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestCPtrC>, CTestCPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestRef>, CTestRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestCRef>, CTestCRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestRRef>, CTestRRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestCRRef>, CTestCRRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<PFFunc0>, PFFunc0>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<PFFunc1>, PFFunc1>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<PFFunc2>, PFFunc2>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc0Ref>, FFunc0Ref>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc1Ref>, FFunc1Ref>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc2Ref>, FFunc2Ref>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc0RRef>, FFunc0RRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc1RRef>, FFunc1RRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc2RRef>, FFunc2RRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc0Ptr>, FFunc0Ptr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc1Ptr>, FFunc1Ptr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc2Ptr>, FFunc2Ptr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc0PtrC>, FFunc0PtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc1PtrC>, FFunc1PtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc2PtrC>, FFunc2PtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc0Ptr>, FMFunc0Ptr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc1Ptr>, FMFunc1Ptr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc2Ptr>, FMFunc2Ptr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc0PtrC>, FMFunc0PtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc1PtrC>, FMFunc1PtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc2PtrC>, FMFunc2PtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc0CPtr>, FMFunc0CPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc1CPtr>, FMFunc1CPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc2CPtr>, FMFunc2CPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc0CPtrC>, FMFunc0CPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc1CPtrC>, FMFunc1CPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc2CPtrC>, FMFunc2CPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<PFFunc0El>, PFFunc0El>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<PFFunc1El>, PFFunc1El>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<PFFunc2El>, PFFunc2El>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc0ElRef>, FFunc0ElRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc1ElRef>, FFunc1ElRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc2ElRef>, FFunc2ElRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc0ElRRef>, FFunc0ElRRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc1ElRRef>, FFunc1ElRRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc2ElRRef>, FFunc2ElRRef>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc0ElPtr>, FFunc0ElPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc1ElPtr>, FFunc1ElPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc2ElPtr>, FFunc2ElPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc0ElPtrC>, FFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc1ElPtrC>, FFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FFunc2ElPtrC>, FFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc0ElPtr>, FMFunc0ElPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc1ElPtr>, FMFunc1ElPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc2ElPtr>, FMFunc2ElPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc0ElPtrC>, FMFunc0ElPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc1ElPtrC>, FMFunc1ElPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc2ElPtrC>, FMFunc2ElPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCPtr>, FMFunc0ElCPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCPtr>, FMFunc1ElCPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCPtr>, FMFunc2ElCPtr>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc0ElCPtrC>, FMFunc0ElCPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc1ElCPtrC>, FMFunc1ElCPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<FMFunc2ElCPtrC>, FMFunc2ElCPtrC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CMPtr>, CTestBase>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CMCPtr>, CTestBase const>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CMPtrC>, CTestBase>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CMCPtrC>, CTestBase const>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestArray2>, CTestArray2>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestArray2C>, CTestArray2C>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestArray>, CTestArray>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTestArrayC>, CTestArrayC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTest2DArray2>, CTest2DArray2>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTest2DArray2C>, CTest2DArray2C>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTest2DArray>, CTest2DArray>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTest2DArrayC>, CTest2DArrayC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTest3DArray2>, CTest3DArray2>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTest3DArray2C>, CTest3DArray2C>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTest3DArray>, CTest3DArray>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<CTest3DArrayC>, CTest3DArrayC>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<void *>, void *>);
static_assert(cIsSame<TCRemoveMemberObjectPointer<void>, void>);


// Class
static_assert(cIsSame<TCMemberObjectPointerClass<CTestUnion>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestClass0>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestClass1>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestStruct0>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestStruct1>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<ETestEnum>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestClass>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestCPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestCPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestCRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestRRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestCRRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<PFFunc0>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<PFFunc1>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<PFFunc2>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc0Ref>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc1Ref>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc2Ref>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc0RRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc1RRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc2RRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc0Ptr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc1Ptr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc2Ptr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc0PtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc1PtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc2PtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc0Ptr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc1Ptr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc2Ptr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc0PtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc1PtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc2PtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc0CPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc1CPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc2CPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc0CPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc1CPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc2CPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<PFFunc0El>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<PFFunc1El>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<PFFunc2El>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc0ElRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc1ElRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc2ElRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc0ElRRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc1ElRRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc2ElRRef>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc0ElPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc1ElPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc2ElPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc0ElPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc1ElPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FFunc2ElPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc0ElPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc1ElPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc2ElPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc0ElPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc1ElPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc2ElPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc0ElCPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc1ElCPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc2ElCPtr>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc0ElCPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc1ElCPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<FMFunc2ElCPtrC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CMPtr>, CTestClass0>);
static_assert(cIsSame<TCMemberObjectPointerClass<CMCPtr>, CTestClass0>);
static_assert(cIsSame<TCMemberObjectPointerClass<CMPtrC>, CTestClass0>);
static_assert(cIsSame<TCMemberObjectPointerClass<CMCPtrC>, CTestClass0>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestArray2>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestArray2C>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestArray>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTestArrayC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTest2DArray2>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTest2DArray2C>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTest2DArray>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTest2DArrayC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTest3DArray2>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTest3DArray2C>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTest3DArray>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<CTest3DArrayC>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<void *>, void>);
static_assert(cIsSame<TCMemberObjectPointerClass<void>, void>);
