// Copyright © 2015 Hansoft AB
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"


// Object
static_assert(cIsObject<CTestUnion>);
static_assert(cIsObject<CTestClass0>);
static_assert(cIsObject<CTestClass1>);
static_assert(cIsObject<CTestStruct0>);
static_assert(cIsObject<CTestStruct1>);
static_assert(cIsObject<ETestEnum>);
static_assert(cIsObject<CTestClass>);
static_assert(cIsObject<CTestC>);
static_assert(cIsObject<CTestPtr>);
static_assert(cIsObject<CTestCPtr>);
static_assert(cIsObject<CTestPtrC>);
static_assert(cIsObject<CTestCPtrC>);
static_assert(!cIsObject<CTestRef>);
static_assert(!cIsObject<CTestCRef>);
static_assert(!cIsObject<CTestRRef>);
static_assert(!cIsObject<CTestCRRef>);
static_assert(!cIsObject<PFFunc0>);
static_assert(!cIsObject<PFFunc1>);
static_assert(!cIsObject<PFFunc2>);
static_assert(!cIsObject<FFunc0Ref>);
static_assert(!cIsObject<FFunc1Ref>);
static_assert(!cIsObject<FFunc2Ref>);
static_assert(!cIsObject<FFunc0RRef>);
static_assert(!cIsObject<FFunc1RRef>);
static_assert(!cIsObject<FFunc2RRef>);
static_assert(cIsObject<FFunc0Ptr>);
static_assert(cIsObject<FFunc1Ptr>);
static_assert(cIsObject<FFunc2Ptr>);
static_assert(cIsObject<FFunc0PtrC>);
static_assert(cIsObject<FFunc1PtrC>);
static_assert(cIsObject<FFunc2PtrC>);
static_assert(cIsObject<FMFunc0Ptr>);
static_assert(cIsObject<FMFunc1Ptr>);
static_assert(cIsObject<FMFunc2Ptr>);
static_assert(cIsObject<FMFunc0PtrC>);
static_assert(cIsObject<FMFunc1PtrC>);
static_assert(cIsObject<FMFunc2PtrC>);
static_assert(cIsObject<FMFunc0CPtr>);
static_assert(cIsObject<FMFunc1CPtr>);
static_assert(cIsObject<FMFunc2CPtr>);
static_assert(cIsObject<FMFunc0CPtrC>);
static_assert(cIsObject<FMFunc1CPtrC>);
static_assert(cIsObject<FMFunc2CPtrC>);
static_assert(!cIsObject<PFFunc0El>);
static_assert(!cIsObject<PFFunc1El>);
static_assert(!cIsObject<PFFunc2El>);
static_assert(!cIsObject<FFunc0ElRef>);
static_assert(!cIsObject<FFunc1ElRef>);
static_assert(!cIsObject<FFunc2ElRef>);
static_assert(!cIsObject<FFunc0ElRRef>);
static_assert(!cIsObject<FFunc1ElRRef>);
static_assert(!cIsObject<FFunc2ElRRef>);
static_assert(cIsObject<FFunc0ElPtr>);
static_assert(cIsObject<FFunc1ElPtr>);
static_assert(cIsObject<FFunc2ElPtr>);
static_assert(cIsObject<FFunc0ElPtrC>);
static_assert(cIsObject<FFunc1ElPtrC>);
static_assert(cIsObject<FFunc2ElPtrC>);
static_assert(cIsObject<FMFunc0ElPtr>);
static_assert(cIsObject<FMFunc1ElPtr>);
static_assert(cIsObject<FMFunc2ElPtr>);
static_assert(cIsObject<FMFunc0ElPtrC>);
static_assert(cIsObject<FMFunc1ElPtrC>);
static_assert(cIsObject<FMFunc2ElPtrC>);
static_assert(cIsObject<FMFunc0ElCPtr>);
static_assert(cIsObject<FMFunc1ElCPtr>);
static_assert(cIsObject<FMFunc2ElCPtr>);
static_assert(cIsObject<FMFunc0ElCPtrC>);
static_assert(cIsObject<FMFunc1ElCPtrC>);
static_assert(cIsObject<FMFunc2ElCPtrC>);
static_assert(cIsObject<CMPtr>);
static_assert(cIsObject<CMCPtr>);
static_assert(cIsObject<CMPtrC>);
static_assert(cIsObject<CMCPtrC>);
static_assert(cIsObject<CTestArray2>);
static_assert(cIsObject<CTestArray2C>);
static_assert(cIsObject<CTestArray>);
static_assert(cIsObject<CTestArrayC>);
static_assert(cIsObject<CTest2DArray2>);
static_assert(cIsObject<CTest2DArray2C>);
static_assert(cIsObject<CTest2DArray>);
static_assert(cIsObject<CTest2DArrayC>);
static_assert(cIsObject<CTest3DArray2>);
static_assert(cIsObject<CTest3DArray2C>);
static_assert(cIsObject<CTest3DArray>);
static_assert(cIsObject<CTest3DArrayC>);
static_assert(cIsObject<void *>);
static_assert(!cIsObject<void>);

