// Copyright © 2015 Hansoft AB 
// Distributed under the MIT license, see license text in LICENSE.Malterlib

#include "Test_TypeTraits_TestTypes.h"

DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClassVirtual, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<int, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestUnion, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClassWithPrivateConstructor, 128>::CType>::mc_Value == 128		));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClassWithPrivateDestructor, 128>::CType>::mc_Value == 128		));


DMibStaticCheck((	TCAlignmentOf<CTestUnion>::mc_Value != 0			));
DMibStaticCheck((	TCAlignmentOf<CTestClass0>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestClass1>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestStruct0>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestStruct1>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<const CTestClass0>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<const CTestClass1>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<const CTestStruct0>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<const CTestStruct1>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<ETestEnum>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<int>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CTestClass>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CTestC>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CTestPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestPtrC>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestRRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestCRRef>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<PFFunc0>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<PFFunc1>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<PFFunc2>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0Ref>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1Ref>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2Ref>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0RRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1RRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2RRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0Ptr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1Ptr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2Ptr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc1PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc2PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0Ptr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1Ptr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2Ptr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2PtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0CPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1CPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2CPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<PFFunc0El>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<PFFunc1El>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<PFFunc2El>::mc_Value == 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElRRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElRRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElRRef>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<FFunc0ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc1ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FFunc2ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCPtr>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc0ElCPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc1ElCPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<FMFunc2ElCPtrC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CMPtr>::mc_Value != 0							));
DMibStaticCheck((	TCAlignmentOf<CMCPtr>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMPtrC>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CMCPtrC>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<CTestArray2>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArray2C>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArray>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTestArrayC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest2DArray2>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest2DArray2C>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest2DArray>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest2DArrayC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest3DArray2>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest3DArray2C>::mc_Value != 0				));
DMibStaticCheck((	TCAlignmentOf<CTest3DArray>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<CTest3DArrayC>::mc_Value != 0					));
DMibStaticCheck((	TCAlignmentOf<void *>::mc_Value != 0						));
DMibStaticCheck((	TCAlignmentOf<void>::mc_Value == 0							));


DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestUnion, 128>::CType>::mc_Value == 128			));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClass0, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClass1, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestStruct0, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestStruct1, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const CTestClass0, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const CTestClass1, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const CTestStruct0, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<const CTestStruct1, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<ETestEnum, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<int, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestClass, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestC, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestPtrC, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestRRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestCRRef, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc0, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc1, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc2, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0Ref, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1Ref, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2Ref, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0RRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1RRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2RRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0Ptr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1Ptr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2Ptr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0Ptr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1Ptr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2Ptr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2PtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0CPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1CPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2CPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc0El, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc1El, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<PFFunc2El, 128>::CType>::mc_Value != 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElRRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElRRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElRRef, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc0ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc1ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FFunc2ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCPtr, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc0ElCPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc1ElCPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<FMFunc2ElCPtrC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMPtr, 128>::CType>::mc_Value == 128							));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCPtr, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMPtrC, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CMCPtrC, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArray2, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArray2C, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArray, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTestArrayC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArray2, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArray2C, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArray, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest2DArrayC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArray2, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArray2C, 128>::CType>::mc_Value == 128				));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArray, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<CTest3DArrayC, 128>::CType>::mc_Value == 128					));
DMibStaticCheck((	TCAlignmentOf<TCAlign<void *, 128>::CType>::mc_Value == 128						));
DMibStaticCheck((	TCAlignmentOf<TCAlign<void, 128>::CType>::mc_Value != 128							));

